### ISSUE TITLE
Nested embedded schema build_generated throws an error.

### ISSUE THREAD

**Issue by snithishkumar** [isar/isar#1003]
### Steps to Reproduce

The nested embedded schema build_generated throws an error.

### Code sample

```dart

Main Class
-----------

import 'package:isar/isar.dart';
import 'product_basic.dart';

part 'products.g.dart';
@Collection()
class Products {
  Id? id = Isar.autoIncrement;
  String? documentId;
  ProductBasic? productBasic;
}


Nested Level 1:
--------------

import 'package:isar/isar.dart';
import 'product_main_cat.dart';

part 'product_basic.g.dart';
@embedded
class ProductBasic {
  String? productName;
  String? productPurchaseDate;
  ProductMainCat? productMainCat;
}


Nested Level 2:
---------------

import 'package:isar/isar.dart';
part 'product_main_cat.g.dart';
@embedded
class ProductMainCat {
  String? documentId;
  String? categoryName;
}

```

### Error Details

```
A value of type 'Null' can't be assigned to a parameter of type 'Map<String, Schema<dynamic>>' in a const constructor. (Documentation) 

Try using a subtype, or removing the keyword 'const'.
```

### Offical Docs says

```
It's often helpful to have nested objects in your collection model. There is no limit to how deep you can nest objects. Keep in mind, however, that updating a deeply nested object will require writing the whole object tree to the database.
```
### Details

I don't know where I went wrong. 

 - Platform: MacBook Pro ,Apple M1 chip
 - Flutter version: [3.3.10]
 - Dart version:[2.18.6]
 - Isar version: [3.0.5]
 - isar_generator: [3.0.5]
 - build_runner:[2.3.3]

**Comment by Dosenbiiir** [comment]
I figured out it happens when you divide your classes into multiple files. If you have them all in one file its working properly. So for now you can continue that way :)

PS: Has nothing todo with your request but I would suggest you to rename your `products` class to `product` (singular) as its storing one product.

**Comment by snithishkumar** [comment]
Thanks a lot. If it's a single file, its works as a charm. It would be great to support multiple files.

**Comment by bambinoua** [comment]
What news about this issue? I do not want to place different domain entities in the sage file. If I will have 100 embedded classes so how my target class will looks? This is no go.

**Comment by mlencki** [comment]
I fixed this in my project by adding missing imports for all embedded (at all nesting depths) schemas to the root collection schema.


```dart
import 'package:isar/isar.dart';
import 'product_basic.dart';
import 'product_main_cat.dart'; // this should be added

part 'products.g.dart';

@Collection()
class Products {
  Id? id = Isar.autoIncrement;
  String? documentId;
  ProductBasic? productBasic;
}
```

No further need to store it in a single file.
