### ISSUE TITLE
Weird id in query result

### ISSUE THREAD

**Issue by ivanesi** [isar/isar#1004]
The `id` field that I receive from database not the same as in database.

Say I have 3 records in collection `tasks` with ids 1,2 and 3. I can see them in inspector.

But when I query records and then print the ids:

```dart
final query = _collection.where();
final result = await query.findAll();
result.forEach((e) => print('${e.name}: ${e.id}'));
```

In console I see this:
```
flutter: task one: -9223372036854775808
flutter: task two: -9223372036854775808
flutter: task three: -9223372036854775808
```

`id` is wrong, negative and number is the same for all records.

Any ideas why it so? 

My model for record is:

```dart
part 'db_app_task.g.dart';

@collection
@Name('tasks')
class DbAppTask {
  final id = Isar.autoIncrement;
 
  @Index(type: IndexType.value)
  final String name;

   /// has other props

  DbAppTask({
      required this.name,
      ...
  });

}
```

### Details
 - iPhone 11 Pro (mobile) • 5A2D796A-1799-48B9-820E-9B0B52B6B460 • ios •com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
 - Flutter version: [3.3.10]
 - Isar version: [3.0.5]

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by ivanesi** [comment]
And at the same time this:

``` dart
final result = await query.idProperty().findAll();
```

returns correct ids

**Comment by ivanesi** [comment]
If I don't use `final` for `id` in `@collection` model, it works as expected. 

``` dart
@collection
@Name('tasks')
class DbAppTask {
  Id id = Isar.autoIncrement;
  ...
```

I notice in your examples you don't use `final` fields. If there are some limitations related to this, please add it to documentation.

**Comment by icodeyou** [comment]
Same happened to me. It'd be nice to have it in the documentation indeed !

**Comment by Huber1** [comment]
basically it's already in the documentation: https://isar.dev/schema.html#anatomy-of-a-collection
there's no warning but it says it only works if not final
