### ISSUE TITLE
Using custom classes objects

### ISSUE THREAD

**Issue by zezo357** [isar/isar#1005]
I don't know if the type converter available before version 3 could help or not 

I want to use custom data type in object like
class data{
Rxint speed;
}

**Describe the solution you'd like**
I want to save the speed value `speed.value;`
and read it as `speed=(database value).obs;`

**Describe alternatives you've considered**
I saw that there is a solution to make setters but to be saved but the getters are not available.

for the type converter code I saw there was a way to set getters and setters for each object which will clean too much of the code in my side

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: any
 - Isar version: 3.*

**Comment by zezo357** [comment]
there was a discussion with similar problem too https://github.com/isar/isar/discussions/730

**Comment by simc** [comment]
I don't intend to add support for this. Convert your objects to json instead in Isar v4
