### ISSUE TITLE
"More than one property annotated with @Id()" when inhereting from base class.

### ISSUE THREAD

**Issue by antholeole** [isar/isar#102]
**Steps to Reproduce**

declare a base class:

```dart
abstract class BaseModel {
  @Id()
  int? isar_id;
}
```

and then a class that inherets from it:

```dart 
@collection()
class TestModel extends BaseModel {}
```

this fails to generate with:  

```
More than one property annotated with @Id().
package:fe/data_classes/isar/test_model.dart:7:7
  ╷
7 │ class TestModel extends BaseModel {
  │       ^^^^^^^^^
  ╵
```

**pubspec.yaml:**
```yaml
  isar: ^0.4.0
  isar_flutter_libs: ^0.4.0

dev_deps:
  isar_generator: ^0.4.0
```

**extra details**
seems to be no way to work around without sacraficing boilerplate; even when implement instead of extend, this issue still exists. 

Ideally, I'd like to create a base class with @id and @index for two properties and have the rest of my models inheret from it, as literally all of my models follow the same pattern.

Thanks!

**Comment by leisim** [comment]
Fixed with stable release
