### ISSUE TITLE
The embedded list object has a fixed list length

### ISSUE THREAD

**Issue by mandreshope** [isar/isar#1020]
### Steps to Reproduce

Hi, the embedded list object has a fixed list length, how to make it a list with no fixed length, because when I try to add a new item(object.embeddedObjectList.add(embeddedObject)), I have this error : UnsupportedError (Unsupported operation: Cannot add to a fixed-length list)

### Code sample

```dart
@collection
class UserEntity {
  Id id;
  @Index(type: IndexType.value)
  String? username;

  List<AttendanceEntityEmbedded> attendancesEmbedded;

  UserEntity({
    required this.id,
    this.username,
    this.attendancesEmbedded = const [],
  });
}

```

### Details

 - Platform: emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
 - Flutter version: 3.3.2
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by LucasPessamilio** [comment]
Instead of using `attendencesEmbedded.add(newAttendence)` I use `attendencesEmbedded = [...attendencesEmbedded, newAttendence]`. This way I can add new items to the list without needing it to have variable length.

**Comment by LucasPessamilio** [comment]
@mandreshope I do the same thing, but filtering out the item I want to delete, suposing I want to delete by id, I would do something like: `attendencesEmbedded = [...attendencedEmbedded.where((e) => e.id == idToDelete)]`

**Comment by CalsRanna** [comment]
I met this error also, and i don't think is a good way to make list fixed list for performance.
And i found a way to solve it base #703 , build an extension can be done but it's not a good way. i think @simc should to think more to add an offical way to solve this.

**Comment by AncientPixel** [comment]
Also, currently (v3.1.0), if you just add one item, that item does not persist, the list will load with 0 items in it.

**Comment by simc** [comment]
This is obsolete for Isar v4
