### ISSUE TITLE
[Bug] num datatype is not supported

### ISSUE THREAD

**Issue by dinbtechit** [isar/isar#1021]
### Steps to Reproduce

1. create a collection class with member variables with `num` dataType. (As shown below)
```dart
import 'package:isar/isar.dart';

part 'food.g.dart';

@collection
@Name('food')
class Food {
  Id id = Isar.autoIncrement;
  String? name;
  num? protein;
  num? carbs;
  num? fat;
  num? calories;
  num? serviceSize;
  String? serviceUnit;
  double? proteinPerUnit;
  double? carbsPerUnit;
  double? fatPerUnit;
}
```
3. Run Build runner
```
flutter pub run build_runner watch --delete-conflicting-outputs
```
**Error**
```
[INFO] Running build...
[SEVERE] isar_generator on lib/repository/models/food.dto.dart:

Unsupported type. Please annotate the property with @ignore.
package:myflutter/repository/models/food.dto.dart:10:8
   ╷
10 │   num? protein;
   │        ^^^^^^^

```

### Details

 - Platform: All
 - Flutter version: >=2.17.6 <3.0.0
 - Isar version: ^3.0.5

---

 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version
 - [X] I am able to provide a reproducible example

**Comment by simc** [comment]
It's not a bug. `num` is a union type of `int` and `double` but Isar needs to know which one you want to store.

Just use `double` if you want to store both.

**Comment by dinbtechit** [comment]
oh ok.. thank you for the explanation!
