### ISSUE TITLE
Db Write Crashes mobile and Desktop applications

### ISSUE THREAD

**Issue by PeterAkande** [isar/isar#1022]
### Steps to Reproduce
On writing to the Db, the runtime crashed with the error

"thread 'isarworker' panicked at 'range start index 7141121 out of range for slice of length 67', library\core\src\slice\index.rs:52:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

### Details

 - Platform:  Windows Desktop App
 - Flutter version: 3.3.9
 - Isar version: 3.0.5

The description is as shown below:
![image](https://user-images.githubusercontent.com/64542587/210385351-6beae34c-b9ea-4d0b-8f9d-00895b9cd93a.png)

**Comment by simc** [comment]
This has been fixed in newer versions
