### ISSUE TITLE
isar_generator that big problem for me 

### ISSUE THREAD

**Issue by IdrisQashan** [isar/isar#1024]
I have 40 classes, each class has more than 20 properties, and I do not need to generate query functions on all properties. Is there a way to generate query functions for the specified properties?

**Comment by simc** [comment]
What is the problem with generating unnecessary methods? Flutter's tree shaking will remove the unused ones during build.

**Comment by IdrisQashan** [comment]
Thank you for Response. The problem is so slow when build runner and when indexing file and when run analyzer. My idea would be to Annotation on the property who will be generating it and be add property to collection Annotation if want to generate for all properties or not?
