### ISSUE TITLE
thread 'isarworker' panicked at 'range start index

### ISSUE THREAD

**Issue by punitganshani** [isar/isar#1031]
Have 3 collections/schema/object types in the database. The application code runs on Isar `3.0.5`
No code change has been done in the code from previously working edition.

**The app crashes when,**

1. For one of the collection/schema, when following code executes to get a list of all objects in a collection

```
var genericList = (await collection?.where().findAll());
```

2. When we click on the same collection in `Isar Inspector`

**Error:**
Following error is printed in the terminal before the app crashes
 
```
thread 'isarworker' panicked at 'range start index 5177344 out of range for slice of length 128', library/core/src/slice/index.rs:52:5
```

**Output of flutter doctor:**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
````

**Comment by simc** [comment]
This has been fixed in newer versions
