### ISSUE TITLE
crashed app when open isar

### ISSUE THREAD

**Issue by Mohammadfazel03** [isar/isar#1038]
isar cannot open in armv7 cpu android device and app crashed 
please ok it

**Comment by Mohammadfazel03** [comment]
and also its have problem with armv8-a

**Comment by chenjie4255** [comment]
same problem here, thought I am a newer to flutter

**Comment by mrclauss** [comment]
Could you please share what the device log tells? (logcat or flutter log). Otherwise it's hard to tell what goes wrong :)

**Comment by Mohammadfazel03** [comment]
i run it in memu emulator v8 (with android 7)

and this is my log

> E/FlutterLoader(10872): Flutter initialization failed.
E/FlutterLoader(10872): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.isar_project-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.isar_project-1/lib/arm, /data/app/com.example.isar_project-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader(10872): 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
E/FlutterLoader(10872): 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
E/FlutterLoader(10872): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:239)
E/FlutterLoader(10872): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/FlutterLoader(10872): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/FlutterLoader(10872): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:271)
E/FlutterLoader(10872): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/FlutterLoader(10872): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/FlutterLoader(10872): 	at android.app.Activity.performCreate(Activity.java:6760)
E/FlutterLoader(10872): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
E/FlutterLoader(10872): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
E/FlutterLoader(10872): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
E/FlutterLoader(10872): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/FlutterLoader(10872): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
E/FlutterLoader(10872): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/FlutterLoader(10872): 	at android.os.Looper.loop(Looper.java:154)
E/FlutterLoader(10872): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E/FlutterLoader(10872): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader(10872): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/FlutterLoader(10872): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/FlutterLoader(10872): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.isar_project-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.isar_project-1/lib/arm, /data/app/com.example.isar_project-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader(10872): 	at java.lang.Runtime.loadLibrary0(Runtime.java:985)
E/FlutterLoader(10872): 	at java.lang.System.loadLibrary(System.java:1562)
E/FlutterLoader(10872): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/FlutterLoader(10872): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:189)
E/FlutterLoader(10872): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:182)
E/FlutterLoader(10872): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/FlutterLoader(10872): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/FlutterLoader(10872): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/FlutterLoader(10872): 	at java.lang.Thread.run(Thread.java:761)
E/AndroidRuntime(10872): FATAL EXCEPTION: main
E/AndroidRuntime(10872): Process: com.example.isar_project, PID: 10872
E/AndroidRuntime(10872): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.isar_project/com.example.isar_project.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.isar_project-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.isar_project-1/lib/arm, /data/app/com.example.isar_project-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/AndroidRuntime(10872): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
E/AndroidRuntime(10872): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
E/AndroidRuntime(10872): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime(10872): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
E/AndroidRuntime(10872): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10872): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(10872): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E/AndroidRuntime(10872): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10872): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/AndroidRuntime(10872): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/AndroidRuntime(10872): Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.isar_project-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.isar_project-1/lib/arm, /data/app/com.example.isar_project-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/AndroidRuntime(10872): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:345)
E/AndroidRuntime(10872): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/AndroidRuntime(10872): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/AndroidRuntime(10872): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:271)
E/AndroidRuntime(10872): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/AndroidRuntime(10872): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/AndroidRuntime(10872): 	at android.app.Activity.performCreate(Activity.java:6760)
E/AndroidRuntime(10872): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
E/AndroidRuntime(10872): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
E/AndroidRuntime(10872): 	... 9 more
E/AndroidRuntime(10872): Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.isar_project-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.isar_project-1/lib/arm, /data/app/com.example.isar_project-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/AndroidRuntime(10872): 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
E/AndroidRuntime(10872): 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
E/AndroidRuntime(10872): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:239)
E/AndroidRuntime(10872): 	... 17 more
E/AndroidRuntime(10872): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.isar_project-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.isar_project-1/lib/arm, /data/app/com.example.isar_project-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/AndroidRuntime(10872): 	at java.lang.Runtime.loadLibrary0(Runtime.java:985)
E/AndroidRuntime(10872): 	at java.lang.System.loadLibrary(System.java:1562)
E/AndroidRuntime(10872): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/AndroidRuntime(10872): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:189)
E/AndroidRuntime(10872): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:182)
E/AndroidRuntime(10872): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(10872): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime(10872): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime(10872): 	at java.lang.Thread.run(Thread.java:761)

**Comment by mrclauss** [comment]
Did you include flutter_isar_libs to "dependencies:" in your pubspec.yaml?

**Comment by Mohammadfazel03** [comment]
yes

**Comment by simc** [comment]
This has been fixed with the newest version 3.1.0. It will be available on pub.dev shortly
