### ISSUE TITLE
IsarLinks lose Sorting

### ISSUE THREAD

**Issue by t-kietzmann** [isar/isar#1041]
### Steps to Reproduce

Create 2 Collection, e.g. Students and Teacher

Add 5 Teachers
Add a Student and attach Teachers with the .add Method (start with the last added Teacher for example)

Save and Load the Links from the Student, the Teachers will be always in the order how they are stored in the Teacher-Collection.
Is there any way to prevent this, or any suggestion how to solve this?

In my "real world" example i have n-Students and n-Teachers, Teachers are attached to Students, but i have to sort in different for every student. 

### Current Workaround

Saving an "orderList" with the isar Ids from the Teachers to every student.

### Details

- Any Platform
- Flutter stable
- Isar 3.0.6-dev

**Comment by mahmoudalaa97** [comment]
Hey @t-kietzmann 

can I ask you about this issue, https://github.com/isar/isar/issues/915 did you find any solution or fix for it?

**Comment by jbdtky** [comment]
This is a serious issue...

**Comment by jarodtang** [comment]
Yes, it decrease the usefulness of IsarLinks greatly, can you guys give a option, sush as sort.

**Comment by simc** [comment]
`IsarLinks` extends `Set` which does not guarantee ordering. I'm looking into ways to fix this however with v4. Closing for now 🙂

**Comment by boogie1989** [comment]
> `IsarLinks` extends `Set` which does not guarantee ordering. I'm looking into ways to fix this however with v4. Closing for now 🙂

Do you have a prognosis for when it will be?

**Comment by ilovelinux** [comment]
> `IsarLinks` extends `Set` which does not guarantee ordering. I'm looking into ways to fix this however with v4. Closing for now 🙂

@simc there will be any performance loss? Some operations of ordered sets are slower than in unordered sets. Maybe having both could be a good idea.

**Comment by boogie1989** [comment]
> > `IsarLinks` extends `Set` which does not guarantee ordering. I'm looking into ways to fix this however with v4. Closing for now 🙂
> 
> @simc there will be any performance loss? Some operations of ordered sets are slower than in unordered sets. Maybe having both could be a good idea.

He removed links from 4 version(
