### ISSUE TITLE
Making IsarLink final does not work; generator generates but code cannot compile due to illigal assignment

### ISSUE THREAD

**Issue by antholeole** [isar/isar#106]
The docs say: "IsarLink and IsarLinks both have a zero-arg constructor which should be used to assign the link property when the object is created. It is good practice to make link properties final."

When I define a schema with anything like:   
```dart
 final groups = IsarLinks<Group>();
``` 

the generator generates:

```dart
object.groups = IsarLinksImpl()
      ..attach(
        collection,
        collection.isar.groups as IsarCollectionImpl<Group>,
        object,
        0,
        false,
      );
```
This does not compile, as it attempts to set a final field.

**Comment by leisim** [comment]
This is fixed 👍
