### ISSUE TITLE
Starting many watch streams causes jank

### ISSUE THREAD

**Issue by cal-g** [isar/isar#1063]
### Steps to Reproduce

I have 2 tables: notes and subnotes each with 20000 records. A note has one subnote record and to create a relationship between the two tables there is a `uuid` column in Note table and  `parentNoteId` in SubNote table.
After loading all the Notes from the database and saving the List<Notes> in a local variable `notes`, I click a button **Watch subNotes** which executes the `watch` on the subnote query for each note record

This causes a jank immediately when the button was clicked as it can be seen from the animation of the circular progress indicator.

What would be the reason for this jank ?

[link](https://github.com/cal-g/isar_app) to full sample app code

### Code sample

```dart
 final isarSubNotesInstance = isarInstance.subNotes;

    notes.forEach((element) {
      isarSubNoteSubscription.add(
        isarSubNotesInstance
            .filter()
            .parentNoteIdEqualTo(element.uuid, caseSensitive: false)
            .build()
            .watch(fireImmediately: true)
            .listen((event) {
          subNotes.addAll(event);
        }),
      );
    });
```

### Details

 - Platform: iPad mini (6th generation) simulator on MacOS.
 - Flutter version: 3.3.10
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

https://user-images.githubusercontent.com/98470469/214374634-7557fc12-57f1-4049-95fa-54b5894be402.mov

**Comment by simc** [comment]
Watching 20000 objects is a very bad idea and jank is expected in such a case. Not everything can be optimized
