### ISSUE TITLE
New watch queries executed only after the previous watch queries are done executing

### ISSUE THREAD

**Issue by cal-g** [isar/isar#1064]
### Steps to Reproduce

I have 2 tables: notes and subnotes each with 20000 records. A note has one subnote record and to create a relationship between the two tables there is a `uuid` column in Note table and `parentNoteId` in SubNote table.
After clicking a button to watch all the Notes from the database (which is very quick) and saving the List in a local variable `notes`, I click a button **Watch subNotes** which executes the `watch` on the subnote query for each note record.

If I quickly click a button to watch all the notes again (or any other watch query) it is not as quick as before and it seems to be waiting till all the subnote watch streams have started and then only the note watch stream emits an event. I tested this by having a `print` statement in the `listen` of the note's watch and is printed to the console after a couple of seconds. 

Is it possible to execute watch queries immediately ?

Thanks.

[link](https://github.com/cal-g/isar_app) to full sample app code

### Code sample

```dart
  void watchAllNotes() {
    notes.clear();
    subNotes.clear();
    final s = isarInstance.notes.where().build().watch(
          fireImmediately: true,
        );

    s.listen((event) {
      print('event :: ${event.length}');
      notes = event;
      setState(() {});
    });
  }

  void watchSubNotesForEachNote() {
    subNotes.clear();
    final isarSubNotesInstance = isarInstance.subNotes;

    notes.forEach((element) {
      isarSubNoteSubscriptions.add(
        isarSubNotesInstance
            .filter()
            .parentNoteIdEqualTo(element.uuid, caseSensitive: false)
            .build()
            .watch(fireImmediately: true)
            .listen((event) {
          subNotes.addAll(event);
        }),
      );
    });
  }
```

### Details

 - Platform: iPad mini (6th generation) simulator on MacOS.
 - Flutter version: 3.3.10
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
This is expected behavior
