### ISSUE TITLE
Immediately cancelling the subscriptions of many recently started watch streams seems to still be doing work after the StreamSubscription.cancel futures have completed

### ISSUE THREAD

**Issue by cal-g** [isar/isar#1065]
### Steps to Reproduce

Almost similar to [issue](https://github.com/isar/isar/issues/1064) I just posted but this deals with cancellation of the streams.

I have 2 tables: notes and subnotes each with 20000 records. A note has one subnote record and to create a relationship between the two tables there is a `uuid` column in Note table and  `parentNoteId` in SubNote table.
After loading all the Notes from the database and saving the List<Notes> in a local variable `notes`, I click a button **Watch subNotes** which executes the `watch` on the subnote query for each note record and saves the StreamSuscriptions in a local variable `isarSubNoteSubscriptions`

If I click the **Cancel** button which calls the StreamSuscription.cancel for every subnote stream all the futures are completed quickly.  But if I execute another watch query immediately by clicking on the **Watch all notes** this watch query still emits notes result after a couple of seconds which is around the same amount of time had the subnote streams not been cancelled. 

It seems to me that the queries are still running even though the streams have been cancelled.

[link](https://github.com/cal-g/isar_app) to full sample app code

### Code sample

```dart
void watchAllNotes() {
    notes.clear();
    subNotes.clear();
    final s = isarInstance.notes.where().build().watch(
          fireImmediately: true,
        );

    s.listen((event) {
      print('event :: ${event.length}');
      notes = event;
      setState(() {});
    });
}

void watchSubNotesForEachNote() {
    subNotes.clear();
    final isarSubNotesInstance = isarInstance.subNotes;

    notes.forEach((element) {
      isarSubNoteSubscriptions.add(
        isarSubNotesInstance
            .filter()
            .parentNoteIdEqualTo(element.uuid, caseSensitive: false)
            .build()
            .watch(fireImmediately: true)
            .listen((event) {
          subNotes.addAll(event);
        }),
      );
    });
}

TextButton(
  onPressed: watchAllNotes,
   child: const Text('Watch all notes'),
 ),

TextButton(
   onPressed: watchSubNotesForEachNote,
    child: const Text('Watch subNotes'),
 ),

TextButton(
     onPressed: () async {
     print('cancel');
      await Future.wait(
     isarSubNoteSubscriptions.map((e) => e.cancel()));
     print('cancelled');
             },
      child: const Text('Cancel'),
       );
```

### Details

 - Platform: iPad mini (6th generation) simulator on MacOS.
 - Flutter version: 3.3.10
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
You really have to change your app design. These are not Isar issue but incorrect usage of watchers
