### ISSUE TITLE
Startup Exception - Collection id is invalid..

### ISSUE THREAD

**Issue by bobekos** [isar/isar#1067]
### Steps to Reproduce

When Isar.open is called twice with different schemas and name,i got the IsarError (IsarError: IllegalArg: Collection id is invalid..) exception on startup.

### Code sample

```dart
final isarOne = await Isar.open([test1, test2], directory: 'path', name: 'db_1');
final isarTwo = await Isar.open([test3, test4], directory: 'path', name: 'db_2');
```
All schemas are generated correctly and also the inspector is showing both databases below. But i can't switched them and the inspector is showing 'loading' on each entity entry.

Update 25.01.2022
In release build the exception doesn't occured. It works also in debug build when there is some delay between the both open calls.

### Details

 - Platform: Android
 - Flutter version: 3.3.10
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by hwkim1127** [comment]
use openSync instead of await and open

**Comment by bobekos** [comment]
Hi @hwkim1127 

this seems to work but does this have impact on the main performance or other issues? I am not opening the instances in a separate isolate.

**Comment by LazyTaz** [comment]
> Hi @hwkim1127
> 
> this seems to work but does this have impact on the main performance or other issues? I am not opening the instances in a separate isolate.

I would like to know what's the performance impact of opening schemas too.

**Comment by bobekos** [comment]
@LazyTaz 

Hi i am using it in production and its ok. I don't see any performance issues

**Comment by Maqcel** [comment]
Any lead on this I'm getting this when I try to work on separate isolate

**Comment by Abdurahmon727** [comment]
> ### Steps to Reproduce
> When Isar.open is called twice with different schemas and name,i got the IsarError (IsarError: IllegalArg: Collection id is invalid..) exception on startup.
> 
> ### Code sample
> final isarOne = await Isar.open([test1, test2], directory: 'path', name: 'db_1');
> final isarTwo = await Isar.open([test3, test4], directory: 'path', name: 'db_2');
> All schemas are generated correctly and also the inspector is showing both databases below. But i can't switched them and the inspector is showing 'loading' on each entity entry.
> 
> Update 25.01.2022 In release build the exception doesn't occured. It works also in debug build when there is some delay between the both open calls.
> 
> ### Details
> * Platform: Android
> * Flutter version: 3.3.10
> * Isar version: 3.0.5
> 
> * [x]  I searched for similar issues already[x]  I filled the details section with the exact device model and version[x]  I am able to provide a reproducible example

I am having same error in release mode (android device). Looks like I need to try using openSync
