### ISSUE TITLE
On Ios thread #26, name = 'isarworker', stop reason = signal SIGABRT    

### ISSUE THREAD

**Issue by IdrisQashan** [isar/isar#1069]
My App Working on Android And Windows Desktop And I run on ios emulator and all worked
put when I run Physics Iphone it crash and write:
Runner(484,0x16bd17000) malloc: *** set a breakpoint in malloc_error_break to debug
* thread #26, name = 'isarworker', stop reason = signal SIGABRT
    frame #0: 0x00000001bf8a184c libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1bf8a184c <+8>:  b.lo   0x1bf8a1868               ; <+36>
    0x1bf8a1850 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1bf8a1854 <+16>: mov    x29, sp
    0x1bf8a1858 <+20>: bl     0x1bf87ef5c               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.

**Comment by Sadmansamee** [comment]
I faced it, then set mib use to 512, that seems to fix the issue.

**Comment by mdmm13** [comment]
Might be the same as #915 and #1053.

**Comment by simc** [comment]
This is fixed in v3.1.0 which will be available soon on pub.dev.
