### ISSUE TITLE
Error isar_flutter_libs: ^3.0.6-dev.0 when Archive

### ISSUE THREAD

**Issue by IdrisQashan** [isar/isar#1070]
I have Xcode 13.3.1 and Facing same issue in Folow only when I Archive.
If delete isar_flutter_libs: ^3.0.6-dev.0 it archive done
could not reparse object file in bitcode bundle: 'Unknown attribute kind (68) (Producer: 'LLVM12.0.1-rust-1.55.0-stable' Reader: 'LLVM APPLE_1_1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' for architecture arm64

**Comment by Sadmansamee** [comment]
try with latest xcode,

**Comment by patilvishwanath** [comment]
I have same issue, iOS build pipeline is failing with below error:

error : 

```
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1400.0.29.102.0_0' Reader: '1300.0.29.30_0')', using libLTO version 'LLVM version 13.0.0, (clang-1300.0.29.30)' for architecture arm64[12:32:49]: 

▸ ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```


Xcode version : 13.2.1
Flutter Version : 3.3.10
Isar Version : 3.0.5

Also tested with Isar version 3.0.0/3.0.1

Couldn't find compatible list of isar_flutter_libs & xcode version. Is there any ?

Kindly help

**Comment by simc** [comment]
Update XCode 👍
