### ISSUE TITLE
IsarError in release mode ios

### ISSUE THREAD

**Issue by chezki1235467** [isar/isar#1072]
Help!
I have been dealing with this problem for a few days now.
In ios, The app is stuck on a white screen when opening in
release mode and testflight in app store connect. (Debug is well)

Exception: IsarError: Could not initialize IsarCore library for processor architecture "ios_arm64". If you create a Flutter app, make sure to add isar_flutter_libs to your 
dependencies

Invalid argument(s): Failed to lookup symbol 'isar_version': dlsym(RTLD_DEFAULT, isar_version): symbol not found

 - Platform: iPhone 13 
 - ios 16.2
 - Xcode: 14.2
 - Flutter version: 3.7.0
 - 
 - dependencies:
 - Isar version: 3.5.0 
 - Isar_flutter_lib: 3.5.0

--
 example https://github.com/isar/isar/issues/519#issue-1316611758

**Comment by bobekos** [comment]
Hi,

could you delete the podfile.lock file in your ios repository and then refetched the pods with this command 'pod update'. I think I remember having the same error and that helped. What I wonder is why it runs in the debug build.

**Comment by chezki1235467** [comment]
thanks i will try "pod update".
From a search I did on this error message it seemed that it was a problem that was fixed in the new versions.  But I still got it in the new version. In ios and release mode

**Comment by morhi** [comment]
I get this error from a multitude of devices, though not locally for quite a few time. It seems to be a random problem.

**Comment by chezki1235467** [comment]
I solved the problem at the end with the highlighted lines in Podfile
![‏‏צילום מסך (43)](https://user-images.githubusercontent.com/120033414/215994131-feed1ab6-37c1-49d5-bb7d-18d3adc6ddb5.png)

**Comment by morhi** [comment]
Interestingly I see this error (in Sentry) exclusively on Android devices only. iOS is not an issue.

**Comment by ekimia** [comment]
There is a similar issue here. If you have the following line in your `Podfile` which is required by some frameworks you will also get the "grey screen of death" in release mode only:

```
target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

One of the frameworks in question: https://developers.is.com/ironsource-mobile/flutter/integration-helper-flutter/

**Comment by Sadmansamee** [comment]
can try with 3.0.6-dev.0?

**Comment by JaonFanwt** [comment]
If your project enables Dead Code Stripping, cause isar_flutter_libs is the static library, it strips unused codes which are not directly referenced, you have two ways to solve the problems.

1. The first way, I am using in my project, turn isar_flutter_libs to the dynamic framework, open your podfile, and add:
``` ruby
dynamic_framework = ['isar_flutter_libs']

pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each {| pod |
      if dynamic_framework.include?(pod.name)
        puts "turn to dynamic framework name:" + pod.name
        def pod.dynamic_framework;
          true
        end
        def pod.build_type;
          Pod::BuildType.dynamic_framework 
        end
      end
    }
  end
```

2. or disable Dead Code Stripping in your target Build Settings.

**Comment by macatingraoallan** [comment]
The first one solved my issue.

> If your project enables Dead Code Stripping, cause isar_flutter_libs is the static library, it strips unused codes which are not directly referenced, you have two ways to solve the problems.
> 
> 1. The first way, I am using in my project, turn isar_flutter_libs to the dynamic framework, open your podfile, and add:
> 
> dynamic_framework = ['isar_flutter_libs']
> 
> pre_install do |installer|
>   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>   installer.pod_targets.each {| pod |
>     if dynamic_framework.include?(pod.name)
>       puts "turn to dynamic framework name:" + pod.name
>       def pod.dynamic_framework;
>         true
>       end
>       def pod.build_type;
>         Pod::BuildType.dynamic_framework
>       end
>     end
>   }
> end
> 2. or disable Dead Code Stripping in your target Build Settings.

**Comment by MilesAdamson** [comment]
If anyone else runs into this issue like me, the fix wasn't working for me until I remembered I am now using `isar_community_flutter_libs`, not `isar_flutter_libs`
