### ISSUE TITLE
Inspector value changed on cancel action.

### ISSUE THREAD

**Issue by twoco** [isar/isar#1083]
Just a minor notice: A click to the backdrop should not touch the value.
<img width="440" src="https://user-images.githubusercontent.com/53160891/216844918-d40bdb9a-269a-41a0-9d73-423502644041.gif"/>
In this case, the value should not be changed to `null` when the backdrop is clicked (cancelled).

**Comment by simc** [comment]
This is fixed in the new v4 inspector
