### ISSUE TITLE
App crashing on calling openIsar a second time

### ISSUE THREAD

**Issue by peterlazar1993** [isar/isar#109]
**Steps to Reproduce**
As mentioned [here](https://github.com/isar/isar/discussions/108) I have added Isar to the ObjectBox benchmarks repo.

I am running into an app crash when running the benchmark a second time.
I have narrowed down the crash to the `IC.isar_get_property_offsets` call in the generated `isar.g.dart` file.

The database files are deleted after each run, and a new path is set before each run. ~~I suspect this has something to do with he crash. Since an earlier implementation of this benchmark reused paths and this crash did not occur then.~~
On closer inspection it seems calling `close` and then opening the db instance again results in the crash.

**Code sample**
Issue can be reproduced by running the app from this [repo](https://github.com/peterlazar1993/objectbox-dart-performance)

- Clone repo with `git clone https://github.com/peterlazar1993/objectbox-dart-performance`
- `cd objectbox-dart-performance`
- `flutter pub get packages`
-  `flutter pub run build_runner build`
- `flutter run`
- pick `Isar Sync` from drop down
- Run benchmark
- Run benchmark again -> Crash occurs

**Version**
 - Platform: Testing on iOS Simulator and Android emulator
 - Flutter version: [e.g. 2.12.0]
 - Isar version: [e.g. 0.4.0]
 - Isar Generator version: [e.g. 0.4.0]

**Comment by leisim** [comment]
Fixed with stable release
