### ISSUE TITLE
v 3.0.5 thenById() throw Unhandled Exception (Unknown property "id")

### ISSUE THREAD

**Issue by heralight** [isar/isar#1090]
### Steps to Reproduce

Please describe exactly how to reproduce the problem you are running into.

Hi Thank you for this great project!
I have the same issue as in #280 with isar version 3.0.5.

### Code sample

```dart
@collection
class Tab {
Id id = Isar.autoIncrement; // same error with Id? id;
String name = "";
}
```
Compared to the documentation, I don't have a sortBy() or sortByXX() under filter().
also, under where(), I don't have a sortById(), only thenById().

when I call:
final items = await isar.browserTabInfos
        .where()
        .sortByName()
        .thenByIdDesc() // or thenById()
        .findAll();

I got: 

```
[GETX] Instance "BController" has been initialized
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: Unknown property "id"
#0      Schema.property (package:isar/src/schema/schema.dart:70:7)
#1      buildNativeQuery (package:isar/src/native/query_build.dart:60:33)
#2      IsarCollectionImpl.buildQuery (package:isar/src/native/isar_collection_impl.dart:598:12)
#3      QueryBuilderInternal.build (package:isar/src/query_builder.dart:281:24)
#4      QueryExecute.build (package:isar/src/query_builder_extensions.dart:194:30)
#5      QueryExecute.findAll (package:isar/src/query_builder_extensions.dart:203:32)
...
```

### Details

 - Platform: iPhone 13 Pro, Galaxy S7, x86 Android Emulator on macos
 - Flutter version: 3.3.10
 - Isar version: 3.0.5

Thank you!!

---

 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version

**Comment by alphasen** [comment]
I have the same issue too!!!

**Comment by JobiJoba** [comment]
I also have the same issue.

**Comment by wildsurfer** [comment]
Same issue

**Comment by simc** [comment]
This is fixed in v4
