### ISSUE TITLE
The method 'contentWordsAnyEqualTo' isn't defined for the type 'QueryBuilder'.

### ISSUE THREAD

**Issue by deadlyrazer** [isar/isar#1091]
### Steps to Reproduce
Copy paste the code, it's taken right from the docs.

### Code sample

```dart
class Message {
  Id? id;

  late String content;

  @Index()
  List<String> get contentWords => content.split(' ');
}


final posts = await isar.messages
  .where()
  .contentWordsAnyEqualTo('hello')
  .findAll();
```

### Details

I've tried all the values of `IndexType`, none work.
 - Platform: Compile time error.
 - Flutter version: [3.8.0-7.0.pre.23]
 - Isar and **generator** version: [3.0.6-dev.0]

---

 - [✅] I searched for similar issues already
 - [✅] I filled the details section with the exact device model and version
 - [✅] I am able to provide a reproducible example

**Comment by simc** [comment]
It's called `contentWordsElementEqualTo`

**Comment by CovenantJunior** [comment]
Not still working

```
void search(q) async {
  final currentList= isar.Lists..where().contentWordsElementEqualTo(q).findAll();
}
```

I got:
**The method 'contentWordsElementEqualTo' isn't defined for the type 'QueryBuilder'.
Try correcting the name to the name of an existing method, or defining a method named 'contentWordsElementEqualTo'.**

**Comment by Jtplouffe** [comment]
> Not still working
> 
> ```
> void search(q) async {
>   final currentList = isar.Lists..where().contentWordsElementEqualTo(q).findAll();
> }
> ```
> 
> I got: **The method 'contentWordsElementEqualTo' isn't defined for the type 'QueryBuilder'. Try correcting the name to the name of an existing method, or defining a method named 'contentWordsElementEqualTo'.**

Could you share the code for the collection class?

**Comment by CovenantJunior** [comment]
```
import 'package:isar/isar.dart';

// Generate collection file by running `dart run build_runner build`
part 'todo_list.g.dart';

@Collection()
class TodoList {
  Id id = Isar.autoIncrement;
  String? plan;
  bool? completed;
  DateTime? created;
  DateTime? modified;
  DateTime? achieved;
}
```

**Comment by Jtplouffe** [comment]
> ```
> import 'package:isar/isar.dart';
> 
> // Generate collection file by running `dart run build_runner build`
> part 'todo_list.g.dart';
> 
> @Collection()
> class Lists {
>   Id id = Isar.autoIncrement;
>   String? plan;
>   bool? completed;
>   DateTime? created;
>   DateTime? modified;
>   DateTime? achieved;
> }
> ```

I am not sure what you are trying to achieve, you have no field of type `List` in your collection.

Function `...ElementEqualTo` only work on `List` fields.

**Comment by CovenantJunior** [comment]
Please, I made some corrections:

```
import 'package:isar/isar.dart';

// Generate collection file by running `dart run build_runner build`
part 'todo_list.g.dart';

@Collection()
class TodoList {
  Id id = Isar.autoIncrement;
  String? plan;
  bool? completed;
  DateTime? created;
  DateTime? modified;
  DateTime? achieved;
}
```

And here is the function:

```
// SEARCH
void search(q) async {
  final currentTodoLists = isar.todoLists..where().contentWordsAnyEqualTo(q).findAll();
}
```

I followed this documentation:

[](https://isar.dev/recipes/full_text_search.html#basic-example)

**Comment by CovenantJunior** [comment]
> > ```
> > import 'package:isar/isar.dart';
> > 
> > // Generate collection file by running `dart run build_runner build`
> > part 'todo_list.g.dart';
> > 
> > @Collection()
> > class Lists {
> >   Id id = Isar.autoIncrement;
> >   String? plan;
> >   bool? completed;
> >   DateTime? created;
> >   DateTime? modified;
> >   DateTime? achieved;
> > }
> > ```
> 
> I am not sure what you are trying to achieve, you have no field of type `List` in your collection.
> 
> Function `...ElementEqualTo` only work on `List` fields.

OK, I get. Thanks!

**Comment by Jtplouffe** [comment]
> Please, I made some corrections:
> 
> ```
> import 'package:isar/isar.dart';
> 
> // Generate collection file by running `dart run build_runner build`
> part 'todo_list.g.dart';
> 
> @Collection()
> class TodoList {
>   Id id = Isar.autoIncrement;
>   String? plan;
>   bool? completed;
>   DateTime? created;
>   DateTime? modified;
>   DateTime? achieved;
> }
> ```
> 
> And here is the function:
> 
> ```
> // SEARCH
> void search(q) async {
>   final currentTodoLists = isar.todoLists..where().contentWordsAnyEqualTo(q).findAll();
> }
> ```
> 
> I followed this documentation:
> 
> [isar.dev/recipes/full_text_search.html#basic-example](https://isar.dev/recipes/full_text_search.html#basic-example)

Like I said, you are missing the `List` in your collection, look carefully at the documentation.
Also, you should not have 2 `.` in `isar.todoLists..where()`, otherwise `currentTodoLists` will be assigned the collection schema.

**Comment by CovenantJunior** [comment]
OK, as for the double dots, I fixed that too. but don't understand what `List ` I'm missing.

Here are most of the methods I've been using and are working fine:

```
import 'package:flutter/foundation.dart';
import 'package:isar/isar.dart';
import 'package:todo_list/models/todo_list.dart';
import 'package:path_provider/path_provider.dart';

class TodoListDatabase extends ChangeNotifier{
  static late Isar isar;

  // Initialize DB
  static Future<void> initialize() async {
    final dir = await getApplicationDocumentsDirectory();
    isar = await Isar.open(
      [TodoListSchema],
      directory: dir.path
    );
  }

  // List of all TodoLists
  List<TodoList> todolists = [];

  /* Handle CRUD operations */

  // CREATE
  void addTodoList(String plan) async {
    final newTodoList = TodoList()..plan = plan..created = DateTime.now()..completed = false;

    // Save to DB
    await isar.writeTxn(() => isar.todoLists.put(newTodoList));
    
    // Update TodoList List
    fetchTodoList();
  }


  // READ
  void fetchTodoList() async {
    final currentTodoLists = isar.todoLists.where().findAllSync();
    todolists.clear();
    todolists.addAll(currentTodoLists);
    notifyListeners();
  }

  // UPDATE
  void updateTodoList(int id, String plan) async {
    var existingTodoList = await isar.todoLists.get(id);
    if (existingTodoList != null) {
      existingTodoList.plan = plan;
      existingTodoList.modified = DateTime.now();
      await isar.writeTxn(() => isar.todoLists.put(existingTodoList));
    }

    // Update TodoList List
    fetchTodoList();
  }


  // DELETE
  void deleteTodoList(int id) async {
    await isar.writeTxn(() => isar.todoLists.delete(id));

    // Update TodoList List
    fetchTodoList();
  }


  // DELETE ALL
  void deleteAllTodoLists() async {
    await isar.writeTxn(() => isar.todoLists.clear());

    // Update TodoList List
    fetchTodoList();
  }

  // COMPLETED
  void completed(int id) async {
    var existingTodoList = await isar.todoLists.get(id);
    if (existingTodoList != null) {
      existingTodoList.completed = true;
      await isar.writeTxn(() => isar.todoLists.put(existingTodoList));
    }

    // Update TodoList List
    fetchTodoList();
  }

  // REPLAN
  void replan(int id) async {
    var existingTodoList = await isar.todoLists.get(id);
    if (existingTodoList != null) {
      existingTodoList.completed = false;
      await isar.writeTxn(() => isar.todoLists.put(existingTodoList));
    }

    // Update TodoList List
    fetchTodoList();
  }
```

**Comment by Jtplouffe** [comment]
> OK, as for the double dots, I fixed that too. but don't understand what `List ` I'm missing.
> 
> Here are most of the methods I've been using and are working fine:
> 
> ```
> import 'package:flutter/foundation.dart';
> import 'package:isar/isar.dart';
> import 'package:todo_list/models/todo_list.dart';
> import 'package:path_provider/path_provider.dart';
> 
> class TodoListDatabase extends ChangeNotifier{
>   static late Isar isar;
> 
>   // Initialize DB
>   static Future<void> initialize() async {
>     final dir = await getApplicationDocumentsDirectory();
>     isar = await Isar.open(
>       [TodoListSchema],
>       directory: dir.path
>     );
>   }
> 
>   // List of all TodoLists
>   List<TodoList> todolists = [];
> 
>   /* Handle CRUD operations */
> 
>   // CREATE
>   void addTodoList(String plan) async {
>     final newTodoList = TodoList()..plan = plan..created = DateTime.now()..completed = false;
> 
>     // Save to DB
>     await isar.writeTxn(() => isar.todoLists.put(newTodoList));
>     
>     // Update TodoList List
>     fetchTodoList();
>   }
> 
> 
>   // READ
>   void fetchTodoList() async {
>     final currentTodoLists = isar.todoLists.where().findAllSync();
>     todolists.clear();
>     todolists.addAll(currentTodoLists);
>     notifyListeners();
>   }
> 
>   // UPDATE
>   void updateTodoList(int id, String plan) async {
>     var existingTodoList = await isar.todoLists.get(id);
>     if (existingTodoList != null) {
>       existingTodoList.plan = plan;
>       existingTodoList.modified = DateTime.now();
>       await isar.writeTxn(() => isar.todoLists.put(existingTodoList));
>     }
> 
>     // Update TodoList List
>     fetchTodoList();
>   }
> 
> 
>   // DELETE
>   void deleteTodoList(int id) async {
>     await isar.writeTxn(() => isar.todoLists.delete(id));
> 
>     // Update TodoList List
>     fetchTodoList();
>   }
> 
> 
>   // DELETE ALL
>   void deleteAllTodoLists() async {
>     await isar.writeTxn(() => isar.todoLists.clear());
> 
>     // Update TodoList List
>     fetchTodoList();
>   }
> 
>   // COMPLETED
>   void completed(int id) async {
>     var existingTodoList = await isar.todoLists.get(id);
>     if (existingTodoList != null) {
>       existingTodoList.completed = true;
>       await isar.writeTxn(() => isar.todoLists.put(existingTodoList));
>     }
> 
>     // Update TodoList List
>     fetchTodoList();
>   }
> 
>   // REPLAN
>   void replan(int id) async {
>     var existingTodoList = await isar.todoLists.get(id);
>     if (existingTodoList != null) {
>       existingTodoList.completed = false;
>       await isar.writeTxn(() => isar.todoLists.put(existingTodoList));
>     }
> 
>     // Update TodoList List
>     fetchTodoList();
>   }
> ```

The function you are trying to use (`contentWordsElementEqualTo`, or any functions ending with `ElementEqualTo`) is only generated for properties that are of type [`List`](https://api.dart.dev/stable/3.2.4/dart-core/List-class.html), and you have none of that type, hence why you cannot use this function.

**Comment by CovenantJunior** [comment]
Ooh, OK. My bad. Thanks a lot!
