### ISSUE TITLE
The method `findAll` isn't defined for the type `QueryBuilder`.

### ISSUE THREAD

**Issue by twoco** [isar/isar#1094]
### Steps to Reproduce

I'm trying to get all entries from the collection using [docs](https://isar.dev/crud.html#reading-from-the-database).

### Code sample

```dart
isarDb = await Isar.open([LogSchema]);
logs = await isarDb.logs.where().findAll(); // <- The method 'findAll' isn't defined for the type 'QueryBuilder'.
//                               ^^^^^^^
```

### Details

 - Platform: Currently Android emulator on Windows 11.
 - Flutter version: 3.3.10 
 - Isar version: 3.0.5
 - VS Code version: 1.75.1
 - Flutter/Dart VS Code Ext: 3.58.0
---

It might be my fault. I remember this working a while ago. I'm not sure if the docs are outdated. I cannot find any related issue and don't see any code issues. The `get` method work. Also `where` exists. But the methods are e.g. `anyId`, `isBetween`, etc. of `QueryBuilder`.

Another weird issue is that the collection memebers of the isar instance are not available in IntelliSense suggestions, if the isar db is `open` from another file. But it's maybe another (not related) issue.

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

<details>
  <summary><h3>More Code (click to show)</h3></summary>
  
 **log.dart**

```dart
import 'package:isar/isar.dart';

part 'log.g.dart';

@collection
class Log {
  Id id = Isar.autoIncrement;
  int? value;
}
```

**db.dart**

```dart
late Isar isarDb;

Future<void> isarInit() async {
  isarDb = await Isar.open([LogSchema]);
}
```

**main.dart**

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await isarInit();
  runApp(const MyApp());
}
```

**log_service.dart**

```dart
class LogService with ChangeNotifier {
  List<Log> logs = [];

  void init() async {
    logs = await isarDb.logs.where().findAll(); // <- The method 'findAll' isn't defined for the type 'QueryBuilder'.
    notifyListeners();
  }
}
```
</details>

**Comment by AdarshaBista** [comment]
You need to import isar on the `log_service.dart` file too.
```dart
import 'package:isar/isar.dart';
```

**Comment by twoco** [comment]
Interesting... it works. Thanks. I'm new to Dart and don't quite understand it, but ok. Good to know. I guess it's because the generated file (log.g.dart) uses Isar indirectly, but does not import. The use of that always requires import isar in same file. Idk why I didn't think of simply importing isar here. Thanks again. ^^
