### ISSUE TITLE
Id type error not true

### ISSUE THREAD

**Issue by ffpetrovic** [isar/isar#110]
**Steps to Reproduce**
The source [here](https://github.com/isar/isar/blob/71a633fcaaba828e35301443a453ee49cd497a3c/packages/isar_generator/lib/src/isar_analyzer.dart#L206-L207), specifically the condition and corresponding error don't line up. The error says that what's supported is "String, Int and Long", yet what's actually supported is `Long` and `Int`.

**Comment by GearGit** [comment]
> **Steps to Reproduce**
> The source [here](https://github.com/isar/isar/blob/71a633fcaaba828e35301443a453ee49cd497a3c/packages/isar_generator/lib/src/isar_analyzer.dart#L206-L207), specifically the condition and corresponding error don't line up. The error says that what's supported is "String, Int and Long", yet what's actually supported is `Long` and `Int`.

Should we change it from:
```
err('Illegal id type. Allowed: String, Int, Long', property);
```
to:
```
err('Illegal id type. Allowed: Int, Long', property);
```

**Comment by stevokk** [comment]
Is the issue that the isar-core hasn't implemented String ID comparator function or that the String type is yet to be supported at all? For distributed record creation 128bit UUID or ULID are common (the latter being easily sorted and existing in Dart/Rust). 

After some extensive Google-foo, the underlying LMDB store supports any key with the compare function being the missing piece per type if you don't want it to sort lexically (though still fairly performant for a first implementation?). Scanning through the isar-core I think it enforces numerical IDs out of choice.

I'm only coming across this topic entirely today to maybe I'm off base here, but I'd think allowing 128bit String IDs is okay?

**Comment by leisim** [comment]
Fixed with stable release

**Comment by gustavorozolin** [comment]
First of all congratulations for your work, I am a Hive user. In my business I need to have a String ID, do you intend to implement this in future versions of Isar? Thanks
