### ISSUE TITLE
Support for Map type

### ISSUE THREAD

**Issue by Mmisiek** [isar/isar#1107]
**Is your feature request related to a problem? Please describe.**
In my Firebase schema I am using Map data type. I am trying to create offline version of it but Map is not supported.

**Describe the solution you'd like**
Map datatype to be supported.

**Describe alternatives you've considered**
Convert Maps to nested objects lists. 

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.5.4]
 - Isar version: [e.g. 0.5.0]

**Comment by JaffaKetchup** [comment]
(See https://github.com/isar/isar/issues/32 maybe?)

**Comment by simc** [comment]
This is supported in v4

**Comment by triggerfx** [comment]
> This is supported in v4

Sorry to ask, I am very new, but is there already a expected date for release?

**Comment by tomasweigenast** [comment]
@simc It is not supported in 4.0.0-dev14
```
Unsupported type. Please add @embedded to the type or implement toJson() and fromJson() methods or annotate the property with @ignore let Isar to ignore it.
package:core/data/models/user/user.freezed.dart:326:28
    ╷
326 │   Map<String, double>? get profitPercentage =>
```

**Comment by yakou32** [comment]
I hope List<Map> will be supported as well :)

**Comment by moshOntong-IT** [comment]
no updated yet because the author of this project seems abandoned this

**Comment by omtodkar** [comment]
Is there any new update? Facing same issue for dynamic map.
