### ISSUE TITLE
can't be represented exactly in JavaScript

### ISSUE THREAD

**Issue by mengzhidaren** [isar/isar#1109]
### Steps to Reproduce
Run the web platform every time

### Code sample

```dart

@Collection(accessor: 'report')
class ReportDB {
  Id id = Isar.autoIncrement;
  String userId = ""; 
  int createTime = 0;
}

```

### Details
------------------------------------
 - Platform: web
 - Flutter version: [3.7.3]
 - Isar version: [3.0.5]
 - Chrome version [109.0.5414.75]
------------------------------------
pubspec.yaml:
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  isar: ^3.0.5
------------------------------------
flutter doctor
 -Flutter (Channel stable, 3.7.3, on Microsoft Windows [版本 10.0.22000.1455], locale zh-CN)
 -Chrome - develop for the web
------------------------------------
log:
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
module/lib_db/lib/dao/box.g.dart:18:7: Error: The integer literal 2746750398816438969 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 2746750398816438784 is the nearest value that can be represented exactly.
  id: 2746750398816438969,
      ^^^^^^^^^^^^^^^^^^^
------------------------------------

**Comment by Likeyong** [comment]
请问这个问题你是怎么解决的?
