### ISSUE TITLE
[bug] libisar.dylib' (no such file), 

### ISSUE THREAD

**Issue by zhangruiyu** [isar/isar#1112]
flutter 3.7.3

I just added a dependency to the pubspec.yaml file and ran macapp with the following error

![image](https://user-images.githubusercontent.com/10591822/219311826-3f8bbc5c-7ce2-4af0-a4c9-175872c116cf.png)
![image](https://user-images.githubusercontent.com/10591822/219311847-9779478a-0813-4fe7-8017-3dd273b3e158.png)

**Comment by zhangruiyu** [comment]
Library not loaded: /Users/runner/work/isar/isar/target/x86_64-apple-darwin/release/deps/libisar.dylib
  Referenced from: <EB7DCAF5-8C16-310C-8CDB-DE805C46356A> /Users/maohouzi/WorkProjects/otod/build/macos/Build/Products/Debug/otod.app/Contents/MacOS/otod
  Reason: tried: '/Users/runner/work/isar/isar/target/x86_64-apple-darwin/release/deps/libisar.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/isar/isar/target/x86_64-apple-darwin/release/deps/libisar.dylib' (no such file), '/Users/runner/work/isar/isar/target/x86_64-apple-darwin/release/deps/libisar.dylib' (no such file), '/usr/local/lib/libisar.dylib' (no such file), '/usr/lib/libisar.dylib' (no such file, not in dyld cache)

**Comment by CaptainDario** [comment]
Also happens to me with v3.0.6 alpha

**Comment by simc** [comment]
Fixed in `3.1.0+1`
