### ISSUE TITLE
Android : Isar Inspector not working for flutter add-to-app 

### ISSUE THREAD

**Issue by patilvishwanath** [isar/isar#1113]
Isar Inspector not working for flutter add-to-app for Android device.
Please find below details

### Steps to Reproduce

I am using flutter codebase as a lib into existing Kotlin CodeBase. Followed this flutter doc for the impl : 
[add-to-app](https://docs.flutter.dev/development/add-to-app)

### Code sample

```dart
class IsarStorage {
  IsarStorage._();
  static final IsarStorage isarStorage = IsarStorage._();


  late Isar isar;

  Future<void> init() async {
    isar = await Isar.open([CacheItemSchema]);
  }


 Future<void> delete(String key) async {
    await isar.writeTxn(() async {
      final success = await isar.cacheItems.filter().keyStartsWith(key).deleteFirst();
      print('Cache --  Isar deleted for  ${key} : $success');
    });
  }

  Future<CacheItem?> getData<T>(String key) async {
    final success =  await isar.cacheItems.
  filter().keyMatches(key).findFirst();
    print('Cache -- Isar getData for param ${key} : ${success?.key}');
    return success;
  }

  

  Future<void> set<T>(CacheItem item) async {
    await isar.writeTxn(() async {
      final success = await isar.cacheItems.put(item);
      print('Cache -- Isar put key ${item.key} : $success');
    });
  }
}

```
main.dart
```dart
await IsarStorage.isarStorage.init();
```

### Details

 - Platform: One plus 6 Android 11
 - Flutter version: [e.g. 3.3.10]
 - Isar version: [e.g. 3.0.5]

---

<details><summary>ScreenShots</summary>
<p>

<img width="1440" alt="Screenshot 2023-02-16 at 5 00 06 PM" src="https://user-images.githubusercontent.com/23475948/219355289-9959aab1-3c40-4b09-b984-ae3f67c8cd5e.png">
<img width="757" alt="Screenshot 2023-02-16 at 5 07 16 PM" src="https://user-images.githubusercontent.com/23475948/219355298-64f6a860-cae8-4538-9f65-7b6ce78c730c.png">
<img width="1440" alt="Screenshot 2023-02-16 at 5 20 54 PM" src="https://user-images.githubusercontent.com/23475948/219357613-3a9a5fe2-a535-4ca8-8361-8119e0b24ed6.png">

</p>
</details>

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by mbn18** [comment]
Same goes for me.
Scenario 1: Build regular `flutter app` - the inspector work
Scenario 2: Build `AAR` module from `flutter` and use it in `Android app` - inspector link is show in the `lgocat` but impossible to connect to.

**Comment by simc** [comment]
This is a Flutter limitation unfortunately
