### ISSUE TITLE
IsarError: IllegalArg: Please provide a valid directory..

### ISSUE THREAD

**Issue by RakaAlrian** [isar/isar#1116]
### Steps to Reproduce
Hi, thanks for this library. Currently I got an error with this library when I run the project on android emulator API 23 or below.

Here is the error :
```
I/flutter ( 4185): ╔════════════════════════════════════════════════════╗
I/flutter ( 4185): ║                ISAR CONNECT STARTED                ║
I/flutter ( 4185): ╟────────────────────────────────────────────────────╢
I/flutter ( 4185): ║        Open the link to connect to the Isar        ║
I/flutter ( 4185): ║       Inspector while this build is running.       ║
I/flutter ( 4185): ╟────────────────────────────────────────────────────╢
I/flutter ( 4185): ║ https://inspect.isar.dev/3.0.5/#/49896/KcmGNpQ7LbI ║
I/flutter ( 4185): ╚════════════════════════════════════════════════════╝
I/flutter ( 4185): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 4185): IsarError: IllegalArg: Please provide a valid directory..
I/flutter ( 4185):
I/flutter ( 4185): ----------------------------------------------------
E/Surface ( 4185): getSlotFromBufferLocked: unknown buffer: 0x7f1c69dacce0
```

I'm using Riverpod to provide Isar instance like this :
_app_database.dart_
```dart
final provideAppDb = Provider.autoDispose<Isar>((ref) {
  throw UnimplementedError();
});

mixin AppDatabase {
  static Isar? _isar;

  static Future<Isar> getInstance() async {
    if (Isar.instanceNames.isEmpty || _isar == null) {
      _isar = await Isar.open(
        [
          TokenCollectionSchema,
          UserCollectionSchema,
        ],
        name: "amazing-app",
        inspector: true,
      );
    }

    return _isar!;
  }
}
```
_app.dart_
```dart
Future<void> main() async {
  await dotenv.load();
  runApp(await intializeApp());
}

Future intializeApp() async {
  WidgetsFlutterBinding.ensureInitialized();

  ConstData.secretKey = dotenv.env["SECRET_KEY"] ?? "";
  ConstData.baseUrl = dotenv.env["BASE_URL"] ?? "";

  await Firebase.initializeApp();

  FlutterError.onError = (errorDetails) {
    FirebaseCrashlytics.instance.recordFlutterError(errorDetails);
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack);
    return true;
  };

  final appDb = await AppDatabase.getInstance();

  return ProviderScope(
    overrides: [
      provideAppDb.overrideWithValue(appDb),
    ],
    child: const AmazingApp(),
  );
}
```
Here is my flutter doctor :
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22621.1265], locale id-ID)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] VS Code (version 1.75.1)
[√] Connected device (1 available)
[√] HTTP Host Availability

• No issues found!
```

### Details

 - Platform: Emulator Pixel 4 API 23, Emulator Pixel 4 API 22, Emulator Nexus S API 23,
 - Flutter version: 3.7.1
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by Dev-Zombie** [comment]
I have same issue with a new project

**Comment by BradKwon** [comment]
Same error message is reported in my Crashlytics.

Mine is only on Android 6 as my app's minimum supported api is 23.

Here is my flutter doctor :

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.2.1 22D68 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

Isar version: 3.0.5

Stack trace from Crashlytics on Android 6.0.1 device:
```

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: IsarError: IllegalArg: Please provide a valid directory... Error thrown Uncaught error: .
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:119)
```

**Comment by dayron9110** [comment]
I have the same error

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: IsarError: IllegalArg: Please provide a valid directory... Error thrown null.
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:119)
       at _initFirebase.<fn>(main.dart:122)
```

**Comment by inkomomutane** [comment]
@RakaAlrian  @Dev-Zombie  @dayron9110  @BradKwon  @ritksm  
Hi  I'm not expert on it but i solved this problem using this approach.
Installing package `path_provider` and then  adding a path to may isar opened instance 
`Future<Isar> isar = Isar.open([GenreSchema], directory: (await getApplicationDocumentsDirectory()).path);`
I think that your can have better solutions now but until @simc  update you can use this start point.

Nb: 'I dint use on production  `env`, i'm still in dev now'

**Comment by RakaAlrian** [comment]
@inkomomutane awesome, this is working! but can you explain more why you prefer using `getApplicationDocumentsDirectory`? Since the path_provider documentation said :
> Consider using another path, such as [getApplicationSupportDirectory] or [getExternalStorageDirectory], if the data is not user-generated.

anyway, thankyou!

**Comment by inkomomutane** [comment]
@RakaAlrian  thanks for the point of view.
 I chose because it's private to user, that's means that only you app can have access to it and in the same time you can store edit data, Like crud operation **user generated data** and you steal no worry about user accidentally modify or delete you `libisar.so` file. instead of `[getApplicationSupportDirectory] or [getExternalStorageDirectory]`.

`Documents directory
    A directory for the app to store files that only it can access. The system clears the directory only when the app is deleted. On iOS, this corresponds to the NSDocumentDirectory. On Android, this is the AppData directory.

This example stores information in the documents directory. You can find the path to the documents directory as follows:`

[More info or Ref:](https://docs.flutter.dev/cookbook/persistence/reading-writing-files#1-find-the-correct-local-path)

**Comment by simc** [comment]
Unfortunately some Android devices don't allow automatic directory detection so with v3.1.0 you'll always have to provide a directory yourself (using `getApplicationDocumentsDirectory()`)

Hope this clears up the confusion 🙂
