### ISSUE TITLE
Error after updating a field

### ISSUE THREAD

**Issue by JsonLinesCode** [isar/isar#112]
**Steps to Reproduce**
Please describe exactly how to reproduce the problem you are running into.
- Add a field to an existing class (for me it was a non-nullable boolean)
- Run build runner
- Restart app
- Try to get data from db

**Output**
`Error 'package:isar/src/native/binary/binary_writer.dart': Failed assertion: line 24 pos 12: '!staticOffset || offset < _staticSize': is not true.`

Something weird is that I'm not able to fix this by deleting the data.mdb file and lock : it is still persisting until app reinstallation 
**Code sample**
```dart
//(how I'm getting data)
return await isarInstance.things.where().findAll();

//(how I open the db)
initIsar() async {
    var dir = await FolderAppUtil.getDirectory();
    isar = await openIsar(directory: "${dir.path}/offline");
}

```

**Version**
 - Platform: Android
 - Flutter version: 2.2.0
 - Isar version: 0.4.0
 - Isar Generator version: ^0.4.0

**Comment by ModernChocolate** [comment]
Oh, btw it was during a writing operation and not a reading operation.

**Comment by barbalex** [comment]
I am suddenly getting this error pretty constantly. After trying to get windows desktop mode to work.

**Comment by leisim** [comment]
Fixed with stable release

**Comment by spatialbits** [comment]
I'm running into this.  Using `1.0.5, added several new int and double properties to my model and started receiving `offset < _staticSize` errors when trying to write. Upgraded to `2.0.0` and also receiving the error.

**Comment by leisim** [comment]
@spatialbits thanks for letting me know. It would be extremely helpful if you could send me the model before and after the changes 🙌

**Comment by spatialbits** [comment]
yeah for sure.

![image](https://user-images.githubusercontent.com/4192023/151033785-39b01905-8e39-414d-b88b-73cfe4ca57f5.png)

(in case string constants scratch your eyeballs, I'm still experimenting with working out how get string prop names for building queries before passing into isar collection objects. Would you suggest using a generator?)

**Comment by leisim** [comment]
Thanks a lot! I will take care of it.

**Comment by spatialbits** [comment]
loving your work btw. Great job 🚀
