### ISSUE TITLE
when will you release support for web 

### ISSUE THREAD

**Issue by MainTEstere** [isar/isar#1123]
i would like to request you to  release support to web as fast as possible.
because i liked the way of fetching data from database by using async functions and it is also very user friendly. while coming web 
we don't have. 
 
please do and release as much as fast as possible.

Thanks in Advance

**Comment by SSebigo** [comment]
Hasn't Isar supported web for almost a year now?
I mean, at least I have been using it on the web for a good while now.

[Isar](https://pub.dev/packages/isar)

**Comment by justro** [comment]
> Hasn't Isar supported web for almost a year now? I mean, at least I have been using it on the web for a good while now.
> 
> [Isar](https://pub.dev/packages/isar)

They are probably asking for web-support in the latest version: https://github.com/isar/isar/issues/686

**Comment by boyd-boyd** [comment]
> 

can you tell me which version you are using.
As mine is giving following error:
Error: The integer literal 7464581877567107533 can't be represented exactly in JavaScript.
database.g.dart:18
Try changing the literal to something that can be represented in Javascript. In Javascript 7464581877567107072 is the nearest value that can be represented exactly.
  id: 7464581877567107533,
      ^^^^^^^^^^^^^^^^^^^

**Comment by SSebigo** [comment]
@boyd-boyd 
```
dependencies:
   isar: 3.0.5

dependency_overrides:
   isar_generator: 3.0.5
```

**Comment by Shubham-Narkhede** [comment]
Is this solved?
