### ISSUE TITLE
Active backing of database into a file

### ISSUE THREAD

**Issue by AAverin** [isar/isar#1133]
**Is your feature request related to a problem? Please describe.**
I would like to share the state of the database between platforms using some shared file in Dropbox/Google Drive/Box/etc.

**Describe the solution you'd like**
It would be great to have a built-in way to point database to some local file to have it as an active backup. File state should be synchronised in real time if data is modified in the database and back to database if the file was updated.

**Describe alternatives you've considered**
I have looked into `Query.exportJsonRaw` and `Collection.importJsonRAW`. While those methods can probably be used to build some kind of synchronisation, it will not be real-time and active and would be prone to errors as Query export might not match Collection import structure and with the complexity of the database growing this would be more difficult to manage.

There is also `Isar.copyToFile` that creates a backup of compacted version of the database into a file, but it is unclear how to import such copied state later back into the database and how to deal with active/realtime requirement here.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web

**Comment by JaffaKetchup** [comment]
Once you've used `copyToFile`, you can just open that file straight back up again: it's a valid database file.
If you want to see a fairly complex and by no means minimal implementation of mine, see https://github.com/JaffaKetchup/fmtc_plus_sharing/blob/e1abe512d752b82e1564e2804ddbdb0b8e2746ea/lib/src/import.dart.

**Comment by simc** [comment]
This request is not in the scope of Isar. It should be rather straightforward to implement this on top of Isar.
