### ISSUE TITLE
Inspector doesn't connect if Isar is in an isolate

### ISSUE THREAD

**Issue by JCKodel** [isar/isar#1134]
### Steps to Reproduce

I'm building a state management system that works entirely on an isolate (the main thread runs Flutter, sending commands to a long-running isolate that do the hard stuff and respond back to Flutter by events).

Isar works just fine in this configuration, however, Isar Ispector says it cannot connect to the database.

If I just add the same initialization code in the main thread, everything works fine (even the Inspector url is the same):

```dart
Future<void> main() async {
  if (kDebugMode) {
    await Isar.open([AppSettingsModelSchema], inspector: true, name: "AppSettings");
  }
  
  await MyFrameworkNameHere.useEnvironment(() => const DevelopmentEnvironment());
  runApp(const ToDoApp());
}
```

but it is ugly, since the entire motivation of this new state manager is to not have boilerplate =\

(btw, in isolate, the Isar initialization is exactly the same, I just copied and pasted the line above).

### Details

 - Platform: iPhone Simulator
 - Flutter version: 3.6.5
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by LazyTaz** [comment]
A workaround I found is to basically instantiate Isar 2 times.

First time in the main thread, second time in the new Isolate.

The first instance (main thread) allows you to watch the db throught the inspector. 
The second instance is the one you can manipulate inside your Isolate.

Even if you use the second instance, the inspector will be updated !

**Comment by simc** [comment]
This is a Flutter limitation unfortunately
