### ISSUE TITLE
@embedded for objects with required parameters

### ISSUE THREAD

**Issue by bambinoua** [isar/isar#1137]
I read that Isar supports `@embedded` annotation for only objects with default constructor without required parameters. But unfortunately I need a constructor with required parameter. For example value object `Money`. This object has no sense without specifying the monetary value. Is it possible to fix this? Or mayse use a private constructor `Money._()` for such functionality?

**Comment by bobekos** [comment]
@bambinoua 
I think it can't be possible, because isar must know how to create the models, for example after you changed the model and isar must migrate the existing database.

I am using always default attributes for the embedded objects so in your case you can do something like:

```dart
@embedded
class Money {
  final double value;

  Money({this.value = 0});
}
```

**Comment by simc** [comment]
Isar v4 supports required parameters

**Comment by emirhalici** [comment]
This issue should be reopened as Isar v4 is not stable and not recommended to be used. What is the solution suggested here?
