### ISSUE TITLE
[bug] Isar.autoIncrement Iterator can't be rolled back when an error occurs in a transaction.

### ISSUE THREAD

**Issue by Meatysoda** [isar/isar#1144]
When I learn _Indexes_ part in tutorial, i found this.

### Steps to Reproduce

I try to update data into the unique index, the transaction is expected to be rolled back and it is.
But next time i run the code, the id in new `user` is not incremented by 1 instead of being incremented by 2.

Data in datebase after first run:
`user1.id = 1`
After second run:
`user1.id = 1`
`user2.id = 3`

I think if transaction is  rolled back perfectly, data is expected to be like this:
`user1.id = 1`
`user2.id = 2`

Or is this a feature?

### Code sample

```dart
class User {
Id id = Isar.autoIncrement ;
...
}
class Dict {
@index(type: IndexType.hash,unique: true)
String key;
...
}

_isar.writeTxn(() => _isar.users.put(_newUser));  //succeeded
_isar.writeTxn(() async {
    await _isar.users.put(_newUser);
    await _isar.dicts.put(Dict(key: 'dd', value: DateTime.now().toIso8601String()));
}); //failed
```

### Details

 - Platform: x86 Android Emulator
 - Flutter version: 3.7.7
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
Auto increment ids don't make any guarantee about the sequence other that it's increasing
