### ISSUE TITLE
Sort by is throws exception

### ISSUE THREAD

**Issue by centy** [isar/isar#1150]
### Steps to Reproduce

Build query: 
db.where().myProperytyEqualTo(false).filter().typeBetween(typeA, typeB).sortByPropertyC().thenById().build();

Getting exception:
════════ Exception caught by widgets library ═══════════════════════════════════
The following StateError was thrown building InheritedProvider<ABloc>:
Bad state: Tried to read a provider that threw during the creation of its value.
The exception occurred during the creation of type ABloc.

══╡ EXCEPTION CAUGHT BY PROVIDER ╞═══════════════════════════════
The following IsarError was thrown:
Unknown property "id"

When the exception was thrown, this was the stack:
#0      Schema.property
schema.dart:70
#1      buildNativeQuery
query_build.dart:60
#2      IsarCollectionImpl.buildQuery
isar_collection_impl.dart:598
#3      QueryBuilderInternal.build
query_builder.dart:281
#4      QueryExecute.build

**Comment by HasanAlqaisi** [comment]
I have the same issue

**Comment by HasanAlqaisi** [comment]
In my case I need a DESC order based on Id so I did this:
```
isar.cats
        .where(sort: Sort.desc)
        .filter()
        ...
```
But I think you don't need `thenById()` because where function already sorting ASC

**Comment by simc** [comment]
fixed in v4
