### ISSUE TITLE
Group By Data 

### ISSUE THREAD

**Issue by navigermobile** [isar/isar#1163]
How to group by data ?

- Example 
  I have questions collections with a group name, I need to get the by group name?

Regards.

**Comment by amrounix** [comment]
I wrote a workaround for my project : (I group the result list into a Map ) 
```
extension Iterables<E> on Iterable<E> {
  Map<K, List<E>> groupBy<K>(K Function(E) keyFunction) => fold(
      <K, List<E>>{},
      (Map<K, List<E>> map, E element) =>
          map..putIfAbsent(keyFunction(element), () => <E>[]).add(element));
}
```

**Comment by pcfjojo** [comment]
@amrounix Thank you for your suggestion. 

![image](https://github.com/isar/isar/assets/11698054/101c9787-b9b1-4f16-a6df-7aa0a171312b)

See the result of your method. 

I attache the snippet for those who may face the same issues.

` getTotalSalesPeriod({required DateTime from, required DateTime to, String format = "MM"}) {
    List<Order> orders = isar?.orders
        .where()
        .filter()
        .createdAtBetween(Utils.formatDayStart(from), Utils.formatDayEnd(to))
        .findAllSync() ?? [];

    final Map<String, List<Order>> listOfOrders = orders.groupBy((order) => DateFormat(format).format(order.createdAt));

    return listOfOrders;
  }`

Once I received the collection of group items, I did this.

`Map<String, List<Order>> graphData = context.read<ReportCubit>().graphData;
    for (var key in graphData.entries) {
      data.add(Data(key.key, key.value.length));
    }`

Regards,
Thanks you.

**Comment by simc** [comment]
I'll close this in favour of #976
