### ISSUE TITLE
Fix path to download Isar core

### ISSUE THREAD

**Issue by insign** [isar/isar#1168]
**Is your feature request related to a problem? Please describe.**
Using in my binary it was downloading libisar.so in every folder I ran the binary.

**Describe the solution you'd like**
I made this workaround:
```dart
final corePath = '${dataDir.path}/libisar.so';
final libraries = <Abi, String>{};
for (var abi in Abi.values) {
  libraries[abi] = corePath;
}
await Isar.initializeIsarCore(download: true, libraries: libraries);
```

**Version**
 - Platform: Mac, Windows, Linux
 - Dart version: 2.19.5
 - Isar version: 3.0.5

**Comment by insign** [comment]
You mean, it is not needed to download it anymore?

**Comment by felipebonezi** [comment]
> No for now you have to download it manually. In a few weeks when the Dart team releases the native asset feature it will be completely automatic

How do I use `Isar` on testWidgets? It isn't working on MacOSX because it wasn't the `libisar.dylib` file.
