### ISSUE TITLE
Delete an item not work. Delete all is ok

### ISSUE THREAD

**Issue by shanelau** [isar/isar#1170]
Delete an item not work. Delete all is ok

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/3140898/229551378-7dcc8208-114d-49ec-b7a3-644bb5158c30.png">
https://inspect.isar.dev/3.0.5/

### Details

 - Platform: macOS  Chrome
 - Flutter version: [3.7.6]
 - Isar version: [e.g. 3.0.5]

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by simc** [comment]
This is caused by #972
