### ISSUE TITLE
Ignore a field from codegen, but not persistance

### ISSUE THREAD

**Issue by hamishjohnson** [isar/isar#1173]
**Is your feature request related to a problem? Please describe.**
I have quite large data models. However, I only care about 1 or 2 fields for queries. The generated files then include a lot of extra code that I don't need.

**Describe the solution you'd like**
A flag, similar to @ignore, that lets me persist, but not generate code for specific properties.

**Comment by hamishjohnson** [comment]
For example, one of my generated files is over 100KB and 3600 lines

**Comment by simc** [comment]
Is there a downside of this extra code? It will be stripped from release builds :)

**Comment by hamishjohnson** [comment]
Do unused class methods also get stripped? If so, ignore :)

**Comment by simc** [comment]
Yes otherwise I would've been more careful what to generate. Flutter tree shaking can very easily determine which methods you use and all others will be removed.
