### ISSUE TITLE
Urgent: Update required for ffi and open_file package

### ISSUE THREAD

**Issue by Anilkhanna** [isar/isar#1178]
Hi Team,

Everyone moved to null safety and due to Isar database I am not able to generate Android build as we are using old open_file package. Please see the screenshot below. I request you to please update and 

```
Because isar >=3.0.0-dev.5 depends on ffi ^2.0.0 and open_file >=3.1.0 depends on ffi ^1.0.0, isar >=3.0.0-dev.5 is incompatible with open_file >=3.1.0.
So, because exp_app_70 depends on both open_file 3.1.0 and isar ^3.0.5, version solving failed.
```

I request you to please look into it and help to resolve it on priority. 

Thanks

**Comment by dastiii** [comment]
Thats not a problem with isar, its a problem with open_file depending on an old version of ffi.

Seems like ffi has been updated a long time ago in the repository of open_file (see: [Issue open_file#242](https://github.com/crazecoder/open_file/issues/242), [commit e51ec86](https://github.com/crazecoder/open_file/commit/e51ec8684e1d7fa99b545692c6196557582b878e)). They just never released a new version on pub.dev.

**Comment by simc** [comment]
Isar depends on the newest version of `ffi`
