### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by davystrong** [isar/isar#12]
Do you plan to add support for Windows/Linux/Mac to Isar? This seems like a good fit for a project I'm planning but it would need to have desktop support. You mention that it will be multiplatform in the README, but only mention Android, iOS and Web.

**Comment by leisim** [comment]
@davystrong yes definitely. There are already [binaries for Isar Core](https://github.com/isar/isar-core/releases/tag/0.0.3) and they just need to be copied in the correct directories. I didn't have time to test Isar on desktop yet so I didn't include the binaries by default.

**Comment by davystrong** [comment]
Ok, great! Hadn't noticed those. Thanks for the quick reply!

**Comment by leisim** [comment]
All desktop platforms are supported now

**Comment by barbalex** [comment]
And it works in my case. Thanks!
