### ISSUE TITLE
exception of type NSException * thread #50, queue = 'CCTClearcutUploader', stop reason = signal SIGABRT

### ISSUE THREAD

**Issue by Abdullayev3635** [isar/isar#1200]
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
2023-04-18 11:55:47.567 Runner[624/0x16d46f000] [lvl=3] -[MLKITx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable
-[__NSCFBoolean objectForKey:]: unrecognized selector sent to instance 0x1eeac8af8
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean objectForKey:]: unrecognized selector sent to instance 0x1eeac8af8'
*** First throw call stack:
(0x1958f5a24 0x18ece5958 0x195a560e0 0x19590abc8 0x19596e6dc 0x10e373510 0x19c80c7c8 0x19c7dceec 0x10e373470 0x10e374cd8 0x10e373c30 0x103405f44 0x103404f4c 0x103404020 0x19c80b850 0x19c80c7c8 0x19c7e7800 0x19c7e8290 0x19c7f2000 0x1de360b50 0x1de36067c)
libc++abi: terminating with uncaught exception of type NSException
* thread #8, queue = 'CCTClearcutUploader', stop reason = signal SIGABRT
    frame #0: 0x00000001cf256274 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1cf256274 <+8>:  b.lo   0x1cf256290               ; <+36>
    0x1cf256278 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1cf25627c <+16>: mov    x29, sp
    0x1cf256280 <+20>: bl     0x1cf251c54               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.

i got this problem when i call textRecognizer.processImage(inputImage) method   p.s the problem occurs on ios device only.

**Comment by simc** [comment]
This is not an Isar issue

**Comment by Nasserelbaba** [comment]
hi how did you fix this issue i have the same issue with facedetector please let me know how did you fix it and thanks

**Comment by mohammedX6** [comment]
actually this is isar issue
