### ISSUE TITLE
Different Ids of object in the app and in the observer. cannot delete.

### ISSUE THREAD

**Issue by mahdi-nvbi** [isar/isar#1202]
### Steps to Reproduce

I have created a collection and added a new object to the collection. But I cannot delete the object through code. I can delete it in the Isar observer though. The interesting thing is that the id of the object shown in the app is different from the id in the Isar observer. I have no idea why.

![Screenshot 2023-04-19 033722](https://user-images.githubusercontent.com/29746159/232924224-73793be7-a768-4c9f-8aec-2ccdbd3e8213.png)

![Screenshot 2023-04-19 033827](https://user-images.githubusercontent.com/29746159/232924283-a33d4116-840f-4095-bc6a-6e791f7023b2.png)

### Code sample

```dart
  Future<void> createCustomer(Customer customer) async {
    try {
      await _isar.writeTxn(() async {
        final res = await _isar.customers.put(customer);
        log(res.toString());
      });
    } on Exception catch (e) {
      log(e.toString(), error: e, name: 'create customer');
      rethrow;
    }
  }

Future<bool> removeCustomer(int customerId) async {
    log(customerId.toString());
    try {
      bool res = false;
      await _isar.writeTxn(() async {
        res = await _isar.customers.delete(customerId);
      });
      return res;
    } catch (e) {
      log(e.toString(), error: e, name: 'remove customer');
      rethrow;
    }
  }

```

### Details

 - Platform: x86 Android Emulator with API 33 on Windows.
 - Flutter version: [3.7.8]
 - Isar version: [3.0.5]

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by DMouayad** [comment]
Hi I've run into the same issue of "getting weird/ inconsistent object IDs" though I think I solved it by using a **nullable + not final** id .i.e.  `Id? id` 
You could try it and let me know if it helps.

**Comment by mahdinba97** [comment]
> Hi I've run into the same issue of "getting weird/ inconsistent object IDs" though I think I solved it by using a **nullable + not final** id .i.e. `Id? id` You could try it and let me know if it helps.

Hi. I tried what you said, but unfortunately, it did not work.

changed the field to this:
`Id? id = Isar.autoIncrement;`
