### ISSUE TITLE
Readme in Pub.dev wrong

### ISSUE THREAD

**Issue by felixkriechbaum** [isar/isar#1205]
Hi folks, there is a little bug in the readme on pub.dev

### Steps to Reproduce

Go to the pub.dev site of isar and scroll to `3. Open a database instance `
There it is explained how to open an Isar database with the new change of the directory.

### Code sample

As it says
```dart
final dir = await getApplicationDocumentsDirectory();
final isar = await Isar.open(
  [EmailSchema],
  directory: dir,
);
```
But how it works only
```dart
final dir = await getApplicationDocumentsDirectory();
final isar = await Isar.open(
  [EmailSchema],
  directory: dir.path,
);
```

**Comment by SupremeDeity** [comment]
Yes, this is how `Isar.open()` and `Isar.openSync()` works starting from v3.1.0

**Comment by felixkriechbaum** [comment]
Yes i know, but what I was trying to explain is that **.path** is missing in the example code.
``dir.path`` 
is correct. 

Only 
``dir`` 
returns the directory object instead of the path as string

**Comment by simc** [comment]
Fixed
