### ISSUE TITLE
Inspector won't run past spinner on MacOS using Chrome, Flutter build to iOS simulator

### ISSUE THREAD

**Issue by misbell** [isar/isar#1214]
### Steps to Reproduce

Please describe exactly how to reproduce the problem you are running into.

https://stackoverflow.com/questions/76104305/how-can-i-make-inspect-isar-dev-show-me-the-data-in-my-running-flutter-build

please see the above stackoverflow note.

**Comment by minizwergi** [comment]
Same issue for me. After updating to isar version > 3, the inspector stopped working in chrome and an endless spinner is displayed

**Comment by chadpav** [comment]
I had this issue using Brave (based on Chrome) and resolved it by disabling shields for the `inspect.isar.dev` domain.

Check for ad blockers, popup blockers, etc.

**Comment by ilovelinux** [comment]
I am using a clean Google Chrome installation (I use it only for Isar Inspector) on Mac OS X 13.4.1 with Isar 3.1.0 and I don't have any issues with the inspector.

**Comment by imorales021098** [comment]
> I had this issue using Brave (based on Chrome) and resolved it by disabling shields for the `inspect.isar.dev` domain.
> 
> Check for ad blockers, popup blockers, etc.

this is work for me, nice info

**Comment by simc** [comment]
Yes unfortunately many browsers and extensions block connections to localhost. There's nothing we can do and it will be obsolete once the inspector is integrated into the Dart Devtools
