### ISSUE TITLE
pin.g.dart(16,19): error G8DAFAF2B: Constant evaluation error

### ISSUE THREAD

**Issue by richard457** [isar/isar#1218]
### Steps to Reproduce

Update flutter to
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (11 days ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
and run: flutter pub run msix:create

### Details

 - Platform:  Windows e
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (11 days ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
 - Isar version: v3.1.0+1

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by antiv** [comment]
same problem here :(

**Comment by simc** [comment]
Please add a little more context an an error message with stack trace 🙂

**Comment by antiv** [comment]
Hi, there was a problem in my code, I annotated the class with @embedded, and had required properties in it. 
So, please,  ignore my previouse comment :)
