### ISSUE TITLE
How to migrate to 3.0 to 3.1 ?

### ISSUE THREAD

**Issue by Romain-Guillot** [isar/isar#1219]
If i migrate the package version from 3.0.x to 3.1.x, I cannot access to the previous database data. 

### Steps to Reproduce

1. Setup a database with Isar 3.0 :
```
isar = await Isar.open(
      [MySchema],
);
```
2. Fill the database with data
3. Migrate the package from 3.0.x to 3.1.x
4. As the [backlog](https://github.com/isar/isar/blob/main/packages/isar/CHANGELOG.md#310) mentioned it is now required to explicitly specify the `directory` attribute :
```
final dir = await getApplicationDocumentsDirectory();
isar = await Isar.open(
      [MySchema],
      directory: dir.path,
);
```

With this modification, the isar database does not reference the old database. If I downgrade the package version and if I remove the directory attribute I can reference again my original database.

There is no migration guide with this breaking change, so my question is: **with Isar 3.1.x, how to reference my database created with Isar 3.0.x ?**

### Details

 - Platform:  Android Emulator on Windows / Pixel 7.
 - Flutter version: 3.7.10.
 - Isar version: 3.1.0

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
I'd check where your old database was stored and set the directory to the same location 🙂

**Comment by alexrabin** [comment]
I'm also having this issue

**Comment by alexrabin** [comment]
@simc In 3.0.x the default directory was nsdocumentdirectory for iOS and getDataDirectory for Android but even when I use `final dir = await getApplicationDocumentsDirectory();` which says in the documentation:

> Example implementations:
> NSDocumentDirectory on iOS and macOS.
> The Flutter engine's PathUtils.getDataDirectory API on Android.

But it still results in not showing the previous data.

**Comment by alexrabin** [comment]
@Romain-Guillot  I think I figured it out. I reverted back to 3.0.5 and I printed out the original directory of my Isar instance and it says it was the ApplicationSupport directory.

I upgraded back to 3.1.0 and I pointed to the parent of the application support directory and everything is working now:

```dart
final dir = await getApplicationSupportDirectory();
final isar = await Isar.open(
        [YourSchema],
        directory: dir.parent.path);
```

**Comment by Romain-Guillot** [comment]
Thanks a lot for your investigation @alexrabin, it seems to work on my devices.

**Comment by alexrabin** [comment]
@simc Can you add this into the documentation for the upgrade guide form 3.0.X to 3.1.X?

**Comment by rohan20** [comment]
Thanks a lot, @alexrabin for your effort in figuring this out! 

In my case:

Isar 3.0.5 --> Isar 3.1.0+1
Flutter 3.3.10 --> Flutter 3.7.12

Just using the application support directly works on both Android and iOS:

```dart
final Directory isarDbStorageDirectory = await getApplicationSupportDirectory();

final Isar isar = await Isar.open(
  [YourSchema],
  directory: isarDbStorageDirectory.path, // Android ✅ & iOS ✅ 
);
```

Maybe someone else runs into the same scenario.

**Comment by iqfareez** [comment]
For Windows, what should be the directory?
