### ISSUE TITLE
unsupported swift arhitecture : while building module isar_flutter_libs

### ISSUE THREAD

**Issue by patilvishwanath** [isar/isar#1234]
HI, while creating a  local build, getting this issue for iOS platform. Trying to run on a simulator.

```dart
while building module 'isar_flutter_libs' imported from /Users/rj/Documents/tn/ui_flutter/ne_app_embed/.ios/Flutter/FlutterPluginRegistrant/Classes/GeneratedPluginRegistrant.m:46:
```

<details>
<summary>Screenshot</summary>
<img width="1459" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/23475948/236422630-1e41e1de-64d7-4ad2-be0c-7c194b058412.png">

</details>

### Details

 - Platform: Xcode 14.3, iOS 16.4, simulator, M1 mac machine.
 - Flutter version:  3.3.10
 - Isar version: 3.0.0

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by patilvishwanath** [comment]
@simc Any suggestions how to resolve this issue

**Comment by simc** [comment]
Not really @patilvishwanath I fail to reproduce the issue. iOS build works fine for my projects and in the CI

**Comment by simc** [comment]
Still unable to reproduce. Please reopen if you still have this issue

**Comment by theGlenn** [comment]
For anyone sutbbling on this iuss

`flutter clean`
`flutter build iOS`

then try and run from Xcode
