### ISSUE TITLE
Include of non-modular header inside framework module 'isar_flutter_libs.binding':

### ISSUE THREAD

**Issue by arreshashikant** [isar/isar#1235]
### Steps to Reproduce
Not able to run iOS build with following configurations, but it's working fine without package **isar_flutter_libs** 

### Details
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.3.1 22E261 darwin-arm, locale en-IN)
    • Flutter version 3.3.10 on channel stable at /opt/homebrew/Caskroom/flutter/3.3.10/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
[✓] Connected device (3 available)
    • iPhone (mobile) • 00008020-000C68662129002E • ios            • iOS 16.3.1 20D67
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3
<img width="270" alt="Screenshot 2023-05-06 at 3 42 07 PM" src="https://user-images.githubusercontent.com/126647827/236618047-11fefc53-3f6a-45e4-b7dd-70f724745795.png">

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1

**Comment by arreshashikant** [comment]
<img width="1259" alt="Screenshot 2023-05-06 at 5 06 57 PM" src="https://user-images.githubusercontent.com/126647827/236621714-e5d95f20-8960-441b-9d4d-d46ca9f96b8e.png">

**Comment by simc** [comment]
Fixed, should be released in the coming days
