### ISSUE TITLE
Updating a watch stream of a property when only the underlying value has changed.

### ISSUE THREAD

**Issue by Curstantine** [isar/isar#1237]
**Is your feature request related to a problem? Please describe.**
Currently, even if we select a property in an object watch query, the stream gets updated regardless of whether the value of the property has changed. And there is no definite way to watch only a single property of an object like in [hive](https://docs.hivedb.dev/#/basics/hive_in_flutter?id=listening-for-specific-keys).

This would come in handy for applications where isar is being used as a settings [store](https://github.com/isar/isar/discussions/572#discussioncomment-3438611).

**Describe the solution you'd like**
A way to select and watch only a single property like hive's `box.listenable(keys: ["property1"])`.

A viable solution would be to only update the stream when the underlying value selected for that query has changed, as it sounds logical since the property was explicitly selected.

As an example:
```dart
@Collection(accessor: "settings")
class Settings {
	static const isarKey = "contentFilterSettings";

	final Id id = Isar.autoIncrement;

	@Index(unique: true, replace: true)
	final String key = isarKey;

	late bool persistFilters;

	@Enumerated(EnumType.ordinal)
	late List<Language> languages;
}

final selectedLanguageStream = Isar.settings.where()
	.keyEqualTo(id)
	.languagesProperty()
	.watch(fireImmediately: true)
	.asyncMap((e) => e.first);

final wholeStream = Isar.settings.where()
	.keyEqualTo(id)
	.watch(fireImmediately: true)
	.asyncMap((e) => e.first);

selectedLanguageStream.listen((event) {
	print("selectedLanguageStream: $event");
	// Prints only selectedLanguageStream: ...languages: [Language.english, Language.german]
});

wholeStream.listen((event) {
	print("wholeStream: $event");
	// Prints wholeStream: ...languages: [Language.english, Language.german]
	// and wholeStream: ...persistFilters: true
});

Isar.writeTxn(() async {
	final settings = await Isar.settings.getByKey(id);
	await Isar.settings.put(settings.copyWith(languages: [Language.english, Language.german]))
});

Isar.writeTxn(() async {
	final settings = await Isar.settings.getByKey(id);
	await Isar.settings.put(settings.copyWith(persistFilters: true))
});
```

**Version**
 - Platform: Android
 - Flutter version: 3.7.12
 - Isar version: 3.0.5

**Comment by simc** [comment]
This is not supported by Isar. You have to check it yourself
