### ISSUE TITLE
Different order when reading IsarLinks

### ISSUE THREAD

**Issue by atpcom** [isar/isar#1245]
### Steps to Reproduce

Why do I get different order of my objects when reading IsarLinks? How to fix it?

### Code sample

```dart
void addOperation({
    required TypeOperation typeOperation,
    required double amount,
    required List<Account> accounts,
  }) async {
    final isar = ref.read(isarProvider).value!;
    final operation = Operation()
      ..typeOperation = typeOperation
      ..amount = amount
      ..accounts.addAll(accounts);
    await isar.writeTxn(() async {
      await isar.collection<Operation>().put(operation);
      await operation.accounts.save();
    });
    
    for (var account in operation.accounts) {
      print(account.title); //I get a different order of my objects (Accounts) which is different from the original List<Account>
    }
}
```

### Details

 - Platform: iPhone 13 Pro, Galaxy S7, x86 Android Emulator on Windows etc.
 - Flutter version: [e.g. 3.0.0]
 - Isar version: [e.g. 2.5.0]

---

 - [ ] I searched for similar issues already
 - [ ] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by simc** [comment]
Isar links extend `Set` which does not provide ordering
