### ISSUE TITLE
.max() always return null even though there is a record in database

### ISSUE THREAD

**Issue by Abdox3** [isar/isar#1248]
### Code sample

```dart
final isarPod = FutureProvider((ref) async {
    final dir = await getApplicationDocumentsDirectory();
    return Isar.open([TrixSchema], directory: dir.path);
  });


final isar = await ref.read(isarPod.future);

final  result = await isar.trixs.where().idProperty().max();
//result : null

final result = await isar.trixs.where().idProperty().findAll();
//result: [0]

final  result = await isar.trixs.where().idProperty().count();
//result: 1
```

### Details

 - Platform:  Android Emulator API 33 on Windows etc.
 - Flutter version: 3.7.12
 - Isar version: ^3.1.0+1

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
This is fixed in Isar v4
