### ISSUE TITLE
add a simple command so people can move from hive to ISAR in a click

### ISSUE THREAD

**Issue by fisforfaheem** [isar/isar#1250]
this would help people use it

**Comment by simc** [comment]
Do you have a suggestion how that could work?

**Comment by fisforfaheem** [comment]
It has a lot of benefits, if there were a command someone writes in the terminal, similar to Dart fix --apply, As hive is not much updated like Isar, it's much needed.

**Comment by simc** [comment]
I agree it would be cool but I have no idea how such a tool would work internally and what kind of transformations it could do. The two databases work very differently. Any suggestions? 🙂

**Comment by fisforfaheem** [comment]
Me too, but i thought it would be a great idea anyway, I also don't know
how.

Also please explicitly mention that nee hive users move to isar, so they
use isar instead of learning hive.

**Comment by monsieurtanuki** [comment]
The first step would be to write a migration guide, in order to have clear ideas about what can be automated.

**Comment by fisforfaheem** [comment]
Exactly 💯, I was starting a course with hive, but just this week came to
know about isar and it's benefits and regular updates

**Comment by fisforfaheem** [comment]
Sounds like a good idea. Also please update the documentation look and
feel, and make it pure beginner friendly



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/15/23,
02:48:42 PM

**Comment by simc** [comment]
What do you dislike about the docs look and feel? Always happy for suggestions 💜 I'll definitely add more real world examples

**Comment by monsieurtanuki** [comment]
> I will ask Hive users officially to move over when Isar v4 is stable. What do you think about a new `isar_kv` package that offers a very similar API and feature set as Hive but depends on Isar. Then people can use a familiar API but get all the benefits of Isar.

@simc We basically use `hive` as a `Map<String, json>` (cf. https://github.com/openfoodfacts/smooth-app/issues/3967).
The impact on our app would be minimal, and limited to our DAO classes.
We would still have to migrate data from `hive` to `isar`.
In our case, `isar_kv` would not be significantly helpful and we would not use it.

**Comment by yaircaballero10** [comment]
Hay un error en alguno dispositivos, cuando se migra de la versión isar 3.0.5 a 3.1.0+1 

hubo una ruptura, volverá a pasar eso en isar más adelante, yo siento un poco de desconfianza ya que hive está estable.

**Comment by simc** [comment]
Hive will get a new version that uses Isar internally

**Comment by fisforfaheem** [comment]
So what's the purpose of this? Why two databases?
