### ISSUE TITLE
[Feature request] allows inspect database / debug on local without internet data

### ISSUE THREAD

**Issue by azkadev** [isar/isar#1251]
As a developer who doesn't have a lot and fast internet, I really want you to make an inspect database on localhost
![Screenshot from 2023-05-14 16-28-01](https://github.com/isar/isar/assets/82513502/b959d9e1-d49a-4da9-9a21-5fa978d639c9)

I'm also worried that my data could be stolen.

Sorry for my bad request and english

**Comment by simc** [comment]
That should be easy: Just clone the Isar repository and run the inspector on your machine. FIY: Data NEVER leaves your device. The inspector runs locally. Just the files are hosted on inspect.isar.dev.

**Comment by MichalNemec** [comment]
How did you do it? Mine cant connect

![image](https://github.com/isar/isar/assets/5663019/d2a6b30e-d3e2-45b5-a7ad-8e5f3f33cdbd)

**Comment by azkadev** [comment]
> How did you do it? Mine cant connect
> 
> ![image](https://user-images.githubusercontent.com/5663019/279763102-d2a6b30e-d3e2-45b5-a7ad-8e5f3f33cdbd.png)

I have made my own package to support local without internet

https://github.com/isar/isar/issues/1251#issuecomment-1789430605
