### ISSUE TITLE
check open transaction 

### ISSUE THREAD

**Issue by alimcomp** [isar/isar#1252]
Hi 
I want to check whether there is open transaction or not

**Comment by simc** [comment]
Could you elaborate your use case a little more? You can always keep track yourself of active transactions.

**Comment by alimcomp** [comment]
@simc I want to use  implement Unit Of Work with Repositories and Clean Architecture  in my flutter project
In this scenario I have to  run transaction above some repository at application layer . and  some time just use repository without transaction and because of that I have to put transaction with condition inside of my repository .

**Comment by simc** [comment]
I recommend tracking transactions in another way. This is not a common use case and I don't think it makes sense to implement this.

**Comment by ravinderparihar** [comment]
Hi simc
I am getting error below
Unhandled Exception: IsarError: Cannot perform this operation from within an active transaction. Isar does not support nesting transactions

in application I have a list of items stored in DB which items I want to post on server one by one and on server response I am deliting item from DB, but while delete first time it delete item and for 2nd item I am getting above error, can you please help

**Comment by DaaTechTeam** [comment]
I have also run into this error IsarError: Cannot perform this operation from within an active transaction. Isar does not support nesting transactions.
I have IsarLink on a collection of app user. At the Initial run, the should be a supper Admin user saved in the database who will act to save the admin user. Meaning I want to save two users at the save time and use the first one as the link to the second one.
![Screenshot 2024-07-09 015718](https://github.com/isar/isar/assets/121167167/a4b54259-a943-4b7b-bff3-39168e7d195b)
