### ISSUE TITLE
Update to 3.1.0+1 from 3.0.5 results in error in isar_generator

### ISSUE THREAD

**Issue by mrclauss** [isar/isar#1262]
### Steps to Reproduce

Updated from 3.0.5 to 3.1.0+1 without any other package changes.

### Code sample

Lots of erros in isar_analyzer happen, see below.
Clean and full rebuild did not help.

### Details

[WARNING] /C:/Users/mc/AppData/Local/Pub/Cache/hosted/pub.dev/isar_generator-3.1.0+1/lib/src/isar_analyzer.dart:127:19: Error: The getter 'element' isn't defined for the class 'InterfaceType'.
 - 'InterfaceType' is from 'package:analyzer/dart/element/type.dart' ('/C:/Users/mc/AppData/Local/Pub/Cache/hosted/pub.dev/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
      return type.element.collectionAnnotation != null ||
                  ^^^^^^^

Packages:
dependencies:
- nativeaccess 0.0.1
  - flutter any
  - flutter_web_plugins any
  - plugin_platform_interface ^2.0.2
- flutter 0.0.0
  - characters 1.2.1
  - collection 1.17.0
  - js 0.6.5
  - material_color_utilities 0.2.0
  - meta 1.8.0
  - vector_math 2.1.4
  - sky_engine any
- flutter_localizations 0.0.0
  - flutter any
  - intl 0.17.0
  - characters 1.2.1
  - clock 1.1.1
  - collection 1.17.0
  - js 0.6.5
  - material_color_utilities 0.2.0
  - meta 1.8.0
  - path 1.8.2
  - vector_math 2.1.4
- flutter_local_notifications 12.0.3+1
  - clock ^1.1.0
  - flutter any
  - flutter_local_notifications_linux >=1.0.0 <3.0.0
  - flutter_local_notifications_platform_interface ^6.0.0
  - timezone ^0.9.0
- intl 0.17.0
  - clock ^1.1.0
  - path ^1.8.0
- ctaapi 1.0.0
  - http >=0.13.0 <0.14.0
  - intl ^0.17.0
  - meta ^1.1.8
- pointycastle 3.6.2
  - collection ^1.15.0
  - convert ^3.0.0
  - js ^0.6.3
- asn1lib 1.1.1
- encrypt 5.0.1
  - args ^2.0.0
  - asn1lib ^1.0.0
  - clock ^1.1.0
  - collection ^1.15.0
  - crypto ^3.0.0
  - pointycastle ^3.2.0
- flutter_svg 1.1.5
  - flutter any
  - meta ^1.7.0
  - path_drawing ^1.0.1
  - vector_math ^2.1.2
  - xml ^6.0.1
- firebase_core 2.7.0
  - firebase_core_platform_interface ^4.5.3
  - firebase_core_web ^2.2.1
  - flutter any
  - meta ^1.3.0
- firebase_messaging 14.2.5
  - firebase_core ^2.7.0
  - firebase_core_platform_interface ^4.5.3
  - firebase_messaging_platform_interface ^4.2.14
  - firebase_messaging_web ^3.2.15
  - flutter any
  - meta ^1.3.0
- phone_numbers_parser 7.0.0+1
  - phone_number_metadata ^5.0.4
  - meta ^1.7.0
  - dart_countries ^3.0.2
- flutter_sim_country_code 0.1.2
  - flutter any
- uni_links 0.5.1
  - flutter any
  - uni_links_platform_interface ^1.0.0
  - uni_links_web ^0.1.0
- cupertino_icons 1.0.5
- draggable_scrollbar 0.1.0
  - flutter any
- isar 3.1.0+1
  - ffi >=2.0.0 <3.0.0
  - js ^0.6.4
  - meta ^1.7.0
- isar_flutter_libs 3.1.0+1
  - flutter any
  - isar 3.1.0+1
- path_provider 2.0.11
  - flutter any
  - path_provider_android ^2.0.6
  - path_provider_ios ^2.0.6
  - path_provider_linux ^2.0.1
  - path_provider_macos ^2.0.0
  - path_provider_platform_interface ^2.0.0
  - path_provider_windows ^2.0.2
- format 1.1.1
  - characters ^1.1.0
  - intl ^0.17.0
- timeago 3.3.0
  - intl ^0.17.0
- background_fetch 1.1.5
  - flutter any
- url_launcher 6.1.6
  - flutter any
  - url_launcher_android ^6.0.13
  - url_launcher_ios ^6.0.13
  - url_launcher_linux >=2.0.0 <4.0.0
  - url_launcher_macos >=2.0.0 <4.0.0
  - url_launcher_platform_interface ^2.1.0
  - url_launcher_web ^2.0.0
  - url_launcher_windows >=2.0.0 <4.0.0
- qr_flutter 4.0.0
  - flutter any
  - qr ^2.0.0
- catcher 0.7.0
  - flutter any
  - flutter_web_plugins any
  - fluttertoast ^8.0.8
  - device_info_plus ^7.0.0
  - device_info_plus_platform_interface ^6.0.0
  - package_info_plus ^3.0.0
  - mailer ^5.0.2
  - dio ^4.0.1
  - flutter_mailer ^2.0.0
  - logging ^1.0.2
  - sentry ^6.1.0
  - universal_io ^2.0.4
- percent_indicator 4.2.2
  - flutter any
- synchronized 3.0.1
- firebase_auth 4.2.9
  - firebase_auth_platform_interface ^6.11.11
  - firebase_auth_web ^5.2.8
  - firebase_core ^2.7.0
  - firebase_core_platform_interface ^4.5.3
  - flutter any
  - meta ^1.3.0
- google_sign_in 6.0.2
  - flutter any
  - google_sign_in_android ^6.1.0
  - google_sign_in_ios ^5.5.0
  - google_sign_in_platform_interface ^2.2.0
  - google_sign_in_web ^0.11.0

dev dependencies:
- isar_generator 3.1.0+1
  - analyzer >=4.6.0 <6.0.0
  - build ^2.3.0
  - dart_style ^2.2.3
  - dartx ^1.1.0
  - glob ^2.0.2
  - isar 3.1.0+1
  - path ^1.8.1
  - source_gen ^1.2.2
  - xxh3 ^1.0.1
- build_runner 2.2.1
  - args ^2.0.0
  - async ^2.5.0
  - analyzer >=4.4.0 <6.0.0
  - build >=2.1.0 <2.4.0
  - build_config >=1.1.0 <1.2.0
  - build_daemon ^3.1.0
  - build_resolvers ^2.0.0
  - build_runner_core ^7.2.0
  - code_builder ^4.0.0
  - collection ^1.15.0
  - crypto ^3.0.0
  - dart_style ^2.0.0
  - frontend_server_client ^2.1.0
  - glob ^2.0.0
  - graphs ^2.0.0
  - http_multi_server ^3.0.0
  - io ^1.0.0
  - js ^0.6.3
  - logging ^1.0.0
  - meta ^1.3.0
  - mime ^1.0.0
  - package_config ^2.0.0
  - path ^1.8.0
  - pool ^1.5.0
  - pub_semver ^2.0.0
  - pubspec_parse ^1.0.0
  - shelf ^1.0.0
  - shelf_web_socket ^1.0.0
  - stack_trace ^1.10.0
  - stream_transform ^2.0.0
  - timing ^1.0.0
  - watcher ^1.0.0
  - web_socket_channel ^2.0.0
  - yaml ^3.0.0
- flutter_test 0.0.0
  - flutter any
  - test_api 0.4.16
  - path 1.8.2
  - fake_async 1.3.1
  - clock 1.1.1
  - stack_trace 1.11.0
  - vector_math 2.1.4
  - async 2.10.0
  - boolean_selector 2.1.1
  - characters 1.2.1
  - collection 1.17.0
  - js 0.6.5
  - matcher 0.12.13
  - material_color_utilities 0.2.0
  - meta 1.8.0
  - source_span 1.9.1
  - stream_channel 2.1.1
  - string_scanner 1.2.0
  - term_glyph 1.2.1
- flutter_lints 1.0.4
  - lints ^1.0.0

transitive dependencies:
- _fe_analyzer_shared 49.0.0
  - meta ^1.0.2
- _flutterfire_internals 1.0.16
  - collection ^1.0.0
  - firebase_core ^2.7.0
  - firebase_core_platform_interface ^4.5.3
  - flutter any
  - meta ^1.3.0
- analyzer 5.1.0
  - _fe_analyzer_shared ^49.0.0
  - collection ^1.15.0
  - convert ^3.0.0
  - crypto ^3.0.0
  - glob ^2.0.0
  - meta ^1.7.0
  - package_config ^2.0.0
  - path ^1.8.0
  - pub_semver ^2.0.0
  - source_span ^1.8.0
  - watcher ^1.0.0
  - yaml ^3.0.0
- args 2.3.1
- async 2.10.0
  - collection ^1.15.0
  - meta ^1.1.7
- boolean_selector 2.1.1
  - source_span ^1.8.0
  - string_scanner ^1.1.0
- build 2.3.1
  - analyzer >=1.5.0 <6.0.0
  - async ^2.5.0
  - convert ^3.0.0
  - crypto ^3.0.0
  - glob ^2.0.0
  - logging ^1.0.0
  - meta ^1.3.0
  - path ^1.8.0
- build_config 1.1.0
  - checked_yaml ^2.0.0
  - json_annotation ^4.5.0
  - path ^1.8.0
  - pubspec_parse ^1.0.0
  - yaml ^3.0.0
- build_daemon 3.1.0
  - built_collection ^5.0.0
  - built_value ^8.1.0
  - http_multi_server ^3.0.0
  - logging ^1.0.0
  - path ^1.8.0
  - pool ^1.5.0
  - shelf ^1.0.0
  - shelf_web_socket ^1.0.0
  - stream_transform ^2.0.0
  - watcher ^1.0.0
  - web_socket_channel ^2.0.0
- build_resolvers 2.0.10
  - analyzer >=4.6.0 <6.0.0
  - async ^2.5.0
  - build ^2.0.0
  - crypto ^3.0.0
  - graphs >=1.0.0 <3.0.0
  - logging ^1.0.0
  - path ^1.8.0
  - package_config ^2.0.0
  - pool ^1.5.0
  - pub_semver ^2.0.0
  - stream_transform ^2.0.0
  - yaml ^3.0.0
- build_runner_core 7.2.4
  - async ^2.5.0
  - build ^2.1.0
  - build_config ^1.0.0
  - build_resolvers ^2.0.0
  - collection ^1.15.0
  - convert ^3.0.0
  - crypto ^3.0.0
  - glob ^2.0.0
  - graphs ^2.0.0
  - json_annotation ^4.3.0
  - logging ^1.0.0
  - meta ^1.3.0
  - path ^1.8.0
  - package_config ^2.0.0
  - pool ^1.5.0
  - timing ^1.0.0
  - watcher ^1.0.0
  - yaml ^3.0.0
- built_collection 5.1.1
- built_value 8.4.1
  - built_collection ^5.0.0
  - collection ^1.15.0
  - fixnum ^1.0.0
  - meta ^1.3.0
- characters 1.2.1
- checked_yaml 2.0.1
  - json_annotation ^4.0.0
  - source_span ^1.8.0
  - yaml ^3.0.0
- clock 1.1.1
- code_builder 4.3.0
  - built_collection ^5.0.0
  - built_value ^8.0.0
  - collection ^1.15.0
  - matcher ^0.12.10
  - meta ^1.3.0
- collection 1.17.0
- convert 3.0.2
  - typed_data ^1.3.0
- crypto 3.0.2
  - typed_data ^1.3.0
- dart_countries 3.0.3
- dart_style 2.2.4
  - analyzer >=4.4.0 <6.0.0
  - args >=1.0.0 <3.0.0
  - path ^1.0.0
  - pub_semver >=1.4.4 <3.0.0
  - source_span ^1.4.0
- dartx 1.1.0
  - characters ^1.1.0
  - collection ^1.15.0
  - crypto ^3.0.0
  - meta ^1.3.0
  - path ^1.8.0
  - time ^2.0.0
- dbus 0.7.8
  - args ^2.0.0
  - ffi ^2.0.0
  - meta ^1.3.0
  - xml ^6.1.0
- device_info_plus 7.0.1
  - device_info_plus_platform_interface ^6.0.1
  - ffi ^2.0.1
  - file ^6.0.0
  - flutter any
  - flutter_web_plugins any
  - meta ^1.3.0
  - win32 >=2.7.0 <4.0.0
- device_info_plus_platform_interface 6.0.1
  - flutter any
  - meta ^1.3.0
  - plugin_platform_interface ^2.0.0
- dio 4.0.6
  - http_parser ^4.0.0
  - path ^1.8.0
- fake_async 1.3.1
  - clock ^1.1.0
  - collection ^1.15.0
- ffi 2.0.1
- file 6.1.4
  - meta ^1.3.0
  - path ^1.8.0
- firebase_auth_platform_interface 6.11.11
  - _flutterfire_internals ^1.0.16
  - collection ^1.16.0
  - firebase_core ^2.7.0
  - flutter any
  - meta ^1.3.0
  - plugin_platform_interface ^2.1.3
- firebase_auth_web 5.2.8
  - firebase_auth_platform_interface ^6.11.11
  - firebase_core ^2.7.0
  - firebase_core_web ^2.2.1
  - flutter any
  - flutter_web_plugins any
  - http_parser ^4.0.0
  - intl ^0.17.0
  - js ^0.6.3
  - meta ^1.3.0
- firebase_core_platform_interface 4.5.3
  - collection ^1.0.0
  - flutter any
  - flutter_test any
  - meta ^1.3.0
  - plugin_platform_interface ^2.1.3
- firebase_core_web 2.2.1
  - firebase_core_platform_interface ^4.5.3
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
  - meta ^1.3.0
- firebase_messaging_platform_interface 4.2.14
  - _flutterfire_internals ^1.0.16
  - firebase_core ^2.7.0
  - flutter any
  - meta ^1.3.0
  - plugin_platform_interface ^2.1.3
- firebase_messaging_web 3.2.15
  - _flutterfire_internals ^1.0.16
  - firebase_core ^2.7.0
  - firebase_core_web ^2.2.1
  - firebase_messaging_platform_interface ^4.2.14
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
  - meta ^1.3.0
- fixnum 1.0.1
- flutter_local_notifications_linux 2.0.0
  - flutter any
  - flutter_local_notifications_platform_interface ^6.0.0
  - dbus ^0.7.8
  - path ^1.8.0
  - xdg_directories ^0.2.0+1
- flutter_local_notifications_platform_interface 6.0.0
  - flutter any
  - plugin_platform_interface ^2.0.0
- flutter_mailer 2.0.1
  - flutter any
- flutter_web_plugins 0.0.0
  - flutter any
  - js 0.6.5
  - characters 1.2.1
  - collection 1.17.0
  - material_color_utilities 0.2.0
  - meta 1.8.0
  - vector_math 2.1.4
- fluttertoast 8.1.1
  - flutter any
  - flutter_web_plugins any
- frontend_server_client 2.1.3
  - async ^2.5.0
  - path ^1.8.0
- glob 2.1.0
  - async ^2.5.0
  - collection ^1.15.0
  - file ^6.0.0
  - path ^1.8.0
  - string_scanner ^1.1.0
- google_identity_services_web 0.2.0
  - js ^0.6.4
  - meta ^1.3.0
- google_sign_in_android 6.1.6
  - flutter any
  - google_sign_in_platform_interface ^2.2.0
- google_sign_in_ios 5.5.1
  - flutter any
  - google_sign_in_platform_interface ^2.2.0
- google_sign_in_platform_interface 2.3.0
  - flutter any
  - plugin_platform_interface ^2.1.0
  - quiver ^3.0.0
- google_sign_in_web 0.11.0+1
  - flutter any
  - flutter_web_plugins any
  - google_identity_services_web ^0.2.0
  - google_sign_in_platform_interface ^2.2.0
  - http ^0.13.5
  - js ^0.6.3
- graphs 2.1.0
  - collection ^1.1.0
- http 0.13.5
  - async ^2.5.0
  - http_parser ^4.0.0
  - meta ^1.3.0
  - path ^1.8.0
- http_multi_server 3.2.1
  - async ^2.5.0
- http_parser 4.0.1
  - collection ^1.15.0
  - source_span ^1.8.0
  - string_scanner ^1.1.0
  - typed_data ^1.3.0
- io 1.0.3
  - meta ^1.3.0
  - path ^1.8.0
  - string_scanner ^1.1.0
- js 0.6.5
  - meta ^1.7.0
- json_annotation 4.7.0
  - meta ^1.4.0
- lints 1.0.1
- logging 1.0.2
- mailer 5.2.0
  - async ^2.5.0
  - logging ^1.0.0
  - intl ^0.17.0
  - mime ^1.0.0
  - path ^1.7.0
  - pedantic ^1.9.2
  - meta ^1.3.0
- matcher 0.12.13
  - meta ^1.8.0
  - stack_trace ^1.10.0
- material_color_utilities 0.2.0
- meta 1.8.0
- mime 1.0.2
- package_config 2.1.0
  - path ^1.8.0
- package_info_plus 3.0.2
  - ffi ^2.0.1
  - flutter any
  - flutter_web_plugins any
  - http ^0.13.0
  - meta ^1.3.0
  - path ^1.8.0
  - package_info_plus_platform_interface ^2.0.1
  - win32 >=2.7.0 <4.0.0
- package_info_plus_platform_interface 2.0.1
  - flutter any
  - meta ^1.3.0
  - plugin_platform_interface ^2.0.0
- path 1.8.2
- path_drawing 1.0.1
  - vector_math ^2.1.0
  - meta ^1.3.0
  - path_parsing ^1.0.1
  - flutter any
- path_parsing 1.0.1
  - vector_math ^2.1.0
  - meta ^1.3.0
- path_provider_android 2.0.20
  - flutter any
  - path_provider_platform_interface ^2.0.1
- path_provider_ios 2.0.11
  - flutter any
  - path_provider_platform_interface ^2.0.0
- path_provider_linux 2.1.7
  - ffi >=1.1.2 <3.0.0
  - flutter any
  - path ^1.8.0
  - path_provider_platform_interface ^2.0.0
  - xdg_directories ^0.2.0
- path_provider_macos 2.0.6
  - flutter any
  - path_provider_platform_interface ^2.0.1
- path_provider_platform_interface 2.0.5
  - flutter any
  - platform ^3.0.0
  - plugin_platform_interface ^2.1.0
- path_provider_windows 2.1.3
  - ffi ^2.0.0
  - flutter any
  - path ^1.8.0
  - path_provider_platform_interface ^2.0.0
  - win32 >=2.1.0 <4.0.0
- pedantic 1.11.1
- petitparser 5.0.0
  - meta ^1.7.0
- phone_number_metadata 5.0.4
  - path ^1.8.0
  - dart_countries ^3.0.1
- platform 3.1.0
- plugin_platform_interface 2.1.3
  - meta ^1.3.0
- pool 1.5.1
  - async ^2.5.0
  - stack_trace ^1.10.0
- process 4.2.4
  - file ^6.0.0
  - path ^1.8.0
  - platform ^3.0.0
- pub_semver 2.1.1
  - collection ^1.15.0
  - meta ^1.3.0
- pubspec_parse 1.2.1
  - checked_yaml ^2.0.1
  - collection ^1.15.0
  - json_annotation ^4.6.0
  - pub_semver ^2.0.0
  - yaml ^3.0.0
- qr 2.1.0
  - meta ^1.3.0
- quiver 3.2.1
  - matcher ^0.12.10
- sentry 6.15.1
  - http ^0.13.0
  - meta ^1.3.0
  - stack_trace ^1.10.0
  - uuid ^3.0.0
  - intl ^0.17.0
- shelf 1.4.0
  - async ^2.5.0
  - collection ^1.15.0
  - http_parser ^4.0.0
  - path ^1.8.0
  - stack_trace ^1.10.0
  - stream_channel ^2.1.0
- shelf_web_socket 1.0.2
  - shelf ^1.1.0
  - stream_channel ^2.1.0
  - web_socket_channel ^2.0.0
- sky_engine 0.0.99
- source_gen 1.2.5
  - analyzer >=4.6.0 <6.0.0
  - async ^2.5.0
  - build ^2.1.0
  - dart_style ^2.0.0
  - glob ^2.0.0
  - meta ^1.3.0
  - path ^1.8.0
  - source_span ^1.8.0
  - yaml ^3.0.0
- source_span 1.9.1
  - collection ^1.15.0
  - path ^1.8.0
  - term_glyph ^1.2.0
- stack_trace 1.11.0
  - path ^1.8.0
- stream_channel 2.1.1
  - async ^2.5.0
- stream_transform 2.0.0
- string_scanner 1.2.0
  - source_span ^1.8.0
- term_glyph 1.2.1
- test_api 0.4.16
  - async ^2.5.0
  - boolean_selector ^2.1.0
  - collection ^1.15.0
  - meta ^1.3.0
  - source_span ^1.8.0
  - stack_trace ^1.10.0
  - stream_channel ^2.1.0
  - string_scanner ^1.1.0
  - term_glyph ^1.2.0
  - matcher >=0.12.11 <0.12.14
- time 2.1.2
  - clock ^1.1.0
- timezone 0.9.0
  - path ^1.8.0
- timing 1.0.0
  - json_annotation ^4.0.0
- typed_data 1.3.1
  - collection ^1.15.0
- uni_links_platform_interface 1.0.0
  - flutter any
  - plugin_platform_interface ^2.0.0
- uni_links_web 0.1.0
  - flutter any
  - flutter_web_plugins any
  - uni_links_platform_interface ^1.0.0
- universal_io 2.0.4
  - collection ^1.15.0
  - crypto ^3.0.0
  - meta ^1.3.0
  - typed_data ^1.3.0
- url_launcher_android 6.0.19
  - flutter any
  - url_launcher_platform_interface ^2.0.3
- url_launcher_ios 6.0.17
  - flutter any
  - url_launcher_platform_interface ^2.0.3
- url_launcher_linux 3.0.1
  - flutter any
  - url_launcher_platform_interface ^2.0.3
- url_launcher_macos 3.0.1
  - flutter any
  - url_launcher_platform_interface ^2.0.3
- url_launcher_platform_interface 2.1.1
  - flutter any
  - plugin_platform_interface ^2.1.0
- url_launcher_web 2.0.13
  - flutter any
  - flutter_web_plugins any
  - url_launcher_platform_interface ^2.0.3
- url_launcher_windows 3.0.1
  - flutter any
  - url_launcher_platform_interface ^2.0.3
- uuid 3.0.7
  - crypto ^3.0.0
- vector_math 2.1.4
- watcher 1.0.1
  - async ^2.5.0
  - path ^1.8.0
- web_socket_channel 2.2.0
  - async ^2.5.0
  - crypto ^3.0.0
  - stream_channel ^2.1.0
- win32 3.0.0
  - ffi >=1.1.2 <3.0.0
- xdg_directories 0.2.0+2
  - meta ^1.3.0
  - path ^1.8.0
  - process ^4.0.0
- xml 6.1.0
  - collection ^1.16.0
  - meta ^1.7.0
  - petitparser ^5.0.0
- xxh3 1.0.1
- yaml 3.1.1
  - collection ^1.15.0
  - source_span ^1.8.0
  - string_scanner ^1.1.0

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by yaircaballero10** [comment]
Tube el mismo problema y lo peor es que estaba utilizando en un proyecto en producción,
En algunos celulares no hay problemas en otros produce error,
creo que ISAR no está muy maduro.

En mi otro proyecto para evitar este inconveniente  terminaré utilizando sql lite.


Los que tienen isar  3.0.5, no cambiar las clases embebidas y no actualizar a isar 3.1.0+1

**Comment by mrclauss** [comment]
@simc Do you have any idea why this happens? Could not figure it out :(

**Comment by mrclauss** [comment]
I thought I already tried that before, but the analyzer package was too old. So isar currently misses to specify the minimum analyzer version (somewhere between 5.1.0 and 5.13.0)
