### ISSUE TITLE
Undefined schema when using double embedded models

### ISSUE THREAD

**Issue by ThiemoImgraben** [isar/isar#1263]
### Steps to Reproduce

I have the following models : 

AccessRight < Entrance < Area 

AccessRight is a collection and has an Entrance attribute. 
Area and AreaType are also embedded Models inside Entrance. 

When using one file for each model, there is an Undefined Schema error, since the auto generated code of AccessRight is not finding the Schemas of Area and AreaType. Is it required to have all the nested Models inside the same file ? 

### Code sample

```
// access_right.dart
@collection
class AccessRight {
  AccessRight({
    String? identityMail,
    DateTime? startsAt,
    DateTime? endsAt,
    Entrance? entrance,
    Permissions? permissions,
    AccessTimes? accessTimes,
  });
}

// entrance.dart
@embedded
class Entrance {
  Entrance({
    Area? area,
  });
}

// area.dart
@embedded
class Area {
Area({
    String? id,
    String? name,
  }) ;
}
```

**Comment by huntrist** [comment]
same problem. Any solution?

**Comment by simc** [comment]
You have to import the class defining the schema

**Comment by DamienDoumer** [comment]
A solution to this problem is to carry the definition of the @embedded class into the collection's class file. Doing this will force the build to have all the definitions and not miss anyone.
