### ISSUE TITLE
Optional constructor parameter in embedded class throws error

### ISSUE THREAD

**Issue by keith555** [isar/isar#1264]
### Code sample

```dart
@embedded
class Dialogue {
  Dialogue(String? speech);
}
```
[SEVERE] isar_generator on lib/model/...

Constructors of embedded objects must not have required parameters.
package:..288:3
    ╷
288 │   Dialogue(String? speech);
    │   ^^^^^^^^
    ╵
[INFO] Running build completed, took 1.2s

**Comment by simc** [comment]
This is now fixed in Isar v4 🎉
