### ISSUE TITLE
Maybe "Ignore" the Map field, and use a getter/setter that converts the Map field into an Isar understandable type.

### ISSUE THREAD

**Issue by karthikeyanmarutham** [isar/isar#1266]
Maybe "Ignore" the Map field, and use a getter/setter that converts the Map field into an Isar understandable type.

```
@Ignore()
Map<String, bool> checked = {};

String get isarChecked => jsonEncode(checked);
set isarChecked(String json) => checked = jsonDecode(json);
```

_Originally posted by @tannermeade in https://github.com/isar/isar/discussions/633#discussioncomment-3578843_

I'm following the same code, but it's not working properly 

In Json o/p Format Like this,

"data": {
        "1": {
            "_id": 1,
            "name": "Finish",
            "active": true,
            "order": 1
        },
}

Dart : 

@collection
class StatusListDbModel {
  Id? id = Isar.autoIncrement;

  @ignore
  Map<String, StatusDatum>? data = {};

  String get statusData => jsonEncode(data);
  set statusData(String json) => data = jsonDecode(json);
}

@embedded
class StatusDatum {
  int? id;
  String? name;
  bool? active;
  int? order;
}

what is the mistake on my side?

**Comment by simc** [comment]
Isar v4 supports maps
