### ISSUE TITLE
Importing Isar into default Dart console project throws an error

### ISSUE THREAD

**Issue by keith555** [isar/isar#1270]
### Steps to Reproduce

1. Create a default dart console project
2. Follow instructions at https://pub.dev/packages/isar/install
2.a. `dart pub add isar`
2.b. `import 'package:isar/isar.dart;'` {unused import}
3 run default app which doesn't use Isar but has the import
4. Error:
`/C:/Users/keith/AppData/Local/Pub/Cache/hosted/pub.dev/isar-3.1.0+1/lib/src/native/isar_core.dart:92:28: Error: Member not found: 'flutter'. dylib = DynamicLibrary.flutter pub add isar isar_flutter_libsopen(libraryPath!);`

### Code sample

```dart
import 'package:isar_map_dart/isar_map_dart.dart' as isar_map_dart;
import 'package:isar/isar.dart';

void main(List<String> arguments) {
  print('Hello world: ${isar_map_dart.calculate()}!');
}
```

### Details

 - Platform: Windows 11
 - Flutter version: Dart SDK version: 3.0.0 (stable)
 - Isar version: ^3.1.0+1

---

 - [ ] I searched for similar issues already
 - [ ] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by simc** [comment]
This is fixed in v4
