### ISSUE TITLE
Flutter's release mode prompts Isar.Open error.

### ISSUE THREAD

**Issue by dot-wei2021** [isar/isar#1272]
### Steps to Reproduce

**Flutter debug will not report an error when debugging**. When packaging the release mode, it will prompt Isar.open to fail.
```
IsarError: Could not initialize IsarCore library for processor architecture "ios_arm64". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
Invalid argument(s): Failed to lookup symbol 'isar_version': dlsym(RTLD_DEFAULT, isar_version): symbol not found #0      
initializeCoreBinary (package:isar/src/native/isar_core.dart:78)
#1      openIsar (package:isar/src/native/open.dart:81)
#2      Isar.open (package:isar/src/isar.dart:107)
#3      initIsarService (package:app/helper/services/isar_service.dart:19)
#4      registerServices (package:app/helper/services/register_services.dart:75)
```

### deps
```
isar: 3.1.0+1
isar_flutter_libs: 3.1.0+1
isar_generator: 3.1.0+1

```

### Code sample

```dart
  final dir = await getApplicationSupportDirectory();
 isar = await Isar.open(
  [
    DWorkSpaceSchema,
  ],
  directory: dir.path,
  maxSizeMiB: 512,
  )
```

### Details

 - Platform: iPhone 14
 - Flutter version: 3.7.12
 - Isar version:  3.1.0+1

---

 - [ x ] I searched for similar issues already
 - [ x ] I filled the details section with the exact device model and version

**Comment by dot-wei2021** [comment]
target 'Runner' do
  use_frameworks! :linkage => :static  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

**Comment by Wing-Li** [comment]
After removing 'use_frameworks! :linkage => :static ', 'pod install' cannot be packaged.
