### ISSUE TITLE
Add support for web

### ISSUE THREAD

**Issue by tbm98** [isar/isar#1277]
Current version: ^3.1.0+1
Error: The integer literal 7587272641431840507 can't be represented exactly in JavaScript
my code:
```dart

const UsedSchema = CollectionSchema(
  name: r'Used',
  id: 7587272641431840507,
  properties: {
    r'avatar': PropertySchema(
      id: 0,
      name: r'avatar',
      type: IsarType.string,
    ),
    r'dateTime': PropertySchema(
      id: 1,
      name: r'dateTime',
      type: IsarType.dateTime,
    ),
    r'medicineId': PropertySchema(
      id: 2,
      name: r'medicineId',
      type: IsarType.long,
    ),
    r'name': PropertySchema(
      id: 3,
      name: r'name',
      type: IsarType.string,
    ),
    r'quantity': PropertySchema(
      id: 4,
      name: r'quantity',
      type: IsarType.long,
    )
  },
  estimateSize: _usedEstimateSize,
  serialize: _usedSerialize,
  deserialize: _usedDeserialize,
  deserializeProp: _usedDeserializeProp,
  idName: r'id',
  indexes: {},
  links: {},
  embeddedSchemas: {},
  getId: _usedGetId,
  getLinks: _usedGetLinks,
  attach: _usedAttach,
  version: '3.1.0+1',
);
```

**Comment by awvreenen95** [comment]
This issue has me stuck on Isar 2.5.0 which is causing a whole lot of dependency issues for me.

**Comment by simc** [comment]
> It is caused by the fact that javascript does not have an integer type.

Not really. This would be a super easy fix but the entire web architecture is missing in Isar v3

**Comment by davidAg9** [comment]
This is a critical issue ,someone should look into this

**Comment by simc** [comment]
You cannot imagine how happy I am to tell you: THIS IS DONE 🎉😇. Isar v4 has web support again. And while it only works in memory for now it's much more capable and WAY FASTER than the old version. Persistence is coming soon.

**Comment by AristideVB** [comment]
@simc Migration Guide to v4 & release on pub.dev soon ? ❤️⚡️

**Comment by mbfakourii** [comment]
> You cannot imagine how happy I am to tell you: THIS IS DONE 🎉😇. Isar v4 has web support again. And while it only works in memory for now it's much more capable and WAY FASTER than the old version. Persistence is coming soon.

We are waiting, just pay attention to [isar_generator](https://pub.dev/packages/isar_generator), it does not have a pre-release version for isar 4
