### ISSUE TITLE
Generic Type Converters

### ISSUE THREAD

**Issue by om-ha** [isar/isar#128]
## **Is your feature request related to a problem? Please describe.**
- Type conversion is superbly done in Isar, as explained in the [TypeConverters documentation](https://isar.dev/type-converters).
- However, say you have a lot of enums, you'd then need to write a converter for each one.
- Other examples may apply as well not just enums, basically for any types with shared data-access behavior.

## **Describe the solution you'd like**
We have three solutions here:

- A. Ability to have generic type converter, in declaration and in annotation. I suppose the annotation part is tough?
    - ```class GenericIntTypeConverter<T> extends TypeConverter<T, int> { ... }```
    - and then in the Isar object's property annotation:
    - ```@GenericIntTypeConverter<SomeType>()```

## **Describe alternatives you've considered**
- B. Using TypeConverter over a superclass or interface class. This is a user's responsibility to have multiple classes extending a super class or implementing a shared interface class. This superclass or interface class can be used in the TypeConverter class definition. 
    - ```class MyInterfaceTypeConverter extends TypeConverter<MyInterface, int> { ... }```
    - and then in the Isar object's property annotation:
    - ```@MyInterfaceTypeConverter()```
    - **Action requested from Isar maintainer**: I think this should be encouraged and mentioned in the  [TypeConverters documentation](https://isar.dev/type-converters).

- C. This final method is related to enums and works only partially (`toIsar` works), which is not enough (compile error in `fromIsar`). Maybe someone can make it work! Now for enums, the solution looked good at first. It seems `Enum` is an abstract class representing all concrete `enum` classes! This was mentioned in two dart issues [one](https://github.com/dart-lang/language/issues/1566) and [two](https://github.com/dart-lang/sdk/issues/35496). And was shipped recently with the stable dart release `2.14` as mentioned in the two issues linked here. But as I said, `fromIsar` fails miserably:
```dart
class EnumTypeConverter extends TypeConverter<Enum, int> {
  const EnumTypeConverter(); // Converters need to have an empty const constructor

  // This property can be assigned from constructor maybe?
  // Used for `fromIsar` -> Option B
  Enum? myEnum;

  // `fromIsar` does NOT work :( Neither options A nor B do.
  @override
  Enum fromIsar(int enumIndex) {
    Enum value;
    // Option A
    // Enum class does not expose `values`
    // compile error `The getter 'values' isn't defined for the type 'Enum'.`
    value = Enum.values[enumIndex]; 
    // Option B
    // An Enum instance (myEnum) does not expose `values`
    // compile error `The getter 'values' isn't defined for the type 'Enum'.`
    value = myEnum!.values; 
    return value;
  }

  // `toIsar` WORKS!
  @override
  int toIsar(Enum myEunm) {
    return myEunm.index;
  }
}
```

**Version**
 - Platform: iOS, Android, Mac
 - Flutter version: 2.5.1 (stable)
 - Dart version: 2.14.2 (stable)
 - Isar version: 0.4.0

**Comment by om-ha** [comment]
This is a nice-to-have of course... A developer can just repeat some code if no other solutions are available.

**Comment by obalak** [comment]
Hi,
I tried this and unfortunately is not recognized by the analyzer/generator:

```
@Collection
class Example {
...
 @RxBoolTypeConverter()
  RxBool? starred;
...
}


class RxBoolTypeConverter extends TypeConverter<RxBool, bool> {
  const RxBoolTypeConverter(); // Converters need to have an empty const constructor

  @override
  RxBool fromIsar(bool value) {
    return RxBool(value);
  }

  @override
  bool toIsar(RxBool value) {
    return value.value;
  }
}
```
This should work in the same way as for Enum ... 
This would be a very appreciated to avoid using workaround like ignoring the current attribute and duplicate it with somewhat is expected stored value in the DB (e.g. bool dbStarred).

**Comment by leisim** [comment]
Type converters have been removed from the library.
