### ISSUE TITLE
Somehow, isar_generator is not supporting any Dart 3.0.2 feature

### ISSUE THREAD

**Issue by JCKodel** [isar/isar#1288]
### Steps to Reproduce

* Create a project using latest Flutter (3.10.2).
* Create a collection
* Run dart build_runner

### Code sample

```dart
import 'package:isar/isar.dart';

abstract base class BaseEntity {
  BaseEntity({
    this.id,
    required this.creationDate,
    required this.updateDate,
    required this.synced,
    required this.deleted,
  });

  DateTime creationDate;
  @Index()
  bool deleted;

  @Index()
  bool synced;

  @Index()
  DateTime updateDate;

  Id? id;
}

@Collection(accessor: "users")
final class User extends BaseEntity {
  User({
    super.id,
    required super.creationDate,
    required super.updateDate,
    required super.synced,
    required super.deleted,
    required this.userId,
    required this.displayName,
    required this.email,
    required this.photoURL,
  });

  @Index(unique: true)
  String userId;

  String displayName;

  String email;

  String photoURL;
}

```

It should work, but it doesn't:

```console
╭─   root  C:  temp  frontend                                                                                                                                                                                1.028s   18:18:34 
╰─ $ dart run build_runner build
Building package executable... (3.1s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 158ms
[INFO] Precompiling build script... completed, took 3.4s
[INFO] Building new asset graph completed, took 433ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] Generating SDK summary completed, took 3.0s
[SEVERE] isar_generator on lib/main.dart:

This builder requires Dart inputs without syntax errors.
However, package:xxx/main.dart (or an existing part) contains the following errors.
main.dart:7:1: Can't have modifier 'final' here.
main.dart:57:1: Can't have modifier 'final' here.

Try fixing the errors and re-running the build.

[SEVERE] isar_generator on lib/test.dart:

This builder requires Dart inputs without syntax errors.
However, package:xxx/test.dart (or an existing part) contains the following errors.
test.dart:26:1: Can't have modifier 'final' here.

Try fixing the errors and re-running the build.

[INFO] Running build completed, took 3.0s
[INFO] Caching finalized dependency graph completed, took 15ms
[SEVERE] Failed after 3.1s
```

### Details

 - Platform: none
 - Flutter version: 3.10.2
 - Isar version: 3.1.0+1

---

 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version
 - [X] I am able to provide a reproducible example

**Comment by JamiuJimoh** [comment]
I'm also facing this issue

**Comment by JCKodel** [comment]
> I'm also facing this issue

According to Dart Team, whenever you have some library that uses an old version of `analyzer`, then it does that.

In my case, that library was `equatable_lint` that used `custom_lint_builder` 0.2.0 that causes all the issues.

I forked it and fixed it on https://github.com/JCKodel/equatable_lint, but the PR was never reviewed (as always, people publish packages and then forget about them).

So, use `dart pub deps > deps.txt` on your project and then seek out references to `analyzer` to see what is going on.

All that because `Dart 3.0 Compatible` badge is a lie.

**Comment by JamiuJimoh** [comment]
@JCKodel Thank you. The badge isn't to be trusted anymore

**Comment by duard-sf** [comment]
Thanks @JCKodel!

I had to add [analyzer 5.13.0](https://pub.dev/packages/analyzer/versions/5.13.0) to my pubspec.yaml's dev_dependencies, because, as of writing, isar_generator constrains analyzer to [>=4.6.0 <6.0.0](https://github.com/isar/isar/blob/a6f7cea6b0a99c1c1fd289ab569dda3e6b6780bb/packages/isar_generator/pubspec.yaml#L11C21-L11C21).

**Comment by abdalmonem** [comment]
for any one facing the same issue :
solved for my by add : https://pub.dev/packages/build_runner
`build_runner: ^2.4.6` to my pubspec.yaml in `dev_dependencies`

**Comment by simc** [comment]
Fixed in v4
