### ISSUE TITLE
Will there be any further changes in the library or it got abandoned?

### ISSUE THREAD

**Issue by dgandhi17** [isar/isar#129]
Will there be any further changes in the library or it got abandoned?

**Comment by flexagoon** [comment]
Well the isar/docs and isar/isar-core repos were updated in august, so Isar is probaby not abandoned, just not as actively developed

**Comment by srix55** [comment]
It's not abandoned. From the author's comments from the discussion tab a month ago:

> I haven't committed any code recently but the project is far from dead and I'm working on a massive feature update. Also still fighting with unit tests haha.

**Comment by leisim** [comment]
Definitely not abandoned just little time. But we are going to need it soon at ClickUp, so you can expect to see more active development

**Comment by dgandhi17** [comment]
@leisim thanks, happy to see you back.
