### ISSUE TITLE
How to import nested Json array object where there are multiple sub arrays?

### ISSUE THREAD

**Issue by SPSpisoft** [isar/isar#1290]
I am going to store a series of data that I receive in layers and in Jason array format in the database.

Similar to this :

@collection
class Email {
Id id = Isar.autoIncrement;
String? title;
List<Recipient>? recipients;
}

@Embedded
class Recipient {
String? name;
String? address;
List<PhoneNumber>? Phones;
}

@Embedded
class PhoneNumber{
String? title;
String? number;
}

I considered the main class (Email) @collection and its subclass (Recipient) @Embedded . So far, the data is stored correctly.. but for the next subclasses (PhoneNumber), the null value is stored

### Code sample

await isar.EmailClass.importJson(json);

### Details

 - Platform: iPhone 13 Pro, Galaxy S7, x86 Android Emulator on Windows etc.
 - Flutter version: Flutter 3.10.0 • channel stable 
 - Isar version: 3.1.0

 - [ + ] I searched for similar issues already
 - [ + ] I filled the details section with the exact device model and version
 - [ + ] I am able to provide a reproducible example

**Comment by simc** [comment]
First of all, you have to specify the generic arguments of your lists.

Then you can import json in the following format:
```json
{
  "id": 1234,
  "title": "Test",
  "recipients": [
    {
      "name": "Someone",
      "address": "mail@example.com",
      "phones": [
        {
          "name": "work",
          "number": "+49 122132123"
        }
      ]
    }
  ]
}
```  

Please reopen if you still face issues
