### ISSUE TITLE
[Inspector] Cannot set time of a DateTime field in the Inspector

### ISSUE THREAD

**Issue by MichaelNZ85** [isar/isar#1292]
When using the Isar Inspector, it is impossible to add a value to a DateTime field with a time other than midnight. The date picker dialogue sets the time to midnight on the chosen date, and it seems to be impossible to enter a time manually along with a date.

![Screenshot 2023-06-02 at 8 43 05 PM](https://github.com/isar/isar/assets/15241383/ceb433ff-5b8a-4fcb-a23a-083430998e3c)

### Steps to Reproduce

1. Create a collection where at least one field is a DateTime.
2. Open Isar Inspector.
3. Click on the DateTime field. Try to change it to add a time.

### Details

 - Platform: Windows 10 and MacOS
 - Flutter version: 3.10.0
 - Isar version: 3.1.0+1
---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
This is fixed in the v4 inspector

**Comment by Vinnie1991** [comment]
Is it possible to have the V4 inspector on Isar V3?
Since Isar v4 isn't production ready right now.
