### ISSUE TITLE
Can you add how much is pending to be near stable 1.0 ?

### ISSUE THREAD

**Issue by dgandhi17** [isar/isar#13]
It will be good if you can add missing things to get stable 1.0, so that people will start help you out because most of people are eagerly waiting for such kind of DB

**Comment by leisim** [comment]
@dgandhi17 Good idea, I'll definitely draft a roadmap. But to be considered stable, we also have to let some time pass and collect feedback from the first users.
I hope to release a reliable beta version in Q1 2021 and a stable version 1.0 in Q2 2021.

**Comment by dgandhi17** [comment]
Well I will try to play with this db as I am planning to use it in future.

**Comment by leisim** [comment]
Here are the next todos. I'll extend this over time: https://github.com/isar/isar/blob/main/TODO.md

**Comment by peterwvj** [comment]
Hi @leisim I'm currently contemplating whether I should switch to Isar (I'm currently using Hive but my app has not made it to production yet). At this point, do you have a more clear plan for when the beta and stable 1.0 versions will be released. Thanks in advance :)

**Comment by leisim** [comment]
Hey @peterwvj! Yes I hope to release a stable version within the next two months.

The next version will bring a lot of new features (support for freezed, getByIndex, final properties, inheritance etc.).

After that I need to work on more unit tests.
