### ISSUE TITLE
Unique Replace index keeps old "dirty" records 

### ISSUE THREAD

**Issue by om-ha** [isar/isar#130]
## **Steps to Reproduce**
- Have a unique-replace index on a property inside a collection.
- Insert an object within an Isar instance.
- Re-insert that same object with the same value for the property with unique-replace index.
- Old object still exists within the Isar instance (2 objects instead of 1)

### Collection Definition
```dart
@Collection()
class Product {
  int? id;

  @Index(unique: true, replace: true)
  late String name;

  late int price;
}
```
### Add new product & check total count
```dart
  // Open Unique Isar
  const isarId = "001";
  final isar = await openIsar(name: 'isar_$isarId');

  const productName = "MineralWater";
  const productPrice = 1;

  // Add product 1
  final newProduct1 = Product()
    ..name = productName
    ..price = productPrice;
  await isar.writeTxn((isar) async {
    await isar.products.put(newProduct1);
  });

  // get total products count
  var allProducts = await isar.products.where().findAll();
  print('PRODUCTS COUNT: ${allProducts.length}'); // OUTPUTS: `PRODUCTS COUNT: 1`, correct!
  
  // Add product 2
  final newProduct2 = Product()
    ..name = productName
    ..price = productPrice;
  await isar.writeTxn((isar) async {
    await isar.products.put(newProduct2);
  });

  // get total products count, again
  allProducts = await isar.products.where().findAll();
  print('PRODUCTS COUNT: ${allProducts.length}'); // OUTPUTS: `PRODUCTS COUNT: 2`, incorrect :( Should be 1

  // get all products with the same unique-index property value
  var duplicateProducts = await isar.products.where().productNameEqualTo(productName).findAll();
  print('DUPLICATES: ${duplicateProducts.length}'); // OUTPUT: `DUPLICATES: 1`, surprisingly correct! What is going on here?
```
### Output
```
PRODUCTS COUNT: 1
PRODUCTS COUNT: 2
DUPLICATES: 1
```

## Expected outcome
I think since we are using unique-replace index here, then shouldn't the old value be discarded?

## **Version**
 - Platform: iOS, Android, Mac
 - Flutter version: 2.5.1 (stable)
 - Dart version: 2.14.2 (stable)
 - Isar version: 0.4.0

**Comment by om-ha** [comment]
Also please note, the values are not actually replaced even though number of duplicates with the final `findAll` is correct.

```dart
  print('DUPLICATES: ${duplicateProducts.length}'); // OUTPUT: `DUPLICATES: 1`, surprisingly correct! What is going on here?
```

This means the replace of other non-index values doesn't happen.

In our product example, if we were to add the second product with a different price, we would still find the first price after object addition with `put`.

**Comment by om-ha** [comment]
@leisim very happy you are back! Would you like some collaboration for this issue?

**Comment by leisim** [comment]
@om-ha Thanks for reporting this issue. Yes I'm grateful for any help.

If you could for example contribute a unit test that reproduces the issue, that would be super helpful.

If you know Rust, maybe you could even write a unit test for Isar core.

**Comment by om-ha** [comment]
Thanks for your reply @leisim.

Will contribute a bug-reproducing unit test in dart. Afterwards I will try writing a unit test for Isar core too.

**Comment by jtzell** [comment]
I'm having the same problem. Any update on this issue?

**Comment by om-ha** [comment]
@jtzell I'm on a tight deadline now, but hopefully I can make a bug-reproducing unit test this week. Then we can look into fixing this with Simon (the maintainer).

**Comment by leisim** [comment]
@om-ha Currently working very hard on a massive Isar core update. Should fix those problems.

**Comment by om-ha** [comment]
> @om-ha Currently working very hard on a massive Isar core update. Should fix those problems.

That sounds amazing! Thanks for the hard work, it is highly appreciated.

**Comment by leisim** [comment]
Fixed with stable release

**Comment by om-ha** [comment]
Awesome news! What an achievement, a new (stable) first of 2022 after new year's eve!

Congratulations!
