### ISSUE TITLE
consider the means of "anyOf"

### ISSUE THREAD

**Issue by yichaosun** [isar/isar#1300]
### anyOf
use anyOf like sql key word in, reference from get Start,
but there is one case ,show different means between "anyOf" and "in"
<img width="411" alt="image" src="https://github.com/isar/isar/assets/7195037/9ea781be-6c4b-49a7-85ce-116bba0589cc">

### Code sample
1、here is my data
<img width="638" alt="image" src="https://github.com/isar/isar/assets/7195037/c873cf10-703c-4d52-b135-80c164975b3a">

2、here , the params todoIds is empty list
what I want ,is like sql: select * from todos where id in todoIds
```dart
/// todoIds is 
  Future<List<Todo>> getTodosByIds(List<int> todoIds) {
    return isar.todos
        .where()
        .anyOf(todoIds, (q, int todoId) => q.idEqualTo(todoId))
        .findAll();
  }
```

3、I got the result of todo(which id equals 1, the data in picture above)
I realize that when todoIds is empty, there is no limit for query, and will find All result 
but, like sql "select * from todoIds where id in todoIds", will get empty result

so, consider about the means of "anyOf", is that right? 

### Details
latest version till now
 - Platform: iPhone 13 Simulator in macOS
 - Flutter version: [3.10.4]
 - Isar version: [3.0.3]

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by yichaosun** [comment]
actually, when the todoIds is empty, I got result todo
however toddies = [2], the result is empty,correctly

**Comment by simc** [comment]
Fixed in the next version
