### ISSUE TITLE
Support Map type

### ISSUE THREAD

**Issue by allumbra** [isar/isar#1301]
I'm converting my project from Hive to Isar.  I have a few models that have a Map type and get the unsupported type error when running the build script

I would like the map type to be supported - especially since I'm dealing with many json files with "object/map" fields

**Describe alternatives you've considered**
I did see a suggestion to ignore the map and provide a conversion from json - but I find this to be cumbersome and a downgrade from Hive functionality

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 3.10
 - Isar version: 3.1

**Comment by simc** [comment]
This is now supported in Isar v4 🎉
