### ISSUE TITLE
Isar inspector works fine on firefox.

### ISSUE THREAD

**Issue by joshpetit** [isar/isar#1307]
When you open Isar inspector on Firefox, it prompts you to use a chrome browser since firefox isn't supported. But it works fine from what I can see on Firefox when I switch the user agent. I'm using the latest 113 version on Linux. Is there something horribly wrong with it that should prevent people from using their preferred browser?

**Comment by bhagn** [comment]
@joshpetit I have been waiting for Isar web support for sometime now. How did you get it to work on web?

**Comment by joshpetit** [comment]
I'm sorry, I'm not talking about web for the application. I'm talking about web for the inspector.

**Comment by ilovelinux** [comment]
I am interested in Isar Inspector support for Firefox too 🙂

**Comment by ilovelinux** [comment]
Related to https://github.com/isar/isar/issues/995
