### ISSUE TITLE
Support (Firebase style) partial update to objects stored in Isar

### ISSUE THREAD

**Issue by arnab** [isar/isar#1309]
**Is your feature request related to a problem? Please describe.**

It will be awesome to have a Firebase style partial update (see [Read and Write Data  |  Firebase Realtime Database](https://firebase.google.com/docs/database/flutter/read-and-write#updating_or_deleting_data)) with Isar. 

I have an object I am storing in Isar with ~10 fields in it. In some circumstances, I need to update 1-2 properties on the object.

What I would like to do is with either:
* with [Isar update](https://isar.dev/crud.html#modifying-the-database)
* or with [Isar Replace/Put Index](https://isar.dev/indexes.html#replace-indexes)

... update only a few properties of an existing object (without needing to read it first, then changing a few properties and then calling `put` again).

**Version**
 - Platform: All supported platforms

_Note: I originally asked if this is possible (as suggested by the repo) in the discussions: [Is it possible to use update (or replace with index) with only partial attributes? · isar/isar · Discussion #1308](https://github.com/isar/isar/discussions/1308). Since I did not receive any responses, I am opening it as a feature request, assuming it is not possible right now._

**Comment by simc** [comment]
This has been implemented in Isar v4. You can do partial and bulk updates:

```dart
isar.shoes.update(
  id: 412,
  brand: "Nike",
  model: "Air Jordan",
);
```
or
```dart
isar.shoes.where()
  .nameContains("Jordan")
  .updateAll(
    brand: "Nike",
  );
```
