### ISSUE TITLE
Awaiting Production Ready Release of Isar DB

### ISSUE THREAD

**Issue by Rushabh1798** [isar/isar#131]
Hi @leisim,
We are currently developing a business solution heavily dependent on local storage. We currently use Hive for that purpose but due to lack of queries and searching we are desperately waiting for Isar to get stable. It seems much promising as compared to its competitors. Please let us know when can we expect a stable version of Isar. Thanks man you are doing a nice work since Hive. 

Regards,
Rushabh,
Rebrewed Tech Team.

**Comment by leisim** [comment]
Hey @Rushabh1798 ,
I'm working very hard on a stable version but I'm not going to make another prediction. Have been a little off in the past haha

**Comment by leisim** [comment]
Just released the stable version :)
