### ISSUE TITLE
Crash in beginning of transaction `(isar_flutter_libs: _$LT$crossbeam_channel..channel..TryIter)`

### ISSUE THREAD

**Issue by JulianBissekkou** [isar/isar#1316]
### Steps to Reproduce

It's one of those sentry bug reports without a reproducible example. Sorry Simon 🙈 
This issue happend while someone was closing the app. Maybe the app was writing to the database while the database was about to close.

### Code sample

The example is the same as in #1312 

### Details

 - Platform: iOS 16.5,  iPhone XR
 - Flutter version: 3.10.2
 - Isar version: ~~2.5.0~~ 3.1.0

<img width="1514" alt="image" src="https://github.com/isar/isar/assets/36447137/82a4e65a-c883-4df4-8e76-464ada3f5123">

---

No other issues found that describe the exact same problem.

**Comment by simc** [comment]
Haha how do you find these lol. This is great thanks. The good news is this issue will be fixed in v4 since this particular code has been replaced completely

**Comment by simc** [comment]
Wait... Version 2.5?

**Comment by JulianBissekkou** [comment]
Sorry of course 3.1.0, that was a typo 🤦🏽

**Comment by simc** [comment]
First version in about a week 🙂

**Comment by simc** [comment]
This is fixed in Isar v4
