### ISSUE TITLE
IsarError: The provided ObjectId does not match the collection.

### ISSUE THREAD

**Issue by gcxfd** [isar/isar#132]
**Steps to Reproduce**

download libisar_macos_x64.dylib and rename to libisar.dylib

clone https://github.com/gcxfd/isar.template

dart run

**Code sample**

I try code in Quickstart ( https://isar.dev/ )

IsarError: The provided ObjectId does not match the collection.

```
import 'package:isar/isar.dart';
import 'package:rmw/isar.g.dart';
import 'package:rmw/db.dart';

void main(List<String> arguments) async {
  final isar = await openIsar(
      directory:".",
      name:"db"
  );
  final contact = Contact()
      ..name = "My first contact";

  await isar.writeTxn((isar) async {
    isar.contacts.put(contact);
  });

  final allContacts = isar.contacts.where().findAll();

  print(allContacts);
}
```

**Version**

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.4
  isar_generator: ^0.4.0
  lints: ^1.0.0

dependencies:
  isar: ^0.4.0

**Comment by leisim** [comment]
Fixed with stable release
