### ISSUE TITLE
anyId() should return QueryBuilder<OBJ, R, QAfterWhereClause> not QueryBuilder<OBJ, R, QAfterWhere>

### ISSUE THREAD

**Issue by otmi100** [isar/isar#1337]
All other WHERE operations like _idEqualTo_ return _QueryBuilder<OBJ, R, QAfterWhereClause>_. As anyId() is a placeholder if no where statement is necessary, it should return _QAfterWhereClause_ too.

Maybe I'm wrong? :) 

  isar_generator: ^3.1.0+1

Keep up the good work!

**Comment by simc** [comment]
This should be fixed in v4
