### ISSUE TITLE
Isar generator fails with "Constructor parameter type does not match property type"

### ISSUE THREAD

**Issue by jcalven** [isar/isar#1348]
### Steps to Reproduce

In isar 4.0.0-dev.3, the isar generator fails in the following use-case:

### Code sample

```dart
abstract class Foo {
  Foo({
    String? id,
  }) : id = id ?? const Uuid().v4();

  @Id()
  final String id;
}

@collection
class Bar extends Foo {
  Bar({
    super.id,
  });
}
```

Error:

```
[SEVERE] isar:isar_generator on lib/src/example.dart:

Constructor parameter type does not match property type
package:example/src/example.dart:40:11
   ╷
40 │     super.id,
   │           ^^
   ╵
[INFO] Running build completed, took 977ms
```

It's of course always possible to work around it, but it's not as clean:

```dart
abstract class Foo {
  Foo({
    String? id,
  }) : id = id ?? const Uuid().v4();

  final String id;

  @Id()
  String get isarId => id;

}

@collection
class Bar extends Foo {
  Bar({
    super.id,
  });
}
```

### Details

 - Platform: x86 Android Emulator on macOS
 - Flutter version: [3.10.6]
 - Isar version: [4.0.0-dev.3]

**Comment by simc** [comment]
Sorry, this one I really don't know how to fix. I recommend creating a separate class just for Isar if you find the requirements to restrictive
