### ISSUE TITLE
Constructor parameter type does not match property type

### ISSUE THREAD

**Issue by valdineifer** [isar/isar#1351]
When I run `build_runner`, it returns an error: `Constructor parameter type does not match property type`, because of createdAt nullable parameter, but it doesn't seems wrong to me.

### Steps to Reproduce
Having the dart/flutter packages described in Isar documentation, create a class like the code below and run `flutter pub run build_runner build`.

### Code sample

```dart
@collection
class Album {
  Id id = Isar.autoIncrement;

  final DateTime createdAt;

  Album(this.id, { DateTime? createdAt }):
    createdAt = createdAt ?? DateTime.now();
}
```

### Details

 - Platform: Windows 11
 - Flutter version: 3.10.6
 - Isar version: 3.1.0+1
 - Build runner: 2.4.6

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
Either use `DateTime?` or `DateTime` for both the constructor parameter and the property

**Comment by nathnaeld** [comment]
I have encountered a similar issue. I am using "freezed" package to generate models. I have no control over how "freezed" generates properties and constructors, so I have to make all properties nullable. This is not a good solution to always use nullable variables. Please, give us a better solution.
