### ISSUE TITLE
isar_flutter_libs - Namespace not specified. Specify a namespace in the module's build file

### ISSUE THREAD

**Issue by MrCsabaToth** [isar/isar#1354]
### Steps to Reproduce

I depend on Isar `3.1.0+1` in my app. I just tried to upgrade the Android side of the Flutter app to AGP 8.0+ (to be precise it's AGP 8.1 now), because Android Studio brings up the upgrade assistant for the last half year about this. The upgrade fails because some of the plugins don't have the `namespace` in their `build.gradle`. On of the failing plugins is the `isar_flutter_libs`.

### The build error message

```
A problem occurred configuring project ':isar_flutter_libs'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
```

### Code sample

Current `build.gradle`:
```groovy
android {
    compileSdkVersion 30

    defaultConfig {
        minSdkVersion 16
    }
}
```

Expected (the way it is handled in Flutter Community plugins, along with he removal of the namespace from the AndroidManifest.xml):
```groovy
android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'dev.isar.isar_flutter_libs'
    }

    compileSdkVersion 30

    defaultConfig {
        minSdkVersion 16
    }
}
```

### Details

 - Platform: Android 12, OnePlus Nord EU (AC2003)
 - Flutter version: Channel beta, 3.13.0-0.2.pre
 - Development OS: Devuan GNU/Linux 6 (excalibur/ceres) 6.4.0-1-amd64, locale en_US.UTF-8
 - Isar version: 3.1.0+1

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
I fixed this in the latest v4 release

**Comment by ZR233** [comment]
please fix it in v3

**Comment by basselalsayed** [comment]
@ZR233 we made a fork of 3.1.0+1 to use gradle v8

I copied what @simc did in v4, so you'll need minSDK 23

```
# pubspec.yaml

isar_flutter_libs:
  git:
    url: https://github.com/toshitech/isar.git
    path: packages/isar_flutter_libs/
```

**Comment by derrickgw** [comment]
v4.0 looks like it will be an extensive release.  In the meantime, this is becoming a serious issue.  I need to upgrade packages that will require gradle 8.0.  

Please release a 3.1.0+2 so that we can keep our projects up to date.

**Comment by MrLittleWhite** [comment]
D

> v4.0 looks like it will be an extensive release. In the meantime, this is becoming a serious issue. I need to upgrade packages that will require gradle 8.0.
> 
> Please release a 3.1.0+2 so that we can keep our projects up to date.

Same issue

**Comment by MrCsabaToth** [comment]
I monkey patched gradle file of the installed version in the Flutter cache. Android Studio marks it as yellow (outside of your repo), but that's a solution. Only if a new version is installed the monkey patch needs to be repeated, but the next version will fix it anyway.

**Comment by derrickgw** [comment]
That could work for testing things out locally.  But unfortunately it won't
work so well in the CI pipeline.

Ultimately I decided to migrate to Realm. Although the dart port is recent,
it has a very strong community, and I don't worry about it disappearing in
the same way the ISAR seems to be.

-- Derrick Gibelyou

**Comment by MrCsabaToth** [comment]
> That could work for testing things out locally.  But unfortunately it won't
> work so well in the CI pipeline.
> 
> Ultimately I decided to migrate to Realm. Although the dart port is recent,
> it has a very strong community, and I don't worry about it disappearing in
> the same way the ISAR seems to be.
> 
> -- Derrick Gibelyou

I have some CI (not CD), but tests don't cover Isar. For me the speed matters a lot, and Isar is very good at that. Someone could fork and patch this or you can also shuttle ahead to the development versions, which cover this already.

**Comment by mrclauss** [comment]
Fixed in isar-community

**Comment by wagner1343** [comment]
! year and still not fixed xP nice package

**Comment by mrclauss** [comment]
That's why Isar-Community fork exists ;)

Am 15. April 2024 22:41:36 MESZ schrieb Wagner Silvestre Wuchryn Martins ***@***.***>:
>1 year and still not fixed xP nice package
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/isar/isar/issues/1354#issuecomment-2057770197
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

-- 
Martin Clauss
Meine Contactulater Card - All meine Kontaktinfo immer aktuell und vollständig:
https://contactulater.app/me/mc

**Comment by deep-sumato** [comment]
```
isar_flutter_libs: 
    git:
      url: https://github.com/Deepjyoti120/isar_flutter_libs.git
      ref: main
```


please try this repo to fix this issue
Thank you
