### ISSUE TITLE
Encryption seems not wot work in Isar v4

### ISSUE THREAD

**Issue by abhay-s-rawat** [isar/isar#1360]
I am not sure how encryption is working but I read in documentation that encryption only works when engine is sqlite.

Step 1: I created a database and inserted 1000 records with some encyption key.
Step2: I am reading same database but with diffrent key but instead of giving error it is giving correct record, seems like encryption is not working.

```
final Isar isar = await Isar.openAsync(
      schemas: [IsarUserSchema],
      directory: dir.path,
      engine: IsarEngine.sqlite,
      encryptionKey: "testKey",
    );
```

Plus if I execute below, they both give opposite bool values.
isar.close() always return false
when I run isar.isOpen after closing it will return isar.isOpen=false
So I don't know it is open or closed.

```
bool isClosed = isar.close();
print( 'isar object closed isClosed: $isClosed, isar.isOpen: ${isar.isOpen}');
```

**Comment by simc** [comment]
Could you please provide a small piece of code that shows the issue? Unit test style 🙂

**Comment by abhay-s-rawat** [comment]
I created getIsarCollection() to get the box.

```
Future<Isar> getIsarCollection() async {
    final dir = await getApplicationSupportDirectory();
    final Isar isar = await Isar.openAsync(
      schemas: [IsarUserSchema],
      directory: dir.path,
      engine: IsarEngine.sqlite,
      encryptionKey: "kb123567",
    );
    return isar;
  }
```
And in Initstate of a stateful widget
```
initialize() async {
    Stopwatch stopwatch = Stopwatch()..start();
    isar = await Helper.instance.getIsarCollection();
    //data = await isar!.isarUsers.where().sortByAge().findAll();
    IsarUser? user = await isar!.isarUsers.getAsync("user_80000");
    //IsarUser2? user2 = await isar!.isarUser2s.get(50000);
    //data = await isar!.isarUsers.where().ageEqualTo(45656).findAll();
    print(
        'ISAR list loaded in ${stopwatch.elapsed.inMilliseconds}ms : age=${user?.age}');
    stopwatch.stop();
    setState(() {});
  }
```

**Comment by abhay-s-rawat** [comment]
I already have data in the table with different key for encryption. In stateful widget I always get the record , even if I have entered wrong ecnryption key.

**Comment by abhay-s-rawat** [comment]
macos

**Comment by simc** [comment]
That's so odd. All the unit tests are passing including the ones that tests encryption. Could you maybe provide a working piece of code that highlights the issue? A whole file or something like that

**Comment by abhay-s-rawat** [comment]
[db_test.zip](https://github.com/isar/isar/files/12233819/db_test.zip)
Here is my test project. I was testing hive vs Isar

**Comment by juliaen-dr** [comment]
I also have a few questions regarding encryption:

- will encryption also be supported for web? 
- will encryption only work with sqlite or also with the native Isar engine?

**Comment by simc** [comment]
Something is wrong here I can reproduce the issue thank you

**Comment by simc** [comment]
Thanks a lot for reporting this error and providing steps to reproduce. You found two bugs and both are fixed. Both encryption and `isar.close()` now work with `Isar.openAsync()`.

Isar 4.0.0-dev.7 should soon be on pub.dev

**Comment by abhay-s-rawat** [comment]
Thanks a lot for your efforts on making this database the best in every class.
