### ISSUE TITLE
Sorting by composite index results in unexpected behavior

### ISSUE THREAD

**Issue by auradigitaldev** [isar/isar#1367]
### Steps to Reproduce

When I sort by a composite index using `where().firstFieldEqualToAnySecondField()`, I expect the sort order to sort by the second field, since that is the only field that varies. However, I've been observing that the results returned will be in an arbitrary order.

I'm not sure if this is intended behavior, but if it is I believe it would make sense to update.

### Code sample

```dart
Provide a few simple lines of code to show your problem.

  Stream<List<ExampleItemModel>> watchItems() async* {
    final query = isar.exampleItemModels.where(sort: Sort.asc).firstFieldEqualToAnySecondField(0).build();
    await for (final results in query.watch(fireImmediately: true)) {
      if (results.isNotEmpty) {
        yield results;
      }
    }
  }

@collection
class ListItemModel {
  Id id = Isar.autoIncrement;

  @Index()
  @Index(composite: [CompositeIndex('secondField')])
  int? firstField;

  String? secondField;
}
```

### Details

 - Platform: Android 13 (Google Pixel 6a)
 - Flutter version: 3.10.5
 - Isar version: 3.1.0+1

---

 - [ X] I searched for similar issues already
 - [X ] I filled the details section with the exact device model and version
 - [X ] I am able to provide a reproducible example

**Comment by simc** [comment]
This may be an issue but I'm going to close it since it has certainly be fixed in Isar v4
