### ISSUE TITLE
[Linux-x64] Failed to load dynamic library (libcrypto.so.1.1)

### ISSUE THREAD

**Issue by FMotalleb** [isar/isar#1375]
### Error:
* > Invalid argument(s): Failed to load dynamic library 'libisar.so': libcrypto.so.1.1: cannot open shared object file: No such file or directory 
same issue in linux

### Details
* Debian 12 bookworm is using (libssl3:3.0.9-1/stable) (LTS)
* IsarLibs using LibSSL:1.1.*(also LTS) which will be discontinued later this year

### Platform
 - Platform: Debian 12 (bookworm) (Linux-x64)
 - LibSLL version: 3.0.9-1
 - Flutter version: 3.10.6

**Comment by simc** [comment]
This is the same issue as #1352
