### ISSUE TITLE
Isar 3.X.X support for latest version of analyzer

### ISSUE THREAD

**Issue by SunlightBro** [isar/isar#1376]
**Is your feature request related to a problem? Please describe.**
isar: 3.1.0+1 (isar_generator) does not support the latest version of analyzer: 6.1.0

I know the main focus atm is isar 4, but would it be possible to publish another version e.g. 3.2.0 of
isar, isar_generator, isar_flutter_libs, ...
that support analyzer: ^6.0.0 ?

**Comment by shilangyu** [comment]
Version 6 of analyzer seems to only remove deprecated code, no real breaking changes for isar. I opened a PR with a bump of the upper bound.

**Comment by philos3** [comment]
any release version to fix this issue @simc

**Comment by FantixX** [comment]
a release would be greatly appreciated
