### ISSUE TITLE
Isar connector throws error at start

### ISSUE THREAD

**Issue by jackdy-prog** [isar/isar#138]
**Steps to Reproduce**
Hi, first of all thank you very much for the great work that you have been doing with Hive and Isar lately. Really looking forward to a stable version of Isar. I have been having some problems recently with connecting to Isar inspector using the example in the docs. I have a very simple _Contact_ table with an id and name. When trying to open the inspector it throws the error below at the start: 
`Something went wrong. ext.isar.excecuteQuery: (-32000) Server error type 'null' is not a subtype of Iterable<dynamic>`

When i print the entry in the table in the terminal it all seems fine and there are no null values or anything weird: 

`Contact(id:1, name: 'My first contact') `

**Version**
   **isar**: ^0.4.0
   **isar_flutter_libs:** ^0.4.0 
  **isar_connect:** 
    git:
     url: git@github.com:isar/isar.git
     path: packages/isar_connect

**dev_dependencies**:
**isar_generator:** ^0.4.0
**build_runner:** any
**analyzer:**^1.0.0

**Comment by leisim** [comment]
Fixed with stable release
