### ISSUE TITLE
WriteTxnRequiredError (WriteTxnRequiredError: This operation requires an active write transaction.)

### ISSUE THREAD

**Issue by richard457** [isar/isar#1382]
### Steps to Reproduce
I updated to isar 4 latest and started getting the error

### Details

 - Platform: Android, Galaxy SM505UI, 
 - Flutter version: [e.g. 3.0.0]
 - Isar version: [e.g. 4.0.0+9]

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by simc** [comment]
This is not a bug. You likely use a write operation outside a write transaction. Please share your code if you need help fixing it.

**Comment by 988494** [comment]
> 这不是一个错误。您可能在写事务之外使用写操作。如果您需要帮助修复它，请分享您的代码。

```
 Future<UimCallback<UimAppLocalConfig>> clearLocalAllData() async {
    try {
      // 获取实列
      Isar _instance = await _isar;

      _instance.uimAppLocalConfigs.where().deleteAll();
      _instance.uimConversations.where().deleteAll();
      _instance.uimUserFullInfos.where().deleteAll();
      _instance.uimMessages.where().deleteAll();
      _instance.uimFriendApplications.where().deleteAll();
      _instance.uimFriendships.where().deleteAll();
      _instance.uimGroups.where().deleteAll();
      _instance.uimGroupMembers.where().deleteAll();
      return UimCallback.ok(msg: "清空本地所有数据完成！");
    } catch (e) {
      return UimCallback.fail(msg: e.toString());
    }
  }
```

**Comment by Jtplouffe** [comment]
> > 这不是一个错误。您可能在写事务之外使用写操作。如果您需要帮助修复它，请分享您的代码。
> 
> ```
>  Future<UimCallback<UimAppLocalConfig>> clearLocalAllData() async {
>     try {
>       // 获取实列
>       Isar _instance = await _isar;
> 
>       _instance.uimAppLocalConfigs.where().deleteAll();
>       _instance.uimConversations.where().deleteAll();
>       _instance.uimUserFullInfos.where().deleteAll();
>       _instance.uimMessages.where().deleteAll();
>       _instance.uimFriendApplications.where().deleteAll();
>       _instance.uimFriendships.where().deleteAll();
>       _instance.uimGroups.where().deleteAll();
>       _instance.uimGroupMembers.where().deleteAll();
>       return UimCallback.ok(msg: "清空本地所有数据完成！");
>     } catch (e) {
>       return UimCallback.fail(msg: e.toString());
>     }
>   }
> ```

You need to use a write transaction in order to delete from the database.
You will also need to `await` all of those calls.

For example:
```dart
await _instance.writeTxn(() async {
  await _instance.uimAppLocalConfigs.where().deleteAll();
  // ...
});
```
