### ISSUE TITLE
Can't read ID of collection object

### ISSUE THREAD

**Issue by binaerverkehr** [isar/isar#1389]
Hello, I'm not able to delete a collection object from the database, because I'm unable to read the ID.

```dart
@Collection()
class MyEntity {
  final Id isarId = Isar.autoIncrement;

  final otherEntity = IsarLink<OtherEntity>();
  final DateTime createdAt;
  final String text;

  MyEntity ({this.text = ""}) : createdAt = DateTime.now();

  // to string
  @override
  String toString() {
    return 'MyEntity (id: $isarId, otherEntity : $otherEntity , createdAt: $createdAt, text: ${text.substring(0, 10)})';
}
```

```dart
  final newMyEntity= MyEntity(
    text: "......",
  )..otherEntity.value = newOtherEntity;

print("newMyEntity.isarId: ${newMyEntity.isarId}"); // --> JobApplicationEntity (id: -9223372036854775808, .....
```

In the database inspector the object ID is 1 and increments with every object, but when I read the ID or print it I get this long number "id: -9223372036854775808"..... What am I doing wrong?

Also when the object is saved in the database, the ID is not correct. But in the inspector it is.

### Details

 - Platform: Windows 10
 - Flutter version: 3.10.6
 - Isar version: 3.1.0+1

---

**Comment by ilovelinux** [comment]
When you use `Isar.autoIncrement` you can't know the real ID until you put it into the database.

The value you see is a special value to indicate that it's not a real id but must be assigned with autoIncrement.

The actual object's ID will be returned by the `put()` function.

**Comment by binaerverkehr** [comment]
> When you use `Isar.autoIncrement` you can't know the real ID until you put it into the database.
> 
> 
> 
> The value you see is a special value to indicate that it's not a real id but must be assigned with autoIncrement.
> 
> 
> 
> The actual object's ID will be returned by the `put()` function.

Thank you for your support.

But I also get this when reading the collection objects which have been saved in the db.

**Comment by ilovelinux** [comment]
As written in [`put()` documentation](https://pub.dev/documentation/isar/latest/isar/IsarCollection/put.html):
>Insert or update an `object`. Returns the id of the new or updated object.
>
>**If the object has an non-final id property, it will be set to the assigned id. Otherwise you should use the returned id to update the object.**

Example:
```dart
// test.dart

import 'package:isar/isar.dart';

part 'test.g.dart';

@collection
class DataWithFinalID {
  final Id id = Isar.autoIncrement;
}

@collection
class DataWithoutFinalID {
  Id id = Isar.autoIncrement;
}

void main() async {
  await Isar.initializeIsarCore(download: true);
  final isar = await Isar.open(
    [DataWithFinalIDSchema, DataWithoutFinalIDSchema],
    directory: '.',
  );

  for (var i = 0; i < 3; i++) {
    final newData = DataWithFinalID();
    print('Created element $i with final ID ${newData.id}');
    final idAfterPut = await isar.writeTxn(() => isar.dataWithFinalIDs.put(newData));
    print('Put element $i with ID $idAfterPut');
    final fetchedData = await isar.dataWithFinalIDs.get(idAfterPut);
    print('Element $i has final ID: ${fetchedData?.id}\n');
  }

  print("=======\n");

  for (var i = 0; i < 3; i++) {
    final newData = DataWithoutFinalID();
    print('Created element $i with ID ${newData.id}');
    final idAfterPut = await isar.writeTxn(() => isar.dataWithoutFinalIDs.put(newData));
    print('Put element $i with ID $idAfterPut');
    final fetchedData = await isar.dataWithoutFinalIDs.get(idAfterPut);
    print('Element $i has ID: ${fetchedData?.id}\n');
  }

  await isar.close(deleteFromDisk: true);
}
```

Output:
```
Created element 0 with final ID -9223372036854775808
Put element 0 with ID 1
Element 0 has final ID: -9223372036854775808

Created element 1 with final ID -9223372036854775808
Put element 1 with ID 2
Element 1 has final ID: -9223372036854775808

Created element 2 with final ID -9223372036854775808
Put element 2 with ID 3
Element 2 has final ID: -9223372036854775808

=======

Created element 0 with ID -9223372036854775808
Put element 0 with ID 1
Element 0 has ID: 1

Created element 1 with ID -9223372036854775808
Put element 1 with ID 2
Element 1 has ID: 2

Created element 2 with ID -9223372036854775808
Put element 2 with ID 3
Element 2 has ID: 3
```

**Comment by binaerverkehr** [comment]
> As written in [`put()` documentation](https://pub.dev/documentation/isar/latest/isar/IsarCollection/put.html):
> 
> >Insert or update an `object`. Returns the id of the new or updated object.
> 
> >
> 
> >**If the object has an non-final id property, it will be set to the assigned id. Otherwise you should use the returned id to update the object.**
> 
> 
> 
> Since your object has final id, it will not be updated.
> 
> 
> 
> Example:
> 
> ```dart
> 
> // test.dart
> 
> 
> 
> import 'package:isar/isar.dart';
> 
> 
> 
> part 'test.g.dart';
> 
> 
> 
> @collection
> 
> class DataWithFinalID {
> 
>   final Id id = Isar.autoIncrement;
> 
> }
> 
> 
> 
> @collection
> 
> class DataWithoutFinalID {
> 
>   Id id = Isar.autoIncrement;
> 
> }
> 
> 
> 
> void main() async {
> 
>   await Isar.initializeIsarCore(download: true);
> 
>   final isar = await Isar.open(
> 
>     [DataWithFinalIDSchema, DataWithoutFinalIDSchema],
> 
>     directory: '.',
> 
>   );
> 
> 
> 
>   for (var i = 0; i < 3; i++) {
> 
>     final newData = DataWithFinalID();
> 
>     print('Created element $i with final ID ${newData.id}');
> 
>     final idAfterPut = await isar.writeTxn(() => isar.dataWithFinalIDs.put(newData));
> 
>     print('Put element $i with ID $idAfterPut');
> 
>     final fetchedData = await isar.dataWithFinalIDs.get(idAfterPut);
> 
>     print('Element $i has final ID: ${fetchedData?.id}\n');
> 
>   }
> 
> 
> 
>   print("=======\n");
> 
> 
> 
>   for (var i = 0; i < 3; i++) {
> 
>     final newData = DataWithoutFinalID();
> 
>     print('Created element $i with ID ${newData.id}');
> 
>     final idAfterPut = await isar.writeTxn(() => isar.dataWithoutFinalIDs.put(newData));
> 
>     print('Put element $i with ID $idAfterPut');
> 
>     final fetchedData = await isar.dataWithoutFinalIDs.get(idAfterPut);
> 
>     print('Element $i has ID: ${fetchedData?.id}\n');
> 
>   }
> 
> 
> 
>   await isar.close(deleteFromDisk: true);
> 
> }
> 
> ```
> 
> 
> 
> Output:
> 
> ```
> 
> Created element 0 with final ID -9223372036854775808
> 
> Put element 0 with ID 1
> 
> Element 0 has final ID: -9223372036854775808
> 
> 
> 
> Created element 1 with final ID -9223372036854775808
> 
> Put element 1 with ID 2
> 
> Element 1 has final ID: -9223372036854775808
> 
> 
> 
> Created element 2 with final ID -9223372036854775808
> 
> Put element 2 with ID 3
> 
> Element 2 has final ID: -9223372036854775808
> 
> 
> 
> =======
> 
> 
> 
> Created element 0 with ID -9223372036854775808
> 
> Put element 0 with ID 1
> 
> Element 0 has ID: 1
> 
> 
> 
> Created element 1 with ID -9223372036854775808
> 
> Put element 1 with ID 2
> 
> Element 1 has ID: 2
> 
> 
> 
> Created element 2 with ID -9223372036854775808
> 
> Put element 2 with ID 3
> 
> Element 2 has ID: 3
> 
> ```
> 
> 

That's it, I removed "final" and now it works. And the ID starts by 1. 

Thank you!
