### ISSUE TITLE
Database hook

### ISSUE THREAD

**Issue by richard457** [isar/isar#1391]
**Is your feature request related to a problem? Please describe.**
I found myself wanting to know if an action is performed anywhere in my app, such as creating, updating, deleting, etc...

**Describe the solution you'd like**
I believe that there is a way to be notified of events performed to the db and potentially knowing the model that is involved in the action will help me a lot, this is like a hook
**Describe alternatives you've considered**
I considered putting watchers everywhere until everything started to be messy and not easy to follow

**Comment by simc** [comment]
I don't think that's a good feature for the database. It would be a good package on top. It should be rather easy to wrap the database and expose callbacks for changes.
