### ISSUE TITLE
RemoteError (Invalid argument:  <- _List len:1 (from dart:core) is unsendable object (see restrictions listed at`SendPort.send()` documentation for more information): Instance of 'Future<Null>')

### ISSUE THREAD

**Issue by richard457** [isar/isar#1393]
RemoteError (Invalid argument:  <- _List len:1 (from dart:core)
is unsendable object (see restrictions listed at`SendPort.send()` documentation for more information): Instance of 'Future<Null>')
at line   _activeIsolates++;
  final result = await Isolate.run(callback, debugName: debugName);

### Details

 - Platform: Android, Galaxy S7, x86 Android Emulator on Windows etc.
 - Flutter version: 3.10
 - Isar version: v9 latest

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by simc** [comment]
You are trying to pass an Isar instance or collection inside an async transaction or to a different isolate.

Use the isar parameter given to you in the transaction

**Comment by simc** [comment]
Please reopen if you still have issues :)

**Comment by Bendix20** [comment]
I'm getting the same error. For me this happens when I try to save data asynchronously. For example:

```
 await _isar.writeAsync((isar) async {
   isar.dbGoalTemplates.putAll(goalTemplates);
 });
```

Saving the data synchronously works just fine

**Comment by simc** [comment]
It seems like you pass data into the async transaction that Dart cannot send to a background isolate. If your sample is the exact code you used, most likely Dart tries to capture more variables than it should. Try using

```dart
await _isar.writeAsyncWith(goalTemplates, (isar, templates) async {
   isar.dbGoalTemplates.putAll(templates);
});
```

**Comment by Bendix20** [comment]
Unfortunately this throws the same exception :/
The `goalTemplates` is a list of isar collection objects. So shouldn't that be fine? In v3 the async insertion also works. I just try to migrate this old insertion function to v4:

```
await _isar.writeTxn(() async {
   for (final goalTemplate in goalTemplates) {
     await _isar.dbGoalTemplates.put(goalTemplate);
   }
});
```

**Comment by simc** [comment]
Could you show me the GoalTemplate class?

**Comment by Bendix20** [comment]
```
@Collection(inheritance: false)
class DbGoalTemplate with EquatableMixin {
  final String id;
  final String title;
  final String description;
  final String longDescription;
  final bool isDefault;
  final bool isUnique;

  DbGoalTemplate({
    required this.id,
    required this.title,
    required this.description,
    required this.longDescription,
    required this.isDefault,
    required this.isUnique,
  });

  @ignore
  @override
  List<Object?> get props {
    return [
      id,
      title,
      description,
      longDescription,
      isDefault,
      isUnique,
    ];
  }
}
```

**Comment by simc** [comment]
That's weird. Unfortunately I'm not sure what is wrong. I'm fairly confident it's not an Isar issue however. If you can share a sample project I can help to debug the issue

**Comment by niklasbartsch** [comment]
@Bendix20 do you use `freezed`? 
I got the same error when using `freezed`, you have to use `@Collection(ignore: {'copyWith'})`
Do you have the `@freezed` annotation?
