### ISSUE TITLE
num data type not supported

### ISSUE THREAD

**Issue by muazam99** [isar/isar#1396]
[ Feature Suggestions ]

Hope you can add num data types to supported data types. 

My use case is im currently working on ecommerce apps which have used num data types across our apps, and now try to implement offline system with the Isar DB. since num is not supported, it would be problems if I want to create another model just for this feature, and also problems if I were to change every num to double. it would be really helpful if can use back the current model. 

Thank you.

**Comment by simc** [comment]
You can change `num` to `dynamic` which allows you to store both integers and doubles. Unfortunately it's not possible to directly support `num`

**Comment by muazam99** [comment]
But I believe dynamic is not supported .

**Comment by simc** [comment]
Isar v4 supports dynamic

**Comment by muazam99** [comment]
i see.. ok thank you!
