### ISSUE TITLE
Add a sample project

### ISSUE THREAD

**Issue by dgandhi17** [isar/isar#14]
Can you add a sample flutter project, as I am facing couple of challanges between flutter version/null safety as the library depends on path_provider.

**Error:**
```
Because no versions of isar_flutter match >0.0.2 <0.1.0 and isar_flutter 0.0.2 depends on path_provider ^1.6.24, isar_flutter ^0.0.2 requires path_provider ^1.6.24.
And because path_provider >=1.6.17 depends on path_provider_windows ^0.0.4, isar_flutter ^0.0.2 requires path_provider_windows ^0.0.4.
And because every version of path_provider_windows depends on ffi ^0.1.3 and isar >=0.0.1 depends on ffi ^0.2.0-nullsafety.1, isar_flutter ^0.0.2 is incompatible with isar >=0.0.1.
So, because test_db depends on both isar ^0.0.2 and isar_flutter ^0.0.2, version solving failed.
pub get failed (1; So, because test_db depends on both isar ^0.0.2 and isar_flutter ^0.0.2, version solving failed.)
```

**Comment by leisim** [comment]
Will do ;)

**Comment by Abhishek01039** [comment]
Thanks @leisim

**Comment by Abhishek01039** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/56479665/104798610-508a3580-57ee-11eb-9a2b-1d6d7cc5403b.png">
Getting this error

**Comment by leisim** [comment]
@Abhishek01039 No you need to import it

**Comment by dgandhi17** [comment]
@Abhishek01039  that .g.dart file will get generated on top of your collections once you run build_runner. and than you can use openIsar()

**Comment by leisim** [comment]
@dgandhi17 @Abhishek01039 I just published the first sample app. I plan to add a lot more. Maybe the community will also help out :)

https://github.com/isar/samples

**Comment by Abhishek01039** [comment]
Thanks @leisim

**Comment by dgandhi17** [comment]
I am looking forward to a documentation specific to queries.

**Comment by leisim** [comment]
@dgandhi17 The docs for queries are finished and quite detailed. What do you miss?

**Comment by dgandhi17** [comment]
I did saw, earlier I thought it wasn't complete my bad.
