### ISSUE TITLE
TimeOfDay is not supported in isar

### ISSUE THREAD

**Issue by gopiKrishnaPuligundla** [isar/isar#1405]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.5.4]
 - Isar version: [e.g. 0.5.0]

**Comment by simc** [comment]
`TimeOfDay` is a Flutter specific class and I don't intend to support those. Please store the time as seconds since midnight instead
