### ISSUE TITLE
[v4]Dart Unit Test: Could not initialize IsarCore library for processor architecture "windows_x64"

### ISSUE THREAD

**Issue by agufagit** [isar/isar#1429]
### Steps to Reproduce

1. git clone https://github.com/agufagit/ferry
2. download isar_windows_x64.dll, put it in folder `ferry/packages/ferry_isar_store/test` (I also tried to place it in every parent folders)
3. `cd ferry/packages/ferry_isar_store`
4. `dart test`

error:
```
00:00 +0 -1: loading test\ferry_isar_test.dart [E]
  Failed to load "test\ferry_isar_test.dart":
  Could not initialize IsarCore library for processor architecture "windows_x64". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies. For Dart-only apps or unit tests, make sure to place the correct Isar binary in the correct directory.
  Invalid argument(s): Failed to load dynamic library '.': error code 6
  package:isar/src/native/native.dart 26:5  initializePlatformBindings
  package:isar/src/isar_core.dart 42:20     IsarCore._initialize
  package:isar/src/isar.dart 35:21          Isar.initialize
  test\ferry_isar_test.dart 8:14            main
```

### Details

 - Platform: windows 11.
 - Dart version: 3.1.0
 - Isar version: 4.0.0-dev14

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by dustincatap** [comment]
I managed to solve this issue by downloading the latest `isar_windows_x64.dll` here https://github.com/isar/isar/releases, renamed it to `isar_windows.dll`, placed it inside the project root directory (i.e `your_app/isar_windows.dll`), and initialized Isar like this:

```dart
class TestIsarDatabaseFactory implements IsarDatabaseFactory {
  @override
  Future<Isar> getIsar() async {
    await Isar.initialize('isar_windows.dll'); // update appropriately based on platform you are running your tests
    const String databasePath = Isar.sqliteInMemory;
    final Isar isar = Isar.open(
      schemas: <IsarGeneratedSchema>[...],
      directory: databasePath,
      engine: IsarEngine.sqlite,
      inspector: false,
    );

    return isar;
  }
}
```
