### ISSUE TITLE
[Feature] Update specific fields

### ISSUE THREAD

**Issue by agufagit** [isar/isar#1435]
**Is your feature request related to a problem? Please describe.**
Possible race condition?

To update a record, now we have to 1. get that record first, 2. update fields in code, then 3. put it in database.  This is fine with single isolate, but I have another background isolate updating the same collection and could possibly update that record during step 2. but before step 3, and background isolate updated information would be lost.

**Describe the solution you'd like**
Ability to update specific fields of a record

**Describe alternatives you've considered**
use SqlLite engine

**Version**
 - Platform: windows 11
 - Flutter version: 3.13
 - Isar version: 4.0.0-dev14

**Comment by johnbonds** [comment]
For the edification of other who land here wondering why I imagine @agufagit closed this issue, I believe that the solution is tied to:

https://isar.dev/transactions.html

While far from a perfect solution, transactions appear to allow the reading of an object, updating its properties and writing back to the database in an ACID compliant manner.

It would be lovely to be able to perform an update using a single query at some point similar to other noSQL databases.

i.e. db.document.update({id: "123456"}, {$set: { property: "newValue" }} )
