### ISSUE TITLE
[V4] nullable enumerations

### ISSUE THREAD

**Issue by w41x** [isar/isar#1439]
In version 3.0.0+1 it was possible to define an EnumerationType, which would allow one to have nullable enumeration properties in a collection (e.g.: via @Enumerated(EnumType.name)).
In version 4.0.0-dev.14 this seems to be not longer possible. There is a @EnumValue()-Annotation though, but it is not completly implemented yet as there is no way to pass arguments to that annotation nor does it make an enumeration nullable.
What is the timeline until this feature is implemented? 

Of course one could define a 'unknown' or 'none' value in the enumeration as an analog way to say: this is null in theory; but what is the point?

### Steps to Reproduce

Mark an enumeration property in a collection as nullable via adding a '?'. There is no way to make this build.
It always throws:

```bash
[SEVERE] isar:isar_generator on xyz.dart:

Bytes must not be nullable.
```

### Code sample

```dart
@collection
class Person {

  @Id()
  late int id;

  late String firstName;

  late String lastName;

  //Does not have to be provided
  PersonGender? gender;

  //Does not have to be provided
  DateTime? birthday;

}

enum PersonGender {

  male(asText: 'male'),
  female(asText: 'female');
  //and others of course ...

  const PersonGender({required this.asText});

  final String asText;

}
```

### Details

 - Platform: MacOS 13.5.2 
 - Flutter version: 3.13.3
 - Isar version: 4.0.0-dev.14

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by w41x** [comment]
I just got it. ;)

You add the @enumValue to the property in the ENUMERATION that defines the value.
So in the above code sample we should have:

```dart
@collection
class Person {

  @Id()
  late int id;

  late String firstName;

  late String lastName;

  //Does not have to be provided
  PersonGender? gender;

  //Does not have to be provided
  DateTime? birthday;

}

enum PersonGender {

  male(asText: 'male'),
  female(asText: 'female');
  //and others of course ...

  const PersonGender({required this.asText});

  @enumValue
  final String asText;

}
```

**Comment by KRTirtho** [comment]
TBH, the old @enummerrated was more convinient. Becuase what if I want to use the `Enum.name` instead of a property.
When we have a large enum, re-declaring their name isn't really a great experience.
