### ISSUE TITLE
ios phone  bug

### ISSUE THREAD

**Issue by htsunshine** [isar/isar#144]
await openIsar()

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, isar_connect_dart_api): symbol not found)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
#1      IsarCoreBindings._isar_connect_dart_api_ptr (package:isar/src/native/bindings.dart:200:60)
#2      IsarCoreBindings._isar_connect_dart_api_ptr (package:isar/src/native/bindings.dart)
#3      IsarCoreBindings._isar_connect_dart_api (package:isar/src/native/bindings.dart:203:7)
#4      IsarCoreBindings._isar_connect_dart_api (package:isar/src/native/bindings.dart)
#5      IsarCoreBindings.isar_connect_dart_api (package:isar/src/native/bindings.dart:194:12)
#6      openIsarInternal (package:isar/src/native/open.dart:18:6)
<asynchronous suspension>
#7      _init (package:bgyh_app/view/app/effect.dart:42:20)
<asynchronous suspension>

**Comment by leisim** [comment]
@htsunshine please switch to the stable version and regenerate your files. `openIsar` no longer exists

**Comment by htsunshine** [comment]
isar^1.0.0+1    The generated file could not be found

appledeiMac-2:bgyh apple$ flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 483ms

[WARNING] Invalidated precompiled build script due to core package update
[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 7.8s

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 126ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 949ms

[INFO] Running build...
[INFO] Running build completed, took 45ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 87ms

[INFO] Succeeded after 144ms with 0 outputs (0 actions)

**Comment by leisim** [comment]
Did you set it up according to the docs? Isar, `isar_generator`, `build_runner` and `isar_flutter_libs`

**Comment by htsunshine** [comment]
Yes, version 0.4.0 can generate isar. g. dart files, not 1.0.0+1 or 1.0.0

**Comment by leisim** [comment]
The generator is not even running. Are you running it in the correct project (with a collection annotated with `@Collection()`? Do you have a `build.yaml`?

**Comment by htsunshine** [comment]
I can generate the same thing with 0.4.0, what is the difference with 1.0.0, there are other things to do these days

**Comment by htsunshine** [comment]
I can generate the same thing with 0.4.0, what is the difference with 1.0.0, there are other things to do these days

**Comment by leisim** [comment]
Fixed. XCode stripped the binary in some cases

**Comment by htsunshine** [comment]
[WARNING] isar_generator:isar_generator on lib/common/floor/entity/msg.dart:
[]
[WARNING] isar_generator:isar_generator on lib/common/floor/entity/session.dart:
[]
[WARNING] isar_generator:isar_generator on lib/common/floor/entity/user_info.dart:
[]
[INFO] 6.8s elapsed, 215/225 actions completed.
[INFO] 8.4s elapsed, 267/280 actions completed.
[INFO] 11.4s elapsed, 488/503 actions completed.
[INFO] 12.4s elapsed, 908/911 actions completed.
[INFO] 13.4s elapsed, 1305/1308 actions completed.
[WARNING] source_gen:combining_builder on lib/common/floor/entity/msg.dart:
msg.g.dart must be included as a part directive in the input library with:
    part 'msg.g.dart';
[WARNING] source_gen:combining_builder on lib/common/floor/entity/user_info.dart:
user_info.g.dart must be included as a part directive in the input library with:
    part 'user_info.g.dart';
[WARNING] source_gen:combining_builder on lib/common/floor/entity/session.dart:
session.g.dart must be included as a part directive in the input library with:
    part 'session.g.dart';
[INFO] Running build completed, took 14.1s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 155ms

[INFO] Succeeded after 14.2s with 3 outputs (1561 actions)

**Comment by htsunshine** [comment]
Is the generated file 'isar.g.dart' not the previous one ?

**Comment by leisim** [comment]
The error messages are quite clear imo. Like for other generator  packages you need to add `part 'your_file.g.dart';` to your collection files.

**Comment by leisim** [comment]
Isar.g.dart is no longer generated.

**Comment by htsunshine** [comment]
谢谢，我在找找原因，不会用这个生成器

**Comment by htsunshine** [comment]
Thank you. I'm trying to figure out why. I won't use this generator

**Comment by leisim** [comment]
I changed the generator to the more common part generation. The reason is the upcoming static metaprogramming feature of Dart.

**Comment by htsunshine** [comment]
Thank you. I saw your demo. It's done.
