### ISSUE TITLE
Unhandled Exception: IsarError: Unsupported processor architecture "linux_arm64". Please open an issue on GitHub to request it.

### ISSUE THREAD

**Issue by BigGitWorld** [isar/isar#1448]
Hello.
I want to use this package in a flutter application on Raspberrypi (linux arm64).
But it seems this package does not support arm64:
```
Unhandled Exception: IsarError: Unsupported processor architecture "linux_arm64". Please open an issue on GitHub to request it.
```

**Comment by BigGitWorld** [comment]
I did it by cloning isar to Raspberry-pi and building it for arm64.

**Comment by Sulisong** [comment]
> I did it by cloning isar to Raspberry-pi and building it for arm64.我通过克隆 isar 到 Raspberry-pi 并为 arm64 构建它来完成的。

Hello, I am also using Isar on Linux ARM64. Could you share the .so files that support Linux ARM64?
