### ISSUE TITLE
Unclear Error in Incorrect Transaction Type

### ISSUE THREAD

**Issue by dickermoshe** [isar/isar#1449]
### Steps to Reproduce

Please describe exactly how to reproduce the problem you are running into.
Use a Async Write function in a Non-Async Transaction or Vice Versa results in the following error:
`Write operations require an explicit transaction. Wrap your code in isar.writeTxn()`
However, it **IS** in a transaction, just the wrong type.
This took hours to debug due to the unclear message.

### Code sample

```dart
isarDB.writeTxnSync(() {
        isarDB.settings.put(state);
      });
OR
isarDB.writeTxn(() {
        isarDB.settings.putSync(state);
      });
```

### Details

 - Platform: Android Emulator
 - Flutter version: 3.13.2
 - Isar version: 3.1.0+1

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by basselalsayed** [comment]
why are you mix and matching sync and async callbacks? 

```
isarDB.writeTxnSync(() => isarDB.settings.putSync(state));

isarDB.writeTxn(() => isarDB.settings.put(state));
```

**Comment by dickermoshe** [comment]
@basselalsayed 
Let me be more clear.  
The error message caused by mixing callbacks is inaccurate.  
It should throw an error that reads "You have used an async function in a sync transaction" (or vice versa). 
Now it says that it's not in a transaction at all, which is false.
 
Mixing up transactions types and functions types will be a quite common bug, there should be a clearer error.
