### ISSUE TITLE
Isar-1.0.0+1 - IsarError: LmdbError (12): "Cannot allocate memory"

### ISSUE THREAD

**Issue by travishaagen** [isar/isar#148]
**Steps to Reproduce**

I was using Isar `0.4.0` and upgraded to `1.0.0+1`. Now, when running the app on an iPhone, startup fails with error:

```
IsarError: LmdbError (12): "Cannot allocate memory"
```

**Code sample**

Example code using `path_provider: 2.0.8` during app startup:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  Directory appDocDir = await getApplicationDocumentsDirectory();
  final isar = await Isar.open(schemas: [MySchema], directory: appDocDir.path);
```

The exception gets thrown from `openIsarNative` on the line `await stream.first;`

**Version**
 - Platform: iOS 15.2
 - Flutter version: `2.9.0-0.1.pre` (beta channel)
 - Isar version: `1.0.0+1`
 - Isar Generator version:`1.0.0+1`

**Comment by leisim** [comment]
@travishaagen thanks for the report.

1. what iPhone model does it happen on?
2. did you upgrade an existing database or is it a new one?
3. how big is the database file?

**Comment by travishaagen** [comment]
@leisim : It's an **iPhone SE**. I deleted the app, so it's a new, empty database.

**Comment by takapiroid88** [comment]
@leisim
I`m too.

platform: iPhoneX
OS version: 11.3
flutter version: 2.2.3
Isar version: 1.0.0+1

**Comment by leisim** [comment]
@takapiroid88 Does it happen for a debug or release build? Do you see the issue for every launch or only sometimes?

**Comment by takapiroid88** [comment]
@leisim 

i'm try debug build. 
every launch happened. 3 / 3

**Comment by leisim** [comment]
@travishaagen thanks! Could you maybe create a small sample app? I fail to reproduce the issue. That would be super helpful 🙌

**Comment by leisim** [comment]
@travishaagen @takapiroid88 Found the issue and fixed it. Would be awesome if you could test again with `isar: 1.0.5`

**Comment by takapiroid88** [comment]
@leisim 
Reproduced...

*Error*
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: IsarError: LmdbError (12): "Cannot allocate memory"
```

pubspec.yaml
```
dependencies:
  ...
  isar: 1.0.5
  isar_flutter_libs: 1.0.0+1
  isar_connect: 1.0.0+1
```

**Comment by leisim** [comment]
This was an isar-core problem so you need to update isar_flutter_libs. Please always use the same version for all isar dependencies.

**Comment by travishaagen** [comment]
@leisim : works in the simulator, but not on my iPhone SE (app deleted first):

```
Installing and launching...
(lldb) 2022-01-06 15:04:54.891305-0800 Runner[23940:949451] Warning: Unable to create restoration in progress marker file
Debug service listening on ws://127.0.0.1:49838/4qAMq07szjk=/ws
Syncing files to device iPhone...
* thread #18, stop reason = EXC_BAD_ACCESS (code=1, address=0x102cd0000)
    frame #0: 0x00000001de4aaca4 libsystem_platform.dylib`_platform_memset + 36
libsystem_platform.dylib`_platform_memset:
->  0x1de4aaca4 <+36>: stnp   x1, x1, [x0]
    0x1de4aaca8 <+40>: stnp   x1, x1, [x0, #0x10]
    0x1de4aacac <+44>: stnp   x1, x1, [x0, #0x20]
    0x1de4aacb0 <+48>: stnp   x1, x1, [x0, #0x30]
Target 0: (Runner) stopped.
Lost connection to device.
```

**Comment by leisim** [comment]
@travishaagen thanks for helping me to fix this! Is it an iPhone SE 2020 or the older model? Which iOS version does it run? do you also see this error in release mode?

**Comment by travishaagen** [comment]
Good news! After cleaning up the cocoapods, it seems OK. I'll do some more testing.

```shell
# from project root
flutter clean
flutter pub get

cd ios/

rm -rf ~/Library/Caches/CocoaPods Pods ~/Library/Developer/Xcode/DerivedData \
  && pod deintegrate \
  && pod repo update \
  && pod install --verbose

cd ..
```
^ Seems like I need to do this for a lot of plugins. Wish Flutter could manage it somehow.

**Comment by travishaagen** [comment]
Original iPhone SE ;)

**Comment by leisim** [comment]
phew, that is really good news! Yes, I also noticed that flutter tooling still needs a lot of work for iOS. I wish that had higher priority. Anyway, happy it works now for you! Please feel free to open issues if you experience problems 🙌

**Comment by takapiroid88** [comment]
@leisim 

thanks. 
working successfull!!
