### ISSUE TITLE
Isar v4 caseSensitive: false doesn't work

### ISSUE THREAD

**Issue by itsJoKr** [isar/isar#1495]
### Steps to Reproduce

1. Use any string query, like `isar.dbItems.where().nameStartsWith(query, caseSensitive: false)`

Expected: `caseSensitive: false` would return the same result if we search for "OEM" or "oem"
Actual: `caseSensitive: false` appears to have no effect on the result. It's doesn't work.

![image](https://github.com/isar/isar/assets/11093480/1b883173-6979-4be0-a9a5-a1a0fe2c24cd)

### Details

 - Platform:  Android Emulator on Mac 
 - Flutter version: 3.13.4
 - Isar version: 4.0.0-dev.14

---
 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version
 - [X] I am able to provide a reproducible example

**Comment by shahmirzali49** [comment]
same happen in isar v3 to me.

**Comment by Jtplouffe** [comment]
@itsJoKr Just to make sure, you are using the SQLite backend?

**Comment by itsJoKr** [comment]
> @itsJoKr Just to make sure, you are using the SQLite backend?

@Jtplouffe Yes, it's SQLite engine (I think Isar v4 still only supports SQLite engine so far).

**Comment by Jtplouffe** [comment]
> > @itsJoKr Just to make sure, you are using the SQLite backend?
> 
> @Jtplouffe Yes, it's SQLite engine (I think Isar v4 still only supports SQLite engine so far).

Perfect, then that PR should fix the issue.

As for v4, it does support the native engine, just not on the web.
