### ISSUE TITLE
Isar3: Can't use generated code in a dynamic query

### ISSUE THREAD

**Issue by bw-flagship** [isar/isar#1496]
### Steps to Reproduce

I want to build dynamic queries and use the great generated code for filtering.
Imagine my repo gets a nullable value called `myValue`.
If the value is given, I want to filter on it. If not, I want to ignore it.
(in reality, there are several values)

### Code sample

I try to do the following:
```dart
var query = _isar.items.filter();
if (myValue != null) {
  query.myValueEqualTo(myValue);
}

final result = await query.findAll();
```

The problem is that the type that is returned from `filter()` can't be used for `findAll()`.

`The method 'findAll' isn't defined for the type 'QueryBuilder'.`

What works, but is very ugly:
```dart
var query = _isar.items.where();

if (myValue != null) {
  // ignore: invalid_use_of_protected_member
  query = QueryBuilder.apply(query, (query) {
    return query.addFilterCondition(
      FilterCondition.equalTo(
        property: r'myValue',
        value: myValue,
      ),
    );  
  });
}
final result = await query.findAll();
```

### Details
 - Flutter version: 3.1.3
 - Isar version: 3.1.0

---

 - [ x ] I searched for similar issues already
 - [ x ] I filled the details section with the exact device model and version
 - [ x ] I am able to provide a reproducible example

**Comment by Jtplouffe** [comment]
I think the ideal way to do this would be to use an optional filter

Conditional:
```dart
final result = await _isar.items
  .filter()
  .optional(
    myValue != null,
    (q) => q.myValueEqualTo(myValue!),
  ).findAll();
```

[Link to docs](https://isar.dev/queries.html#query-modifiers)

**Comment by bw-flagship** [comment]
Thats exactly what I was looking for, thanks!
