### ISSUE TITLE
[isar_generator]: Update freezed_annotation to the latest version

### ISSUE THREAD

**Issue by eli1stark** [isar/isar#150]
Because isar_generator >=1.0.0 depends on freezed_annotation ^0.14.3 and my_project depends on freezed_annotation ^1.1.0, isar_generator >=1.0.0 is forbidden.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.8.1
 - Isar version: 1.0.0

**Comment by leisim** [comment]
Updated :)
