### ISSUE TITLE
[v4] anyOf return all values when list is empty

### ISSUE THREAD

**Issue by agufagit** [isar/isar#1524]
### Steps to Reproduce

- isar.counters.where().anyOf([], (q, e) => q.idEqualTo(e)).count();

when list is empty, it returns all the values instead of empty value.

### Code sample

```dart
@colleciton
class Counter{
  Counter({
    required this.id,
  })

  int id;
}
```

### Details

 - Platform:  x86 Android Emulator on Windows 11
 - Flutter version: 3.16.0
 - Isar version: 4.0.0-dev14

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by DevNico** [comment]
If you define no filter you get all elements. This is expected behaviour.
