### ISSUE TITLE
build_runner doesn't generate files

### ISSUE THREAD

**Issue by mojtabana** [isar/isar#1561]
### Steps to Reproduce
this is very simple example of Isar usage I create a dedicated repository for that.

`git clone https://github.com/mojtabana/brunner.git`
`flutter pub get`
`dart run build_runner build -d -v`

### expected result
*user.g.dart generation

### result
nothing happened!

**Comment by Jtplouffe** [comment]
I don't know if maybe you forgot to push something in that repository, but the `user.dart` file has nothing in it. For the build runner to generate the schema, you need to have a collection defined.

**Comment by mojtabana** [comment]
I pushed missing commit.
please re-check it.
thanks

**Comment by Jtplouffe** [comment]
> I pushed missing commit. please re-check it. thanks

Running the build_runner with `flutter pub run build_runner build -d` seems to be working properly on my system, maybe try upgrading flutter to the latest version?

**Comment by mojtabana** [comment]
I try it and its work in this (for test) repo.

but It did not work in my company main project!
is build_runner has conflicts with Isar?

**Comment by Jtplouffe** [comment]
> I try it and its work in this (for test) repo.
> 
> but It did not work in my company main project! is build_runner has conflicts with Isar?

I don't know, it's pretty hard to tell without a reproductible example, but I would suggest making sure that the different packages version are correct, and that the class in annotated with the `@collection` decorator.

**Comment by mojtabana** [comment]
excuse me, 
I tried to:

      - downgrade SDK to lower version fit with analyzer package => but it didn't solve
      - dependency_overrides "meta" and "analyzer" to last version => but it didn't solve
      - exactly copy/paste safe example of Isar to our root project => but still build_runner doesn't generate file
      
now after many hours struggling with Isar dependencies I found that build_runner maybe wait for isar_generator in my case,
so it's actions not completed.

> [WARNING] Heartbeat:
No actions completed for 15.1s, waiting on:
  - isar:isar_generator on lib/main.dart
  - isar:isar_generator on lib/user.dart
  
I think maybe defining order will be answer!
can you tell me how I can do this?

regards

**Comment by fenghonghui89** [comment]
> excuse me, I tried to:
> 
> ```
>   - downgrade SDK to lower version fit with analyzer package => but it didn't solve
>   - dependency_overrides "meta" and "analyzer" to last version => but it didn't solve
>   - exactly copy/paste safe example of Isar to our root project => but still build_runner doesn't generate file
> ```
> 
> now after many hours struggling with Isar dependencies I found that build_runner maybe wait for isar_generator in my case, so it's actions not completed.
> 
> > [WARNING] Heartbeat:
> > No actions completed for 15.1s, waiting on:
> 
> * isar:isar_generator on lib/main.dart
> * isar:isar_generator on lib/user.dart
> 
> I think maybe defining order will be answer! can you tell me how I can do this?
> 
> regards

I have a model file UserModel.dart. And I find that I need to create UserModel.g.dart by hand. After that, I run 'dart run build_runner build' , then I will see the generated code.

**Comment by vault-me** [comment]
Is this solved? Cause I just encounter this issue and I don't know what to do?

**Comment by mojtabana** [comment]
Try master channel, it should be work

**Comment by rddewan** [comment]
I am using [v4.0.0-dev.14] but still unable to generate a .g.dart file
