### ISSUE TITLE
Isar inspector does not work on brave

### ISSUE THREAD

**Issue by stan-at-work** [isar/isar#1570]
### Steps to Reproduce

Start your flutter application.

On chrome everything woks fine, but if i try to open the url in brave, it keeps loading.

![image](https://github.com/isar/isar/assets/147701137/110dcabf-30aa-444b-b3b6-ffef5b89c4f0)

### Details

 - Oneplus nord

![image](https://github.com/isar/isar/assets/147701137/3ac92e1e-3e40-41d8-8fbd-6022ebe95b71)

 - Isar version:
     isar: ^3.1.0+1
     isar_flutter_libs: ^3.1.0+1
     isar_generator: ^3.1.0+1

---

 - [ ] I searched for similar issues already
 - [ x] I filled the details section with the exact device model and version
 - [ x] I am able to provide a reproducible example

**Comment by samithe7** [comment]
Isar inspector only work on Google  chrome

**Comment by stan-at-work** [comment]
Why is that ? it should work on all chromium based browsers.

> Isar inspector only work on Google chrome

**Comment by vicenterusso** [comment]
It works on Brave, disable Brave Shield

**Comment by Sten435** [comment]
> It works on Brave, disable Brave Shield

Thanks
