### ISSUE TITLE
Target of Backlink does not exist for IsarLinks

### ISSUE THREAD

**Issue by kanntim** [isar/isar#1597]
### Steps to Reproduce

When I try to make a @Backlink using IsarLinks, I get the error "Target of Backlink does not exist". 
Even the code from the official example gives the same error:

### Code sample

```dart
@collection
class Teacher {
  Id id = Isar.autoIncrement;

  late String subject;

  @Backlink(to: 'teacher')
  final student = IsarLinks<Student>();
}

@collection
class Student {
  Id? id = Isar.autoIncrement;

  late String name;
  
}
```

The ERROR:

```
Target of Backlink does not exist
package:app/entity.dart:10:9
   ╷
10 │   final student = IsarLinks<Student>();
   │         ^^^^^^^
   ╵

```

### Details

 - Platform: Android 13, API Level 33, x86_64 Android Emulator on Linux.
 - Flutter version: [3.19.5]
 - Isar version: 3.1.0+1

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by JunHuaAhuaChen** [comment]
`@Backlink(to: 'teacher')`
The "teacher" is an attribute of the  @Student().
You can use
`@Backlink(to: 'name)`
@kanntim

**Comment by JunHuaAhuaChen** [comment]
@kanntim 
Student() no have IsarLinks,so no backlink.
You can
```
@collection
class Teacher {
  Id id = Isar.autoIncrement;

  late String subject;

  @Backlink(to: 'name')
  final student = IsarLinks<Student>();
}

@collection
class Student {
  Id? id = Isar.autoIncrement;

  final name=IsarLinks<Teacher >();
  
}
```
