### ISSUE TITLE
[Android11] FileSystemException is happened at Isar.open

### ISSUE THREAD

**Issue by takapiroid88** [isar/isar#162]
**Steps to Reproduce**
execute Isar.open, directory is below.

**Errors**
```
Unhandled Exception: FileSystemException: Creation failed, path = 'some' (OS Error: Read-only file system, errno = 30)
E/flutter (11085): #0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:117:11)
E/flutter (11085): #1      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (11085): #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (11085): <asynchronous suspension>
E/flutter (11085): #3      openIsarNative (package:isar/src/native/open.dart:25:3)
```

**Code sample**
```
    final isar = await Isar.open(
      schemas: [DataSchema],
      directory: 'some/directory',
    );
```

**Version**
 - Platform: Android
 - Flutter version: 2.2.3
 - Isar version: 1.0.0+1

help me...

**Comment by leisim** [comment]
You need to provide a valid directory on the platform you are running on. I recommend using `path_provider`

**Comment by barbalex** [comment]
It would help noobs like me if this were the way it is implemented in the docs - or mentioned there

**Comment by leisim** [comment]
Added it here: https://github.com/isar/isar#3-open-an-instance 🙂

**Comment by barbalex** [comment]
I am now a happy noob 😄
