### ISSUE TITLE
DateTime is not converting to local time on real device

### ISSUE THREAD

**Issue by youngNyvek** [isar/isar#1621]
### Steps to Reproduce

It's simple to reproduce the error... in my application interface, I select the date "2024-05-01" and run to save in isar. As expected and as written in the documentation, isar converts to UTC, so "2024-04-30". But when I get the record from the database, the date is not converted to the previously selected local time "2024-05-01"

But, the strange thing is... This bug only occurs on my real device, on the emulator everything is ok.

#### IN REAL DEVICE:
_The date value before inserting into ISAR:_
![image](https://github.com/isar/isar/assets/63109439/8e666a09-c8a0-487b-94ec-c7ed7aabfecf)

_The value in ISAR:_
![image](https://github.com/isar/isar/assets/63109439/f21737a7-310e-4246-9f9d-aaeb23b6a400)

_The value when I try to return it:_
![image](https://github.com/isar/isar/assets/63109439/56dd5306-f15d-49fd-a310-3c8c044d0bb9)

#### IN EMULATOR

_The date value before inserting into ISAR:_
![image](https://github.com/isar/isar/assets/63109439/30b509a1-c660-4c08-a914-8180210e0ec2)

_The value in ISAR:_
![image](https://github.com/isar/isar/assets/63109439/d510eec1-43ef-4cfc-b972-bc5039ac7be0)

_The value when I try to return it:_
![image](https://github.com/isar/isar/assets/63109439/3e76c549-9208-45e9-a585-02693040596d)

### Code sample

the problem is not with the code itself, since the error only occurs on real devices that I use, so I don't know exactly what code I can provide.. As I said, in the emulator it occurs without errors

### Details

 - Platform: Galaxy a34 (real device), Pixel 3a (emulator)
 - Flutter version: Flutter 3.22.1
 - Isar version: isar: ^3.1.0+1

---

 - [ X ] I searched for similar issues already
 - [ x ] I filled the details section with the exact device model and version
 - [ x ] I am able to provide a reproducible example

**Comment by Jtplouffe** [comment]
Maybe I'm not understanding the error properly, but this seems to be working as expected.
Isar saves dates as utc epoch microseconds, and reads them as utc epoch microseconds and then converts them to local.
I'm assuming your timezone is UTC-3?

**Comment by youngNyvek** [comment]
> Talvez eu não esteja entendendo o erro corretamente, mas parece estar funcionando conforme o esperado. Isar salva datas como microssegundos da época UTC, lê-as como microssegundos da época UTC e depois as converte para locais. Presumo que seu fuso horário seja UTC-3.

Exactly, but look at the prints. The convert to local behavior does not occur on the real device, only on the emulator

**Comment by Jtplouffe** [comment]
> > Talvez eu não esteja entendendo o erro corretamente, mas parece estar funcionando conforme o esperado. Isar salva datas como microssegundos da época UTC, lê-as como microssegundos da época UTC e depois as converte para locais. Presumo que seu fuso horário seja UTC-3.
> 
> Exactly, but look at the prints. The convert to local behavior does not occur on the real device, only on the emulator

The value that you are passing to isar is `2024-05-01T00:00:00.000Z`, which is in UTC.
Isar then returns `2024-04-30T21:00:00.000`, which is the exact same value as the input, but in your local time (`UTC-3`).

**Comment by youngNyvek** [comment]
> > > Talvez eu não esteja entendendo o erro corretamente, mas parece estar funcionando conforme o esperado. Isar salva datas como microssegundos da época UTC, lê-as como microssegundos da época UTC e depois as converte para locais. Presumo que seu fuso horário seja UTC-3.
> > 
> > 
> > Exactly, but look at the prints. The convert to local behavior does not occur on the real device, only on the emulator
> 
> The value that you are passing to isar is `2024-05-01T00:00:00.000Z`, which is in UTC. Isar then returns `2024-04-30T21:00:00.000`, which is the exact same value as the input, but in your local time (`UTC-3`).


I think I structured the issue wrong... See, I sent 6 screenshots, the first 3 are from my real device, where isar removes -3 hours, making it a UTC date as expected, but when trying to get the entered value, it is not converting to the local time, which would be +3 hours. 

Now, the other 3 prints are from the emulator, where ISAR removes -3 hours at the time of insertion and adds +3 hours at the time of obtaining the Date. In this example, I understand that it is the correct way. 

Another important detail is that both devices are UTC-3, as we can see at the time of insertion, but the results are different.

**Comment by youngNyvek** [comment]
I found the problem, I was saving the data with `DateTime.utc`... I removed that and put the conventional `DateTime`.

For some reason this was causing inconsistency between devices.
