### ISSUE TITLE
[M1 macOS] ld: library 'isar' not found

### ISSUE THREAD

**Issue by ryanhoo** [isar/isar#1628]
### Steps to Reproduce

Just add isar(along with isar_flutter_libs, isar_generator) to pubspec.yaml as the README says.

Do nothing else, just select flutter app target as macOS(Desktop), click run button and then fails:

**ld: library 'isar' not found**

```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-001429982229801E }
{ platform:macOS, arch:x86_64, id:00006000-001429982229801E }
ld: library 'isar' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **

Error: Build process failed
```

### Details

 - Platform: MacBook Pro 14.4.1 (23E224)
 - Flutter version: Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-CN)
 - Isar version: 3.1.0+1

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by Jtplouffe** [comment]
Since you are running on desktop, you will need to add `await Isar.initializeIsarCore(download: true)` before opening the `Isar` instance

**Comment by ryanhoo** [comment]
After I manually added the `libisar.dylib` to my macOS project, the project ran successfully.

**Comment by felipecastrosales** [comment]
> After I manually added the `libisar.dylib` to my macOS project, the project ran successfully.

where exactly I can add?
