### ISSUE TITLE
Isar Not Generating .g file ( 0 outputs on build)!

### ISSUE THREAD

**Issue by nate587** [isar/isar#1646]
### Steps to Reproduce

-Open new vs code (flutter) project

-Create a new folder called "note.dart" in /lib directory

-paste in following code below (in code sample section)

-Add Isar dependencies:

flutter pub add isar isar_flutter_libs path_provider
flutter pub add -d isar_generator build_runner

-Run Following command to add .g file:

dart run build_runner build

### Code sample

```import 'package:isar/isar.dart';


part 'lib/note.g.dart';


@Collection()
class Note {
  Id id = Isar.autoIncrement;
  late String text;
} 
```

My pubspec.yaml:

```name: test1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true```

I have tried creating this build,yaml too (recommended by chatgpt):

```
targets:
  $default:
    builders:
      isar_generator:
        generate_for:
          - lib/*.dart```

When I run dart run build_runner doctor:

```[WARNING] Builder isar_generator:isar_generator outputs .isar_generator.g.part  from .dart which is not specified in the `build.yaml````

### Details

 - Platform: VS Code [lastest version]
 - Flutter version: [lastest]
 - Isar version: [3.1.0+1]

---

I have tried everything and have found no help! 
1.) I have tried flutter clean and redoing build
2.) downgrading / upgrading dependencies
3.) Manually creating build.yaml 
4.) Looked at other similar issues and try those solutions
5.) Googled Same Error
6.) Asked in other communities.

**Comment by Jtplouffe** [comment]
The `part` should not have a directory in the path, it should only be the file.
Try this instead:

```dart
```
