### ISSUE TITLE
Clarify whether/how it is possible to define collections at runtime.

### ISSUE THREAD

**Issue by gisborne** [isar/isar#1653]
The only discussion of how to create a collection is by annotating a class.

But what if I want to let my users define a collection at runtime? Say, I want to make my own version of FileMaker. Is this possible?

If it is, please clarify how.

If it is not, please consider adding this feature.

Great project, thanks!

**Comment by Jtplouffe** [comment]
Hi, creating a collection at runtime is not possible.

One way to circumvent that would be to have a collection with a collection type and a field for the custom collection object data:
```dart
@collection
class CustomCollection {
  Id id;

  @Index()
  String collectionType;

  // This field could be the JSON encoded data from a custom collection type
  String customCollectionData;
}
```

Otherwise, you could use `Hive`, which might be more adequate for this use case.
