### ISSUE TITLE
Support Latest compileSdk 34 on Isar Flutter Libs

### ISSUE THREAD

**Issue by macedondev** [isar/isar#1654]
### Steps to Reproduce

Please describe exactly how to reproduce the problem you are running into.

While Build the flutter apk.

###Error: 
* What went wrong:
Execution failed for task ':isar_flutter_libs:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:D:\aurvon\aurvon\build\isar_flutter_libs\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.

### Details

 - Platform: iPhone 13 Pro, Galaxy S7, x86 Android Emulator on Windows etc.
 - Flutter version: [3.24.0]
 - Isar version:  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.4
 - 

---

 - [ ] I searched for similar issues already
 - [ ] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by f4bio** [comment]
what solved this for me, adding some scripts to the subprojects section in `android/build.gradle`:

```
allprojects {
  repositories {
    google()
    mavenCentral()
  }
}

rootProject.buildDir = "../build"
subprojects {
  //  fix for verifyReleaseResources
  // ============
  afterEvaluate { project ->
    if (project.plugins.hasPlugin("com.android.application") ||
      project.plugins.hasPlugin("com.android.library")) {
      project.android {
        compileSdkVersion 34
        buildToolsVersion "34.0.0"
      }
    }
    if (project.hasProperty("android")) {
      project.android {
        if (namespace == null) {
          namespace project.group
        }
      }
    }
  }
  // ============
  project.buildDir = "${rootProject.buildDir}/${project.name}"
  project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
  delete rootProject.buildDir
}
```

**Comment by fsmdeveloper** [comment]
> what solved this for me, adding some scripts to the subprojects section in `android/build.gradle`:
> 
> ```
> allprojects {
>   repositories {
>     google()
>     mavenCentral()
>   }
> }
> 
> rootProject.buildDir = "../build"
> subprojects {
>   //  fix for verifyReleaseResources
>   // ============
>   afterEvaluate { project ->
>     if (project.plugins.hasPlugin("com.android.application") ||
>       project.plugins.hasPlugin("com.android.library")) {
>       project.android {
>         compileSdkVersion 34
>         buildToolsVersion "34.0.0"
>       }
>     }
>     if (project.hasProperty("android")) {
>       project.android {
>         if (namespace == null) {
>           namespace project.group
>         }
>       }
>     }
>   }
>   // ============
>   project.buildDir = "${rootProject.buildDir}/${project.name}"
>   project.evaluationDependsOn(":app")
> }
> 
> tasks.register("clean", Delete) {
>   delete rootProject.buildDir
> }
> ```

it worked! thanks

**Comment by 4nkit-5hukla** [comment]
@f4bio after failing so many git hub actions your solution finally worked for me

**Comment by kshatriyaArjunDeveloper** [comment]
Worked thanks a ton

**Comment by Vishanti** [comment]
@f4bio worked for me, thanks

**Comment by wasim353** [comment]
worked for me a lot of thanks

**Comment by BensonStark** [comment]
it worked! thanks!!!

**Comment by Yongle-Fu** [comment]
A problem occurred evaluating root project 'android'.
> Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

**Comment by Tr736** [comment]
I also get this..

A problem occurred evaluating root project 'android'.

Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

any tips on how to fix?

**Comment by nillbiplob** [comment]
> I also get this..
> 
> A problem occurred evaluating root project 'android'.
> 
> Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
> 
> any tips on how to fix?


Here's the correct order:


`rootProject.buildDir = '../build'

subprojects {
    afterEvaluate { project ->

        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }

        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
            }
        }
    }

    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')

}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}`


project.evaluationDependsOn(':app') should be called as last line.

**Comment by JoelOvien** [comment]
> > I also get this..
> > A problem occurred evaluating root project 'android'.
> > Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
> > any tips on how to fix?
> 
> Here's the correct order:
> 
> `rootProject.buildDir = '../build'
> 
> subprojects { afterEvaluate { project ->
> 
> ```
>     if (project.plugins.hasPlugin("com.android.application") ||
>             project.plugins.hasPlugin("com.android.library")) {
>         project.android {
>             compileSdkVersion 34
>             buildToolsVersion "34.0.0"
>         }
>     }
> 
>     if (project.hasProperty('android')) {
>         project.android {
>             if (namespace == null) {
>                 namespace project.group
>             }
>         }
>     }
> }
> 
> project.buildDir = "${rootProject.buildDir}/${project.name}"
> project.evaluationDependsOn(':app')
> ```
> 
> }
> 
> tasks.register("clean", Delete) { delete rootProject.buildDir }`
> 
> project.evaluationDependsOn(':app') should be called as last line.

I did this but also got the error

```
* What went wrong:
A problem occurred evaluating root project 'android'.
> Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
```

**Comment by ihoon9203** [comment]
I thank you with all my sincierity!

**Comment by CrossEvol** [comment]
thank you, it works for me , as flutter3.24.1 with isar3.10+1

**Comment by Dixi-Sangani** [comment]
it's worked fine

**Comment by lahirunc** [comment]
I'm still having this error. I did follow the given solution but didn't work.

```FAILURE: Build failed with an exception.

* Where:
Build file '<PATH>/android/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'android'.
> Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.```


This is my `android\build.gradle`

```buildscript {
    ext.kotlin_version = '2.0.20'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    //  fix for verifyReleaseResources
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
        project.plugins.hasPlugin("com.android.library")) {
        project.android {
            compileSdkVersion 34
            buildToolsVersion "34.0.0"
        }
        }
        if (project.hasProperty("android")) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
            }
        }
    }
    // ===============================
    
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

**Comment by mihai-gabriel8** [comment]
> > > I also get this..
> > > A problem occurred evaluating root project 'android'.
> > > Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
> > > any tips on how to fix?
> > 
> > 
> > Here's the correct order:
> > `rootProject.buildDir = '../build'
> > subprojects { afterEvaluate { project ->
> > ```
> >     if (project.plugins.hasPlugin("com.android.application") ||
> >             project.plugins.hasPlugin("com.android.library")) {
> >         project.android {
> >             compileSdkVersion 34
> >             buildToolsVersion "34.0.0"
> >         }
> >     }
> > 
> >     if (project.hasProperty('android')) {
> >         project.android {
> >             if (namespace == null) {
> >                 namespace project.group
> >             }
> >         }
> >     }
> > }
> > 
> > project.buildDir = "${rootProject.buildDir}/${project.name}"
> > project.evaluationDependsOn(':app')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > tasks.register("clean", Delete) { delete rootProject.buildDir }`
> > project.evaluationDependsOn(':app') should be called as last line.
> 
> I did this but also got the error
> 
> ```
> * What went wrong:
> A problem occurred evaluating root project 'android'.
> > Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
> ```

@Tr736 here's a fix for this error

**Comment by PranayKoleyWeavers** [comment]
Thanks a lot man, It works for me when Implementing SendBird SDK

**Comment by Rajatg180** [comment]
works thanks

**Comment by rusenaliyilmaz** [comment]
> what solved this for me, adding some scripts to the subprojects section in `android/build.gradle`:
> 
> ```
> allprojects {
>   repositories {
>     google()
>     mavenCentral()
>   }
> }
> 
> rootProject.buildDir = "../build"
> subprojects {
>   //  fix for verifyReleaseResources
>   // ============
>   afterEvaluate { project ->
>     if (project.plugins.hasPlugin("com.android.application") ||
>       project.plugins.hasPlugin("com.android.library")) {
>       project.android {
>         compileSdkVersion 34
>         buildToolsVersion "34.0.0"
>       }
>     }
>     if (project.hasProperty("android")) {
>       project.android {
>         if (namespace == null) {
>           namespace project.group
>         }
>       }
>     }
>   }
>   // ============
>   project.buildDir = "${rootProject.buildDir}/${project.name}"
>   project.evaluationDependsOn(":app")
> }
> 
> tasks.register("clean", Delete) {
>   delete rootProject.buildDir
> }
> ```

It works, thanks a lot! But why does it work? What does it actually do? I know the minimum of the minimum of Gradle.

**Comment by ITApexGroup** [comment]
> A problem occurred evaluating root project 'android'.
> 
> > Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

Me too.

**Comment by mihai-gabriel8** [comment]
> > A problem occurred evaluating root project 'android'.
> > > Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
> 
> Me too.

@ITApexGroup 

have you tried this solution: https://github.com/isar/isar/issues/1654#issuecomment-2370930364

**Comment by Mainak009** [comment]
> what solved this for me, adding some scripts to the subprojects section in `android/build.gradle`:
> 
> ```
> allprojects {
>   repositories {
>     google()
>     mavenCentral()
>   }
> }
> 
> rootProject.buildDir = "../build"
> subprojects {
>   //  fix for verifyReleaseResources
>   // ============
>   afterEvaluate { project ->
>     if (project.plugins.hasPlugin("com.android.application") ||
>       project.plugins.hasPlugin("com.android.library")) {
>       project.android {
>         compileSdkVersion 34
>         buildToolsVersion "34.0.0"
>       }
>     }
>     if (project.hasProperty("android")) {
>       project.android {
>         if (namespace == null) {
>           namespace project.group
>         }
>       }
>     }
>   }
>   // ============
>   project.buildDir = "${rootProject.buildDir}/${project.name}"
>   project.evaluationDependsOn(":app")
> }
> 
> tasks.register("clean", Delete) {
>   delete rootProject.buildDir
> }
> ```

worked like a charm in one go😍🔥🔥

**Comment by Devansh176** [comment]
> > what solved this for me, adding some scripts to the subprojects section in `android/build.gradle`:
> > ```
> > allprojects {
> >   repositories {
> >     google()
> >     mavenCentral()
> >   }
> > }
> > 
> > rootProject.buildDir = "../build"
> > subprojects {
> >   //  fix for verifyReleaseResources
> >   // ============
> >   afterEvaluate { project ->
> >     if (project.plugins.hasPlugin("com.android.application") ||
> >       project.plugins.hasPlugin("com.android.library")) {
> >       project.android {
> >         compileSdkVersion 34
> >         buildToolsVersion "34.0.0"
> >       }
> >     }
> >     if (project.hasProperty("android")) {
> >       project.android {
> >         if (namespace == null) {
> >           namespace project.group
> >         }
> >       }
> >     }
> >   }
> >   // ============
> >   project.buildDir = "${rootProject.buildDir}/${project.name}"
> >   project.evaluationDependsOn(":app")
> > }
> > 
> > tasks.register("clean", Delete) {
> >   delete rootProject.buildDir
> > }
> > ```
> 
> it worked! thanks

**Comment by coderbaba0** [comment]
It works, thanks a lot! thanks from my soul

**Comment by CezarTech** [comment]
it works,  thanks a lot guyes

**Comment by Rajveer7688** [comment]
Thank You so much, It is worked! 100%

**Comment by UppunuthulaPrashanthGoud** [comment]
worked for me.    great  solution

**Comment by amankevatIzonnet** [comment]
> > I also get this..
> > A problem occurred evaluating root project 'android'.
> > Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
> > any tips on how to fix?
> 
> Here's the correct order:
> 
> `rootProject.buildDir = '../build'
> 
> subprojects { afterEvaluate { project ->
> 
> ```
>     if (project.plugins.hasPlugin("com.android.application") ||
>             project.plugins.hasPlugin("com.android.library")) {
>         project.android {
>             compileSdkVersion 34
>             buildToolsVersion "34.0.0"
>         }
>     }
> 
>     if (project.hasProperty('android')) {
>         project.android {
>             if (namespace == null) {
>                 namespace project.group
>             }
>         }
>     }
> }
> 
> project.buildDir = "${rootProject.buildDir}/${project.name}"
> project.evaluationDependsOn(':app')
> ```
> 
> }
> 
> tasks.register("clean", Delete) { delete rootProject.buildDir }`
> 
> project.evaluationDependsOn(':app') should be called as last line.

thank you buddy its working

**Comment by luisomdev** [comment]
Thanks :)

**Comment by joaolima7** [comment]
Deu muito certo, salvou, muito obrigadooo!!!

**Comment by aloketewary** [comment]
Id you are using kotlin then this code applied to you `android/build.gradle.kts`

```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

plugins {
    // No plugins defined here in the original, but you might have some in your actual file
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Add your buildscript dependencies here, e.g.,
        // classpath("com.android.tools.build:gradle:...")
        // classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:...")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

val newBuildDir: Directory = rootProject.layout.buildDirectory.dir("../../build").get()
rootProject.layout.buildDirectory.value(newBuildDir)
subprojects {
    // fix for verifyReleaseResources
    // ============
    afterEvaluate {
        val project = this // 'this' refers to the Project

        if (project.plugins.hasPlugin("com.android.application") || project.plugins.hasPlugin("com.android.library")) {
            val androidExtension =
                project.extensions.getByName("android") as? com.android.build.gradle.LibraryExtension
                    ?: project.extensions.getByName("android") as? com.android.build.gradle.AppExtension

            androidExtension?.apply {
                compileSdkVersion(34)
                buildToolsVersion = "34.0.0"
            }
        }

        if (project.extensions.findByName("android") != null) {
            val androidExtension =
                project.extensions.getByName("android") as? com.android.build.gradle.LibraryExtension
                    ?: project.extensions.getByName("android") as? com.android.build.gradle.AppExtension

            androidExtension?.apply {
                if (namespace == null) {
                    namespace = project.group.toString()
                }
            }
        }
    }
    // ============
    buildDir = file("${rootProject.buildDir}/${project.name}")
    evaluationDependsOn(":app")
}

tasks.register<Delete>("clean") {
    delete(rootProject.buildDir)
}
```

**Comment by ahsan-stepsharp** [comment]
Worked. Thanks alot

**Comment by sagor995** [comment]
> If you are using kotlin then this code applied to you `android/build.gradle.kts`
> 
> ```
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>     }
> }
> 
> plugins {
>     // No plugins defined here in the original, but you might have some in your actual file
> }
> 
> buildscript {
>     repositories {
>         google()
>         mavenCentral()
>     }
>     dependencies {
>         // Add your buildscript dependencies here, e.g.,
>         // classpath("com.android.tools.build:gradle:...")
>         // classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:...")
>     }
> }
> 
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>     }
> }
> 
> val newBuildDir: Directory = rootProject.layout.buildDirectory.dir("../../build").get()
> rootProject.layout.buildDirectory.value(newBuildDir)
> subprojects {
>     // fix for verifyReleaseResources
>     // ============
>     afterEvaluate {
>         val project = this // 'this' refers to the Project
> 
>         if (project.plugins.hasPlugin("com.android.application") || project.plugins.hasPlugin("com.android.library")) {
>             val androidExtension =
>                 project.extensions.getByName("android") as? com.android.build.gradle.LibraryExtension
>                     ?: project.extensions.getByName("android") as? com.android.build.gradle.AppExtension
> 
>             androidExtension?.apply {
>                 compileSdkVersion(34)
>                 buildToolsVersion = "34.0.0"
>             }
>         }
> 
>         if (project.extensions.findByName("android") != null) {
>             val androidExtension =
>                 project.extensions.getByName("android") as? com.android.build.gradle.LibraryExtension
>                     ?: project.extensions.getByName("android") as? com.android.build.gradle.AppExtension
> 
>             androidExtension?.apply {
>                 if (namespace == null) {
>                     namespace = project.group.toString()
>                 }
>             }
>         }
>     }
>     // ============
>     buildDir = file("${rootProject.buildDir}/${project.name}")
>     evaluationDependsOn(":app")
> }
> 
> tasks.register<Delete>("clean") {
>     delete(rootProject.buildDir)
> }
> ```

Thanks a lot.

**Comment by SathishSelvakumar05** [comment]
@f4bio excellent
