### ISSUE TITLE
[FAILED BUILD] build app with latest isar failed

### ISSUE THREAD

**Issue by azkadev** [isar/isar#1663]
### Steps to Reproduce

I tried to build a flutter application with isar database, but failed

 - Platform: ANDROID.
 - Flutter version: 3.24.3
 - Isar version: 4.0.0-dev.14

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example
 
  COMMAND BUILD
  
 `flutter build apk --release`
 
 ERROR 
 
 
```bash
Font asset "hicons.ttf" was tree-shaken, reducing it from 322856 to 9048 bytes (97.2% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "Octicons.ttf" was tree-shaken, reducing it from 27440 to 932 bytes (96.6% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "Iconsax.ttf" was tree-shaken, reducing it from 992800 to 15876 bytes (98.4% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 6312 bytes (99.6% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':isar_flutter_libs:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: /home/azkadev/Documents/azkadev/app/azkadev_app/example/build/isar_flutter_libs/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 53s
Running Gradle task 'assembleRelease'...                          114.5s
```

**Comment by azkadev** [comment]
I have tried this https://github.com/isar/isar/pull/1659

and it works

**Comment by santhosh-D-subramani** [comment]
@azkadev 
what version used for generator??
im getting error
Because isar_generator 3.1.0+1 depends on isar 3.1.0+1 and no versions of isar_generator match >3.1.0+1 <4.0.0, isar_generator ^3.1.0+1 requires isar 3.1.0+1.

**Comment by azkadev** [comment]
> @azkadev what version used for generator?? im getting error Because isar_generator 3.1.0+1 depends on isar 3.1.0+1 and no versions of isar_generator match >3.1.0+1 <4.0.0, isar_generator ^3.1.0+1 requires isar 3.1.0+1.

if you are using the latest version, you don't need to isar the generator, just build_runner
