### ISSUE TITLE
random crash when using this query "return isar.logs.where().anyDate().sortByDateDesc().findAll();"

### ISSUE THREAD

**Issue by ayman2ppp2** [isar/isar#1666]
### Steps to Reproduce

i am not 100% sure but you can try to make a collection and query it with this line "return isar.logs.where().anyDate().sortByDateDesc().findAll();"  , it will have a date field mine has an imbedded list of objects also.

### Code sample

```dart
Future<List<Log>> getAllLogs() {
 
    try {
      return isar.logs.where().anyDate().sortByDateDesc().findAll();
    } on Exception catch (e, s) {
      // TODO0
      print(e);
      print(s);
      return Future.value([]);
    }
  }
```

when i export my collection data to json and reimport it back the issue will go away , and if i remove the .anyDate() the issue also go away .

### Details

 - Platform: android 9 , android 11 , windows native .
 - Flutter version:Flutter 3.16.8 • channel stable
 - Isar version: 3.1.0+1

---

 - [yes ] I searched for similar issues already
 - [ yes] I filled the details section with the exact device model and version
 - [x ] I am able to provide a reproducible example

**Comment by ZhuJHua** [comment]
You don't need to use both `anyDate&sortByDate`, because the date is a index,  when you call `anyDate` , the result are automatically sorted.

**Comment by ayman2ppp2** [comment]
ok thanks
