### ISSUE TITLE
Upgraded the analyzer version to 3.0.0 for Freezed 1.1.1

### ISSUE THREAD

**Issue by rifaldhiaw** [isar/isar#172]
Hi,
thanks for the awesome work! :)

Could you please upgrade to analyzer version to 3.0.0
So it compatible with freezed 1.1.1

They just upgrade it like a week ago https://github.com/rrousselGit/freezed/commit/258ee1c9e7e089c7a74e270b838f8acd84ccc95e

Thanks

**Comment by leisim** [comment]
Fixed in `2.0.0-dev.0`
