### ISSUE TITLE
Automatically connect Isar Inspector to active debugging session (please upvote)

### ISSUE THREAD

**Issue by leisim** [isar/isar#177]
Need your help to upvote a [devtools issue](https://github.com/flutter/devtools/issues/1632) to allow the Isar Inspector to be more user-friendly and not require entering the URL every time 🙌

Edit: Ideally there even was a way to load / update the inspector via the devtools but that's a stretch goal.

**Comment by MaximilianFlechtner** [comment]
@leisim  It could be done in such a way that the URL is written into a file, which the Isar inspector then reads. 

`
flutter run --vmservice-out-file=isar_connect.txt 
`

**Comment by aloisdeniel** [comment]
Maybe the best approach would be to integrate the inspector to the Flutter devtools ?

Remi did that with provider and [wrote an article on the subject](https://invertase.io/blog/how-to-flutter-devtool-plugin).

The main downside is that it must be part of the official devtools ...

**Comment by leisim** [comment]
@aloisdeniel I agree that would be super cool (and easy because the inspector already relies on the vm service protocol).

The question is what qualifies a package to be part of the official devtools. Are there some rules / requirements or can anyone submit an extension?

**Comment by leisim** [comment]
Obsolete with the new inspector.
