### ISSUE TITLE
Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, isar_connect_dart_api): symbol not found

### ISSUE THREAD

**Issue by htsunshine** [isar/isar#181]
022-01-12 15:27:30.198144+0800 Runner[16682:8571892] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, isar_connect_dart_api): symbol not found)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31)
#1      IsarCoreBindings._isar_connect_dart_api_ptr (package:isar/src/native/bindings.dart:332)
#2      IsarCoreBindings._isar_connect_dart_api (package:isar/src/native/bindings.dart)
#3      IsarCoreBindings.isar_connect_dart_api (package:isar/src/native/bindings.dart)
#4      openIsarNative (package:isar/src/native/open.dart:26)
<asynchronous suspension>

32/5000 
Ios Debug mode can be initialized, but release mode fails to be initialized.

**Version**
 - Platform: iOS （iphone8p）
 - Flutter version: 2.14.3
 - Isar version: 1.0.5
 - Isar Generator version: 1.0.5

**Comment by rizzi37** [comment]
#169

**Comment by leisim** [comment]
@htsunshine did you find a solution?

**Comment by htsunshine** [comment]
No, I saw you pointed me to 169 issues.Ios Debug mode can be initialized, but release mode fails to be initialized.

**Comment by leisim** [comment]
Yes, I already fixed it on main. Will release a new version in the coming days 👍

**Comment by htsunshine** [comment]
Thank you

**Comment by htsunshine** [comment]
I want to know what you changed. I want to fix it first

**Comment by calipee** [comment]
I've got the same error with version 3.0.5 building for iOS. It works in debug mode but not in release.

```
IsarError: Could not initialize IsarCore library for processor architecture "ios_arm64". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
Invalid argument (s): Failed to lookup symbol 'isar_version': dism(RTLD_DEFAULT, isar_version): symbol not found
```
