### ISSUE TITLE
Watching aggregations

### ISSUE THREAD

**Issue by UCetinkaya94** [isar/isar#182]
**Is your feature request related to a problem? Please describe.**
Aggregations return a Future. It would be nice if we could listen to them. Let's say we have a sessions collections and want to show the sum of all sessions. This can be done with the sum operation. But we won't get notified when a sessions is added, deleted or updated.

**Describe the solution you'd like**
Expose a stream for aggregations.  

**Describe alternatives you've considered**
Watching the collection and manually calling the aggregation operation again:

```dart
final sessionsNotifier = StreamProvider((ref) => isar.sessions.watchLazy());

final totalTimePod = FutureProvider(
  (ref) {
    ref.watch(sessionsNotifier);
    
    final selectedProject = ref.watch(selectedProjectPod);

    return isar.sessions //
        .where()
        .projectIDEqualTo(selectedProject)
        .timeWorkedMillsProperty()
        .sum();
  },
);
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Isar version: 1.0.5

**Comment by leisim** [comment]
Thanks for this suggestion. How would you like the API to look like?

Maybe we can solve it with static extension methods?

**Comment by UCetinkaya94** [comment]
> Thanks for this suggestion. How would you like the API to look like?

Maybe something like `watchCount`, `watchSum`, `watchAverage`, `watchMin`, `watchMax`

> Maybe we can solve it with static extension methods?

I came up with this, but since we can watch collections only lazily, we won't get the data until something changes.

```dart
extension on IsarCollection<Session> {
  Stream<int> watchCount() {
    return watchLazy().asyncMap((event) => where().count());
  }

  Stream<int> watchSum() {
    return watchLazy().asyncMap((event) => where().timeWorkedMillsProperty().sum());
  }

  Stream<double> watchAverage() {
    return watchLazy().asyncMap((event) => where().timeWorkedMillsProperty().average());
  }
}
```

**Comment by leisim** [comment]
Watching a query and then performing the aggregation will give you the same effect.

I'm going to close this because providing this feature would not lead to any performance improvements.
