### ISSUE TITLE
where id in [1,2,3]

### ISSUE THREAD

**Issue by DJafari** [isar/isar#189]
is possible make query something like this  ?

```
SELECT * From `users` WHERE `id` in (4, 7, 12, 16)
```

**Comment by DJafari** [comment]
i found a way, but is it optimize for large ids list ?

```dart
final ids = [4 , 7, 12, 16];

isar.users
  .where()
  .filter()
  .repeat(
    [38, 40, 42],
    (q, int id) => q.sizeEqualTo(id).or()
).findAll();
```

**Comment by leisim** [comment]
Hey @DJafari

You should use something like this:

```dart
isar.users
  .where()
  .repeat(
    ids,
    (q, id) => q.idEqualTo(id).or()
  ).findAll();
```

Or if you have a range of ids:
```dart
isar.users
  .where()
  .idBetween(4, 16)
  .findAll();
```

These queries directly use the primary index (id) and are very fast.

**Comment by canastro** [comment]
@leisim whats the recommended approach now that .repeat will be removed?

**Comment by leisim** [comment]
There are replacements for repeat: `oneOf()`, `anyOf()`, and `allOf()`
