### ISSUE TITLE
IsarLinks documentation seems to be outdated

### ISSUE THREAD

**Issue by UCetinkaya94** [isar/isar#190]
Both the `Queries` and `Links` sections in the documentation use the `@IsarCollection` annotation, which seems to be replaced by `@Collection()`. 

And the example query also doesn't work anymore. The generated code doesn't have a property for the linked collection:

```dart
import 'package:isar/isar.dart';

part 'isar_links_example.g.dart';

@Collection()
class Teacher {
  int? id;

  late String subject;
}

@Collection()
class Student {
  int? id;

  late String name;

  final teachers = IsarLinks<Teacher>();
}

Future<void> query(Isar isar) async {
  final result = await isar.students
      .filter()
      .teachers( // => The method 'teachers' isn't defined for the type 'QueryBuilder'
        (q) => q.subjectEqualTo('Math').or().subjectEqualTo('English'),
      )
      .findAll();
}
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.8.1
 - Isar version: ^2.0.0-dev.1
 - Isar Generator version: ^2.0.0-dev.1

**Comment by snehmehta** [comment]
`  .teachers( // => The method 'teachers' isn't defined for the type 'QueryBuilder'
        (q) => q.subjectEqualTo('Math').or().subjectEqualTo('English'),
      )`
So, is this a generator issue or a documentation issue?

Also if it's a documentation issue, then what's the updated ways of querying Isarlink ?

**Comment by joaopinacio** [comment]
Same here, i was trying to use Isar on my Flutter Project and everything that is in documentation seems outdated, especifically the query filters and where clauses.

**Comment by Hcs66** [comment]
> ` .teachers( // => The method 'teachers' isn't defined for the type 'QueryBuilder' (q) => q.subjectEqualTo('Math').or().subjectEqualTo('English'), )` So, is this a generator issue or a documentation issue?
> 
> Also if it's a documentation issue, then what's the updated ways of querying Isarlink ?

The `generateQueryLinks` method has been commented in `isar_generator/collection_generator.dart` line 38, so that there has no link extensions generated.

Is the link function not ready for releasing? @leisim

**Comment by leisim** [comment]
I didn't have all the unit tests ready to enable it. Hopefully the next release will fix that :)

**Comment by leisim** [comment]
This is already fixed
