### ISSUE TITLE
app crash, once writeTxn data size maybe than 10m ?

### ISSUE THREAD

**Issue by rizzi37** [isar/isar#193]
I have a big JSON object (30m) to save in DB, once write use writeTxn(), the app crashed, when resized to 10m, the crash is still in.

**Comment by leisim** [comment]
Sorry I'm not 100% sure what you mean? Is the problem that inserting a json object >10mb crashes and <10mb works?

**Comment by rizzi37** [comment]
yes.

**Comment by leisim** [comment]
@rizzi37 I can't reproduce the issue with isar `2.0.0`. Do you still see it? What is the exception? Do you have some sample code?

I tried importing 100mb of json and it worked fine 🤔

**Comment by rizzi37** [comment]
@leisim thx. have you tests same time with multiple links data? like this:

```
await db.writeTxn((isar) async {
    for (var data in raws) {
      final model = Model.fromJson(data);

      // put links
      await isar.linkAs.putAll(model.As ?? []);
      model.linkAs.assignAll(model.linkAs ?? []);

      await isar.linkBs.putAll(model.Bs ?? []);
      model.linkBs.assignAll(model.linkBs ?? []);

      // save models
      await isar.models.put(model);
      await model.linkAs.save();
      await model.linkBs.save();
      // break;

    }
  });


```

**Comment by rizzi37** [comment]
#204
