### ISSUE TITLE
APK size optimization

### ISSUE THREAD

**Issue by javadi69** [isar/isar#194]
**Is your feature request related to a problem? Please describe.**
Kind of, I built APK for arm64 devices but the APK also includes both x86_64 and armeabi-v7a libraries.
`flutter build apk --target-platform android-arm64 --obfuscate --split-debug-info=./symbols`

**Describe the solution you'd like**
Exclude unused libisar.so for other architectures to reduce the APK size.
This will reduce the size of targeted APK for about 1.2 MB
Thank you,

**Version**
 - Platform: Android
 - Flutter version: 2.8.1
 - Isar version: 2.0.0-dev.1

**Comment by leisim** [comment]
Please try the `--split-per-abi` flag https://docs.flutter.dev/deployment/android#build-an-apk

**Comment by leisim** [comment]
This sounds more like a Flutter problem. Are the other native dependencies (like the flutter engine itself) excluded?

**Comment by javadi69** [comment]
Yes, both libflutter.so and libapp.so are excluded.
