### ISSUE TITLE
Isar inspector unable to connect

### ISSUE THREAD

**Issue by ProgUser145** [isar/isar#195]
**Steps to Reproduce**
Hi, I was trying to launch the Isar inspector with the example _quotes_ app and it didn't open at first. After I ran it with the source code it threw the error:

```
flutter: ERROR: Unable to connect to VMService
flutter: SocketException: OS Error: Connection refused, errno = 61
flutter: #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:681:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1808:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2027:22)
#4      Socket.startConnect (dart:io/socket.dart:784:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2439:18)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2808:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2813:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2697:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2569:7)
#10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42)
#11     WebSocket.connect (dart:_http/websocket.dart:360:22)
#12     vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
#13     Service.connect (package:isar_inspector/service.dart:18:29)
#14     _ConnectPageState._connect (package:isar_inspector/connect.dart:24:37)
#15     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#16     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#17     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#18     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#19     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#20     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#28     _rootRunUnary (dart:async/zone.dart:1444:13)
#29     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#31     _invoke1 (dart:ui/hooks.dart:169:10)
#32     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)```

````
**Version**

 - Platform:  Mac
 - Flutter version: 2.8.1
 - Isar version: latest
 - Isar Generator version: latest

**Comment by leisim** [comment]
Are you sure that the connection URL is correct? (All the characters are needed)

**Comment by ProgUser145** [comment]
I did try multiple times and different versions or phones. In IOS emulator for example it throws this error

`flutter: ERROR: Unable to connect to VMService
flutter: WebSocketException: Connection to 'http://127.0.0.1:57916/My-AuthCode-here/#' was not upgraded to websocket
flutter: #0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:360:22)
#2      vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
#3      Service.connect (package:isar_inspector/service.dart:18:29)
#4      _ConnectPageState._connect (package:isar_inspector/connect.dart:25:37)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#18     _rootRunUnary (dart:async/zone.dart:1444:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#21     _invoke1 (dart:ui/hooks.dart:169:10)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
`

Not entirely sure if this is an issue with Isar inspector. Seems more an issue with vm_service
