### ISSUE TITLE
Non-lazy(Automatic) IsarLink/IsarLinks save() and load()

### ISSUE THREAD

**Issue by Peng-Qian** [isar/isar#196]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the collection have many link/links since the all of them need manually call `save()` and `load()`, I understand this might help to improve performance if user only create/update of few of these fields, but it almost the top pain to manage and maintain these lazy link/links.

**Describe the solution you'd like**
Is it possible to give an option that let these link/links are automatic save and load, like object box do.

**Version**
 - Platform: iOS, Android,
 - Flutter version: [2.9.0-0.1.pre]
 - Isar version: [2.0.0 dev.1]

**Comment by leisim** [comment]
Thanks for this request. It's not planned in the immediate future because of performance considerations but I'll keep it in mind :+1:

**Comment by duduf15** [comment]
Same problem here, I discovered Isar for a new project. I wonder if Isar is optimized for models with many relationships? Thank you @leisim

**Comment by leisim** [comment]
I'm going to close this for now as it is not likely to be implemented.

**Comment by moritz157** [comment]
I would also really appreciate this feature. Perhaps it could be optional to automatically save them. That way you could still decide to not use this feature in case you want to make certain performance optimizations.
