### ISSUE TITLE
Support for Encryption

### ISSUE THREAD

**Issue by asaph26** [isar/isar#199]
**Is your feature request related to a problem? Please describe.**
The support for encryption when writing/reading data to/from disk.

**Describe the solution you'd like**
This can be similar to the current crypto implementation in HiveDB. An enhancement to this would be to be able to handle larger workloads. Hive loads the entire data which at times leads to a memory overflow. 

**Describe alternatives you've considered**
Not Really. The HiveDB solution was fairly resilient under lower workloads.

**Version**
 - Platform: All
 - Flutter version: [e.g. 1.5.4]
 - Isar version: 1.0.5

**Comment by rizzi37** [comment]
https://github.com/isar/isar/discussions/176 here some discussions about encryption

**Comment by asaph26** [comment]
Thanks @rizzi37 @leisim . Closing this.
