### ISSUE TITLE
How to write a converter for this class

### ISSUE THREAD

**Issue by leisim** [isar/isar#209]
### Discussed in https://github.com/isar/isar/discussions/208

<div type='discussions-op-text'>

<sup>Originally posted by **Anan-Saadi** January 26, 2022</sup>
I read the docs about converters but I am confused on how to write a converter for a class with with multiple parameters
```

import 'dart:convert';

import 'package:isar/isar.dart';
part 'Room.g.dart';

@Collection()
class Room {
  int? id;

  late String RoomId;
  late List<String>? members;
  late int? unread;
  late bool? pinned;
  @MessageConverter()
  late List<Message> messages;

}


class Message{
   String? type;
   String? sender;
   String? time;
   String? message;
  Message({this.type, this.sender, this.message, this.time});

  Message.fromJson(Map<String, dynamic> json)
      : type =  json['type'],
        sender = json['sender'],
        time = json['time'],
        message = json['message'];



  Map<String, dynamic> toJson() =>
      {
        'type': type,
        'sender': sender,
        'time': time,
        'message': message
      };


class MessageConverter extends TypeConverter<Message, String>{
  const MessageConverter();

  @override
  Message fromIsar(String object) {
    return Message.fromJson(jsonDecode(object));
  }

  @override
  String toIsar(Message object) {
    return jsonEncode(object.toJson());
  }


}
```

You can see above that I have an isar model that stores some data plus a list of messages, I tried converting `Message` class to json and then passing it to isar but I am not sure if this is how it is supposed to be done since when I try to get data out of `Message` I get an error `Unhandled Exception: LateInitializationError: Field 'messages' has not been initialized.`, but it works for other `Room` parameters. 

I tested it like this :

```

import 'package:isar/isar.dart';
import 'package:neox/Helper.dart' as global;
import 'package:flutter/material.dart';
import 'package:neox/Isar/Room.dart';

class test extends StatefulWidget {
  const test({Key? key}) : super(key: key);

  @override
  _testState createState() => _testState();
}

class _testState extends State<test> {
  @override
  Widget build(BuildContext context) {
    final database  = global.isar;
    
    Message message = Message(time: "103", message: "hello", sender: "Me", type: "m");
    
    var newRoom = Room()
      ..members = ["me", "someone"]
      ..messages = [message]
      ..unread = 1
      ..RoomId = "093485"
      ..pinned = false;
    
    IsarCollection<Room> Rooms;


    Future<void> getData()async{
      Rooms = await database.rooms;
    };
    
    Future<void> writeData() async {
      await database.writeTxn((isar) => isar.rooms.put(newRoom));
    };

    return Container(
      child:
      Column(
        children: [
          ElevatedButton(onPressed: ()=> writeData(), child: Text("store")), // for testing purposes I run each command using a button and wait a moment for it to execute
          ElevatedButton(onPressed: ()=> getData(), child: Text("get")),

          ElevatedButton(onPressed: ()=> Rooms.filter().roomIdGreaterThan("").findAll().then((value){ // also I don't know if this is the best method to get all rooms
            for(int i=0; i<(value.length); i++){
              print(value[i].messages.first.message);
            };
          }), child: Text("print messages")),
        ],
      ),);
  }
}
```
some help on how exactly to write the converter would be much appreciated  </div>

**Comment by Anan-Saadi** [comment]
So I have been missing around with this issue today and I wasn't able to solve it but I found out that `Unhandled Exception: LateInitializationError: Field 'messages' has not been initialized.` just means null, but because the variable is `late` it was throwing this error, also I noticed that in `Isar Inspector` `messages` doesn't show up, there is no column for it, but I don't know if this is by-design or something is preventing the data from being written to the database

**Comment by zawadZwd** [comment]
There shoudn't be:

```dart
class MessageConverter extends TypeConverter<List<Message>, String> {
...
}
```
?

**Comment by Anan-Saadi** [comment]
after following #236 I was able to make the convertor work for storing a single `Message` not `List<Message>`

adding `print` to `fromIsar` and `toIsar` to check the `json` response shows that when storing a `Message` there is indeed encoding and decoding happening, but when trying to store a list nothing gets invoked, which makes me believe that there is nothing getting passed to the `convertor`, should the `convertor` instead take a `List` as suggested by @zawadZwd  above ?

**Comment by leisim** [comment]
Isar ignores fields with unknown types and it can't use a `Message` `TypeConverter` to handle a `List<Message>` yet.

**Comment by Anan-Saadi** [comment]
So how is the convertor supposed to work in this case?

Should it convert a `List<Message>` to a single `String` or to `List<String>` ?

**Comment by leisim** [comment]
That is up to you. Both works

**Comment by leisim** [comment]
@Anan-Saadi do you think we can close this issue?

**Comment by Anan-Saadi** [comment]
I still haven't created a working convertor yet, which doesn't answer the original question "How to write a convertor for this class", after I do it I'll post the convertor here.

I'll also add to the docs if you are interested since right now it only includes an example for enum

**Comment by Anan-Saadi** [comment]
I was able to finally write a working convertor, and it turned out to be simpler than I expected (I guess @leisim did all the heavy lifting), anyway, the convertor turned out to be just a `json` encoder that turns the list into a single `String`



```dart
//Message class is unchanged
class MessageListConverter extends TypeConverter<List<Message?>?, String?>{
  const MessageListConverter();
  @override
  List<Message?>? fromIsar(String? object) {
    List<Message?>? list = decodeList(object);
    return list;
  }

  @override
  String? toIsar(List<Message?>? object) {
    String? string  = encodeList(object);
    return string;

  }

}
```
encode & decode list:
```dart
String? encodeList (List<Message?>? list){
  String? encodedList =  jsonEncode(list!.map((elem)=> elem!.toJson()).toList());
  return encodedList;
}

List<Message?>? decodeList(String? encodedList ){
  List<dynamic> decoded;
  List<Message?>? decodedList;
  decoded = jsonDecode(encodedList!);
  decodedList =  decoded.map((e) => Message.fromJson(e)).toList();
  return decodedList;
}
```

Also @leisim, would you like me to update the docs? Since it is quite unclear what you have to do in such case by just reading the docs

**Comment by leisim** [comment]
Type converters have been removed from the library
