### ISSUE TITLE
opening second Isar instance crashes the app

### ISSUE THREAD

**Issue by msxenon** [isar/isar#215]
**Steps to Reproduce**
Open Isar Instance
Close it and delete its folder
Open new instance in a new folder
 
Logs 
I/flutter: Using temporary DB directory Directory: '/data/user/0/io.objectbox.dartbench/app_flutter/UUNKGV' for DbEngine.IsarSync
I/flutter: _createExecutor for DbEngine.IsarSync
W/1.ui: type=1400 audit(0.0:1833): avc: denied { getattr } for path="/mnt/vendor" dev="mmcblk0p1" ino=2 scontext=u:r:untrusted_app:s0:c77,c257,c512,c768 tcontext=u:object_r:prod_file:s0 tclass=dir permissive=0
I/flutter: deleting temporary DB directory Directory: '/data/user/0/io.objectbox.dartbench/app_flutter/UUNKGV' for DbEngine.IsarSync
V/AutofillManager: requestHideFillUi(null): anchor = null
**D/: Gralloc Register  w:1200, h:1848, f:0x1101, usage:0xb00, ui64Stamp:89182, sSize:8888320, line = 2270
I/flutter: Using temporary DB directory Directory: '/data/user/0/io.objectbox.dartbench/app_flutter/OZGHLU' for DbEngine.IsarSync
I/flutter: _createExecutor for DbEngine.IsarSync
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2e646c4f2e658a in tid 10814 (1.ui), pid 10657 (ctbox.dartbench)
I/DEBUG: Crash thread undumpable**
**Version**
 - Platform: Android
 - Flutter version: [2.8.1]
 - Isar version: [2.1.0]
 - Isar Generator version: [2.1.0]

**Comment by leisim** [comment]
Thanks for the report! Do you have a few lines of sample code?

**Comment by msxenon** [comment]
Sure
1. Opening DB 
https://github.com/msxenon/flutter-db-benchmarks/blob/to_packages/lib/main.dart#L143
https://github.com/msxenon/flutter-db-benchmarks/blob/to_packages/databases/isardb/lib/executor_plain.dart#L23

PS I have commented closing Isar to prevent this error for now

**Comment by leisim** [comment]
Fixed in `2.1.4` :+1:
