### ISSUE TITLE
The generated auto incremented id is "restarted" when the app is restarted

### ISSUE THREAD

**Issue by robban112** [isar/isar#216]
Hi! 
I've had problems with overwrites in my app for a certain collection, and I've come across an issue.

**Steps to Reproduce**

Using an auto incremented id with a model where the id is optional. Isar handles the auto increment correctly while running the app in one session, starting at int.MIN (-9223372036854775807) and incrementally increases towards int.MAX.

When restarting the app (closing & opening), this auto increment is reset (starting at int.MIN again), and does not take into account the previous id's, leading to overwrites in the collection.

Is this intentional?

**Code sample**
I've followed the documentation writing a data model with an optional id, along with a collection for these.
I'm using the standard way of appending to this collection, namely:

collection?.put(model)

**Version**
 - Platform: Mac
 - Flutter version: 2.8.1
 - Isar version: 2.1.0
 - Isar Generator version: 2.1.0

**Comment by leisim** [comment]
Thanks for reporting! That is not intended and I will push a new version with a fix later today :+1:

**Comment by robban112** [comment]
Thanks! Awesome job by the way, love the package 👍

**Comment by leisim** [comment]
Fixed in `2.1.4` :+1:
