### ISSUE TITLE
Not storing UTC property of DateTime

### ISSUE THREAD

**Issue by FineFindus** [isar/isar#218]
When a datetime object is stored, the utc property gets lost. 
**Steps to Reproduce**
When utc date is stored and queried later, the date is no longer a utc date, as can be seen in the example below.

**Code sample**
```dart
final dir = await getApplicationSupportDirectory(); // path_provider package
  final isar = await Isar.open(
    schemas: [TimeSchema],
    directory: dir.path,
  );

  final date = DateTime.utc(2020);
  //this is just a simple collection with a single datetime property
  final time = Time(date: date);

  await isar.writeTxn((isar) async {
    isar.times.put(time);
  });

  print(isar.times
      .where()
      .findAllSync()
      .first
      .date
      .isUtc); //this always prints false, although a utc date was stored
```

**Version**
 - Platform: Linux
 - Flutter version: 2.8.1/2.10.0
 - Isar version: 2.1.0
 - Isar Generator version: 2.1.0

**Comment by leisim** [comment]
Thanks for reporting this but it's working as intended. Isar always stores dates in UTC and returns them in local timezone. You can create an additional `isUTC` field if you want to store this information.

I'll update the docs :)

**Comment by leisim** [comment]
Added explanation here: https://isar.dev/schema.html#annotating-classes

**Comment by brinux** [comment]
Is there a way to avoid the automatic conversion to local time on read?
I actually appreciate the conversion to UTC on write, which I'd anyway do in the code, but in general performing automatic conversions can in my opinion easily lead to errors.
