### ISSUE TITLE
Better support for DateTime

### ISSUE THREAD

**Issue by FineFindus** [isar/isar#222]
**Is your feature request related to a problem? Please describe.**
Currently it is very verbose to query for a specific datetime and the method names are kind of unusual.
For example if you want to query for a datetime after a certain date,
a greaterThan Method is used, as can be seen in this example.

```dart
filter().dateGreaterThan(DateTime.now()).findAll();
```

**Describe the solution you'd like**
I think it would be better to have similar method names to dart´s datetime class.
For example, the above code would change to:

```dart
filter().dateAfter(DateTime.now()).findAll();
```

It could have the advantage to be more aware of what type of data is queried, as well as being easier to understand for beginners.

It would also be great if Isar could support more query conditions for datetimes, for example it is currently not easy to query for just a date.
Instead of using something like

```dart
filter().dateOnDate(DateTime(2020, 7, 9)).findAllSync();
```

or

```dart
filter().dateDay(DateTime(2020, 7, 9)).findAllSync();
```

this much more verbose looking query needs to be used.

```dart
filter().dateBetween(DateTime(2020, 7, 9), DateTime(2020, 7, 9, 23, 59)).findAllSync();
```

This also applies to not just days, but also all other time units, like months, hours, minutes, etc....

**Describe alternatives you've considered**
While strictly speaking all needed query conditions for datetime exist,
they seem to be more verbose and deviating for the dart method names, which can be confusing, then they need to.

**Version**

- Platform: iOS, Android, Mac, Windows, Linux, Web
- Flutter version: 2.10.0
- Isar version: 2.1.0

**Comment by leisim** [comment]
Thanks for this request! I completely agree with `.dateBefore()` and `.dateAfter()`. I'll add those with the next version of Isar.

Not so sure about the other proposed methods. Somehow they don't feel in line with the rest of the query API 🤔 I'll need to think about it...

**Comment by leisim** [comment]
I thought about this and I think it's better to keep the API simple and consistent. The requested feature can be achieved easily with custom extension methods so I'm going to close this for now :)
