### ISSUE TITLE
Isar Inspector on Windows

### ISSUE THREAD

**Issue by richard457** [isar/isar#237]
How to install  Isar Inspector  on windows

**Comment by leisim** [comment]
It's a Flutter app, you can run it from source. Unfortunately I didn't have time to automate and test the build in the CI.

A PR would be greatly appreciated if you'r interested 🙂

**Comment by richard457** [comment]
sure, will look at it in my free time.

**Comment by CodeDoctorDE** [comment]
Duplicate of #90 ?

**Comment by leisim** [comment]
@CodeDoctorDE Oh yes, thanks!
