### ISSUE TITLE
Allow query operations for IsarLinks

### ISSUE THREAD

**Issue by richard457** [isar/isar#238]
I think it would be better to have something like  teacher.students.length  and other method as long as the relation exist.

**Comment by richard457** [comment]
```

@Collection()
class Post {
  late int id = Isar.autoIncrement;
  late String title;
  final users = IsarLink<User>();
}

```
```
@Collection()
class User {
  late int id = Isar.autoIncrement;
  late String name;
}
```
```
Post ipost = isar.posts
        .where()
        .filter()
        .titleEqualTo("isar")
        .findFirst() as Post;
```
I can not call ipost.users.lenght or ipost.users.isEmpty and other methods on List. I think would be cool if that is a possibility as

**Comment by flocbit** [comment]
@leisim As far as I understand @richard457 he is looking for a way to use length, isEmpty etc. on not yet loaded IsarLinks.

This would actually be a huge improvement imho :)

**Comment by leisim** [comment]
@flocbit Could you give an example use case for this?

**Comment by flocbit** [comment]
@leisim  Let's say I have a ListView listing all teachers. Each ListTile shows a teacher's name and the number of students as subtitle (e.g. `2 students`).

In order to calculate the number of students one has to load all students into memory (as far as I understand current querying functionality) with a separate query before counting and showing them in subtitle.

With a lazily loaded `teachers.students.length` count function it would be more convenient to realize such a task.

Especially when working with a lot of links this functionality would be quite useful.

**Comment by leisim** [comment]
@richard457 @flocbit I like the idea. How about we allow all operations of a query for `IsarLinks` then you can also sort, aggregate and filter links?

**Comment by flocbit** [comment]
@leisim that would be even better! :)

**Comment by wardy484** [comment]
> @richard457 @flocbit I like the idea. How about we allow all operations of a query for `IsarLinks` then you can also sort, aggregate and filter links?

🙌  I was literally about to raise a request for sorting on links.

**Comment by fakalit** [comment]
> > @richard457 @flocbit I like the idea. How about we allow all operations of a query for `IsarLinks` then you can also sort, aggregate and filter links?
> 
> 🙌 I was literally about to raise a request for sorting on links.

This would be greatly appreciated. There are ways to get around it at runtime, so I understand its low priority feature. But right now when we load relationships through IsarLinks there are no guarentees about the order in which they return, and the order is non-deterministic and different each time. One possible inspiration could be ORM tools like hibernate. They usually offer a way to sort this out declaratively like [@OrderBy("aProperty")](url)

**Comment by leisim** [comment]
This is implemented with the newest version :)

**Comment by Allenxuxu** [comment]
> This is implemented with the newest version :)

So, how do I sort 🤔
