### ISSUE TITLE
[BUG] `buildQuery` on multiple indexed fields always return only 1 object

### ISSUE THREAD

**Issue by jtzell** [isar/isar#247]
**Steps to Reproduce**
Model:
```
import 'package:equatable/equatable.dart';

@Collection()
class Orderline with EquatableMixin {
     int? id;
     @Index(unique: true, type: IndexType.value, caseSensitive: true)
     String? guid;
     @Index(type: IndexType.value, caseSensitive: true)
     String? orderId;
     @Index(type: IndexType.value, caseSensitive: true)
     String? productId;
     
     @Ignore()
     @override
     List<dynamic> get props => [id, guid, orderId, productId];

}
```
Code
```
final oline1 = Orderline()
    ...guid = 'guid-01'
    ...orderId = 'order-01'
    ...productId = 'product-01';
final oline2 = Orderline()
    ...guid = 'guid-02'
    ...orderId = 'order-01'
    ...productId = 'product-02'

isar.writeTxnSync((txnIsar) {
      final txnCol = txnIsar.getCollection<Orderline>('Orderline');
      txnCol.putAllSync([oline1, oline2], replaceOnConflict: true);
      final results = txnCol.collection.buildQuery(
           whereClauses: [
                WhereClause(indexName: 'orderId', lower: ['order-01'], upper: ['order-01']),
                WhereClause(indexName: 'productId', lower: ['product-03'], upper: ['product-03']),
           ],
      ).findAllSync();
      
      // The below `assert` will throw, since the query will always return 'Orderline'
      // with 'productId' = ['product-01','product-02']
      // NOTICE: `productId` is defined as String; however, the query result return 
      // array of type String!!!
      assert(results.length == 0, "Expect 0 result; Got: ${results.map((ol) => '$ol').join('\n')}"); 
}
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.10.1
 - Isar version: 2.2.0+1
 - Isar Generator version: 2.2.0+1

**Comment by leisim** [comment]
Hey, the result works for me as expected. The query returns both objects so the assert will always throw.

I strongly recommend not to use dynamic queries as it is easy to make mistakes :)

**Comment by jtzell** [comment]
> Hey, the result works for me as expected. The query returns both objects so the assert will always throw.

The query mean to search for orderline with productId = "product-03". I create only 2 orderline; one with productId = "product-01" and the other with productId = "product-02".

However, both orderline shared the same orderId, which is "order-01".

The query of where orderId = "order-01" AND productId = "product-03" should return 0 results.


> I strongly recommend not to use dynamic queries as it is easy to make mistakes :)

I'm trying do covert custom query syntax into Isar `Whereclause`(s) and `FilterOperation`(s). Therefore, the pre-generated code is not used in our app.

**Comment by leisim** [comment]
Important: Where clauses are combined using logical **OR**
https://isar.dev/queries.html#where-clauses

Your query equals `orderId == 'order-01' || productId == 'product-03'`.

You can use filters for logical **AND**
