### ISSUE TITLE
Isar inspector issue when clicking on any collection

### ISSUE THREAD

**Issue by jackdy19** [isar/isar#251]
I am receiving an error with Isar Inspector. It opens without any problem, but when clicking on any of the collections it shows this error message:

```
Something went wrong

Type _InternalLinkedHashMap<String, dynamic> is not a subtype of type Map<String, Object> in type Cast

```

I am not sure if this is an issue on my side? And many thanks for this awesome package!

**Version**
 - Platform: iOS, Mac,
 - Flutter version: 2.10.1
 - Isar version: 2.2.0
 - Isar Generator version: 2.2.0

**Comment by mny459** [comment]
same issue, change <String, Object> to  <String, dynamic> works for me

**Comment by dev-thinks** [comment]
> 

@mny459 where to change this to make it work? please let me know. thanks.

**Comment by mny459** [comment]
> > 
> 
> @mny459 where to change this to make it work? please let me know. thanks.

1. clone isar to local
2. cd to isar_inspector and open by AndroidStudio
3. find all <String, Object> and replace to <String, dynamic>
4. run isar_inspector

**Comment by dev-thinks** [comment]
cool. let me try. thank you.

**Comment by leisim** [comment]
Fixed in latest release 👍
