### ISSUE TITLE
Minor miscellaneous typos

### ISSUE THREAD

**Issue by volund** [isar/isar#252]
Greetings,

There are minor typos in the documentation:

On the page https://isar.dev/crud.html#opening-isar:

```
it is possible to loose the last commited transaction. Corruption is not possible
```

`loose` should probably be `lose` and `commited` should probably be `committed`.

On the page https://isar.dev/links.html#isarlinks:

```
to assign multiple teachers to a single student (without loosing data).
```

`loosing` should probably be `losing`.

By the way thank you for this amazing project. The documentation is excellent and the presentation is beautiful.

**Comment by leisim** [comment]
Haha great findings! Would you mind opening a PR? Thanks a lot 🙂 https://github.com/isar/docs

**Comment by volund** [comment]
My first github PR. It was easier than I thought.

https://github.com/isar/docs/pull/12

**Comment by leisim** [comment]
Wohoo great job 🎉
Thank you!
