### ISSUE TITLE
Add support for encryption

### ISSUE THREAD

**Issue by wferem1** [isar/isar#253]
**Is your feature request related to a problem? Please describe.**
Allow for encryption of the database

**Describe the solution you'd like**
specify an encryption key which encrypts the isar database

**Describe alternatives you've considered**
I used hive, but I needed queries, so that's why i want to migrate to Isar. However, without encryption of the data, this won't be possible since the app stores sensitive data.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.5.1
 - Isar version: 2.0.0

**Comment by leisim** [comment]
This is not planned at the moment on in foreseeable future. Please see #199
