### ISSUE TITLE
App crash when multiple query thread runs in backroung.

### ISSUE THREAD

**Issue by anandsubbu007** [isar/isar#263]
Platform: windows

isar is really fast.

when multiple queries run in a loop on one page.
when I switch that page due to too much load. 
app crash

**Comment by leisim** [comment]
Could you provide some sample code or at least an exception and steps to reproduce it? Otherwise I'm unable to help 🙁

**Comment by anandsubbu007** [comment]
can't able find any details (exception) in debug console.

**Comment by leisim** [comment]
I'm sorry, I cannot help without example code or an exception. Please reopen once you have more information 🙌
