### ISSUE TITLE
IsarError (IsarError: Cannot open Environment: MdbxError (22): Invalid argument)

### ISSUE THREAD

**Issue by richard457** [isar/isar#268]
**Steps to Reproduce**

**Code sample**
```
await Isar.open(
      directory: dbName,
      schemas: [
     
      ],
      inspector: false,
)
```

**Version**
 - Platform:Android, 4x ARM Cortex-A7
 - Flutter version: Version 10.0.19042.1526
 - Isar version:isar: ^2.2.0+1
 - Isar Generator version: ^2.2.0+1

**Comment by richard457** [comment]
I know ARM Cortex-A7 is 32, but I used to run a 64-bit app on it. but it seems like it does not work with isar @leisim

**Comment by anandsubbu007** [comment]
any Update?

**Comment by richard457** [comment]
> any Updates?

There is none, last time I tested it  we can keep track here https://github.com/isar/isar/issues/187
