### ISSUE TITLE
[bug] index caseSensitive: false not work

### ISSUE THREAD

**Issue by rizzi37** [isar/isar#271]
```

class Person {
  @Index(caseSensitive: false) // not work
  late String name;
}

```

**Comment by leisim** [comment]
This should be fixed by now :)

**Comment by AristideVB** [comment]
```dart 
@Index(type: IndexType.value, caseSensitive: false)
  List<String> get mainTextWords => Isar.splitWords(mainText);
```

I'm using `.filter().mainTextWordsElementStartsWith('Hello')` it finds values but if I write `.filter().mainTextWordsElementStartsWith('hello')` it finds not values are you sure `caseSensitive: false` is fixed @simc ? :)

**Comment by Jtplouffe** [comment]
> ```dart
> @Index(type: IndexType.value, caseSensitive: false)
>   List<String> get mainTextWords => Isar.splitWords(mainText);
> ```
> 
> I'm using `.filter().mainTextWordsElementStartsWith('Hello')` it finds values but if I write `.filter().mainTextWordsElementStartsWith('hello')` it finds no values are you sure `caseSensitive: false` is fixed @simc ? :)

When querying the database with `.filter()`, you are not using the index.
In order to use the index, you must use `.where()`.

For example, this query would be using the index:
```dart
.where().mainTextWordsElementStartsWith("Hello")
```

**Comment by AristideVB** [comment]
@Jtplouffe 

Okay I see, thanks for your answer. But thing is `.where()` only allows the use of `.or()` & not `and()` & I need to intersect multiple conditions - do you know how I can do something like this with `.where()` ? ->

```dart 
  Future<List<PlacesSuggestion>> searchPlacesSuggestions(
      String searchTerm) async {
    final splitSearchTerm = Isar.splitWords(searchTerm);

    var query = _isar.placesSuggestions
        .filter()
        .mainTextWordsElementStartsWith(splitSearchTerm.first);

    for (final word in splitSearchTerm.skip(1)) {
      query = query.and().mainTextWordsElementStartsWith(word);
    }

    return query.findAll();
  }
```

**Comment by Jtplouffe** [comment]
> @Jtplouffe
> 
> Okay I see, thanks for your answer. But thing is `.where()` only allows the use of `.or()` & not `and()` & I need to intersect multiple conditions - do you know how I can do something like this with `.where()` ? ->
> 
> ```dart
>   Future<List<PlacesSuggestion>> searchPlacesSuggestions(
>       String searchTerm) async {
>     final splitSearchTerm = Isar.splitWords(searchTerm);
> 
>     var query = _isar.placesSuggestions
>         .filter()
>         .mainTextWordsElementStartsWith(splitSearchTerm.first);
> 
>     for (final word in splitSearchTerm.skip(1)) {
>       query = query.and().mainTextWordsElementStartsWith(word);
>     }
> 
>     return query.findAll();
>   }
> ```

This is a limitation of indexes (almost all database have this `or` limitation).

One way to do this query would be to do it without the index. If you don't have thousands of entries in the collection, it shouldn't impact performance much.

Using the `.filter()`, like you were doing initially, you can pass the named argument `caseSensitive` and set it to `false`.

Your query could look something like this:
```dart
.filter().allOf(splitSearchTerm, (q, String word) => q.mainTextWordsElementStartsWith(word, caseSensitive: false))
```
