### ISSUE TITLE
Dump / Import Database

### ISSUE THREAD

**Issue by wardy484** [isar/isar#278]
The ability to dump my database to a file that can be re-imported later would be a huge boon to development and debugging.

I'm quite open to that fact that I might be missing something really obvious but if not then just being able to drop a local database to a json file (or something less human readable) and equally re-import. 

I appreciate this _could_ be implemented locally with some reads/writes and I will probably do so at some point, however I feel like dumping out the exact state as is in the database would feel more accurate than me grabbing all the rows in my database dumping them explicitly.

**Comment by hygehyge** [comment]
+1.
Currently, I copy mdbx.dat for this purpose.
But this is rely on the implemantation and will be invalid in the future.
On the other hand, there is `Query.exportJson()` and `IsarCollection.importJson()`.
What is the recommended way ?

**Comment by leisim** [comment]
Going to close this because there are no plans for other ways to export.
