### ISSUE TITLE
isar.clear() makes auto incremented id to int.MIN

### ISSUE THREAD

**Issue by appano1** [isar/isar#279]
**Steps to Reproduce**
isar.clear() makes auto incremented id to int.MIN (-9223372036854775807)

**Code sample**
```dart
await isar.writeTxn((isar) => isar.clear());
...

final id = await isar.writeTxn((isar) => isar.someObjs.put(someObj));
print(id); // -9223372036854775807
```

**Version**
 - Platform: iOS
 - Flutter version: 2.10.2
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

**Comment by rizzi37** [comment]
what's your expectation?

**Comment by appano1** [comment]
I expected id 1. 
I want to reset db to the initial state for testing or handling user log out event...
Whenever hot restart in test environment, I had to make the object first id 1.

**Comment by leisim** [comment]
This is fixed in the latest release :+1:
