### ISSUE TITLE
Isar Error: Could not initialize IsarCore library

### ISSUE THREAD

**Issue by hygehyge** [isar/isar#281]
When I run Flutter app on Android 5 emulator, below error is occurred.
![image](https://user-images.githubusercontent.com/30744088/157168817-2d46eafd-871b-4760-b8e1-1a30cb836b40.png)
Emulator's image is for x86_64, so I think this is running under 64 bit.
![image](https://user-images.githubusercontent.com/30744088/157169254-87288161-ea16-43ee-85d1-2b0961affd8c.png)

Here is dependency definitions and flutter doctor -v.
```yaml
dependencies:
  isar: 2.2.1
  isar_flutter_libs: 2.2.1

dev_dependencies:
  isar_generator: 2.2.1
```

[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.493], locale ja-JP)
    • Flutter version 2.10.2 at D:\Flutter\SDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\AndroidSDK
    • Platform android-31, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32210.238
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.65.0)
    • VS Code at C:\Users\\\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 5.0.2 (API 21) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 99.0.1150.30

[√] HTTP Host Availability
    • All required HTTP hosts are available

I think Isar can run on 64 bit devices, or is there another limitation ?

**Comment by catalunha** [comment]
Here I had the same problem
![image](https://user-images.githubusercontent.com/19995819/158916122-d4b206d8-a8f7-49e8-a37e-a0e2a00dfcd6.png)

**Comment by richard457** [comment]
I believe this is related to https://github.com/isar/isar/issues/187 which is not fixed yet.

**Comment by leisim** [comment]
Already fixed
