### ISSUE TITLE
Cannot assign dynamic id when adding items to IsarLinks<T>()

### ISSUE THREAD

**Issue by marcorossitb** [isar/isar#282]
**Steps to Reproduce**
I got this simple 1:N structure where a `ApiResponse` can have multiple `MyItem`.

`MyItem` has already a property named 'Id' obtained from apis so I created the isar id with an other name (offId) and the "@ Id" annotation.

My goal is to assign to 'offId' (off stands for offline) the hashcode of 'Id' because it's a string.
If I try not assigning manually 'offId' the items are correctly inserted but when I assign to 'offId' any custom value (hashcode, and index etc.) the items are not saved.

**Code sample**
The collections
```
@Collection()
class MyItem {
  // Isar ID
  @Id()
  int? offId;

  // Api ID and other properties
  late String id; // I would like to don't change its name
  String? name;
  String? description;
}

@Collection()
class ApiResponse {
  // constant ID because I always want to overwrite the ApiResponse collection
  // This works fine.
  int id = 999999999;

  // Items fetched by apis
  List<MyItem> items = [];

  // IsarLinks where I want to save the items.
  final offItems = IsarLinks<MyItem>();
}
```
My Code:
```
Future<void> writeItemsOffline(ApiResponse response) async {
    // This works
    // final offApiResponse = ApiResponse()..offItems.addAll(response.items);

    // This doesn't work
    final offApiResponse = ApiResponse();

    for (final item in response.items) {
      offApiResponse.offItems.add(item..offId = item.id.hashCode);
    }

    await isar.writeTxn((isar) async {
      await isar.apiResponses.put(offApiResponse);
      await offApiResponse.offItems.save();
    });
  }
```
Call to 'writeItemsOffline':
```
writeItemsOffline(ApiResponse()
  ..items = [
    MyItem()
      ..id = "ID1"
      ..name = "Name1",
    MyItem()
      ..id = "ID2"
      ..name = "Name2",
  ],
)
```
**Version**
 - Platform: iOS
 - Flutter version: [2.8.1]
 - Isar version: [2.2.1]
 - Isar Generator version: [2.2.1]

**Comment by marcorossitb** [comment]
I tried to look inside the "save" method of the IsarLinks to better understand and I made a edit that makes the save works (with custom ids).
**File**: isar_link_impl.dart
**Method**: `Future<void> save()` at row 147.

**Edit**, row 169:
```
if (unsavedAdded.isNotEmpty) {
  final unsavedIds = await targetCol.putAll(unsavedAdded);
  ids.setAll(i, unsavedIds);
  i += unsavedIds.length;
} else { // I added this else statement
  await targetCol.putAll(added);
  i += ids.length;
}
```

This correctly save my items with my custom Id. For sure the logic could be wrong for other cases but I think it's a start point to better understand the behavior of the IsarLinks "save" method.

So, is this a bug/issue or there are some other way to save IsarLinks with custom ids?

**Comment by leisim** [comment]
Should be fixed by now. Please reopen if you still have issues

**Comment by BladiCreator** [comment]
Apparently it hasn't been fixed.
Launching lib\main.dart on Edge in debug mode...
lib/database/models/activityClass.g.dart:18:8: Error: The integer literal 4666365104263147782 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 4666365104263147520 is the nearest value that can be represented exactly.
  id: -4666365104263147782,
       ^^^^^^^^^^^^^^^^^^^
lib/database/models/activityClass.g.dart:43:12: Error: The integer literal 3417391711198963146 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 3417391711198963200 is the nearest value that can be represented exactly.
      id: -3417391711198963146,
           ^^^^^^^^^^^^^^^^^^^
lib/database/models/activityClass.g.dart:58:11: Error: The integer literal 2216500372255670030 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 2216500372255670016 is the nearest value that can be represented exactly.
      id: 2216500372255670030,
          ^^^^^^^^^^^^^^^^^^^
lib/database/models/student.g.dart:18:8: Error: The integer literal 252783119861727542 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 252783119861727552 is the nearest value that can be represented exactly.
  id: -252783119861727542,
       ^^^^^^^^^^^^^^^^^^
lib/database/models/student.g.dart:39:11: Error: The integer literal 879695947855722453 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 879695947855722496 is the nearest value that can be represented exactly.
      id: 879695947855722453,
          ^^^^^^^^^^^^^^^^^^
lib/database/models/student.g.dart:543:8: Error: The integer literal 7365220742139980663 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 7365220742139980800 is the nearest value that can be represented exactly.
  id: -7365220742139980663,
       ^^^^^^^^^^^^^^^^^^^
lib/database/models/studentOnClass.g.dart:18:8: Error: The integer literal 3531454797178724705 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 3531454797178724864 is the nearest value that can be represented exactly.

const ActivityClassSchema = CollectionSchema(
  name: r'ActivityClass',
  id: -4666365104263147782,
  properties: {...
