### ISSUE TITLE
Cannot distribute as IPA generation fails due to isar post Archiving

### ISSUE THREAD

**Issue by czaku** [isar/isar#287]
**Steps to Reproduce**
Build, then archive, then distribute as IPA

I am not even using isar, just added in pubspec.yaml and as the build was triggered in codemagic I noticed all the builds for iOS started failing

**Code sample**
```
ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -L /var/folders/__/yww5sl0s2zx_l_mf4jmk7cs80000gn/T/ipatool20220310-73262-1h0u74u/thinned-out/arm64/Payload/Goala\ Dev.app/Frameworks/Flutter.framework --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -o /var/folders/__/yww5sl0s2zx_l_mf4jmk7cs80000gn/T/ipatool20220310-73262-1h0u74u/thinned-out/arm64/Payload/Goala\ Dev.app/Frameworks/isar_flutter_libs.framework/isar_flutter_libs --generate-dsym /var/folders/__/yww5sl0s2zx_l_mf4jmk7cs80000gn/T/ipatool20220310-73262-1h0u74u/thinned-out/arm64/Payload/Goala\ Dev.app/Frameworks/isar_flutter_libs.framework/isar_flutter_libs.dSYM --strip-swift-symbols /var/folders/__/yww5sl0s2zx_l_mf4jmk7cs80000gn/T/ipatool20220310-73262-1h0u74u/thinned-in/arm64/Payload/Goala\ Dev.app/Frameworks/isar_flutter_libs.framework/isar_flutter_libs
Status: pid 73652 exit 1
Stdout:
```

**Version**
 - Platform: iOS
 - Flutter version: 2.10.3
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

**Comment by czaku** [comment]
A little bump, screenshot attached, appstoreconnect validation passes but ad hoc ipa generation fails... I haven't submitted to the appstoreconnect yet as the app is not ready so cannot check that, I am completely block and cannot be producing test builds of the app... [https://capture.dropbox.com/dgpeR0fxFb5C4C4Y](https://capture.dropbox.com/dgpeR0fxFb5C4C4Y)

**Comment by leisim** [comment]
Does it work with other profiles?

**Comment by leisim** [comment]
Should be fixed by now. Please reopen if you still have issues.
