### ISSUE TITLE
Does not load when packaged on Linux

### ISSUE THREAD

**Issue by krillefear** [isar/isar#288]
**Steps to Reproduce**
1. Create a simple Flutter app with Isar
2. Build it for Linux using a snapcraft file
3. Install the snap and run it
4. Isar crashes

**Logs**
```
flutter: Invalid argument(s): Failed to load dynamic library 'libisar.so': /snap/fun-with-kanji/x2/bin/../lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /snap/fun-with-kanji/x2/bin/lib/libisar.so)
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
#0      initializeIsarCore (package:isar/src/native/isar_core.dart:55)
#1      openIsar (package:isar/src/native/open.dart:61)
#2      _IsarNative.open (package:isar/src/native/isar_native.dart:90)
#3      Isar.open (package:isar/src/isar.dart:84)
#4      main (package:fun_with_kanji/main.dart:17)
<asynchronous suspension>
```

**Version**
 - Platform: Ubuntu 20.04
 - Flutter version: [2.10.2]
 - Isar version: [2.2.1]
 - Isar Generator version: [2.2.1]

**Comment by tsavo-at-pieces** [comment]
We are super interested in this as well. We are looking at Isar to be used in a cloud server & on our Linux Flutter application.

**Comment by leisim** [comment]
I have a potential fix for this issue. The next release should solve it :+1:

**Comment by leisim** [comment]
Should be fixed by now. Please reopen if you still have issues
