### ISSUE TITLE
Small tip to improve docs - how to access the Isar instance without passing it through

### ISSUE THREAD

**Issue by Musta-Pollo** [isar/isar#289]
When I first played with Isar, I couldn't access the Isar instance in other parts of the program without passing it through widgets.

I found it later on, but I think that adding a small section to the documentation, how to access it would be beneficial for people starting with it.

**Comment by lodisy** [comment]
> Out of interest,  how do you access the isar instance without passing it through widgets?

You can use state management libs, for example provider, riverpod etc.

**Comment by Musta-Pollo** [comment]
You can access it similarly to the Hive package. The main difference is that Isar has multi Isolate support, so you need to pass the isolate's name, or it will return the instance for the primary isolate.

This is the function you are looking for:

``` dart /// Returns an Isar instance opened in the current isolate by its name. If
  /// no name is provided, the default instane is returned.
  static Isar? getInstance([String name = defaultName]) {
    return _instances[name];
  }
  ```
And like this, you can use it, for example, with riverpod:

main.dart

``` dart
import 'package:isar/isar.dart';
....


void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final dir = await getApplicationSupportDirectory();

  final isar = await Isar.open(
    schemas: [TodoSchema],
    directory: dir.path,
  );

  runApp(
    const ProviderScope(
      child: App(),
    ),
  );
}
```

todos_provider.dart
``` dart
import 'package:isar/isar.dart';

final todosProvider = StreamProvider<List<Todo>>((
  ref,
) async* {
  Isar isar = Isar.getInstance()!;
  ...
});
```

**You need to import the Isar source file where you want to use it.**

I hope it helps.
