### ISSUE TITLE
Add encryption support

### ISSUE THREAD

**Issue by ahalunetsvisionable** [isar/isar#292]
Can you add database encryption support as in `Hive`? 
This is very important for medical and financial projects.

**Comment by Anan-Saadi** [comment]
This is not a priority right now as mentioned here #176

**Comment by leisim** [comment]
We discussed this multiple times and currently it's not planned. I'm going to leave this PR open, maybe more users need this feature.

**Comment by chaoyebugao** [comment]
I am building a 1Password-liked, and I really need the encryption.

**Comment by TheGreatAxios** [comment]
Was planning to switch from Hive to hear. Lack of encryption just negates the option sadly. 
The technology looks amazing, so hopefully can make a full switch in the future with encryption.

**Comment by Hesamedin** [comment]
I am working on an Internal project for my company. My company has a lot of assets that should be secured. Therefore, having encryption is super important for my company and the lack of this feature is a blocker for us to use Isar.

**Comment by leisim** [comment]
@Hesamedin you can always encrypt the data yourself before storing it in Isar if you feel like there is a need for it.

I don't think there is. All of todays phones are fully encrypted. There has been a lot of discussion about this already 🙂

**Comment by elhe26** [comment]
Hey @leisim , is there a roadmap we can follow? Isar is really nice but without encryption is really difficult to switch over.

**Comment by tbleiker** [comment]
> @Hesamedin you can always encrypt the data yourself before storing it in Isar if you feel like there is a need for it.
> 
> I don't think there is. All of todays phones are fully encrypted. There has been a lot of discussion about this already 🙂

That might be true for mobile, but not for cross-platform projects covering desktop apps...

**Comment by leisim** [comment]
By all means, switch to "competitors" then.

It's currently not technically possible to support encryption the way I want to. I'll not ship a half baked feature. If you really want to use Isar with encryption just encrypt your data before storing it!

**Comment by leisim** [comment]
> Looking at the latest updates of Isar, one gets the impression that you do not want to pay attention to really important features.

That's certainly subjective...

> you do not even consider the possibility of solving this problem

1. How do you know that? I've been very actively working on this issue. Fun fact: The initial versions of Isar even had encryption support.

But like I said it's not possible with Isar's current architecture.

2. Why do you think I have to implement this. Why don't you help out instead of complaining. I'm spending my free time here so I'll work on what I believe brings the most benefits to the users.

**Comment by ahalunetsvisionable** [comment]
>I'll work on what I believe brings the most benefits to the users.

Judging by the fact that many people ask about it and like it, this is a really necessary functionality

>How do you know that? I've been very actively working on this issue. Fun fact: The initial versions of Isar even had >encryption support.

I have come to the conclusion that you are not responding to people's questions regarding the update on this issue and are constantly offering the same bad solution.

**Comment by TheGreatAxios** [comment]
To everyone who has requested encryption;There is no reason to ever be rude, mean, disrespectful to them. They built an amazing package already that you clearly have or may find benefit from from. Please be grateful for their great contribution to the open source community as opposed to being aggressive and rude resulting in not just them leaving; but potentially the loss of this software. Thanks to the author for your quick responses, I hope you get more appreciation and help as opposed to rudeness. On Oct 28, 2022, at 6:46 AM, ahalunetsvisionable ***@***.***> wrote:﻿

I'll work on what I believe brings the most benefits to the users.

Judging by the fact that many people ask about it and like it, this is a really necessary functionality

How do you know that? I've been very actively working on this issue. Fun fact: The initial versions of Isar even had >encryption support.

I have come to the conclusion that you are not responding to people's questions regarding the update on this issue and are constantly offering the same bad solution.

**Comment by ahalunetsvisionable** [comment]
I apologize if I seemed rude. I really appreciate your work! You are great guys! But the long wait and lack of result, when others implement it and respond quickly, it causes annoyance...

**Comment by leisim** [comment]
Completely understandable. Unfortunately others wait for web support for 3.0 translated docs or sync. And encryption is very close to impossible currently 😭

**Comment by ahalunetsvisionable** [comment]
Guys, I support you and I'm on your side! It's hard to compete with big companies and here's a low bow! But commerce needs encryption! ObjectBox and Realm don't have web support either! Flutter is raw for the web... That's a fact... You're incredible, that's a fact too! 😉

**Comment by leisim** [comment]
Would it help you if we had a column based encryption? Where you would annotate one or multiple properties (including embedded objects) with `@encrypted` to store them encrypted?

The downside is that you won't be able to index those properties or use them in queries

**Comment by soumyadeep-ghosh** [comment]
> Would it help you if we had a column based encryption? Where you would annotate one or multiple properties (including embedded objects) with `@encrypted` to store them encrypted?
> 
> The downside is that you won't be able to index those properties or use them in queries

Seems reasonable as we don't really need to mask all the data, but some

**Comment by elhe26** [comment]
> Completely understandable. Unfortunately others wait for web support for 3.0 translated docs or sync. And encryption is very close to impossible currently 😭

Thanks for your honesty and for creating this package ( I love hive too, hehe).

**Comment by mghase** [comment]
> This is not a priority right now as mentioned here #176

the packege is good but without encryption it will be useless for most app.try to rethink about it

**Comment by AlexDochioiu** [comment]
Same here. I cannot consider using this before encryption is implemented. Until then I'll stick with Hive and move to alternatives if Hive stops being properly maintained.

**Comment by Dosenbiiir** [comment]
First really big thanks for your awesome work here. I love Isar so much. It's super powerful, has a nice syntax and makes development so fast. Encryption is an important topic but I think it's not that easy to get it working with all of the features Isar provides. I don't have the knowledge but I think its hard to encrypt the whole database but remain the power indexes, filters etc.

> Would it help you if we had a column based encryption? Where you would annotate one or multiple properties (including embedded objects) with `@encrypted` to store them encrypted?
> 
> The downside is that you won't be able to index those properties or use them in queries

I think that would be awesome. It might not cover every usecase but at least some or many of them. In my current project it would fit perfectly. At the moment we have to manually encrypt the fields.

**Comment by Hesamedin** [comment]
Encrypting the whole database or all the contents does not make sense. Particularly, the fact that we miss some of the important features such as sort and filter. What I would recommend is to annotate those fields we want to encrypt. In this case, the process of encryption/decryption is faster and we can benefit from sort/filter/watch/etc.

**Comment by saguado69** [comment]
> Would it help you if we had a column based encryption? Where you would annotate one or multiple properties (including embedded objects) with `@encrypted` to store them encrypted?
> 
> The downside is that you won't be able to index those properties or use them in queries

That would be great and will cover all my needs, so, is this feature going to be available on next release (3.0.6)?

**Comment by saborrie** [comment]
For those who want the encryption of Hive, but the rest of the features of Isar: why not use both?

When you want to store an encrypted value in Isar, store it in Hive against a UUID key and store the key instead. Then, when you want it back, just look up the value in Hive.


Something like this:

```dart
String tokenise(String value) {
  final token = uuid.v4();
  encryptedBox.put(token, value);
  return token;
}

String detokenise(String token) {
  return encryptedBox.get(token);
}

// save a new item
final plainText = Item(name: "Hello World", age: 10);
final tokenised = plainText..name = tokenise(plainText.name);
isar.writeTxnSync<int>(() => isar.items.putSync(tokenised));

// read an item
final tokenised = isar.items.where().ageIsEqualTo(10).findFirstSync();
final plainText = tokenised..name = detokenise(tokenised.name);
```

**Comment by simc** [comment]
Full encryption support is coming with Isar 4.0! Don't ask for a timeline lol 😂

**Comment by abhay-s-rawat** [comment]
Actually I am in middle of my project and I am using Hive but I am getting errors like "Recovering corrupted box" when I am using encryption in macos builds for some boxes.
I love the way it is designed but 255 limit of models and less frequent updates on it makes me think to move to isar. But I need encryption support very badly so I am eagerly wating for your update. If you can provide a way to use encryption in current latest version of isar then I can use it till v4 is released. The way hive was saving nonce int database is better than field encryption, what do you think ?
Can you please tell when we can expect already best database to be best in all classes ?

**Comment by simc** [comment]
Haha first preview version in a few weeks

**Comment by abhay-s-rawat** [comment]
> Haha first preview version in a few weeks

Can I migrate to ISAR now and when you add encryption support I will just update. Will there me too much changes in v3 and v4 ?

**Comment by simc** [comment]
Yes you can. There will be some breaking API changes but there will be an easy migration guide.

**Comment by heynext** [comment]
Politely ask when will v4.0 be released?

**Comment by simc** [comment]
Encryption is implemented and working but I'm still fighting a few bugs. Probably a few more weeks

**Comment by simc** [comment]
This is now supported in Isar v4 🎉

**Comment by neiljaywarner** [comment]
@simc  woo hoo, way to go!  can't wait for v4 to be stable, very exciting!

**Comment by abhay-s-rawat** [comment]
Well I was wondering encryption name used in isar4, can we change it ?

**Comment by talkbiz** [comment]
@simc, thank you so much for the great work.

**Comment by itsJoKr** [comment]
>  Isar engine does not support encryption. Please set the engine to IsarEngine.sqlite.
Just a note for others that this is what I get with 4.0.0-dev.14

Not sure are there plans to support Isar engine as well.

**Comment by juppdes** [comment]
Where can I find the instructions for version 4 that include encryption?

**Comment by SoftWyer** [comment]
In the code documentation it suggests to supply and encryption key to the [open command](https://github.com/isar/isar/blob/04886f692d6e1935e695ae993f77848b023dfb80/packages/isar/lib/src/isar.dart#L62):

```
  /// If [encryptionKey] is provided, the database will be encrypted with the
  /// provided key. Opening an encrypted database with an incorrect key will
  /// result in an error. Only the SQLite storage engine supports encryption.
  ///
```
