### ISSUE TITLE
Unit testing and how to get started?

### ISSUE THREAD

**Issue by wildaces215** [isar/isar#294]
Is there a way or an example to get started writing unit test cases for production apps?

**Comment by mastro993** [comment]
Hi! I tried to init the Isar library from the `setUp()` method in my unit tests but I got this error:

> IsarError (IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.)

I think I need to do something else 🤣
Any help would be appreciated 😃

**Comment by scottbisaillon** [comment]
> Hi! I tried to init the Isar library from the `setUp()` method in my unit tests but I got this error:
> 
> > IsarError (IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.)
> 
> I think I need to do something else 🤣 Any help would be appreciated 😃

I had some luck by looking at: https://github.com/isar/isar/blob/a1fd2bc90a2d979047b0ee0d25e6307ed04fc3a8/packages/isar_test/test/common.dart#L89 That should give you an idea on how to open a temporary database. It shows how to register the binaries at runtime. I currently have some unit tests working following this method.

**Comment by ayalma** [comment]
Hi 
I have problem for mocking the isar using mockito package
and i think this is related to this issue

**Comment by leisim** [comment]
@ayalma what problem are you facing?

**Comment by leisim** [comment]
Isar can now handle downloading the binaries automatically. Check out this section in the readme: https://github.com/isar/isar#unit-tests
