### ISSUE TITLE
Nothing is happening when click on connect button after entering url

### ISSUE THREAD

**Issue by arv-aks** [isar/isar#295]
unable to connect to isar inspector. 
Need a documentation .

**Comment by marcorossitb** [comment]
I think it's because no Isar instance is open. Not sure

**Comment by arv-aks** [comment]
Isar instance is opened and I am doing transactions i.e. writeTxn -> collection.put , and this is working. 
The process I am following is : running my app in android device. and launching isar inspector. is this correct?

**Comment by vlado-rudenok** [comment]
@arv-aks be sure to open Isar with `inspector: true`

**Comment by arv-aks** [comment]
> 
![Screenshot 2022-03-19 at 10 04 28 AM](https://user-images.githubusercontent.com/84610386/159106948-a2e8693e-b74d-4be9-a045-cb4ead8dff9f.png)

ThankYou, Isar inspector is connected now , but I am getting an error..

**Comment by vlado-rudenok** [comment]
There is open issue about it (with workaround) #251

**Comment by leisim** [comment]
Fixed in latest release 👍
