### ISSUE TITLE
Xcode archive failed - Unknown attribute kind (68)

### ISSUE THREAD

**Issue by Allenxuxu** [isar/isar#303]
could not reparse object file in bitcode bundle: 'Unknown attribute kind (68) (Producer: 'LLVM12.0.1-rust-1.55.0-stable' Reader: 'LLVM APPLE_1_1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' for architecture arm64

**Version**
 - Platform: iOS
 - Flutter version: [ 2.10.3]
 - Isar version: [2.2.1]
 - Isar Generator version: [2.2.1]

**Comment by Allenxuxu** [comment]
Xcode version : 2.4

**Comment by moicw** [comment]
I also facing same issue on Xcode version : 2.4. May i know do you found anyway to solve it? Thanks

**Comment by leisim** [comment]
What do you mean by "XCode version 2.4". Shouldn't it be something like 13.3.1?

**Comment by leisim** [comment]
Anyway, upgrading XCode should fix the issue 🙂

Please reopen if it doesn't work

**Comment by moicw** [comment]
Yes. It have been solved by upgrading xcode. Thanks

**Comment by Allenxuxu** [comment]
I am very sorry that I provided the wrong version earlier.
In fact the Xcode version I use is 13.3 (13E113).
I can run it fine, but when I archive it by xcode, it reports an error.

**Comment by IdrisQashan** [comment]
I have Xcode 13.3.1 and Facing same issue only when I Archive.
 If delete isar_flutter_libs: ^3.0.6-dev.0 it archive done
