### ISSUE TITLE
Getter of model class collection is not defined for the type `Isar`

### ISSUE THREAD

**Issue by red-star25** [isar/isar#305]
I've a User model with Isar annotation as shown below

**user_model.dart**
```
import 'package:isar/isar.dart';

part 'user_model.g.dart';

@Collection()
class User {
  final String name;
  final String email;
  final String phoneNumber;
  @Id()
  final int id;

  User({
    required this.name,
    required this.email,
    required this.phoneNumber,
    required this.id,
  });
}
```
- Also generated a file using `isar_generator` package. And it has extension over Isar for getting the users collection as shown below
```
//....
extension GetUserCollection on Isar {
  IsarCollection<User> get users {
    return getCollection('User');
  }
}
//......
```

- The problem is in my UserRepository. As shown in the documentation that the class with @Collection annotation will automatically generates the getter for getting the reference. But whenever I try to access the `user` getter it say :

- ### The `getter` isn't defined for type Isar

```
import 'package:isar/isar.dart';

class UserRepository {
  final Isar isar;

  UserRepository({required this.isar});

  Future<void> getAllUsers() async {
    await isar.users.where().findAll(); // Error: The `getter` isn't defined for type Isar
  }
}
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.10.3
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

**Comment by hatemragab** [comment]
Is there any updates?

**Comment by richard457** [comment]
You need to open the isar instance and pass the collection the users will then become available.

**Comment by scottbisaillon** [comment]
In the file containing your repository class, add an import to the file containg the user collection.

**Comment by richard457** [comment]
replace ```await isar.users.where().findAll(); ``` with ``` await isar.users.filter().findAll();  ```

**Comment by leisim** [comment]
You need to import the user class to make the getter extension available.
