### ISSUE TITLE
flutter: IsarError: Instance has already been opened.

### ISSUE THREAD

**Issue by bilalgodesto** [isar/isar#307]
**Steps to Reproduce**
- Isar is initialized in main function to load all schemas.
- When i receive firebase notification and application is in background or terminated
- I want to add some data in isar collection.
- Instead i am getting error 

### Error

``` IsarError: Instance has already been opened.```

**Code sample**
```
Future<void> onBackgroundMessage(RemoteMessage message) async {
  await Firebase.initializeApp();

  var isar;
  try {
    isar = await Isar.open(
      schemas: [ChatItemsSchema],
    );
  } catch (e) {
    print('exception  start onbackground process ');
    print(e.toString());
  }
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(onBackgroundMessage);
  final isar = await Isar.open(
    schemas: [ChatItemsSchema],
    directory: (await getApplicationDocumentsDirectory()).path,
  );
  runApp(const MyApp());
  

```

**Version**
 - Platform: iOS
 - Flutter version: 2.10.3
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

**Comment by PapyElGringo** [comment]
@bilalgodesto you should check https://github.com/isar/isar/discussions/256

**Comment by leisim** [comment]
Please check whether the instance is already open using `Isar.getInstance("yourInstanceName")`
