### ISSUE TITLE
Unhandled Exception: IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.

### ISSUE THREAD

**Issue by devr0306** [isar/isar#309]
I'm unable to load the library on macOS. Whenever I run the app, I get:

```
flutter: Invalid argument(s): Failed to load dynamic library 'libisar.dylib': dlopen(libisar.dylib, 0x0001)
[ERROR:flutter[/lib/ui/ui_dart_state.cc]()(209)] Unhandled Exception: IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
```

**Version**
 - Platform: Mac
 - Flutter version: 2.10.2
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

**Comment by devr0306** [comment]
I was able to solve it. I downloaded the latest binary file from https://github.com/isar/isar-core/releases and added it to my project in `/build/macos/Build/Products/Debug`. I also had to follow the steps in https://flutter.dev/docs/development/platform-integration/c-interop#compiled-dynamic-library-macos to add the framework to my Xcode project.

**Comment by sithu-aung** [comment]
Hello @devr0306 , I have followed your steps and able to successfully run app on Mac. But in distribution to appstore connect , it shows the following error. Have you release or upload  your app to app store ? Please kindly share with me how to upload it to appstore if you have done already.

**Comment by sithu-aung** [comment]
Missing signing identifier at "/var/folders/w7/sb40fxv91ts8l50l_lr5yptw0000gp/T/XcodeDistPipeline.~~~PrB2lm/Root/Applications/pos.app/Contents/Resources/libisar.dylib".
<img width="991" alt="Screen Shot 2022-04-01 at 12 58 33" src="https://user-images.githubusercontent.com/43056388/161207454-0959a901-364f-4ae9-ba6d-3f042dbfaef3.png">

**Comment by holdenhinkle** [comment]
Hi @devr0306 ,

I [posted the same issue as this](https://github.com/isar/isar/issues/330) a couple of hours ago and then discovered this page.

I'm following the steps [you linked to on this page](https://docs.flutter.dev/development/platform-integration/c-interop#compiled-dynamic-library-macos) but I can't find `Embed Libraries` anywhere under this step - `Under Embed Libraries, check Code Sign on Copy.` I've Googled this and I'm not getting anywhere.

If you have a moment, can you please send me a screenshot of where `Embed Libraries` is located or some additional instructions?

Here's a screenshot of my Build Phases page:
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/9326247/162589443-5596f559-f58e-4b3e-8ed6-3038aa08db96.png">

I'm kind of new to Dart/Flutter (I'm a rails/node engineer) so I haven't had to use Xcode before.

Thanks so much,

Holden
