### ISSUE TITLE
Application crashes when attempting to put( ) an object with IsarLink

### ISSUE THREAD

**Issue by SherwinJames** [isar/isar#312]
**Steps to Reproduce**
Saving an object with IsarLink, causes the app to crash with the following result:

F/libc    (27659): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27688 (1.ui), pid 27659 (****.*****)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/barbet/barbet:12/SP2A.220305.012/8177914:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2022-03-22 21:16:19.419596401-0400
Process uptime: 0s
Cmdline: com.****.*****
pid: 27659, tid: 27688, name: 1.ui  >>> com.****.***** <<<
uid: 10351
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    x0  0000000000000000  x1  0000000000006c28  x2  0000000000000006  x3  00000074f4af17b0
    x4  00000074c5a561c8  x5  00000074c5a561c8  x6  00000074c5a561c8  x7  00000074c5a56000
    x8  00000000000000f0  x9  54f41560bcb91f28  x10 0000000000000000  x11 ffffff80fffffbdf
    x12 0000000000000001  x13 00000000ffffd8f0  x14 000000000000147b  x15 00000000ffffff9c
    x16 000000781a921050  x17 000000781a8fddb0  x18 00000074f3e92000  x19 0000000000006c0b
    x20 0000000000006c28  x21 00000000ffffffff  x22 0000000000000000  x23 00000074c5b81000
    x24 0000000000000001  x25 00000074c5b815f8  x26 00000074c5b815a8  x27 0000000000000005
    x28 0000000000000000  x29 00000074f4af1830
    lr  000000781a8b0aa0  sp  00000074f4af1790  pc  000000781a8b0acc  pst 0000000000001000
backtrace:
      #00 pc 000000000004facc  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: cd7952cb40d1a2deca6420c2da7910be)
      #01 pc 0000000000081a8c  /data/app/~~2O0Pv_95CA9EHMQumdE0Zg==/com.****.*****-AsQP-90Y_YBeaoREekGu1Q==/lib/arm64/libisar.so
      #02 pc 0000000000082e60  /data/app/~~2O0Pv_95CA9EHMQumdE0Zg==/com.****.*****-AsQP-90Y_YBeaoREekGu1Q==/lib/arm64/libisar.so
      #03 pc 00000000000829c0  /data/app/~~2O0Pv_95CA9EHMQumdE0Zg==/com.****.*****-AsQP-90Y_YBeaoREekGu1Q==/lib/arm64/libisar.so
      #04 pc 000000000009c67c  /data/app/~~2O0Pv_95CA9EHMQumdE0Zg==/com.****.*****-AsQP-90Y_YBeaoREekGu1Q==/lib/arm64/libisar.so
      #05 pc 000000000009c604  /data/app/~~2O0Pv_95CA9EHMQumdE0Zg==/com.****.*****-AsQP-90Y_YBeaoREekGu1Q==/lib/arm64/libisar.so
      #06 pc 000000000009c5d0  /data/app/~~2O0Pv_95CA9EHMQumdE0Zg==/com.****.*****-AsQP-90Y_YBeaoREekGu1Q==/lib/arm64/libisar.so
      #07 pc 000000000000b520  /data/app/~~2O0Pv_95CA9EHMQumdE0Zg==/com.****.*****-AsQP-90Y_YBeaoREekGu1Q==/lib/arm64/libisar.so
      #08 pc 000000000000b700  /data/app/~~2O0Pv_95CA9EHMQumdE0Zg==/com.****.*****-AsQP-90Y_YBeaoREekGu1Q==/lib/arm64/libisar.so
      #09 pc 00000000000340d8  /data/app/~~2O0Pv_95CA9EHMQumdE0Zg==/com.****.*****-AsQP-90Y_YBeaoREekGu1Q==/lib/arm64/libisar.so
      #10 pc 0000000000032200  /data/app/~~2O0Pv_95CA9EHMQumdE0Zg==/com.****.*****-AsQP-90Y_YBeaoREekGu1Q==/lib/arm64/libisar.so (isar_link_replace+88)
      #11 pc 0000000000006db4  [anon:dart-codespace]
Lost connection to device.

**Code sample**
```
    await db.writeTxn((_) async {
      db.jobs.putAll(jobsToSave, replaceOnConflict: true, saveLinks: true);
    });
```

**Version**
 - Platform: Android
 - Flutter version: 2.10.3
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

**Comment by leisim** [comment]
Fixed in latest release 👍
