### ISSUE TITLE
IsarError: You need to provide a valid directory for mobile or desktop apps.

### ISSUE THREAD

**Issue by IbneUmmah** [isar/isar#313]
First of all, thanks for this library. While I was testing this library, I faced the issue given below.

**Steps to Reproduce**
Documentation example of isolates throws the error. Documentation  says that we don't need to provide path in isolate but when we try to open Isar in isolate it throws the error given below.
**Code sample**
void main() {
    final dir = await getApplicationSupportDirectory();

    // Open Isar in the UI isolate
    final isar = await Isar.open(
        name: 'myInstance',
        schemas: [PostSchema],
       directory: dir.path,
    );

    // listen to changes in the database
    isar.posts.watchLazy(() {
        print('omg the posts changed!');
    });

    // start a new isolate and create 10000 posts
    compute(createDummyPosts, 10000).then(() {
        print('isolate finished');
    });

    // after some time:
    // > omg the posts changed!
    // > isolate finished
}

// function that will be executed in the new isolate
Future createDummyPosts(int count) async {
    // we don't need the path here because the instance is already open
    final isar = await Isar.open(
        name: 'myInstance',
        schemas: [PostSchema],
    );

    final posts = List.generate(count, (i) => Post()..title = 'Post $i');
    // we use a synchronous transactions in isolates
    isar.writeTxnSync((isar) {
        isar.posts.insertAllSync(posts);
    });
}
Provide a few simple lines of code to show your problem.
Unhandled Exception: Exception: IsarError: You need to provide a valid directory for mobile or desktop apps.
E/flutter ( 7503): #0      _IsarNative.open
package:isar/…/native/isar_native.dart:87
E/flutter ( 7503): #1      Isar.open
package:isar/src/isar.dart:84
E/flutter ( 7503): #2      insertIntoDB
package:testapp/db.dart:52
E/flutter ( 7503): #3      _IsolateConfiguration.apply
package:flutter/…/foundation/_isolates_io.dart:83**Version**
 - Platform: Android, Windows, 
 - Flutter version: 2.10.3
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

**Comment by leisim** [comment]
This should work now :+1:

**Comment by zawadZwd** [comment]
Im so sorry for opening the closed issue, but I believe I did everything ok and I get the error from the title. Here are the samples: 


flutter version: 2.10.5
device: emulated arm64 API 31

```yaml 
dependencies:
  isar: ^2.4.0
  isar_flutter_libs: ^2.4.0

dev_dependencies:
  build_runner: ^2.1.10
  isar_generator: ^2.4.0
```

1. The global list of schemas:
```dart
final schemas = [ContactModelSchema];
```
2. The main function: 
```dart
void main() async {
    WidgetsFlutterBinding.ensureInitialized();
    final dir = await getApplicationSupportDirectory();
    final isar = await Isar.open(name: 'isarDB', schemas: schemas, directory: dir.path);
   ...
}
```

4. The UI trigger 
```dart
Future<void> uiTrigger() async {
   final contacts [ContactModel(), ContactModel(), ContactModel];
   await compute(isolateTrigger, contacts);
}
```

5. The isolate trigger:
```dart
Future isolateTrigger(List<ContactModel> contacts) async {
    final isarIsolate = await Isar.open(name: 'isarDB', schemas: schemas);
    isarIsolate.writeTxnSync((db) {
      db.contactModels.clearSync();
      db.contactModels.putAllSync(contacts);
    });
}
```


aaaand its not working...The error reveals:
```dart
log('Exception: IsarError: You need to provide a valid directory for mobile or desktop apps');
```

The error stacktrace is in 
```dart 
package:isar/…/native/isar_native.dart:87

  @override
  @pragma('vm:prefer-inline')
  Future<Isar> open({
    String? directory,
    required String name,
    required bool relaxedDurability,
    required List<CollectionSchema> schemas,
  }) {
    if (directory == null) {
      throw IsarError(
          'You need to provide a valid directory for mobile or desktop apps.');
    }
    return openIsar(
      directory: directory,
      name: name,
      relaxedDurability: relaxedDurability,
      schemas: schemas,
    );
  }
```

and 

```dart 
package:isar/src/isar.dart:82

  static Future<Isar> open({
    required List<CollectionSchema> schemas,
    String? directory,
    String name = defaultName,
    bool relaxedDurability = true,
    bool inspector = false,
  }) {
    if (inspector) {
      assert(() {
        _initializeIsarConnect();
        return true;
      }());
    }
    _checkOpen(name, schemas);
    return IsarNative.open(
      schemas: schemas,
      directory: directory,
      name: name,
      relaxedDurability: relaxedDurability,
    );
  }
```

I did something wrong or there is some bug elsewhere? 🤔

**Comment by leisim** [comment]
@zawadZwd sorry, this is indeed an issue. Please just use an empty string as directory in your isolate until it is fixed.

**Comment by zawadZwd** [comment]
Hey, you said empty string? This should not be the same path as the path in main thread? 🤔

**Comment by leisim** [comment]
no it's not necessary. Isar core will recognize the already open instance. Just the Dart side throws an incorrect error right now. So `Isar.open(name: "yourName", directory: "")` is perfectly fine in isolates.

**Comment by leisim** [comment]
This is fixed now in `3.0.0-dev.0` 🙂

**Comment by dayron9110** [comment]
I have this issue in the last version of Isar

**Comment by betonn** [comment]
```
import 'package:path_provider/path_provider.dart'; 
final isar = await Isar.open([
        schemas..,
      ], name: 'test_instance', directory: (await getApplicationDocumentsDirectory()).path,); 
```
This solves the problem. You should have path_provider library and required permissions from user.
