### ISSUE TITLE
i can't visit isar inspector

### ISSUE THREAD

**Issue by g0coders** [isar/isar#315]
I've visited the url given isar, but the result is not isar inspector, but dart vm

![image](https://user-images.githubusercontent.com/54851209/160239544-85c3b90c-f025-4c51-a609-b40c00e5f7c1.png)
![image](https://user-images.githubusercontent.com/54851209/160239552-25daff75-443f-4a4b-9b71-4fd58c9020a4.png)

**Comment by lodisy** [comment]
You got put it in the inspector mac app instead of browser. But there is an issue, check out #251 for workaround.

**Comment by g0coders** [comment]
> Anda memasukkannya ke dalam aplikasi mac inspektur alih-alih browser. Tapi ada masalah, lihat #251 untuk solusinya.

I didn't find an error like that, the problem is when I open the given link it redirects to the dart vm, not the inspector page.
![image](https://user-images.githubusercontent.com/54851209/160311190-2ebce804-846c-4332-8f03-44b936acdb32.png)

**Comment by lodisy** [comment]
> > Anda memasukkannya ke dalam aplikasi mac inspektur alih-alih browser. Tapi ada masalah, lihat #251 untuk solusinya.
> 
> I didn't find an error like that, the problem is when I open the given link it redirects to the dart vm, not the inspector page.
> ![image](https://user-images.githubusercontent.com/54851209/160311190-2ebce804-846c-4332-8f03-44b936acdb32.png)
> 

As far as I know, the inspector only has macOS client. You have to install the app to use it.

**Comment by g0coders** [comment]
I don't have Mac OS, I have Linux, hopefully in the future there will be applications for Linux, especially Debian.
