### ISSUE TITLE
Upload compile fail for Distribution to MacOS App Store

### ISSUE THREAD

**Issue by sithu-aung** [isar/isar#322]
Archive works well and in uploading to App Store. The following error occurred.

Missing signing identifier at "/var/folders/w7/sb40fxv91ts8l50l_lr5yptw0000gp/T/XcodeDistPipeline.~~~QnoD8c/Root/Applications/pos.app/Contents/Frameworks/isar_flutter_libs.framework/Versions/A/Resources/libisar.dylib".

<img width="993" alt="Screen Shot 2022-03-30 at 16 27 08" src="https://user-images.githubusercontent.com/43056388/160846350-9d2528fc-153c-4187-a4a4-25093b05822b.png">

**Version**
 - Platform: Mac
 - Flutter version: 2.10.4
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

**Comment by sithu-aung** [comment]
<img width="993" alt="Screen Shot 2022-03-30 at 16 27 08" src="https://user-images.githubusercontent.com/43056388/160846676-c9a30838-709c-46f0-beb4-d106a4fa966c.png">

**Comment by sithu-aung** [comment]
I have solved this problem by removing "isar_flutter_libs: 2.2.1" from pubspec.yaml file. Pod installing and Archiving works well after it. I don't know why .

**Comment by sithu-aung** [comment]
In removing "isar_flutter_libs:2.2.1" , the app cannot initialize and after using Dynamic library , it also return the same error of  "Missing signing identifier". Please kindly help me.

**Comment by oscarpalomar** [comment]
It's also happening to me

**Comment by leisim** [comment]
This is fixed in version 3.0.1
