### ISSUE TITLE
Ability to run isar on background Isolates/Web Workers 

### ISSUE THREAD

**Issue by martin-robert-fink** [isar/isar#324]
**Is your feature request related to a problem? Please describe.**
isar throws exceptions when run on a background thread due to the use of dart:ui

**Describe the solution you'd like**
I'm creating a parser to process very large files.  The parser needs to be multi-threaded (multi-isolate on native platforms, multi-web worker on web.  I'd like to be able to add objects to the ISAR DB in a background isolate/web worker.  I'm using the Squadron package (version 3.3) to do the common interface to isolate/web worker.  Any calls to isar when on the background web worker causes an exception to be thrown.  It appears isar is using dart:ui and you can't do ui stuff when not on the primary thread.

**Describe alternatives you've considered**
The only available alternative is to pass data from the background web worker to the main isolate and then add the data to isar from the main isolate.  The issue with this is that I'm dealing with 100's of MB files/objects and there's a large overhead to do the transfer of objects from web worker to the main thread.

**Version**
 - Platform: all
 - Flutter version: 2.10.4
 - Isar version: 2.2.1

**Comment by leisim** [comment]
It should work in isolates. Isn't `dart:ui` available in isolates?

Web workers are unsupported in Flutter unfortunately :(

**Comment by martin-robert-fink** [comment]
Correct, it works in isolates.  Web worker is what I'm looking for.  I'm using a package called Squadron 3.3 which does support web workers and it's working great.  I am able to run true multi-platform with isolates on native platforms and web workers on web (with a common interface) and it works great.  The part of the code that is the threaded code, I just have to `dart compile js ...`, and load that js.  I just have to be cautious about data types crossing boundaries; but it works great.

Now, I did do a test of isar on web (without any web workers), and a `.where().findAll()` of 100,000 entries took 31 minutes.  So, I can't use isar for now, since I need support for 10 million+ entries.

But, support for web workers is definitely an option and works great.  Take a look at [Squadron](https://pub.dev/packages/squadron)

**Comment by leisim** [comment]
Unfortunately, IndexedDB is quite slow for huge amounts of data. Especially on Chrome. Not much we can do to improve it unfortunately. IndexedDB is the only real cross platform database backend on web...

**Comment by leisim** [comment]
squadron looks really cool! I need to check it out in detail

**Comment by Fraa-124** [comment]
Hello there,  yes, Squadron is awesome. 
For reference, In the repository of Hive package they are discussing a solution about how to run Hive on web workers https://github.com/hivedb/hive/issues/939

**Comment by leisim** [comment]
Unfortunately I don't expect big performance improvements because Isar is not the bottleneck.

IndexedDB is really slow for > 10-50k entries and web workers don't help much.

**Comment by d-markey** [comment]
Hello, 

I believe Isar can be made to run in Web Workers, with little effort. Main problem is in `web/open.dart` where access to the DOM is assumed, as well as in the `isar-web` library where it's using `window` instead of `self`. I have tried with this (+ the attached fixed library that I have placed in the `test` folder). But then it crashed in `isar_impl.dart` because of the reference to `DomException` (it comes from `dart:ui`). I haven't looked further. I shall create a fork and post my changes but there aren't enough hours in one day!

```dart
Future<void> initializeIsarWebFromWindow() async {
  ScriptElement script = ScriptElement();
  script.type = 'text/javascript';
  script.src = 'https://unpkg.com/isar@$isarWebVersion/dist/index.js';
  script.async = true;
  assert(document.head != null);
  document.head!.append(script);
  await script.onLoad.first.timeout(Duration(seconds: 30), onTimeout: () {
    throw IsarError('Failed to load Isar');
  });
}

Future initializeIsarWebFromWorker() async {
  try {
    // >>> testing
    DedicatedWorkerGlobalScope.instance.postMessage('Loading Isar-Web...');
    final script = await HttpRequest.getString('isar-web-fixed.js');
    DedicatedWorkerGlobalScope.instance.postMessage('Isar-Web found, length = ${script.length}');
    WorkerGlobalScope.instance.importScripts('isar-web-fixed.js');
    DedicatedWorkerGlobalScope.instance.postMessage('Isar-Web is ready!');
    // <<< testing
    // >>> intended final version: 
    // WorkerGlobalScope.instance.importScripts('https://unpkg.com/isar@$isarWebVersion/dist/index.js');
  } catch (ex) {
    DedicatedWorkerGlobalScope.instance.postMessage('failed to load Isar-Web');
    throw IsarError('Failed to load Isar-Web');
  }
}

var _loaded = false;
Future<void> initializeIsarWeb() async {
  if (_loaded) return;
  _loaded = true;

  try {
    await initializeIsarWebFromWindow();
  } catch (ex) {
    await initializeIsarWebFromWorker();
  }
}
```

[isar-web-fixed.zip](https://github.com/isar/isar/files/8595330/isar-web-fixed.zip)

**Comment by jpolstre** [comment]
> Correct, it works in isolates. Web worker is what I'm looking for. I'm using a package called Squadron 3.3 which does support web workers and it's working great. I am able to run true multi-platform with isolates on native platforms and web workers on web (with a common interface) and it works great. The part of the code that is the threaded code, I just have to `dart compile js ...`, and load that js. I just have to be cautious about data types crossing boundaries; but it works great.
> 
> Now, I did do a test of isar on web (without any web workers), and a `.where().findAll()` of 100,000 entries took 31 minutes. So, I can't use isar for now, since I need support for 10 million+ entries.
> 
> But, support for web workers is definitely an option and works great. Take a look at [Squadron](https://pub.dev/packages/squadron)

Hello, Did you also test with that amount of data in native isolation? How long did it take? I use hive with a lot of data in native isolation and wanted to know that Isar is faster than Hive.
I also have memory leak issues with Hive as I have to leave the box open in the isolate to improve response speed.
Thank you.

**Comment by leisim** [comment]
> How long did it take? I use hive with a lot of data in native isolation and wanted to know that Isar is faster than Hive.
I also have memory leak issues with Hive as I have to leave the box open in the isolate to improve response speed.

Native Isar is MUCH faster than IndexedDB and Hive. Querying 100k entries should be well below a second (using an index probably around 50ms)

Hive does not have memory leaks it just can't share memory across isolates. Isar does not have this limitation.

**Comment by Fraa-124** [comment]
> Unfortunately I don't expect big performance improvements because Isar is not the bottleneck.
> 
> IndexedDB is really slow for > 10-50k entries and web workers don't help much.

The main goal of running Isar in Isolate/webworker for me isn't performance, but release main thread from getting stuck loading heavy tasks. I don't mind if it takes more seconds to process If I achieve a stable fps rate.

**Comment by leisim** [comment]
> The main goal of running Isar in Isolate/webworker for me isn't performance, but release main thread from getting stuck loading heavy tasks.

Did you experience that using Isar? Indexeddb runs in a background thread and Isar itself is extremely lightweight. I'd have to see an example where that actually happens

**Comment by Fraa-124** [comment]
> Did you experience that using Isar? Indexeddb runs in a background thread and Isar itself is extremely lightweight. I'd have to see an example where that actually happens.
I haven't tested it yet, but @martin-robert-fink did, <<Now, I did do a test of isar on web (without any web workers), and a .where().findAll() of 100,000 entries took 31 minutes. So, I can't use isar for now, since I need support for 10 million+ entries.>>

I known fetching 100k items and retrieving is a lot maybe, but my use case is to retrieve those 100k items in webworker and only give the main thread some of those items, already processed.


> And Isar already supports background Isolates 
But not in webworkers, maybe @d-markey gave some ideas in his previous comment.

**Comment by leisim** [comment]
> I known fetching 100k items and retrieving is a lot maybe, but my use case is to retrieve those 100k items in webworker and only give the main thread some of those items, already processed.

Like I said, Isar is not the bottleneck here, IndexedDB is. And to my knowledge it doesn't get any faster if you access it from a web worker. If you have different information or maybe even a benchmark, I'll work on web worker support. But until then I just see no point in implementing it 🤷🏼‍♂️

**Comment by d-markey** [comment]
Hello,

actually it's a tad more complicated. Dart libraries also reference the "window" object eg. in https://github.com/dart-lang/sdk/blob/main/sdk/lib/html/html_common/device.dart and that's not available in Web workers. It seems the scope of changes goes beyond just isar and isar-web!

**Comment by leisim** [comment]
I'm going to close this for now since it won't benefit the performance. We might be able to revisit this when Dart supports WASM.
