### ISSUE TITLE
no openIsar on dart project

### ISSUE THREAD

**Issue by erf** [isar/isar#33]
**Steps to Reproduce**

I tried `isar` in a dart project (not Flutter), so i only included the `isar` dep and noticed that `openIsar` was not defined.

**Code sample**
```
import 'package:isar/isar.dart';

void main(List<String> args) async {
  // openIsar is not defined
  final isar = await openIsar();
}
```

**Version**
 - Platform: Mac
 - Flutter version: 2.0.2
 - Isar version: 0.1.0
 - Isar Generator version: NA

**Comment by leisim** [comment]
@erf It should be generated by the `isar_generator`. You then need to import it from `isar.g.dart`

**Comment by erf** [comment]
Ah, ok. So `isar` can't store primitive Dart objects?

Btw i noticed a dependency conflict with `Hive`.

```
Resolving dependencies... (1.8s)
Because no versions of hive match >2.0.0 <3.0.0 and hive 2.0.0 depends on crypto ^3.0.0, hive ^2.0.0 requires
  crypto ^3.0.0.
And because every version of isar_generator depends on dartx ^0.5.0 which depends on crypto ^2.1.0, hive ^2.0.0
  is incompatible with isar_generator.
So, because redis_vs_hive depends on both hive ^2.0.0 and isar_generator any, version solving failed.
~/
```

**Comment by erf** [comment]
Ok thanks. I will test this later and close. Intuitively it seem a bit odd to me that such an important Api comes from generated code, but i will look into this later :)

**Comment by leisim** [comment]
The reason is that it "magically" initializes all your collections without any configuration needed ;)

**Comment by erf** [comment]
I tried to generate the code now. My code resided in a `bin` folder. I had to create it's own file and move it to a `lib` folder for it to generate. Also I had to add `part '../post.g.dart';` like with `json_serializable`. Maybe the instructions could be clearer here. Also the generated file is `null-safe` even though my project is not.

**Comment by leisim** [comment]
Thanks I'll work on those issues :)

**Comment by leisim** [comment]
The newest version should generate files in the bin directory.
