### ISSUE TITLE
Casting Isar Links does not work

### ISSUE THREAD

**Issue by richard457** [isar/isar#332]
``` await linda.teachers.load(); ```

can't do
``` List<Teachers> teachers = linda.teachers as List<Teachers>; ```
How Can I achieve the above?

**Comment by flocbit** [comment]
@richard457 have you tried using `linda.teachers.toList()` or `linda.teachers.map(...)`? I think you can't cast Iterable to List.

**Comment by lodisy** [comment]
```dart
linda.teachers.toList()

```
should work. But would you be able to load the links?

**Comment by leisim** [comment]
Yes that's correct. `IsarList<Teacher> extends Set<teacher>` because it has no order.

`yourLink.toList()` should work 👍
