### ISSUE TITLE
Isar Web - Can't find variable: BroadcastChannel

### ISSUE THREAD

**Issue by rac146** [isar/isar#341]
Took awhile to figure this one out, but it seems Isar Web is taking advantage of BroadcastChannel to do its magic. And for the most part that works beautifully. However, our friends at Apple literally just started supporting BroadcastChannel as of iOS 15.4. (I believe this came out last month.) So unfortunately if you're on any other version of iOS, Isar on the web will fail with:

`ReferenceError: Can't find variable: BroadcastChannel`

I haven't gone into the Isar source to look at it further, but from a high level, is it possible to use something else besides BroadcastChannel for Isar web as a fallback for iOS?

https://caniuse.com/broadcastchannel

**Version**
 - Platform: Web
 - Flutter version: 2.1.4
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

**Comment by leisim** [comment]
Yes, we can use polyfill. I'll fix it in a coming release

**Comment by rac146** [comment]
Awesome, thanks! I did try to add a simple polyfill to the compiled JS (https://gist.github.com/sechel/e6aff22d9e56df02c5bd09c4afc516e6), but it still errors out further into the code. 

You might need to integrate an implementation like this:
https://github.com/pubkey/broadcast-channel

**Comment by leisim** [comment]
Fixed in latest release 👍
