### ISSUE TITLE
Should Isar switch to LMDB

### ISSUE THREAD

**Issue by leisim** [isar/isar#342]
As you probably know, Isar depends on libmdbx, a fork of LMDB.

It is more actively developed, more feature rich and a little bit faster but developed in Russia.

GitHub removed the author and repository from its platform. It is now hosted on a Russian alternative.

To be clear: The license of the project is not the problem and we can continue using it without issues. The question is: do we want to.
The attitude of the author is cause of concern: https://github.com/isar/isar/issues/187#issuecomment-1102835419

The alternative is switching to LMDB. Both databases are completely incompatible and apps in production would need to take care of data migration.

Please use this issue to state your opinion. We will follow the majority.

**Comment by spatialbits** [comment]
Thought I should add, as mentioned by @blaugold [here](https://github.com/isar/isar/issues/187#issuecomment-1102874986) there is also the option to fork and bring mdbx but that obviously raises the question of who will maintaining it.

All things considered equal, I'd be in favour of a switch to lmdb.

Some considerations I can think of are: 

1. Effort/time to implement the switch,  
  - @leisim do you have a rough idea of when the change could be released? Would it likely be like a multi-month timeframe?
  - Is it worth delaying development on other Isar issues for this change.
2. Who has the availability (and knowledge) to contribute - @leisim and/or other developer.
  - I'd love to be able to contribute but have no useful experience with Rust or C, so getting up to speed will be slow.   
3. Migration strategies for those who have already rolled production builds.
  - Perhaps some idea-sharing here as it's not entirely clear to me how a migration would be possible once mdbx is dropped. Using the dump to json as a go-between seems like it would be a starting point.

I'd be in favour of switching to lmdb provided the effort is within reason; hope for a migration path would be also ideal.

**Comment by richard457** [comment]
I don't see a need to switch to other alternatives such as LMDB, because first of all the fact that the sources code is now living in Russia is not a concern at all as the same concern can be with source code hosted in the united states, the key factor here is if the package is still actively maintained,  so libmdbx is a good candidate here, also it is important to avoid political fuss when building anything, the valid suggestion is to fork libmdbx and keep it in sync with the upstream this should be there in the first place even if we are using GitHub. so unless  you provide meaningful full valid concerns such as:

1. The libmdbx is no longer maintained here https://gitflic.ru/project/erthink/libmdbx 
2. The other valid factors other than political and bias about Russia

**Comment by richard457** [comment]
> As you probably know, Isar depends on libmdbx, a fork of LMDB.
> 
> It is more actively developed, more feature rich and a little bit faster but developed in Russia.
> 
> GitHub removed the author and repository from its platform. It is now hosted on a Russian alternative.
> 
> To be clear: The license of the project is not the problem and we can continue using it without issues. The question is: do we want to. The attitude of the author is cause of concern: [#187 (comment)](https://github.com/isar/isar/issues/187#issuecomment-1102835419)
> 
> The alternative is switching to LMDB. Both databases are completely incompatible and apps in production would need to take care of data migration.
> 
> Please use this issue to state your opinion. We will follow the majority.

Why you don't like his attitude yet GIHUB is the one removed from the author? I think we need to be clear here who removed who, by having a biass can read to taking wrong decision.

**Comment by leisim** [comment]
> do you have a rough idea of when the change could be released? Would it likely be like a multi-month timeframe?

Not at all. The APIs are very similar and I could perform a switch in a single weekend.

> Migration strategies for those who have already rolled production builds.

That is very difficult and I have no real idea how I can help there.

> sources code is now living in Russia is not a concern at all as the same concern can be with source code hosted in the united states

I very much disagree with this statement but we could mirror the repository so it is not the main problem.

> Why you don't like his attitude yet GIHUB is the one removed from the author

You surely know there are strong sanctions in place against Russian organisations. I don't have insight whether it is justified in this case but he works for a Russian cybersecurity company after all. The statement to continue development in Russian is something I find very difficult.

Personally I believe using libmdbx is the better option from a technical standpoint.

**Comment by richard457** [comment]
> > do you have a rough idea of when the change could be released? Would it likely be like a multi-month timeframe?
> 
> Not at all. The APIs are very similar and I could perform a switch in a single weekend.
> 
> > Migration strategies for those who have already rolled production builds.
> 
> That is very difficult and I have no real idea how I can help there.
> 
> > sources code is now living in Russia is not a concern at all as the same concern can be with source code hosted in the united states
> 
> I very much disagree with this statement but we could mirror the repository so it is not the main problem.
> 
> > Why you don't like his attitude yet GIHUB is the one removed from the author
> 
> You surely know there are strong sanctions in place against Russian organisations. I don't have insight whether it is justified in this case but he works for a Russian cybersecurity company after all. The statement to continue development in Russian is something I find very difficult.
> 
> Personally I believe using libmdbx is the better option from a technical standpoint.

Then in this case forking the repo is the best option, this will not break the existing apps on production build and will make everyone happy.

**Comment by richard457** [comment]
I support mirroring the repo instead of totally wasting time and energy moving to other new kid in town, there is more work that need to be addressed.

**Comment by zexross** [comment]
I am just curious and interested in knowing myself. I tried going through the comment the author of mdbx placed thrice. All I was able to understand was that since his account was removed. He just mentioned how he will be taking his work ahead I believe. The only issue I was able to see was about the migration of documentation (for which he mentioned the provision of machine translation).


I am not sure if the different platforms will generate issues but I just can't think given the actions that happened with author and options he had. What else he can have done or why his current plan of action is an issue.

I will be happy to understand things better here!

---

> You surely know there are strong sanctions in place against Russian organisations. I don't have insight whether it is justified in this case but he works for a Russian cybersecurity company after all. The statement to continue development in Russian is something I find very difficult.
Speaking about the first two sentences. I don't have anything to add to the first two sentences. Although, I am not an expert here. I at least can think that it might be a concern. The last sentence is what I am not sure. I don't understand his situation clearly perhaps. But I think is still willing to give the access and then machine translation (I believe that's Russian to English. If I am not wrong)

Again I am not saying things right or wrong. I am just trying to understand things here. Ultimately, whatever happens, is @leisim  and collective decision from others.

**Comment by richard457** [comment]
> I am just curious and interested in knowing myself. I tried going through the comment the author of mdbx placed thrice. All I was able to understand was that since his account was removed. He just mentioned how he will be taking his work ahead I believe. The only issue I was able to see was about the migration of documentation (for which he mentioned the provision of machine translation).
> 
> I am not sure if the different platforms will generate issues but I just can't think given the actions that happened with the author and the options he had. What else he can have done or why his current plan of action is an issue.
> 
> I will be happy to understand things better here!
> 
> > You surely know there are strong sanctions in place against Russian organisations. I don't have insight whether it is justified in this case but he works for a Russian cybersecurity company after all. The statement to continue development in Russian is something I find very difficult.
> 
> Speaking about the first two sentences. I don't have anything to add to the first two sentences. Although, I am not an expert here. I at least can think that it might be a concern. The last sentence is what I am not sure about. I don't understand his situation clearly perhaps. But I think is still willing to give the access and then machine translation (I believe that's Russian to English. If I am not wrong)
> 
> Again I am not saying things right or wrong. I am just trying to understand things here. Ultimately, whatever happens, is @leisim and collective decision from others.

Can't agree more, what option did he have?? what a guarantee do we have by switching to another author that they too will not be removed by GITHUB?

**Comment by spatialbits** [comment]
LMDB isn't a one-man show. It's been around for a very long time now and is not at risk of disappearing overnight. I get that it isn't as interesting or performant as mdbx, which obviously needs to be considered.

What does it mean for the future viability of mdbx if the codebase and docs are entirely in Russian and hosted on a Russian-language site? 

While there will certainly be pain for migrating production apps, these are still early-ish days for Isar. It could be an early pivot for what might be long-term stability.

**Comment by richard457** [comment]
> LMDB isn't a one-man show. It's been around for a very long time now and is not at risk of disappearing overnight. I get that it isn't as interesting or performant as mdbx, which obviously needs to be considered.
> 
> What does it mean for the future viability of mdbx if the codebase and docs are entirely in Russian and hosted on a Russian-language site?
> 
> While there will certainly be pain for migrating production apps, these are still early-ish days for Isar. It could be an early pivot for what might be long-term stability.

I understand your concern, but I am not sure if it is me but I am hearing fear of something with no proof presented. the suggestion of mirroring is okay for the situation and we can keep the docs in whatever language to me that is easy than using something that is going to break everyone.

**Comment by richard457** [comment]
> > LMDB isn't a one-man show. It's been around for a very long time now and is not at risk of disappearing overnight. I get that it isn't as interesting or performant as mdbx, which obviously needs to be considered.
> > What does it mean for the future viability of mdbx if the codebase and docs are entirely in Russian and hosted on a Russian-language site?
> > While there will certainly be pain for migrating production apps, these are still early-ish days for Isar. It could be an early pivot for what might be long-term stability.
> 
> I understand your concern, but I am not sure if it is me but I am hearing fear of something with no proof presented. the suggestion of mirroring is okay for the situation and we can keep the docs in whatever language to me that is easy than using something that is going to break every one.

for example is the license allowing us to fork the repo and bring it back to GITHUB? Then this way we can keep the repo updated according the Russian update version.

**Comment by FredJul** [comment]
LMDB does not seems to be really maintained anymore and libmdbx seems to have major advantages over lmdb (seems 10-20% faster if we trust the author), so I would says it's maybe better to stay to libmdbx and see how it really evolves in few months. In worse case forking libmdbx to fix major issues only is certainly doable.

**Comment by leisim** [comment]
The biggest advantage of mdvx imo is that it can also shrink the file size if you remove entries. LMDB is ever growing and can only reuse the space at a later time.

**Comment by flocbit** [comment]
Even though I can't tell much about the technical differences between mdbx and LMDB, I'd go for a switch to LMDB. 

Here is why:

LMDB is backed by a company/team of 19 people (as far as we can trust the company's LinkedIn page) whereas mdbx is  maintained by only one developer. The fact he is Russian or living in Russia does not concern me too much. The problem I'd rather focus on and find highly critical is that he lost access to GitHub's community AND continues development in Russian. This will most likely reduce the number of people (interested in) contributing which significantly increases the risk of abandonment. All the advantages of mdbx compared to LMDB will be useless the second he abandons the project.

If Isar wouldn't be a database and mdbx it's most important part, I wouldn't make a huge fuss about stability.

Since databases play an integral part in most apps and data migration is a pain in the *** I would strongly vote for switching to LMDB, no matter the cost.

Isar's (long-term) future will likely depend on it.

**Comment by richard457** [comment]
> Even though I can't tell much about the technical differences between mdbx and LMDB, I'd go for a switch to LMDB.
> 
> Here is why:
> 
> LMDB is backed by a company/team of 19 people (as far as we can trust the company's LinkedIn page) whereas mdbx is maintained by only one developer. The fact he is Russian or living in Russia does not concern me too much. The problem I'd rather focus on and find highly critical is that he lost access to GitHub's community AND continues development in Russian. This will most likely reduce the number of people (interested in) contributing which significantly increases the risk of abandonment. All the advantages of mdbx compared to LMDB will be useless the second he abandons the project.
> 
> If Isar wouldn't be a database and mdbx it's most important part, I wouldn't make a huge fuss about stability.
> 
> Since databases play an integral part in most apps and data migration is a pain in the *** I would strongly vote for switching to LMDB, no matter the cost.
> 
> Isar's (long-term) future will likely depend on it.

We don't know if the community will follow him, obviously, if someone depends on it will consider forking the repo and can put repo anywhere he want.

**Comment by richard457** [comment]
> > Even though I can't tell much about the technical differences between mdbx and LMDB, I'd go for a switch to LMDB.
> > Here is why:
> > LMDB is backed by a company/team of 19 people (as far as we can trust the company's LinkedIn page) whereas mdbx is maintained by only one developer. The fact he is Russian or living in Russia does not concern me too much. The problem I'd rather focus on and find highly critical is that he lost access to GitHub's community AND continues development in Russian. This will most likely reduce the number of people (interested in) contributing which significantly increases the risk of abandonment. All the advantages of mdbx compared to LMDB will be useless the second he abandons the project.
> > If Isar wouldn't be a database and mdbx it's most important part, I wouldn't make a huge fuss about stability.
> > Since databases play an integral part in most apps and data migration is a pain in the *** I would strongly vote for switching to LMDB, no matter the cost.
> > Isar's (long-term) future will likely depend on it.
> 
> We don't know if the community will follow him, obviously, if someone depends on it will consider forking the repo and can put repo anywhere he want.

These are really hard choices to be honest but for this type of choice I consider giving enough time to have all options

**Comment by richard457** [comment]
Discovered libmdbx telegram https://t.me/libmdbx and have been asking questions, I think it is worth joining and ask questions
![Screenshot 2022-04-20 222357](https://user-images.githubusercontent.com/8529700/164316578-01f39671-b5fe-4aa9-8e30-1803fee8313e.png)

**Comment by richard457** [comment]
This is their response when I asked about the timeline.
Sure before v0.11.7 (scheduled for 2022-04-22)
just git revert befb8dd2033a0aa4ecc300935802d7de134038fa if you're in a hurry.

**Comment by richard457** [comment]
So, guys, I think we need to stick on libmdbx and for any concern we can always join their telegram and ask question, I am happy that the 32 bit issue is being resolved which was the main concern for many and for us our app is almost useless without support of 32 bit and now switching back to something else might come with other unexpected issue.

**Comment by richard457** [comment]
Online docs restored here https://libmdbx.website.yandexcloud.net/

**Comment by ignertic** [comment]
> This is their response when I asked about the timeline. Sure before v0.11.7 (scheduled for 2022-04-22) just git revert befb8dd2033a0aa4ecc300935802d7de134038fa if you're in a hurry.

The commit is a workaround for supporting  x86 devices in the meantime ? Also curious what issues could arise from other parts of the application

**Comment by richard457** [comment]
> (scheduled for 2022-04-22)

Don't know, but as they say, the release is scheduled for 2022-04-22, from my understanding the package as for now has no other known issue except this one, we can always fill the issue report and it can always be fixed.

**Comment by richard457** [comment]
> Even though I can't tell much about the technical differences between mdbx and LMDB, I'd go for a switch to LMDB.
> 
> Here is why:
> 
> LMDB is backed by a company/team of 19 people (as far as we can trust the company's LinkedIn page) whereas mdbx is maintained by only one developer. The fact he is Russian or living in Russia does not concern me too much. The problem I'd rather focus on and find highly critical is that he lost access to GitHub's community AND continues development in Russian. This will most likely reduce the number of people (interested in) contributing which significantly increases the risk of abandonment. All the advantages of mdbx compared to LMDB will be useless the second he abandons the project.
> 
> If Isar wouldn't be a database and mdbx it's most important part, I wouldn't make a huge fuss about stability.
> 
> Since databases play an integral part in most apps and data migration is a pain in the *** I would strongly vote for switching to LMDB, no matter the cost.
> 
> Isar's (long-term) future will likely depend on it.

I gave this a more thought, this is my thinking on this, we know how performant libmdbx is, and the fact that is one guy who made incredible work is also another point to not ignore, I can't assume that 19 team backing LMDB is a thing to back the decision as we are not even sure. again given to my above message, libmdbx has a community on telegram and they are okay to answer questions, I suggest we don't assume we just ask because nothing good comes from assumption.

**Comment by richard457** [comment]
> https://libmdbx.website.yandexcloud.net/

https://libmdbx.website.yandexcloud.net/

**Comment by mikekosulin** [comment]
Seems like the author fixed that issue
https://gitflic.ru/project/erthink/libmdbx/issue/2

**Comment by richard457** [comment]
> Seems like the author fixed that issue https://gitflic.ru/project/erthink/libmdbx/issue/2

yes, https://gitflic.ru/project/erthink/libmdbx/release/90ec9985-cd60-4d9a-8c98-8417506fd26d @leisim maybe can help us with 32-bit issue.

**Comment by leisim** [comment]
@richard457 no, I already updated libmdbx and a new release is ready very soon (probably today). I just need to implement the new link features (query, filter, sort) for web.

Right after the release I'll start working on contributor docs. I think it is crucial that isar becomes a multi-dev project 🙂

**Comment by FredJul** [comment]
@leisim I'm very happy to hear that a new version is coming. I don't know if you already planned to do it but could I ask you to look at the PR I have created? I think it would be great to merge them before the release (unless there is issues with them of course).

**Comment by leisim** [comment]
Done, @FredJul! Thanks a lot 🥳

**Comment by leisim** [comment]
We should've created a poll but I feel like the majority wants to continue using libmdbx. I compared the upvotes and downvotes of all the comments. Please downvote here if you disagree.

Here is a mirror of libmdxb: https://github.com/isar/libmdbx

**Comment by spatialbits** [comment]
Thanks @leisim for opening the issue for discussion. Your efforts are really appreciated.

**Comment by leisim** [comment]
Hey, just writing here because I promised contributing docs. [Here you go](https://github.com/isar/isar/blob/main/CONTRIBUTING.md) 🙂

Please also [join](https://t.me/isardb) the new telegram channel to discuss work on Isar.
