### ISSUE TITLE
Nested objects without IsarLinks

### ISSUE THREAD

**Issue by MaddinMade** [isar/isar#348]
Sometimes you want to use simple nested objects that are not natively supported by Isar. Currently you would have to store them in a separate collection and use IsarLinks. But this is quite cumbersome if you don't want to apply queries to them.

My suggestion would be to allow objects in individual columns in addition to collections (with a separate annotation, of course). Currently I use my own TypeConverter for this case, which simply uses fromJson and toJson to be able to store an object as a string. You could of course solve the problem by creating a collection internally, but only accessible to users via the parent collection. This would save the user from using the IsarLinks, which cause some overhead if you don't want to query over everything.

But of course I also understand if this approach doesn't fit with the concept of Isar that everything is a collection and can be searched for.

**Comment by leisim** [comment]
This is something I really want to support but it's not trivial. Also I want to make sure that we don't rush this feature and later discover that queries would be nice but impossible to implement.

Same discussion here: https://github.com/isar/isar/discussions/343

**Comment by leisim** [comment]
And how will schema migrations work. Which changes to nested objects should be allowed?

**Comment by MaddinMade** [comment]
If Collections were used in the background, I guess the same migrations would be allowed as to all Collections. Unless I am misunderstanding something.

**Comment by MaddinMade** [comment]
> This is something I really want to support but it's not trivial. Also I want to make sure that we don't rush this feature and later discover that queries would be nice but impossible to implement.
> 
> Same discussion here: https://github.com/isar/isar/discussions/343

Ah sorry. I had not seen the discussion. Of course I understand that this is not a trivial feature. It would actually have to be implemented with collections in the background to enable queries after all. But of course it is not an urgent feature, because there are workarounds and you can still use IsarLinks until then.
Thanks for your quick answers.

**Comment by leisim** [comment]
I really like this feature request because I'm actually missing it myself in some projects. Already working on a solution 😂 I'll use the opportunity to make the binary format more space efficient

**Comment by leisim** [comment]
This is implemented in `3.0.0-dev.9`
