### ISSUE TITLE
Following Quickstart - get error 

### ISSUE THREAD

**Issue by davoutuk** [isar/isar#351]
I'm experimenting with your Isar product.    Whenever I try to save an object I get the following error...

I/flutter ( 8523): Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found
E/flutter ( 8523): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
E/flutter ( 8523): #0      initializeIsarCore (package:isar/src/native/isar_core.dart:55:5)
E/flutter ( 8523): #1      openIsar (package:isar/src/native/open.dart:52:3)
E/flutter ( 8523): #2      _IsarNative.open (package:isar/src/native/isar_native.dart:90:12)
E/flutter ( 8523): #3      Isar.open (package:isar/src/isar.dart:82:23)
E/flutter ( 8523): #4      RulesRepositoryIsar.save (package:gin_rummy_scorecard/repository/isar/rules_repository_isar.dart:33:31)

**Steps to Reproduce**
I have followed the steps outlined in your Quick start web page.  
Note:  are these steps are different to those included in the sample app?

**Code sample**

    final Directory aDir = await getApplicationDocumentsDirectory();
    final anIsar = await Isar.open(
      schemas: [DefaultRulesIsarSchema],
      directory: aDir.path
    );
    DefaultRulesIsar aNew = RulesUtil.toIsar(aRules);
    return await anIsar.writeTxn( (isar) async {
      return await isar.defaultRulesIsars.put(aNew);
    });

**Version**
 - Platform: Android Emulator Pixel 3A API_30:5554  (x86)

ame: Pixel_3a_API_30 CPU/ABI: Google Play Intel Atom (x86) Path: C:\Users\Ian\.android\avd\Pixel_3a_API_30.avd Target: google_apis_playstore [Google Play] (API level 30) Skin: 1080x2220 SD Card: 512 MB fastboot.chosenSnapshotFile: runtime.network.speed: full hw.accelerometer: yes hw.device.name: pixel_3a hw.lcd.width: 1080 hw.initialOrientation: Portrait image.androidVersion.api: 30 tag.id: google_apis_playstore hw.mainKeys: no hw.camera.front: emulated avd.ini.displayname: Pixel 3a API 30 hw.gpu.mode: auto hw.ramSize: 1536 PlayStore.enabled: true fastboot.forceColdBoot: no hw.cpu.ncore: 4 hw.keyboard: yes hw.sensors.proximity: yes hw.dPad: no hw.lcd.height: 2220 vm.heapSize: 256 skin.dynamic: yes hw.device.manufacturer: Google hw.gps: yes skin.path.backup: _no_skin hw.audioInput: yes image.sysdir.1: system-images\android-30\google_apis_playstore\x86\ showDeviceFrame: no hw.camera.back: virtualscene AvdId: Pixel_3a_API_30 hw.lcd.density: 440 hw.arc: false hw.device.hash2: MD5:0e6953ebf01bdc6b33a2f54746629c50 fastboot.forceChosenSnapshotBoot: no fastboot.forceFastBoot: yes hw.trackBall: no hw.battery: yes hw.sdCard: yes tag.display: Google Play runtime.network.latency: none disk.dataPartition.size: 6G hw.sensors.orientation: yes avd.ini.encoding: UTF-8 hw.gpu.enabled: yes

 - Flutter version: 
 - PS D:\Ian\Documents\github\gin_rummy_scorecard> flutter --version
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c860cba910 (4 weeks ago) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

 - Isar version: 2.4.0
 - Isar Generator version: 2.4.0

**Comment by davoutuk** [comment]
Debugging the problem the error occurs inside 'isar_core.dart'

Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found

**Comment by davoutuk** [comment]
I have just tried deploying the app to another emulator  

![image](https://user-images.githubusercontent.com/25985256/165079566-ad025b25-2043-469d-83d0-ba5f89b50720.png)

... and I get the same error

04-25 12:13:38.357     0     0 I         : Linux version 5.4.86-android11-2-00006-gae78026f427c-ab7595864 (build-user@build-host) (Android (7284624, based on r416183b) clang version 12.0.5 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee), LLD 12.0.5 (/buildbot/src/android/llvm-toolchain/out/llvm-project/lld c935d99d7cf2016289302412d708641d52d2f7ee)) #1 SMP PREEMPT Thu Jul 29 20:54:47 UTC 2021
04-25 12:13:38.357     0     0 I Command line: no_timer_check clocksource=pit console=0 cma=294M@0-4G ndns=4 mac80211_hwsim.channels=2 loop.max_part=7 ramoops.mem_address=0xff018000 ramoops.mem_size=0x10000 memmap=0x10000$0xff018000 printk.devkmsg=on qemu=1 androidboot.hardware=ranchu androidboot.serialno=EMULATOR31X2X10X0 qemu.gles=1 qemu.settings.system.screen_off_timeout=2147483647 qemu.encrypt=1 qemu.vsync=60 qemu.gltransport=pipe qemu.gltransport.drawFlushInterval=800 qemu.opengles.version=196608 qemu.uirenderer=skiagl qemu.dalvik.vm.heapsize=512m qemu.camera_protocol_ver=1 qemu.camera_hq_edge_processing=0 androidboot.vbmeta.size=6144 androidboot.vbmeta.hash_alg=sha256 androidboot.vbmeta.digest=2097f1f053b257c338a9e0d15480bdefe7d25463fc4d344c76802c3826e03db0 androidboot.boot_devices=pci0000:00/0000:00:03.0 qemu.wifi=1 qemu.hwcodec.avcdec=2 qemu.hwcodec.vpxdec=2 android.qemud=1 qemu.avd_name=Pixel_5_API_30 ndns=4 mac80211_hwsim.radios=0
04-25 12:13:38.357     0     0 I x86/fpu : x87 FPU will use FXSAVE

**Comment by leisim** [comment]
Please use an x64 emulator. This is a known problem for x86 emulators and will be fixed very soon #187
