### ISSUE TITLE
it cannot clear the isarlinks

### ISSUE THREAD

**Issue by git-maven** [isar/isar#359]
**Steps to Reproduce**
Please describe exactly how to reproduce the problem you are running into.

`ChatMessageEntity chatMessageEntity = ChatMessageEntity();
      chatMessageEntity.gid = gid;
      chatMessageEntity.msgLinks.loadSync();
      chatMessageEntity.msgLinks.clear();
      chatMessageEntity.msgLinks.addAll(_cacheMessageList);
      isar.writeTxn((isar) async {
        await isar.chatMessageEntitys.put(
            chatMessageEntity,
            replaceOnConflict: true,
            saveLinks: true
        );
      });`
```
Provide a few simple lines of code to show your problem.
```
i want to update the isarlinks with a new list, how can i do？

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 2.10.5]
 - Isar version: [e.g. 2.4.0]
 - Isar Generator version: [e.g. 2.4.0]

**Comment by git-maven** [comment]
i also use update, but i wonnt use my new list, i will add it to old data

**Comment by leisim** [comment]
This is fixed in the latest release :+1:
