### ISSUE TITLE
Dynamic location of the generated file "isar.g.dart"

### ISSUE THREAD

**Issue by nnior** [isar/isar#36]
Currently when "flutter pub run build_runner build" is executed, the file `isar.g.dart` is generated in the `LIB` folder. This works fine, but when working under some architecture such as ddd, each file has to be placed within a corresponding folder to be able to respect the principles of architecture.

Currently I have manually moved the file `isar.g.dart` to the corresponding folder, for example:

From
`lib -> isar.g.dart`

To
`lib -> shared -> infrastructure -> isar -> isar.g.dart`

The problem comes when there are many Isar domains, I have to re-import all of them.

![image](https://user-images.githubusercontent.com/49848980/111669173-834bac80-87e4-11eb-9590-31be8d9e7cda.png)

The solution could be, maybe a parameter can be passed when generating the file `isar.g.dart`, or maybe put the configuration in the file 'pubspect.yaml' and be able to configure some parameters, for example:

```yml
...
...
isar:
  path: shared/infrastructure/isar/ #default /
...
...
```

I come from Hive, and the truth is that I am very happy with all the improvements that Isar brings :grinning:

Happy Codding :yellow_heart:

**Comment by om-ha** [comment]
Related: https://github.com/Dart-Code/Dart-Code/issues/548#issuecomment-932830758

**Comment by om-ha** [comment]
I think the changes may need to be here?

1. https://github.com/isar/isar/blob/d7dbb532ece0e81255749714e2ddfce11a2c8779/packages/isar_generator/build.yaml#L21
2. https://github.com/isar/isar/blob/d7dbb532ece0e81255749714e2ddfce11a2c8779/packages/isar_generator/lib/src/code_gen/isar_code_generator.dart#L31
3. https://github.com/isar/isar/blob/d7dbb532ece0e81255749714e2ddfce11a2c8779/packages/isar_generator/lib/src/code_gen/isar_code_generator.dart#L63

**Comment by om-ha** [comment]
This could help!

https://pub.dev/packages/drtimport

**Comment by leisim** [comment]
Fixed with stable release
