### ISSUE TITLE
Should keep previous record id when put with `replaceOnConflict: true`

### ISSUE THREAD

**Issue by debuggerx01** [isar/isar#364]
**Is your feature request related to a problem? Please describe.**
When I run [this code](https://github.com/isar/isar/issues/280#issuecomment-1112718581) multiple times, the ID of the record increases.

For example, the first time, the result is `[{"id":1,"name":"Tom"},{"id":2,"name":"Jack"}]`. But when I run it again, the result is `[{"id":3,"name":"Tom"},{"id":4,"name":"Jack"}]`.

**Describe the solution you'd like**
I think the `replaceOnConflict` feature should behave the same as `SQLite's REPLACE command.

**Describe alternatives you've considered**
Query exists record's id for update, but this is too verbose.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.10.5
 - Isar version: 2.4.0

**Comment by leisim** [comment]
That's an interesting proposal. Could you give an example why this would be useful? Why do you need the id to stay the same?

**Comment by debuggerx01** [comment]
> That's an interesting proposal. Could you give an example why this would be useful? Why do you need the id to stay the same?

I think it is more intuitive to keep the id unchanged. Taking the user collection as an example, if you add a unique index to the email field, after triggering 'replaceOnConflict', the new record and the old record should represent the same user, so they should have the same id.

And, if there is another collection of orders that uses user's id as the join condition, then if the user's id changes, we'll lose those relations.

There is also a use case. If isar is used as local storage, in extreme cases, entries may be continuously updated with the same unique index field. In this case, if the id keeps increasing, it may eventually exceed the maximum value of int.

**Comment by Mihai-B** [comment]
If you keep the same ID then basically you've done an update on the record but using a different "method". The attribute does not state update on conflict but rather replace on conflict, and I think this is the way it should work.

**Comment by leisim** [comment]
I put some more though into this and unfortunately it's not possible to implement this efficiently and with good developer experience. There are too many edge cases for example when multiple indexes are violated.
