### ISSUE TITLE
When trying to open an Isar connection in Flutter Web, an error is raised

### ISSUE THREAD

**Issue by NekrodNIK** [isar/isar#373]
When trying to open an Isar connection in Flutter, an error is raised: 
```cmd
TypeError: dart.global.openIsar is not a function
    at openIsar (http://localhost:45309/packages/isar/src/web/open.dart.lib.js:554:103)
    at openIsar.next (<anonymous>)
    at http://localhost:45309/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:45309/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:45309/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:45309/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:45309/dart_sdk.js:35969:17)
    at _Future.new.[_completeWithValue] (http://localhost:45309/dart_sdk.js:35817:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:45309/dart_sdk.js:35838:35)
    at Object._microtaskLoop (http://localhost:45309/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:45309/dart_sdk.js:40714:13)
    at http://localhost:45309/dart_sdk.js:36191:9
Application finished.

```

To reproduce this error, you need to open an Isar connection using Isar.open in the flutter web application.

Sample code:

``` dart
Future<Isar> _connect() async {
    Directory? dir;

    if (!kIsWeb) {
      dir = await getApplicationSupportDirectory();
    }

    try {
      return await Isar.open(schemas: [
        UserConfigSchema,
        FlowSchema,
        MessageSchema,
        ApplicationSettingSchema
      ], directory: dir?.path);
    } on IsarError {
      return Isar.getInstance()!;
    }
}
```

Versions:
-
- Platform: Web
- Flutter: 2.10.5
- Isar: 2.5.0
- Isar Generator: 2.5.0

**Comment by richard457** [comment]
```
    Directory? dir;

    if (!kIsWeb) {
      dir = await getApplicationSupportDirectory();
    }

    try {
      return await Isar.open(schemas: [
        UserConfigSchema,
        FlowSchema,
        MessageSchema,
        ApplicationSettingSchema
      ], directory: !kIsWeb?dir?.path : ' ');
    } on IsarError {
      return Isar.getInstance()!;
    }
}
```
Try to use the above code, I think it should work

**Comment by NekrodNIK** [comment]
@richard457, the code you provided doesn't work either. The problem is not in my code, but in the Isar web code. It might have been worth giving another code example, because I pulled it out of my application's code as soon as I realized it was apparently a bug.

**Comment by NekrodNIK** [comment]
What could be the problem, @leisim? Of course, for me now it does not slow down development much, because first of all my application is focused on desktop and mobile platforms, and no problems were noticed there in their implementation of Isar.

**Comment by leisim** [comment]
Something seems to prevent Isar from loading the web library. Do you see a request for Isar web javascript?

**Comment by NekrodNIK** [comment]
![Screenshot_20220519_221004](https://user-images.githubusercontent.com/60639354/169358296-09727960-49bd-40da-84ec-a7dd52c4e17d.png)

I don't observe any Isar Web library loading errors

**Comment by leisim** [comment]
Closing in favour of #686
