### ISSUE TITLE
Membrane Crate

### ISSUE THREAD

**Issue by jwinarske** [isar/isar#374]
You should check out my colleagues crate:  https://github.com/jerel/membrane

It currently supports asynchronous green threading, zero copy, auto-generates Dart, and synchronous support will be done in the next week or so.

**Comment by leisim** [comment]
@jwinarske thag looks extremely cool! Could you quickly explain how it works?

I think zero copy is not possible on our case because the database uses mmap so the results of a query for example are only valid while the transaction is active.

**Comment by richard457** [comment]
I think this could be awesome for upcoming https://github.com/isar/isar/issues/2 I think meta programming where the drawback @leisim

**Comment by leisim** [comment]
Isar already has a very powerful custom solution for asynchronicity so I'm going to close this for now
