### ISSUE TITLE
saveLinks is not working for more than one level of depth.

### ISSUE THREAD

**Issue by fakalit** [isar/isar#376]
**Steps to Reproduce**
I'm using putAll function to initialize my db with some seed data. saveLinks flag for the function is not working as expected if the objects I'm saving have linked instances that are linked to a third object. 

I'm not sure if this is a regression, cause I could swear it was working as expected before. Although reverting to isar 2.4 didn't fix the issue, so maybe not.

**Code sample**
```
@Collection()
class A{
  late int id;
  final b= IsarLink<B>();
}

@Collection()
class B{
  late int id;
  final c= IsarLink<C>();
}

@Collection()
class C {
  late int id;
}

txn.a.putAll(aList, saveLinks: true);

```

**Version**
 - Platform: All platforms
 - Flutter version: 2.10.5
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Comment by leisim** [comment]
Unfortunately that is a necessary restriction. Otherwise there could be loops (objects linking to each other)
