### ISSUE TITLE
Support older Safari versions

### ISSUE THREAD

**Issue by chenyifan88** [isar/isar#377]
this is my code，at this time  `AppGlobal.isar.isOpen = true`
```
AppGlobal.isar.contaicts
          .filter()
          .chatUuidEqualTo(WebSocketUtility.uuid)
          .or()
          .userUuidEqualTo(WebSocketUtility.uuid)
          .findAll()
```
![截屏2022-05-13 16 15 18](https://user-images.githubusercontent.com/40348648/168252355-fc27d3c1-6c4e-4763-8747-285a3a3758c8.png)
![截屏2022-05-13 16 15 33](https://user-images.githubusercontent.com/40348648/168252317-91589e8b-1ac9-4cf6-8b2b-fa012bb1cc8c.png)
last output error `Error:TypeError: this.txn.commit is not a function. (In 'this.txn.commit()', 'this.txn.commit' is undefined)`

![截屏2022-05-13 16 18 35](https://user-images.githubusercontent.com/40348648/168252908-4c79cc41-df00-44d5-a08f-5ec43c4b2b78.png)

**Comment by chenyifan88** [comment]
定位到错误可能出现在```findAll()```method

**Comment by chenyifan88** [comment]
Locating errors may occur in```findAll()```method

**Comment by chenyifan88** [comment]
![截屏2022-05-13 17 54 20](https://user-images.githubusercontent.com/40348648/168269192-24ab606d-d73f-47a2-ad9e-012e3227f811.png)
This code goes ```catch```
But in Google Chrome it is normal and won't go ```catch```

**Comment by chenyifan88** [comment]
> 

safari version 14.1.2

**Comment by chenyifan88** [comment]
> @chenyifan88 Do you have a Safari version older than 15.0?

safari version 14.1.2

**Comment by leisim** [comment]
Yeah then I know what the issue is. The old safari misses IndexedDB transaction commit. I can try to work around it but no promise that it'll work

**Comment by chenyifan88** [comment]
> Yeah then I know what the issue is. The old safari misses IndexedDB transaction commit. I can try to work around it but no promise that it'll work

Thank you so much bro, you are so helpful to me
