### ISSUE TITLE
Compilation problem using repeat filter

### ISSUE THREAD

**Issue by Mihai-B** [isar/isar#379]
Hey,
Really nice library. I really like it. Everything goes well except for one thing that I will describe below.

**Steps to Reproduce**
So it is very simple, I just want to use a repeat filter but for some reason using repead does not compile the code. Example of code below.

I am using the code in a Transaction because I am doing multiple operations but those are no relevant for the scenario. So I only added the part with the repead filter.

**Code sample**
```
final items = DatabaseUtil().getConnection().writeTxnSync((conn) {
   return conn.houses
          .filter()
          .repeat(
            [2, 3],
            (q, int element) =>
                q.roomsEqualTo(element).or(),
          )
          .findAllSync();
 });
```

The error that I get is:
```
The method 'findAllSync' isn't defined for the type 'QueryBuilder'
```

Am I missing something here?

**Version**
 - Platform: not aplicable
 - Flutter version: 3.0.0
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Comment by leisim** [comment]
Fixed in `3.0.0-dev.2`
