### ISSUE TITLE
isar_generator is incompatible with multipule packages.

### ISSUE THREAD

**Issue by DarkHeros09** [isar/isar#38]
**Steps to Reproduce**

installing the following packages:
- dependencies:
    freezed_annotation: ^0.14.1
    isar: ^0.1.0
    isar_flutter: ^0.1.0

- dev_dependencies:
  build_runner: ^1.12.2
  freezed: ^0.14.1+1
  isar_generator: ^0.1.0
  json_serializable: ^4.0.2

**Error sample**
This is the error message i get:
```
Because every version of isar_generator depends on freezed_annotation ^0.12.0 and tdd_null_safe depends on freezed_annotation ^0.14.1, isar_generator is forbidden.
```

and if  change the dependencies version of [freezed, freezed_annotation, json_serializable] to any,
i get this error message:
```
Because every version of isar_generator depends on glob ^1.1.0 and build_runner >=1.11.2 depends on glob ^2.0.0, isar_generator is incompatible with build_runner >=1.11.2.
```

and finnaly if i change build_runner version to any, i get this error message:
```
Because every version of isar_generator depends on dartx ^0.5.0 which depends on crypto ^2.1.0, every version of isar_generator requires crypto ^2.1.0.

And because universal_io >=2.0.0 depends on crypto ^3.0.0, isar_generator is incompatible with universal_io >=2.0.0.
```

i learned about this database on hive's github issues, so i wanted to give it a try, but alas i got the same errors that hive currently has, i know that almost all the generator dependent packages are having a problem fixing the compatibility issues.. so good luck on fixing it, and i wish you all the best, the data base does look promising and i can't wait to start using it.

**Version**
 - Platform: Android,  Windows.
 - Flutter version: 2.0.3
 - Isar version: 0.1.0
 - Isar Generator version: 0.1.0

**Comment by leisim** [comment]
I'm almost finished with the new version. I will publish this weekend ✌️

**Comment by DarkHeros09** [comment]
Great, thank you all for your efforts. 🙏

**Comment by leisim** [comment]
New version released 💪
