### ISSUE TITLE
*Sync() doesn't work with web?

### ISSUE THREAD

**Issue by fredrikbaberg** [isar/isar#380]
**Steps to Reproduce**
Change from async to *Sync version of isar calls.

**Code sample**
The following works with web (tested in debug):
```
async isar?.writeTxn(
  (isar) async {
    await isar.answers.put(a, saveLinks: true);
  },
);
```
The following doesn´t work with web:
```
isar?.writeTxnSync(
  (isar) async {
    isar.answers.putSync(a, saveLinks: true);
  },
);
```

There's a lot of content in the log when this happens, but it seems to begin with:
> Error: Unsupported operation: This operation is not supported for Isar web

**Version**
 - Platform: Web
 - Flutter version: 3.0.0
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Comment by leisim** [comment]
IndexedDB does not support synchronous access so it's not possible for Isar to provide synchronous methods on web :/

**Comment by fredrikbaberg** [comment]
Thank you for a really quick answer!
Could this be mentioned in https://isar.dev/limitations.html, in case others encounters this?

I'll keep trying to figure out synchronization/async, any suggestions on resources? It's specifically the following issues I'm working on:
- Missing an entry when I read data, possibly because the write did not have time to finish (should be enough with await?).
- Create a `List<B>` from IsarLink in `List<A>`, where I have to call `load()` for each IsarLink property in `A`. I currently do this with `map()`.

**Comment by leisim** [comment]
Your first issue can be avoided with `await`. For automatically loading many links there is no great solution right now :(

I'll use this issue to remember documenting this web limitation.

**Comment by frank06** [comment]
Bummer. @leisim would something like [waitFor](https://api.dart.dev/stable/2.3.1/dart-cli/waitFor.html) or an alternative in Javascript be possible to block async calls?

(Could be slower, and discouraged, but at least it would work)

I have functions that heavily rely on `*Sync` methods won't otherwise run on web.

**Comment by Macacoazul01** [comment]
@leisim any chances of working with [greenrobot](https://github.com/greenrobot) to allow web support of  [objectbox](https://pub.dev/packages/objectbox)

**Comment by leisim** [comment]
@Macacoazul01 there are no plans to do that.
