### ISSUE TITLE
watchLazy()  How do I close this stream?

### ISSUE THREAD

**Issue by ismanong** [isar/isar#382]
Example：
```dart
@override
void initState() {
  super.initState();
  Stream<User> userChanged = isar.users.watchObject(5);
  userChanged.listen((newUser) {
    print('User changed: ${newUser?.name}');
  });
}
```

userChanged How do I close this stream?
Because there are multiple openings of a page, multiple duplicate streams will be created at the time of initialization and cannot be deleted

**Comment by leisim** [comment]
This is not an Isar specific question, it works the same for all Dart `Streams`: Listen returns a [`StreamSubscription`](https://api.dart.dev/stable/2.16.1/dart-async/StreamSubscription-class.html) that has a `cancel` method

**Comment by ismanong** [comment]
Thank you, forgive my ignorance, my basic knowledge is not good.

**Comment by leisim** [comment]
No worries at all. Please use the Github discussions or Isar Telegram channel for further questions 🙂

**Comment by ismanong** [comment]
The database you designed is fantastic, I switched from hive to isar, all very convenient, simple, smart and automated, wish you good health, as well as isar getting better and better.
