### ISSUE TITLE
DB Corrupt When Try to use 3.0.0-dev.0

### ISSUE THREAD

**Issue by anandsubbu007** [isar/isar#389]
i have some data in isar db that already exist. when i upgrade that to new version.

DB is corrupted
```
 Snapshot Error:: IsarError: DbCorrupted: Could not deserialize existing schema: missing field `replace` at line 1 column 821
```

**Comment by lodisy** [comment]
> i have some data in isar db that already exist. when i upgrade that to new version.
> 
> DB is corrupted
> ```
>  Snapshot Error:: IsarError: DbCorrupted: Could not deserialize existing schema: missing field `replace` at line 1 column 821
> ```

Delete the app. And rebuild again.

**Comment by leisim** [comment]
@anandsubbu007 Did you regenerate your files?

**Comment by anandsubbu007** [comment]
Yes

**Comment by lodisy** [comment]
> > > i have some data in isar db that already exist. when i upgrade that to new version.
> > > 
> > > DB is corrupted
> > > ```
> > >  Snapshot Error:: IsarError: DbCorrupted: Could not deserialize existing schema: missing field `replace` at line 1 column 821
> > > ```
> > 
> > Delete the app. And rebuild again.
> 
> Can't u able to use existing db?

I am still in the dev phase. The data will be fetched again from the backend. But it did remove the error.

**Comment by richard457** [comment]
> > i have some data in isar db that already exist. when i upgrade that to new version.
> > DB is corrupted
> > ```
> >  Snapshot Error:: IsarError: DbCorrupted: Could not deserialize existing schema: missing field `replace` at line 1 column 821
> > ```
> 
> Delete the app. And rebuild again.

Deleting the app is not a permanent solution for the production account.

**Comment by leisim** [comment]
It's not a big issue just a problem with the schema parsing. That's why I marked this release as dev. The final 3.0.0 won't have this problem

**Comment by simonpham** [comment]
After having this issue when upgrade from 2.4.0 to 3.0.0-dev.0, I reverted back to isar 2.5.0 and had this error:

[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: IsarError: SchemaError: Could not deserialize schema JSON

**Comment by leisim** [comment]
fixed
