### ISSUE TITLE
Build Runner type 'dynamic' cannot be assigned to 'Object'

### ISSUE THREAD

**Issue by fershous** [isar/isar#394]
**Steps to Reproduce**
Please describe exactly how to reproduce the problem you are running into.
Got my model:

import 'package:isar/isar.dart';

part 'reagent_model.g.dart';

@Collection()
class Reagent {
  @Id()
  @Name('id')
  int? uid;

  @Name('description')
  late String description;

  @Name('method')
  late String method;

  @Name('primeCost')
  late int primeCost;

  @Name('sample')
  late String sample;

  @Name('type')
  late String type;

  @Name('units')
  late String units;
}
Then I run flutter pub run build_runner build and it creates the reagent_model.g.dart
But I got The argument type 'dynamic' can't be assigned to the parameter type 'Object'

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [3.0.1]
 - Isar version: [2.5.0]
 - Isar Generator version: [2.5.0]

**Comment by RaphaelArabeyre** [comment]
It's maybe because you have `strict-casts: true` inside your `analysis_options.yaml` :
```yaml
analyzer:
  language:
    strict-casts: true
```

You can set to false ou ad `as Object` inside your `reagent_model.g.dart`:
```dart
object.id = IsarNative.jsObjectGet(jsObj as Object, 'id') as int?;
```

**Comment by leisim** [comment]
This should be fixed in the newest version.
