### ISSUE TITLE
Cannot do text search in dynamic query builder

### ISSUE THREAD

**Issue by joranmulderij** [isar/isar#395]
You cannot do text search in dynamic query builder. This is quite limiting when doing complex queries.

**Comment by frank06** [comment]
What do you mean by "text search"? All the necessary primitives are there to build the query.

What have you tried so far?

**Comment by joranmulderij** [comment]
I mean for example `isar.{dataset}.where().titleWordsAnyStartsWith(query)`

**Comment by frank06** [comment]
Like this:

```dart
    isar.{dataset}.buildQuery(
      whereClauses: [
        IndexWhereClause.between(
          indexName: 'titleWords',
          lower: [query],
          includeLower: true,
          upper: ['$query\u{FFFFF}'],
          includeUpper: true,
        )
      ],
    );
```

**Comment by leisim** [comment]
It's really not recommended to use dynamic queries unless you have a specific reason to do so.

**Comment by joranmulderij** [comment]
Well I am using a lot (6+) of potential filters that have to be turned on and off dynamically. Does it not make more sense to have a `TextSearchWhereClause` with a `TextSearchWhereClause.startWith` constructor?

**Comment by frank06** [comment]
@leisim agree, just please do not remove dynamic queries from the public API. I have specific reasons and heavily rely on them.

**Comment by leisim** [comment]
@frank0Fri won't remove the API. Specifically added it for uncommon use cases.

@joranmulderij did you check the `.optional()` method

**Comment by leisim** [comment]
Going to close this for now :)
