### ISSUE TITLE
Isar Web: IsarCollection.clear() seems not to reset autoIncrement id

### ISSUE THREAD

**Issue by psine** [isar/isar#396]
Unless I'm mistaken, clear() is not resetting autoIncrement id in Isar web.

**Steps to Reproduce**
Please describe exactly how to reproduce the problem you are running into.
1. put one or more Items into a collection
2. get count and last inserted id
3. invoke clear() on collection
4. count() is now 0; last id is indeterminate / negative infinity
5. put another Item into collection
6. count is now 1, but last inserted id increments previous value instead of restarting at 1

**Code sample**
```
  void addItem() async {
    int? newId;
    int? itemCount;
    await db?.writeTxn((db) async {
      newId = await db.items.put(Item());
      itemCount = await db.items.count();
      setState(() {
        _counter = itemCount;
        lastId = newId;
      });
    });
  }

  void clearItems() async {
    await db?.writeTxn((db) async {
      await db.items.clear();
    });
    int newCount = await db!.items.count();
    setState(() {
      _counter = newCount;
    });
  }
```

**Version**
 - Platform: Web
 - Flutter version: 3.0.1
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Comment by leisim** [comment]
Unfortunately, indexeddb does not support resetting the auto increment key.

I'll document this as a limitation.

**Comment by psine** [comment]
Thanks, another limitation I've discovered is that LinkFilters are unsupported on web.  I won't bother creating another issue for that, but is that planned in the future, or would it be another inherent limitation of IndexedDB?  Thanks.
