### ISSUE TITLE
IsarError: Could not initialize IsarCore library

### ISSUE THREAD

**Issue by santoshakil** [isar/isar#398]
On Some devices (Google Pixel 3a(Snapdragon 670)), it is working perfectly fine. But on some devices (Example: Samsung Galaxy A10(Exynos 7884)) it shows this error:

**Unhandled Exception: IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies: Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/.......==/lib/arm/libisar.so"...**

**Version**
 - Platform: Android
 - Flutter version: 3.0.1
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Comment by Anan-Saadi** [comment]
I think it's the same issue with 32 bit devices(#281), a galaxy A10 should 64 bit, but it seems that it runs on 32 bit mode (refer to this discussion : https://android.stackexchange.com/questions/225314/is-the-cpu-of-samsung-galaxy-a10s-64-bit-or-32-bit), you can try upgrading to isar 3.0.0 and see if it fixes the issue

**Comment by santoshakil** [comment]
> I think it's the same issue with 32 bit devices(#281), a galaxy A10 should 64 bit, but it seems that it runs on 32 bit mode (refer to this discussion : https://android.stackexchange.com/questions/225314/is-the-cpu-of-samsung-galaxy-a10s-64-bit-or-32-bit), you can try upgrading to isar 3.0.0 and see if it fixes the issue

Isar 3.0.0 is not stable yet.

**Comment by jeremylcarter** [comment]
I think you have no other choice. I am using Isar 3.0.0 dev in production right now, if you look at the generated files you will notice that there aren't many changes, and there are no breaking changes to the core API's.

**Comment by rodevapp** [comment]
> I think it's the same issue with 32 bit devices(#281), a galaxy A10 should 64 bit, but it seems that it runs on 32 bit mode (refer to this discussion : https://android.stackexchange.com/questions/225314/is-the-cpu-of-samsung-galaxy-a10s-64-bit-or-32-bit), you can try upgrading to isar 3.0.0 and see if it fixes the issue

I have same issue with Isar 2.5.0 in 32bit devices(Motorola XT1626, Android 7.0), after upgrade to Isar 3.0.0 i solved my issue.

**Comment by leisim** [comment]
Awesome, thanks for confirming @rodevapp
