### ISSUE TITLE
Backlinks don't load() on web, but do on native (iOS, Android)

### ISSUE THREAD

**Issue by psine** [isar/isar#399]
**Steps to Reproduce**

- create a Collection with a Backlink (in my case self-referential: 'subitems'  Backlinks to 'superitem' Link)
- put an item (rootItem) with no superitem Link
- put another item with superitem.value set to rootItem and saveLinks: true
- invoke load() on rootItem.subitems; succeeds on native, remains empty on web
- rootItem.subitems.length is now 1 on native (correct), but 0 on web (incorrect).
- attempting to manually add() and save() subitem now fails with 'Unique index violation', assuming because the Link already exists, but is apparently unidirectional (i.e. superitem only) on web platform.

**Code sample**
```
@Collection()
class Item {
  int? id;
  String name = 'Item Name';
  final superitem = IsarLink<Item>();
@Backlink(to: 'superitem')
  final subitems = IsarLinks<Item>();

var subItem = Item();
      subItem.superitem.value = rootItem;
      await isarDb.writeTxn((db) async {
        newId = await db.items.put(subItem, saveLinks: true);
      });
      await rootItem.subitems.load(); // always empty on web
      print('==> subitem count: ${rootItem.subitems.length}'); // always 0 on web
```

**Version**
 - Platform: Web
 - Flutter version: 3.0.1
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Comment by leisim** [comment]
Closing in favour of #686
