### ISSUE TITLE
Materialised views and one way sync

### ISSUE THREAD

**Issue by gedw99** [isar/isar#40]
Checkout https://github.com/MaterializeInc/materialize.

its 100% rust too

it allows materialised views with mutations pushing out a change event.

there are various things you could use it with Isar to make it reactive.

Have a PostgreSQL dB on the server and create materialised views that get synced with Isar

Or / also embed it with Isar to have the same functionality on the client 

Timely data flows are really powerful construct 

Marrying the two would allow one way sync with mutations going back to the server and then mutating the materialised view and then creating a change event that is propagated to allow flutter clients that are viewing that materialised view.

**Comment by leisim** [comment]
This looks very interesting. I'll definitely evaluate integrating it :+1:
