### ISSUE TITLE
Ignore generated files in test coverage

### ISSUE THREAD

**Issue by dewbambs** [isar/isar#400]
We have to add additional step of modifying lcov.info before we build it for coverage.  So I suggest that the library adds `coverage:ignore-file` in every generated file. Which will avoid extra efforts to modify lcov.

**Comment by leisim** [comment]
Will do, thanks!

**Comment by dewbambs** [comment]
It's really a small change If you want I can provide PR.

**Comment by leisim** [comment]
Fixed in `3.0.0-dev.2`
