### ISSUE TITLE
IsarError: Link has been moved! It is not allowed to move a link to a differenct collection. (attempting to update isar collection.

### ISSUE THREAD

**Issue by richard457** [isar/isar#407]
**Steps to Reproduce**
Attempting to uni test my update function where I am attempting to change my collection property hence the error is shown when attempting to update.
**Code sample**
```
if (data is Order) {
      final order = data;
      await isar.writeTxn((isar) async {
        return await isar.orders.put(order, saveLinks: true);
      });
    }
```

**Version**
 - Platform: unit testing
 - Flutter version: 3.0.1
 - Isar version:^3.0.0-dev.0
 - Isar Generator version: ^3.0.0-dev.0

**Comment by leisim** [comment]
Did you move the link object? That is not allowed

**Comment by leisim** [comment]
Do you have a sample reproducing the issue?

**Comment by leisim** [comment]
Going to close this for now. Please reopen if you have more information.
