### ISSUE TITLE
findAll bug

### ISSUE THREAD

**Issue by git-maven** [isar/isar#408]
if the isar.chatGroupMemberEntitys.where().gidEqualTo(gid).build().countSync() == 0
findAll return nothing

isar.chatGroupMemberEntitys.where().gidEqualTo(gid).build().findAll().then((value){
        logger.d(value);
      }, onError: (e){
        logger.d(e);
      });

but findAllSync is work

**Comment by git-maven** [comment]
ps, my entity contains the isarLink
is it don't work in findAll when my entity contains isarLink because the isolate?
how can i do?
only use findAllSync?

**Comment by leisim** [comment]
Do you have sample code reproducing the issue?
