### ISSUE TITLE
when the isarlink has uniqueindex

### ISSUE THREAD

**Issue by git-maven** [isar/isar#409]
**Steps to Reproduce**
Please describe exactly how to reproduce the problem you are running into.

int id = Isar.autoIncrement;

  @Index(unique: true)
  String memId = ''

  @Index()
  String gid = '';
  UserInfoEntity ui = UserInfoEntity();
  final userInfoLink = IsarLink<UserInfoEntity>();

int id = Isar.autoIncrement;

	@Index(unique: true)
	String uid = '';
	String name= '';

```
Provide a few simple lines of code to show your problem.
```

when i use 

await isar.writeTxn((isar) async{
      for (var element in data) {
        element.userInfoLink.value = element.ui;
      }
      await isar.chatGroupMemberEntitys.putAll(
          data,
          replaceOnConflict: true,
          saveLinks: true
      );
    }).then((value){

      logger.d(value);
    }, onError: (e){
      logger.d(e);
    });

i will throw the error 

IsarError: There was an error but it could not be loaded from IsarCore.

i think isar should like object box let the replaceOnConflict to @Index(replaceOnConflict: true)

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 2.10.5]
 - Isar version: [e.g. 2.5.0]
 - Isar Generator version: [e.g. 2.5.0]

**Comment by Mihai-B** [comment]
I am not sure but I think `replaceOnConflict` will be removed starting with Isar 3.0.

**Comment by leisim** [comment]
Yes, this issue should be fixed in `3.0`
