### ISSUE TITLE
Isar generation when collections are in multiple dart packages

### ISSUE THREAD

**Issue by srix55** [isar/isar#43]
When there are multiple packages with a set of collections each, for a single isar instance, we have to manually merge the generated isar code from each of the packages

There should be a way to tell the code generator to consider the generated isar code from other packages.

**Comment by leisim** [comment]
That's not as easy as it sounds because the build runner runs for different packages are independent.

Could you give an example why you need to use Isar in a package?

**Comment by srix55** [comment]
In my case, the pure-dart package auth_persistence and inventory_persistence each contain their domain specific collections that only make sense for their respective packages. A logical separation of concerns.

**Comment by leisim** [comment]
Oh so you split your app into several packages. I think that's rather unusual but I'd love to hear reports from other users. I have no idea how we could support multiple packages to be honest. Maybe you have an idea.

**Comment by cenumi** [comment]
Maybe add type adapters after openIsar manually just like hivedb?
void main( ) async{
  final isar = await openIsar();
  isar.addTypeAdaper(TypeAdapter());
}

**Comment by leisim** [comment]
There is now an option to setup multi-package projects: https://isar.dev/generator_config
