### ISSUE TITLE
Support for non-int ids

### ISSUE THREAD

**Issue by SimonHausdorf** [isar/isar#433]
Currently only int is allowed as id type, however, it is common to use uuid or ObjectId (mongodb) as id if data is loaded from API endpoints / external databases.

Is there any plan to support non-int ids?

**Comment by leisim** [comment]
There is no plan to support non-in t ids because you can easily create a unique index that replaces existing entries with the same property value.

Also `getByYourId()` and `deleteByYourId()` and in the new version even `putByYourId()` methods are generated.

**Comment by leisim** [comment]
If you just put an object with existing unique index (replace enabled) it will remove and recreate the opject.

If you use the new `putBy` method the object will be updated. I'll document all of this once v3 is stable

**Comment by SimonHausdorf** [comment]
Thanks, replace did the trick
