### ISSUE TITLE
XOR logical operator

### ISSUE THREAD

**Issue by Viper-Bit** [isar/isar#437]
in query right now isar have and, or, not logical operators, what about xor ?
```
( A AND NOT(B) ) || ( B AND NOT(A) )
```

pseudo code:
```dart
final result = await isar.shoes.filter()
  .group((q) => q
    .modelNameContains('Nike')
    .xor()
    .isUnisexEqualTo(false)
  )
  .findAll()
```

**Comment by leisim** [comment]
I like the idea. Let's add it :)

**Comment by leisim** [comment]
Core support [here](https://github.com/isar/isar-core/commit/582e21ace2a2f2ef8938717af526fb0ee439d825). Dart support will follow in the next release.

**Comment by Viper-Bit** [comment]
added in 3.0.0-dev.2
