### ISSUE TITLE
support for string type ids

### ISSUE THREAD

**Issue by Dhruv-Garg79** [isar/isar#443]
**Is your feature request related to a problem? Please describe.**
We use string ids in our system. 

**Describe the solution you'd like**
support for string ids, currently only int ids are possible. 

**Describe alternatives you've considered**
I thought of using timestamp as id since it's int, but that will be little weird. If an API only returns say txnId, I won't be able to get by id, I will have to iterate or will have to return timestamp everywhere to use in place of original id.

**Comment by leisim** [comment]
There have been many similar feature requests recently. Ease use the search to find duplicates 🙂

**Comment by Dhruv-Garg79** [comment]
thanks @Viper-Bit 
I will keep that in mind moving forward @leisim, thanks.
