### ISSUE TITLE
web-based inspector appears to be broken

### ISSUE THREAD

**Issue by alevinetx** [isar/isar#454]
**Steps to Reproduce**
  isar: 3.0.0-dev.2 and  3.0.0-dev.1

No changes were done to any models or annotations
- removed the deprecated ```inspector``` parameter

The web inspector shows a record count, but not the actual records
Downgrading to 3.0.0-dev.0 and using the application version of the inspector works as expected

**Code sample**
```
  // open the database
  final isar = await Isar.open(
    schemas: databaseSchemas,
    directory: dir.path,
    inspector: true

  );
```

**Version**
 - Platform: Windows app, Chrome for inspector 102.0.5005.115
 - Flutter version: Flutter 3.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 676cefaaff (3 days ago) • 2022-06-22 11:34:49 -0700
Engine • revision ffe7b86a1e
Tools • Dart 2.17.5 • DevTools 2.12.2

 - Isar version: 3.0.0-dev.1 / 3.0.0-dev.2
 - Isar Generator version: 3.0.0-dev.1 / 3.0.0-dev.2

**Comment by leisim** [comment]
Could you please try `3.0.0-dev.5`. I made added Inspector fixes

**Comment by alevinetx** [comment]
.5 appears to be working fine.

Thank you !
