### ISSUE TITLE
3.0.0-dev.5 - Inspector: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 127.0.0.1, port = 56411

### ISSUE THREAD

**Issue by SimonHausdorf** [isar/isar#457]
**Steps to Reproduce**
I am receiving the following error on restart of my app:

```
ERROR - 2022-06-26 18:16:38.161193
PUT /*******=/
Error thrown by handler.
SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 127.0.0.1, port = 56414
dart:isolate  _RawReceivePortImpl._handleMessage
```

This keeps happening a few times and stops the app sometimes from restarting. Also, it would be nice if there still would be a way to disable the inspector support.

**Version**
 - Platform: MacOS Ventura
 - Flutter version: 3.0.3
 - Isar version: 3.0.0-dev.5
 - Isar Generator version: 3.0.0-dev.5

**Comment by leisim** [comment]
Are you accessing Isar from a background isolate?

**Comment by SimonHausdorf** [comment]
Not really. However, I am using xcode and macOS beta. Not sure if this has something to do with it.
I could try to setup an example app to see if this problem persists.

There is currently no way to disable the inspector?

**Comment by SimonHausdorf** [comment]
Here is a full log:

```
ERROR - 2022-06-26 18:34:07.814412
PUT /*********=/
Error thrown by handler.
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = 127.0.0.1, port = 57318

ERROR - 2022-06-26 18:34:08.409916
PUT /*********=/
Error thrown by handler.
SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 127.0.0.1, port = 57320
dart:isolate  _RawReceivePortImpl._handleMessage
2

ERROR - 2022-06-26 18:34:08.967424
PUT /*********=/
Error thrown by handler.
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = 127.0.0.1, port = 57322

ERROR - 2022-06-26 18:34:09.756031
PUT /*********=/
Error thrown by handler.
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = 127.0.0.1, port = 57324

ERROR - 2022-06-26 18:34:10.399682
PUT /*********=/
Error thrown by handler.
SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 127.0.0.1, port = 57328
dart:isolate  _RawReceivePortImpl._handleMessage
2

ERROR - 2022-06-26 18:34:11.000553
PUT /*********=/
Error thrown by handler.
SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 127.0.0.1, port = 57330
dart:isolate  _RawReceivePortImpl._handleMessage
2

ERROR - 2022-06-26 18:34:11.580179
PUT /*********=/
Error thrown by handler.
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = 127.0.0.1, port = 57332

ERROR - 2022-06-26 18:34:12.220931
PUT /*********=/
Error thrown by handler.
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = 127.0.0.1, port = 57334

ERROR - 2022-06-26 18:34:13.104493
PUT /*********=/
Error thrown by handler.
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = 127.0.0.1, port = 57336

Restarted application in 6,976ms.
(application log)
```

**Comment by leisim** [comment]
When does it happen exactly? After a hot restart? This looks like a Dart/websocket bug somehow.

No I removed the parameter to disable the Inspector because I wanted to make it easier to use and didn't see a point in disabling it 🤔

**Comment by SimonHausdorf** [comment]
I made a simple example app and it seems like that this problem only happens on real devices.
On iOS simulator it works fine.

Regarding disabling the inspector, I guess enabling it by default is good but I still would love the option to disable it.
I am not sure if it requires any resources to initialize with inspector but most of the time I don't really make use of it. It's nice to have but not mandatory in my opinion.

**Comment by leisim** [comment]
Yes makes sense, I'll reintroduce the option.

But when does the error happen exactly. Randomly or after hot restart?

**Comment by SimonHausdorf** [comment]
after hot restart (on mac shift+cmd+F5)

**Comment by leisim** [comment]
Let's reintroduce disabling the Inspector then and see whether other users experience similar issues :)

**Comment by leisim** [comment]
Added option to disable the inspector in the newest release.
