### ISSUE TITLE
Unable to connect to isar connect

### ISSUE THREAD

**Issue by dgandhi17** [isar/isar#46]
**Steps to Reproduce**
Simply run the isar inspector
copy the url from your application
press connect

Error:
flutter: isolates/1011297615749035
flutter: ERROR: Unable to connect to VMService
flutter: ext.isar.getVersion: (-32601) Unknown method "ext.isar.getVersion".

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: stable channel with null safety enable
 - Isar version: 0.2.0
 - Isar Generator version:0.2.0

**Comment by leisim** [comment]
Should be fixed :)

**Comment by JsonLinesCode** [comment]
I'm still getting this error on MacOS...
