### ISSUE TITLE
SIGABRT on isar.open()

### ISSUE THREAD

**Issue by mrclauss** [isar/isar#462]
isar Version: 3.0.0-dev.5
Target: android qemu x64 Nexus 6 API 31

Sigabrt when calling await Isar.open([schema]), both, with database present and with fresh install. Providing a directory solves this.

Backtrace:
F/libc    (22351): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 22422 (1.ui), pid 22351 (t.contactulater)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone64_x86_64/emulator64_x86_64_arm64:12/SE1A.220203.002.A1/8151367:userdebug/dev-keys'
Revision: '0'
ABI: 'x86_64'
Timestamp: 2022-06-27 17:46:55.873664900+0000
Process uptime: 0s
Cmdline: es.com.skynet.contactulater
pid: 22351, tid: 22422, name: 1.ui  >>> es.com.skynet.contactulater <<<
uid: 10148
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'android context was not initialized'
    rax 0000000000000000  rbx 000000000000574f  rcx 000079b41c9475cf  rdx 0000000000000006
    r8  000079b41c9ce740  r9  000079b41c9ce740  r10 000079b0f1b01260  r11 0000000000000207
    r12 000079b0f1d49580  r13 000079b0f1d46af0  r14 000079b0f1b01258  r15 0000000000005796
    rdi 000000000000574f  rsi 0000000000005796
    rbp 0000000000000001  rsp 000079b0f1b01250  rip 000079b41c9475cf
backtrace:
      #00 pc 000000000005e5cf  /apex/com.android.runtime/lib64/bionic/libc.so (abort+191) (BuildId: 5db8d317d3741b337ef046540bbdd0f7)
      #01 pc 0000000000080c96  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #02 pc 0000000000080bba  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #03 pc 00000000000a88a7  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #04 pc 00000000000aa94d  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #05 pc 00000000000aa511  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #06 pc 00000000000aa485  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #07 pc 00000000000aa441  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #08 pc 000000000000b081  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #09 pc 00000000000378df  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #10 pc 000000000003788a  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #11 pc 000000000000b165  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #12 pc 00000000000800f8  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #13 pc 0000000000055db0  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #14 pc 000000000002f55a  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk (isar_instance_create+826)
      #15 pc 000000000001393b  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #16 pc 00000000000ac1d6  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #17 pc 00000000000ab38a  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #18 pc 00000000000ab044  /data/app/~~X55L5vgWyWXYIJeW2vI2Og==/es.com.skynet.contactulater-n8OBH2lCWorBDwkdXaNARA==/base.apk
      #19 pc 00000000000c758a  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+58) (BuildId: 5db8d317d3741b337ef046540bbdd0f7)
      #20 pc 000000000005fd87  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+55) (BuildId: 5db8d317d3741b337ef046540bbdd0f7)
Lost connection to device.

**Comment by leisim** [comment]
Fixed in the newest release.
