### ISSUE TITLE
filter().idProperty().findAll() returns List<int?> instead of List<int>

### ISSUE THREAD

**Issue by t-kietzmann** [isar/isar#465]
**Steps to Reproduce**

Try the official example for deleting documents:
https://isar.dev/crud.html#modifying-the-database (Delete records #2)

The query returns a List<int?> so the .deleteAll() functions does not work:
The argument type 'List<int?>' can't be assigned to the parameter type 'List<int>'

My tests showed that the findAll() Function always returns a List with ints, or an empty List.

My Workaround ist to cast the result with "myResultList.cast<int>()"

Flutter 3.0.3, isar 3.0.0-dev5.

**Comment by leisim** [comment]
Did you make id non-nullable in your collection class?
