### ISSUE TITLE
path_provider dependency isar_flutter >=0.0.4 depends on isar 0.0.4 and isar_flutter <0.0.4 depends on path_provider ^1.6.24, path_provider ^2.0.1 is incompatible with isar_flutter

### ISSUE THREAD

**Issue by Sadmansamee** [isar/isar#47]
**Steps to Reproduce**

**Code sample**
```
path_provider: ^2.0.1
isar: any
isar_flutter: any
```

**Version**
 - Platform: iOS
 - Flutter version: 2
 - Isar version: 0.0.4
 - Isar_flutter >=0.0.4

**Comment by leisim** [comment]
@Sadmansamee You should try a newer version of Isar :)

**Comment by Sadmansamee** [comment]
Thanks, I missed the latest version point :) 

If my projects will go live 3-4 months later then is this library safe to use?

**Comment by leisim** [comment]
> If my projects will go live 3-4 months later then is this library safe to use?

Definitely. There will be a few minor API changes but that's it.
