### ISSUE TITLE
Target link does not exist

### ISSUE THREAD

**Issue by richard457** [isar/isar#473]
**Steps to Reproduce**
create a flutter app, add the latest isar, then create 3 models like this
```dart

@Collection()
class IT {
  ITenant(
      {this.id = 0,
      required this.name,);
  late int id = Isar.autoIncrement;
  late String name;
  final branches = IsarLinks<A>();
  final businesses = IsarLinks<B>();
  final permissions = IsarLinks<C>();
}
```
Run the app it will show the error target links do not exist. so a couple of things I tested, commenting on the links and building and running the app works, and uncomment it again and running build sometime works, then I thought, maybe you can not declare the links and models at the same time maybe you need to run declare model first then add links later which worked once until it didn't
**Code sample**

**Version**
 - Platform:  Android, Windows, Linux, Web
 - Flutter version: 3.0.3
 - Isar version: isar: ^3.0.0-dev.5
 - Isar Generator version: ^3.0.0-dev.5

**Comment by leisim** [comment]
Fixed in `3.0.0-dev.8`
