### ISSUE TITLE
IsarLinks contains does only identity check

### ISSUE THREAD

**Issue by robpot95** [isar/isar#478]
**Steps to Reproduce**
This will work:
```
  final user = await isar.users.get(1);
    if (user != null) {
      await user.friends.load();
      final targetFriend = await isar.users.get(2);
      for (User user in user.friends) {
        print("${user.id} - ${user.hashCode}");
        if (user == targetFriend) {
          print("Found match");
          break;
        }
      }
   }
```
While this will not work. Always return false:
`user.friends.contains(targetFriend)`

**Version**
 - Platform: Linux
 - Flutter version: 3.0.4
 - Isar version: 3.0.0-dev.5
 - Isar Generator version: 3.0.0-dev.5

**Comment by leisim** [comment]
Fixed in `3.0.0-dev.8`
