### ISSUE TITLE
IsarError: Object Instance of 'Object' has no id and can therefore not be linked.

### ISSUE THREAD

**Issue by GabrielCR99** [isar/isar#480]
**Steps to Reproduce**
Hi there! Thanks for the amazing package, it's really helpful and easy to understand how NoSQL Databases work on Dart. Unfortunately, I'm having a problem to save an IsarLink. The Project is created normally, but when I try to save a linked object (a task in the project) with the following code, it shows this error: 
E/flutter (16773): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: IsarError: Object Instance of 'ProjectTask' has no id and can therefore not be linked.
Do I need to also tell Isar that a Task is a Link to Project?

**Code sample**
```dart
import 'package:isar/isar.dart';

import 'converters/project_status_converter.dart';
import 'project_status.dart';
import 'project_task.dart';

part 'project.g.dart';

@Collection()
class Project {
  int id = Isar.autoIncrement;
  late String name;
  late int estimate;

  @ProjectStatusConverter()
  late ProjectStatus status;

  final tasks = IsarLinks<ProjectTask>();
}
```
``` dart
import 'package:isar/isar.dart';

part 'project_task.g.dart';

@Collection()
class ProjectTask {
  int id = Isar.autoIncrement;
  late String name;
  late int duration;
  late DateTime created = DateTime.now();
}
```

``` dart
  @override
  Future<Project> addTask(int projectId, ProjectTask task) async {
    try {
      final connection = await _database.openConnection();

      final project = await findById(projectId);

      project.tasks.add(task);
      connection.writeTxn(() async => await project.tasks.save());

      print(project.tasks);

      return project;
    } on IsarError catch (e, s) {
      log('Erro ao cadastrar task!', error: e, stackTrace: s);
      Error.throwWithStackTrace(
        const Failure(message: 'Erro ao cadastrar task!'),
        s,
      );
    }
  }
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 3.0.4
 - Isar version: 3.0.0-dev.5
 - Isar Generator version: 3.0.0-dev.5

**Comment by leisim** [comment]
The full error message should be `Object has no id and can therefore not be linked. Make sure to .put() objects before you use them in links.`

Links cannot save objects yet so you need to `.put()` an object before you can use it. The next Isar version will improve that.

**Comment by GabrielCR99** [comment]
Seems that `.put()` works, but it doesn't load the tasks saved in the object with `get()`

**When saving an object with ```await project.tasks.put()```**
![image](https://user-images.githubusercontent.com/42328188/177865745-1d227e5e-9972-4da5-9ada-39bdbcb9336c.png)

**When loading with ```await connection.projects.get()```**
![image](https://user-images.githubusercontent.com/42328188/177867240-80cafd22-cb8a-4377-8f5b-be43c2a56c94.png)

```dart
  @override
  Future<Project> findById(int projectId) async {
    final connection = await _database.openConnection();
    final project = await connection.projects.get(projectId);
    if (project == null) {
      throw const Failure(message: 'Erro ao encontrar projeto');
    }

    return project;
  }
```

**Comment by leisim** [comment]
I don't quite understand. What is the issue?

**Comment by leisim** [comment]
Put does not save links automatically. I know it's weird and not easy to use. It will be better soon!

**Comment by GabrielCR99** [comment]
No worries man! Now I really understand how it works, and it's working like a charm (both in Web, Android and iOS) :)
Many thanks for your help and your patience. I'll keep using Isar in my apps, as this looks like a very promising offline DB to use in my future projects!
I'll close this issue since we've understanded each other!
