### ISSUE TITLE
Support for TypeConverters with constructor arguments

### ISSUE THREAD

**Issue by buraktabn** [isar/isar#481]
**Is your feature request related to a problem? Please describe.**
I need to store `Enum` values in Isar. TypeConverters are great, but it's frustrating when it comes to writing it for a bunch of enums.

**Describe the solution you'd like**
I'd like to create a helper class that I can use for non-null enums in a `Collection`.
```dart
class EnumConverter<E extends Enum> extends TypeConverter<E, int> {
  const EnumConverter(this.values);

  final List<E> values;

  @override
  E fromIsar(int object) {
    return values[object];
  }

  @override
  int toIsar(E object) {
    return object.index;
  }
}
```
```dart
@Collection()
class Amenity {
  @EnumConverter(MyEnum1.values)
  late MyEnum1 muEnum1;
  @EnumConverter(MyEnum2.values)
  late MyEnum2 muEnum2;
  ...
}
```
**Describe alternatives you've considered**
I created a new `TypeConverter` for each `Enum`. Tried above and got the following error on `build_runner`

```
TypeConverters with constructor arguments are not supported.
enum_test.dart:177:7
    ╷
477 │ class EnumConverter<E extends Enum> extends TypeConverter<E, int> {
    │       ^^^^^^^^^^^^^
    ╵
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web

**Comment by buraktabn** [comment]
It would be great to have those out of the box. I understand that it can be difficult but we need to think of other types that Isar doesn't support. I'll definitely work on a PR once I got some free time :).

**Comment by leisim** [comment]
Type converters have been removed from the library.
