### ISSUE TITLE
query watcher returning type CastList instead of List

### ISSUE THREAD

**Issue by Anan-Saadi** [isar/isar#483]
**Steps to Reproduce**

create a query watcher like `contacts.where().findAll().watch()` and listen to it

**Code sample**
```dart
Stream stream = contacts.where().findAll().watch();

stream.listen((event) {
  print(event.runtimeType);
 //CastList<Contact, Contact>

});
```
casting the result to type `List` works, but casting it to `List<Object>` returns `CastList<Contact, Contact> is not a subtype of List<Conatct>`

**Version**
 - Platform: Android
 - Flutter version: 3.1.0-0.0.pre.1309
 - Isar version: 3.0.0-dev.5
 - Isar Generator version: 3.0.0-dev.5

**Comment by leisim** [comment]
Use `.toList().cast()`

**Comment by Anan-Saadi** [comment]
thanks, this worked

**Comment by guiiamorim** [comment]
Sorry for commenting on a closed issue, but I'm having the same issue when building a query like `contacts.where().build()` and then trying to execute `findAll()` on the query.

Already tried the solution above but the error continues the same. Also tried to cast using `(await query.findAll()) as List<Contact>` but not worked.

Any help would be appreciated, also, if it's best to create another issue I can do that.
