### ISSUE TITLE
3.0.0-dev.7 - @Id() causing error: Annotation must be either a const variable reference or const constructor invocation.

### ISSUE THREAD

**Issue by SimonHausdorf** [isar/isar#491]
```dart
@Collection()
class MyClass {
  @Id()
  int? isarId;
}
```

Causing error
```
Annotation must be either a const variable reference or const constructor invocation.
```

**Comment by md-weber** [comment]
If I understand it correctly the @Id is now deprecated. The new Way is now in 3.0.0 to have your id like this: `Id id = isarAutoIncrementId;` but this is just based on personal observation. I hope that helps.

**Comment by SimonHausdorf** [comment]
yes correct, that changed, I will close this issue.

**Comment by thzero** [comment]
This shouldn't have been closed until the documentation has not been updated.

Both of these still use the @Id() annotation approach.

https://isar.dev/tutorials/quickstart.html
https://isar.dev/schema.html#annotating-classes

**Comment by leisim** [comment]
The documentation is for the latest stable version.
