### ISSUE TITLE
Links are not automatically saved

### ISSUE THREAD

**Issue by canastro** [isar/isar#493]
**Steps to Reproduce**
I'm trying to understand how I can put an entry on a collection and guaranteed that every link gets created.
From what I've read in the documentation I assumed that would be automatically guaranteed by isar:

> First we create a the teacher and assign it to a student. As you can see in this example, we have to put() the student manually (obviously) but the link is saved automatically and also takes care of adding the mathTeacher to the database.

But when I tried to run the example I've seen that only the Student is created, but no Teacher is created. (I confirmed this by using the Isac inspector).

**Code sample**
```
final dir = await getApplicationSupportDirectory();

  final isar = await Isar.open(
    [
      StudentSchema,
      TeacherSchema,
    ],
    directory: dir.path,
    inspector: true,
  );

 final mathTeacher = Teacher()
    ..id = 1
    ..subject = 'Math';

  final linda = Student()
    ..id = 1
    ..name = 'Linda'
    ..teachers.value = mathTeacher;

  await isar.writeTxn(() async {
    await isar.students.put(linda);
  });
```

**Version**
 - Platform: iOS
 - Flutter version: 3.0.1
 - Isar version: 3.0.0-dev.7
 - Isar Generator version: 3.0.0-dev.7

**Comment by ozzfelipe** [comment]
In the `put` method you need to mark the `saveLinks: true`, like this:
`await isar.writeTxn(() async {
    await isar.students.put(linda, saveLinks: true,);
  });`

**Comment by canastro** [comment]
It seems that only putSync has the option to set `saveLinks` as true. Is that on purpose?

**Comment by canastro** [comment]
Just one more question. I'm trying to change to use the Sync methods, but I'm getting `IsarError (IsarError: Write operations require an explicit transaction.)`. Here is the snippet that produces this error:

```dart
await database.writeTxn(
      () async {
        database.productModels.putAllSync(
          products.toList(),
          saveLinks: true,
        );
      },
    );
```
