### ISSUE TITLE
Version no. not accurate

### ISSUE THREAD

**Issue by md-siam** [isar/isar#498]
![Screen Shot 2022-07-17 at 9 22 48 AM](https://user-images.githubusercontent.com/21225918/179382448-a0c83fc9-c40f-4502-bd03-929452a6c3ee.png)

**Comment by leisim** [comment]
The standalone inspector has been replaced by a web version in 3.0.x so this issue is obsolete soon.

**Comment by md-siam** [comment]
Oh, thanks for this excellent package.
