### ISSUE TITLE
Feature / Idea collection

### ISSUE THREAD

**Issue by leisim** [isar/isar#5]
- Conflict free sync #2 
- Relationship support (how to do it with IndexedDB?)
- Offline first
- Peer-to-peer change distribution
- Schemaless?
- CloudKit integration
- Firebase integration

**Comment by drmirk** [comment]
Merge one box into another.

```dart
final primaryBox = await Isar.openBox('primary');
final secondaryBox = await Isar.openBox('secondary');

primaryBox.merge(secondaryBox);

// OR

Isar.merge(primaryBox, secondaryBox);
```

With an optional parameter to solve merge conflicts.

```dart
resolveConflict(firstVal, secondVal) {
  ...
  ...
  return winner;
}

Isar.merge(primary, secondary, resolveConflict);
```

**Comment by AKushWarrior** [comment]
@drmirk @leisim this is trivial if we implement #2 correctly. Merge conflicts will be resolved automatically; we can look into users overriding that functionality.

**Comment by AKushWarrior** [comment]
RE integration: we should sample some other integrations. Things like Redis, memcached, etc. have similar architectural goals.

**Comment by drmirk** [comment]
> 
> 
> @drmirk @leisim this is trivial if we implement #2 correctly. Merge conflicts will be resolved automatically; we can look into users overriding that functionality.

@AKushWarrior After posting, I thought that too. But I kept it,  thinking this might give someone some idea. 😁😁😁

**Comment by drmirk** [comment]
Please make box names case sensitive.

Originally I requested this in, [https://github.com/hivedb/hive/issues/338](Hive)

**Comment by TomasWeg** [comment]
@leisim Add per-folder instance. For example, one Isar instance for cache folder and another for app-data

**Comment by AKushWarrior** [comment]
> @leisim Add per-folder instance. For example, one Isar instance for cache folder and another for app-data

The user provides a path to the database. If you want a database in a folder, just pass that folder.

**Comment by leisim** [comment]
Closing this in favor of GitHub discussions.
