### ISSUE TITLE
Support Value Classes for ids

### ISSUE THREAD

**Issue by DevNico** [isar/isar#500]
Instead of using the `Id` type directly I would like to create value classes for all ids.

These Id ValueClasses might look something like this:
```dart
class CustomerId {
  const CustomerId(this.value);

  final int? value;
}
```

Would it be possible to support something like this? Best case would be if Isar supported ValueClass ids like the one up top out of the box but if that doesn't work maybe support `TypeConverter` for ids?

**Comment by leisim** [comment]
It would be possible to implement this but I don't really see the point. We'll have the limitation that ids have to be integers.

Could you please explain why you need the `CustomerId`?

**Comment by DevNico** [comment]
The use case would be to have strongly typed ids. This would reduce the possibility of calling a repository method or a widget constructor with the wrong id.

An example for strongly typed ids in the C# world can be seen [here](https://andrewlock.net/using-strongly-typed-entity-ids-to-avoid-primitive-obsession-part-1/).

**Comment by TimWhiting** [comment]
There are proposals in the dart language repo about "extension structs" or "views" which are strongly typed "typedefs". There are higher priority things like macros and pattern matching / tuples on their list, so I wouldn't get my hopes up too much, but it is a very active discussion topic.

**Comment by leisim** [comment]
I don't intend to implement this in Isar. Maybe one of the planned language features gives us an opportunity to implement strongly typed ids.
