### ISSUE TITLE
Unable to create iOS archive 

### ISSUE THREAD

**Issue by KumarArab** [isar/isar#507]
**Steps to Reproduce**
I'm able to produce a build but not an archive on iOS.

**Error Logs**
```
❌  ld: Invalid value (Producer: 'LLVM14.0.1-rust-1.62.0-nightly' Reader: 'LLVM APPLE_1_1300.0.29.30_0') for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Version**
 - Platform: iOS,
 - Flutter version: 2.10.3
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Comment by leisim** [comment]
Which `isar_flutter_libs` version are you using?

**Comment by KumarArab** [comment]
2.5.0

**Comment by leisim** [comment]
Yeah you can try that. And make sure to have the latest version of XCode.

**Comment by sbenmeddour** [comment]
I had the same issue.
I have to make a first build with flutter build... then it fails
Then go to xcode, and disable bitcode for isar in the pods targets
Re launch a build in your terminal and it should work

**Comment by devxpy** [comment]
I quick fixed this by adding a `post_install` hook to disable bitcode for this plugin to `ios/Podfile` - 

```rb
post_install do |installer|
  installer.pods_project.targets.each do |target|
    ...

    target.build_configurations.each do |config|
      ...

      if ['isar_flutter_libs'].include? target.name
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
   end
end
```

**Comment by leisim** [comment]
Great that you figured out a solution :)
