### ISSUE TITLE
2.5.0: update analyzer dependency

### ISSUE THREAD

**Issue by fix92** [isar/isar#510]
**update analyzer dependency to >=4.2.0**
Similar to https://github.com/isar/isar/issues/172 the isar dependency `analyzer` is clashing with packages like `freezed` and one has to manually use `dependency_overrides` so that both can run with the latest stable version.
See https://github.com/isar/isar/blob/2.5.0/packages/isar_generator/pubspec.yaml
vs.
https://github.com/rrousselGit/freezed/blob/master/packages/freezed/pubspec.yaml

**Describe the solution you'd like**
`  analyzer: ">=4.2.0 <5.0.0"`

**Describe alternatives you've considered**
One could of course wait until 3.0.0 where this is fixed. I'm not sure about the current release plans, but until then a 2.5.1 release would be nice. Please close this issue if this is not desired. Thank you!

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 3.0.5
 - Isar version: 2.5.0

**Comment by leisim** [comment]
Thanks for this issue. A release is actually quite a bit of work so I kindly ask you to use overrides until v3. My hope is to release it end of July. Mid August at the latest.

**Comment by fix92** [comment]
Perfect, looking forward! Closing this issue then 👍
