### ISSUE TITLE
data table to json

### ISSUE THREAD

**Issue by AndreDataprime** [isar/isar#514]
Hello, how do I transform a data table into json to be sent to an api?

**Comment by leisim** [comment]
`isar.yourCollection.filter().exportJson()`

**Comment by AndreDataprime** [comment]
widget.isar.rotinass.filter().exportJson(); 
The method 'exportJson' isn't defined for the type 'QueryBuilder'.
Try correcting the name to the name of an existing method, or defining a method named 'exportJson'.

**Comment by AndreDataprime** [comment]
widget.isar.rotinass.where().exportJson(); OK
widget.isar.rotinass.where().Filter().exportJson(); NOK
widget.isar.rotinass.filter().exportJson(); NOK

**Comment by AndreDataprime** [comment]
[{dia: Terça, horario: 10:35 am, id: 1, titulo: titulo 1}, {dia: Quarta, horario: 6:35 am, id: 2, titulo: titulo 2}] missing quotes
[{"dia": "Terça", "horario": "10:35 am", "id:" 1, "titulo": "titulo 1"}] The json should be like this
See what I had to do:
    final rotinasCollections = widget.isar.rotinass;
    List<Rotinas> getRotinas = await rotinasCollections.where().findAll();
    String x = '[';
    for (int i = 0; i < getRotinas.length; i++) {
      x = '$x{"id": ${getRotinas[i].id.toString()}, ';
      x = '$x "titulo": "${getRotinas[i].titulo}", ';
      x = '$x "dia": "${getRotinas[i].dia}", ';
      x = '$x "horario": "${getRotinas[i].horario}"}, ';
    }
    x = '$x]';
    x = x.replaceFirst(', ]', ']');
