### ISSUE TITLE
Incompatible with the Equatable package

### ISSUE THREAD

**Issue by FredJul** [isar/isar#516]
If you extend an Isar collection with Equatable (to generate the equals method), you will notice that:
- with Isar 2.5.0 you will have two unwanted attributes in your database: `stringify` and `hashCode`
- with Isar 3.0.0 you will not be able to generate the code since you can't add `@ignore` on the 'props' attribute from the Equatable superclass

You can easily fix that issue by modifying the `isar_generator/lib/src/helper.dart` file line 27 and remove the whole supertypes handling, but I guess this has been done in purpose.
Maybe we could solve that with an `List<String> ignoreFieldNames`  attribute on the `@Collection` annotation?

**Comment by leisim** [comment]
The `@Collection` annotation has a setting to ignore superclasses.

**Comment by FredJul** [comment]
My bad, I didn't notice... Thank you for your answer.
