### ISSUE TITLE
IsarError: Could not initialize IsarCore library for processor architecture "ios_arm64". 

### ISSUE THREAD

**Issue by adriank** [isar/isar#519]
**Steps to Reproduce**

In testing mode all is fine. In Release mode I'm getting the following error:

```
2022-07-25 12:18:25.006595+0200 Runner[60690:2913737] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: IsarError: Could not initialize IsarCore library for processor architecture "ios_arm64". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
Invalid argument(s): Failed to lookup symbol 'isar_version': dlsym(RTLD_DEFAULT, isar_version): symbol not found
#0      initializeCoreBinary (package:isar/src/native/isar_core.dart:71)
#1      openIsar (package:isar/src/native/open.dart:56)
#2      _IsarNative.open (package:isar/src/native/isar_native.dart:99)
#3      Isar.open (package:isar/src/isar.dart:95)
#4      main (package:isar_test/main.dart:9)
```

**Code sample**

A new app from scratch. 

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final isar = await Isar.open(
    [AppConfigSchema, BeaconSchema],
    directory: (await getApplicationSupportDirectory()).path,
  );
  await isar.writeTxn(() async {
    final id = await isar.appConfigs.put(AppConfig()
      ..id = 1
      ..jwt = 'token');
  });
  final appConfig = (await isar.appConfigs.get(1))!;
  print(appConfig.jwt);
  print('aaa');

  runApp(const MyApp());
}```

```
name: isar_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  isar: ^3.0.0-dev.8
  isar_flutter_libs: ^3.0.0-dev.8
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  isar_generator: ^3.0.0-dev.8
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

**Version**
 - Platform: iOS, XCode 13.2.1
 - Flutter version: 3.0.5
 - Isar version: from 2.5.0 to 3.0.0-dev.8
 - Isar Generator version: 2.5.0 to 3.0.0-dev.8

**Comment by leisim** [comment]
Hey, I asked in the Isar Telegram group and someone replied:
> i got a similar issue after some debugging i noticed that isar was conflicting with fluttertoast plugin in some way. unfortunately i was unable to solve the problem so just deleted the depenency. i got these logs after deleting the pods, podfile and podfile.lock then installing again:  
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_IsarFlutterLibsPlugin
> 
> Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FluttertoastPlugin
>
> m1 mac with flutter version of 3.0.5 and 2.5.0 on isar

Do you also use fluttertoast? Could you maybe share a verbose build log?

**Comment by adriank** [comment]
No i don't. I tested it on completely new project without any additional  dependencies.

**Comment by leisim** [comment]
Unfortunately I cannot reproduce this. Please try running the example app and reopen if you still have issues :)

**Comment by achenglike** [comment]
> Hey, I asked in the Isar Telegram group and someone replied:
> 
> > i got a similar issue after some debugging i noticed that isar was conflicting with fluttertoast plugin in some way. unfortunately i was unable to solve the problem so just deleted the depenency. i got these logs after deleting the pods, podfile and podfile.lock then installing again:
> > Error (Xcode): Undefined symbol: _OBJC_CLASS_$_IsarFlutterLibsPlugin
> > Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FluttertoastPlugin
> > m1 mac with flutter version of 3.0.5 and 2.5.0 on isar
> 
> Do you also use fluttertoast? Could you maybe share a verbose build log?

i got same error, but i used fluttertoast, what should i do
