### ISSUE TITLE
How to import json files in Isar database.

### ISSUE THREAD

**Issue by Siddhesh-Nalawade** [isar/isar#526]
### Discussed in https://github.com/isar/isar/discussions/525

<div type='discussions-op-text'>

<sup>Originally posted by **Siddhesh-Nalawade** July 27, 2022</sup>
I have some nested complex json files. I want to load these json files into isar database. Also I want to implement full text search feature for these json files. I tried to create model class for these jsons but jsons are really complex. How should I load these json files in Isar and implement full text search feature.

Structure of JSON:

```
{
"mainCategoryName": ,
"options":[
              {
              "name":
              "details":[
                            {
                            "title"
                            "detailsArray": [
                                        {
                                         "BackgroundColour": ,
                                          "name": ,
                                          "information": []
                                        }
                                  ]
                             }
                        ]
                  }
            ],
"definition": [],
"id":,
"symptomName":
}
```

**Comment by leisim** [comment]
The discussion section was the correct place
