### ISSUE TITLE
How to unit test Isar?

### ISSUE THREAD

**Issue by davorkomusanac** [isar/isar#529]
Hi, I must say I like Isar and it seems pretty cool, however I have a problem with testing it.  

I don't even know where to begin, I see that there are no docs regarding testing, and no other open issues regarding it. How would one proceed with mocking Isar, or just trying to create basic unit tests? 

Thanks

**Comment by leisim** [comment]
Mocking Isar I can't really help you but you can just use Isar in unit tests: https://github.com/isar/isar#unit-tests

**Comment by davorkomusanac** [comment]
Thanks for the fast reply, I don't know if I am blind, but the only similar method I can call is 'initializeLibraries' and I cannot await it?

**Comment by leisim** [comment]
You need to use the newest dev version 🙂

**Comment by davorkomusanac** [comment]
Ah cool, didn't know that. Thank you!
