### ISSUE TITLE
“Isar Inspector” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by eli1stark** [isar/isar#534]
version: https://github.com/isar/isar/releases/tag/2.5.0
<img width="254" alt="Screenshot at Jul 29 10-30-05" src="https://user-images.githubusercontent.com/57593530/181813021-34bc4652-ddab-46cb-a223-ca2e6c5f211c.png">

**Comment by leisim** [comment]
You can allow it in settings > security

**Comment by eli1stark** [comment]
Cool, thanks. 

Steps:
1. Open Finder
2. Traverse through to “Applications” Folder
3. Highlight the software you are trying to Open
4. Press “control”
5. Right “Click” & Select “Open”
