### ISSUE TITLE
Can't launch web on ^3.0.0-dev.8

### ISSUE THREAD

**Issue by eli1stark** [isar/isar#535]
**Steps to Reproduce**
Use libraries with the following version: `^3.0.0-dev.8` and try to launch the app.

**Debug console**
```
Launching lib/main.dart on Chrome in debug mode...
lib/main.dart:1
: Error: Not a constant expression.
../…/src/isar.dart:36
  static const Id autoIncrement = isarAutoIncrementId;
                                  ^^^^^^^^^^^^^^^^^^^
: Error: Constant evaluation error:
../…/src/isar.dart:36
  static const Id autoIncrement = isarAutoIncrementId;
                                  ^
: Context: The invocation of 'isarAutoIncrementId' is not allowed in a constant expression.
../…/src/isar.dart:36
  static const Id autoIncrement = isarAutoIncrementId;
                                  ^
: Context: While analyzing:
../…/src/isar.dart:36

  static const Id autoIncrement = isarAutoIncrementId;
                  ^
Failed to compile application.
Exited
```

**Comment by leisim** [comment]
Hey, we is unfortunately not supported yet in the dev versions 😕

**Comment by eli1stark** [comment]
Got it, is there any approximate timeline on when 3rd version will be stable?

**Comment by leisim** [comment]
The goal is in August but not a promise 😜

**Comment by nelchael730** [comment]
Any update on this? Client has decided they want to explore PWA option after project has started. I can just try downgrading to 2x anyway but thought I'd ask just in case release was imminent

**Comment by leisim** [comment]
I'll close this issue when 3.0 stable is released. Going to take at least two more weeks. Today I'll release a huge update however with enum and embedded object support.

**Comment by nelchael730** [comment]
Wonderful, 2-3 weeks is great. Thank you for the swift response it will allow me to plan appropriately

**Comment by cgestes** [comment]
JFYI: just dropped the const and it runs on the web.
