### ISSUE TITLE
Data on web is not persisted (2.5.0)

### ISSUE THREAD

**Issue by eli1stark** [isar/isar#536]
**Steps to Reproduce**
1. Launch web, save something, read object, object is not null
2. Terminate web browser
3. Launch again
4. Read object, the object is null

**Comment by leisim** [comment]
Did you try it in Flutter debug mode? Flutter opens a clean browser with every launch.

**Comment by eli1stark** [comment]
Yes, I did, this was my initial thought, how to test it?

**Comment by eli1stark** [comment]
I managed to launch prod, looks like data is presisted, the only question is do we have access to Isar Inspector on the Web in debug mode? And also for the web what directory do we need to provide when opening Isar?

**Comment by leisim** [comment]
You don't need to provide a directory and can inspect the data using the Chrome inspector. Just look at the indexeddb 🙂
