### ISSUE TITLE
IsarLink doesn't work (2.5.0)

### ISSUE THREAD

**Issue by eli1stark** [isar/isar#537]
**Steps to Reproduce**
1. I used an example straight from the docs.
2. Add Teacher and Student collections
3. Put them to Isar using examples from the docs: https://isar.dev/links.html#isarlinks

I checked this issue and tried to use a workaround there, but it doesn't work either
https://github.com/isar/isar/issues/511

**Comment by leisim** [comment]
This is a known issue and already fixed in 3.x
