### ISSUE TITLE
After hot restart Isar Inspector throws sentinel kind of problem

### ISSUE THREAD

**Issue by eli1stark** [isar/isar#539]
**Steps to Reproduce**
1. Launch app
2. Hot restart
3. Switch collections in Inspector
4. You got the problem

Maybe related to this somehow, this was a long time ago:
https://github.com/isar/isar/issues/152

**Version**
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Comment by eli1stark** [comment]
<img width="790" alt="Screenshot at Jul 29 17-10-07" src="https://user-images.githubusercontent.com/57593530/181862255-b58a12a0-3f12-4426-89ab-7601b2b9ad9e.png">

**Comment by leisim** [comment]
Going to close this since the old inspector won't receive any updates
