### ISSUE TITLE
Example App Request

### ISSUE THREAD

**Issue by themumy10** [isar/isar#540]
This great package needs a good example app. 

Multiple example apps with different state management solutions needed.

At least simple complete app for newbies.
(If possible an example app with bloc would be great)
Documentation needs to be updated too. 
Thanks for the great and unique work

**Comment by leisim** [comment]
Hey, Isar is completely unrelated to state management.

The documentation is up to date with the latest stable version. What do you miss?

**Comment by themumy10** [comment]
> Hey, Isar is completely unrelated to state management.
> 
> The documentation is up to date with the latest stable version. What do you miss?

I am trying to say we need example apps with different architectures. For example there may be an example using Isar via bloc pattern or provider pattern. Also there must be a simple example app using set state style like basic flutter.

Documentation can be improved like hive db.

**Comment by leisim** [comment]
Check out the new pub example app https://github.com/isar/isar/tree/main/examples/pub
