### ISSUE TITLE
IsarCollection methods [eg; count(), findAll()] doesn't seem to return anything when a collection doesn't have initial entries. 

### ISSUE THREAD

**Issue by atercode** [isar/isar#542]
On Isar 2.5.0, I'm trying to run a count check for the local db if there aren't any values then conduct an initial pull request from the remote DB else do an incremental pull request.

I've run into this challenge where for collections that have values it returns the count but for where no initial value has been inserted, then the code seems to stall at the point of "awaiting". Is it possible to check if a collection is instantiated vs initialized? Or even initialized with no values therefore returning a count of 0?

**Code sample**
final mainDB = Isar.getInstance(mainDBInstaceName);
debugPrint("Fetching Possible CustomTypeObjects");
var countCustomTypeObjects = await mainDB?.getCollection<CustomType>().count();
debugPrint("Hey $countCustomTypeObjects");

Also tried this format but same thing.
var countCustomTypeObjects = await mainDB?.customTypes.count(); which is essentially the generated type

**Version**
 - Platform: Android, Web ; only tested on these two platforms for now
 - Flutter version: 3.0.4
 - Isar version: 2.5.0

**Comment by atercode** [comment]
@leisim  found what the issue is, there are 2 similar "CustomTypes" in our implementations. Realized when trying to debug by adding timeouts as a temporary measure. When trying this IsarCollection<CustomType>? customTypeCollection = await mainDB?.getCollection<CustomType>(); it still freezes the await if the type isn't found. Is there a way to throw an exception or something from the getCollection method for future reference?

**Comment by leisim** [comment]
This has been fixed in `3.0.0-dev.9`
