### ISSUE TITLE
IsarLinks  `loadSync/load`supports to query orderly

### ISSUE THREAD

**Issue by Allenxuxu** [isar/isar#548]
The result currently querying through `loadSync/load` is random.

**Comment by leisim** [comment]
Yes because IsarLinks is a set so it has no guaranteed order. Use `IsarLinks.filter()` to sort the linked objects.

**Comment by westy92** [comment]
@leisim would it be possible to instead use an ordered set?

@Allenxuxu as a workaround, I compute the `id`s for each linked item and store another list with just the linked `id`s. Upon retrieval, I sort the output to match this additional list.
