### ISSUE TITLE
Migrations and post-migration callbacks

### ISSUE THREAD

**Issue by listepo** [isar/isar#55]
I would like to have a mechanism for schema/data migration
like https://moor.simonbinder.eu/docs/advanced-features/migrations/#post-migration-callbacks
and https://docs.mongodb.com/realm/sdk/react-native/examples/modify-an-object-schema

**Comment by leisim** [comment]
@listepo I thought about it but didn't come up with a feature that could not be implemented by the users themselves very easily.

Isar does migrate your models (like removing fields or creating an index) and you can just store the version of your data in shared preferences and do data migration yourself.

Do you have a suggestion how Isar could simplify migration?

**Comment by listepo** [comment]
>you can just store the version of your data in shared preferences and do data migration yourself

How fast will the migration of millions of records be? can the shared preferences fit all this data?

> Isar does migrate your models (like removing fields... 

I am afraid that this may lead to the loss of user data if errors are made in the code

> Do you have a suggestion how Isar could simplify migration?

I like how it works in https://docs.mongodb.com/realm/sdk/react-native/examples/modify-an-object-schema/ and post-migration callbacks in https://moor.simonbinder.eu/docs/advanced-features/migrations/#post-migration-callbacks (for example, I'm starting a new project and there is not enough place where I could fill the database with the default data like `beforeOpen` with `wasCreated ` in [moor](https://moor.simonbinder.eu/docs/advanced-features/migrations/#post-migration-callbacks))

@listepo could we provide something like this in Isar? possibly as a separate package

**Comment by leisim** [comment]
@listepo

> How fast will the migration of millions of records be? can the shared preferences fit all this data?

That's not what I mean. You can just store the version of your data in shared preferences (like "v6") and before you use the database you check the version in shared preferences and perform the required migrations. It allows you to implement "pre and post migration callbacks" like moor.

The document you liked from the realm docs is unnecessary in Isar. Everything is done automatically without you providing a "schemaVersion" or something like that. There is a section in the docs about [legal modifications](https://isar.dev/schema#schema-migration).

> I am afraid that this may lead to the loss of user data if errors are made in the code

Yes it does. If you remove a field that you want to keep that's on you but no database can stop you from errors like that.

> could we provide something like this in Isar? possibly as a separate package

Do you still think there is something missing?

**Comment by listepo** [comment]
@leisim thanks for clarifying, I will try to follow your recommendations

**Comment by leisim** [comment]
@listepo please let me know if I can somehow simplify schema or data migration

**Comment by listepo** [comment]
@leisim I am thinking of a package that would provide a simple api to implement the above: saving the database version, provide beforeOpen hook or something similar

**Comment by leisim** [comment]
@listepo That's a great idea for a package. The reason why I'm hesitant to implement it into Isar is that I don't want to complicate the API with opinionated features.

**Comment by tijanirf** [comment]
I am so sorry for necroposting,

@listepo could you share your solution for this problem? I am interested in how we can scale the migration 

@leisim is there an official migration feature on the Isar roadmap? I can't find a similar topic elsewhere, I'd like to subscribe to the discussion

**Comment by dalewking** [comment]
The proposed scheme of storing a schema version number in a shared preference is a very bad plan, because you are storing it separate from the database and not under a transaction so there is potential for the shared preference and the database to be out of sync.

Any schema version must be stored in the database and only written as part of the transaction that is migrating the data. That is still something that a user CAN do themselves but would be a lot more convenient to provide support for it.

**Comment by simc** [comment]
@dalewking just store the version number in Isar then. I don't really see the difficulty

**Comment by dalewking** [comment]
Yes, I know I can do all that work myself, but it seems an awful burden to tell every user of Isar to do that work when it could be done once and provided to everyone.
