### ISSUE TITLE
Missing UUID support in the documentation

### ISSUE THREAD

**Issue by Chris1234567899** [isar/isar#556]
Using UUIDs is quite common, especially with offline data & sync. I understand that isar only supports integer ids out of the box - fair enough.
There are a couple of issues here however that suggest using Strings or UUIDs in combination with an auto increment isar ID, but unfortunately it is highly unclear whether or how this can be implemented. The "solutions" posted there offer just enough info to let us know, that somehow it is probably possible, but not how.

Please add this very common use case in the docs - with a working, up to date and precise instruction.
Thanks, would really appreciate that.

**Version**
 - Isar version: 2.5.0

**Comment by leisim** [comment]
I won't do that because if I do, users will blindly copy that solution even though I discourage using UUIDs in Isar. Please let me know what is unclear exactly :)

```dart
@Collection()
class Example {
  Id? id;
  
  @Index(unique: true, replace: true)
  String uuid;
}
```

**Comment by Chris1234567899** [comment]
Thanks for the response.
I tried that, both in 2.5 and the latest 3.x.preview, but it creates always a new entry instead of overwriting the existing one. So I thought there must be more to it? Or maybe it's a bug? I've seen this issue existed in the past but was closed as solved...

The thing with UUIDs is that often you have no say in the development in the backend and if you have to keep data in sync between server and device, being able to rely on the consistent keys (& foreign keys!) makes your life way easier. So whether you encourage it or not, plenty of users will want (or have to) work with different key types anyway ;-)

**Comment by leisim** [comment]
If you want to replace by uuid use `col.putByUuid()` instead of `col.put()`.

**Comment by shihuayong** [comment]
Hi @leisim, I strongly agree with @Chris1234567899 about the String type ID!!! I was planning to use Isar these days util I found it tells me "Only int ids are allowed". I've never seen a database that doesn't support using String as ID. It's really important for some business. Now, I have to choose other databases.

Hope that one day it could support string id :)

**Comment by leisim** [comment]
@shihuayong please provide a reason why you can't use a unique index instead of a string id.

**Comment by shihuayong** [comment]
Thanks for your response. It's not my decision. The server side is using string id and we share the same models.

**Comment by leisim** [comment]
Yes but you can easily model string ids using an index. It makes not difference.

**Comment by shihuayong** [comment]
That's a solution. I'll consider it.
