### ISSUE TITLE
Allow default values for fields

### ISSUE THREAD

**Issue by MaddinMade** [isar/isar#558]
**Is your feature request related to a problem? Please describe.**
When you add a new field to a collection, you often want to set a default value for all objects that do not (yet) have the field in the database.
For example, you might want a `bool` to default to `true`, but Isar defaults it to `false`. You could make the field nullable and handle the null cases yourself, but that's messy.

**Describe the solution you'd like**
A new annotation could be introduced so that you can assign a default value to fields:
```
@Default(true)
final bool myBool;
```
Alternatively, the default values could also be taken from the constructors.
```
MyClass({this.myBool = true});
```
Since the default values are traded in Dart, the implementation would be relatively simple.

**Comment by leisim** [comment]
This is already implemented in the main branch :) going to be released in a few days.

**Comment by MaddinMade** [comment]
@leisim Oh sorry, I didn't know that 😅
