### ISSUE TITLE
Don't see .sortBy(), .sortByDesc(), .thenBy() and .thenByDesc() option on the collection where clause

### ISSUE THREAD

**Issue by dgandhi17** [isar/isar#56]
Not able to do the .sortBy(), .sortByDesc(), .thenBy() and .thenByDesc() operation as the methods are not there for the
collection as mentioned in documentation https://isar.dev/queries Sorting. Did you removed it?

@leisim

**Comment by leisim** [comment]
😱😅 They are not implemented yet. Core already supports sorting I just need to provide these methods in the code generator. I'll implement them for the coming new version.

**Comment by leisim** [comment]
Here is the problem: https://github.com/isar/isar/blob/main/packages/isar_generator/lib/src/code_gen/query_sort_by_generator.dart

**Comment by dgandhi17** [comment]
@leisim  I was going through documentation for queries helper method and find out that those are not available. Thought am i doing anything wrong or what is the reason.

**Comment by dgandhi17** [comment]
By the way can you update the document to match with the version supports ? Last week only I started a big project that has around 15+ collection and I will need good documentation to get help.

**Comment by leisim** [comment]
> By the way can you update the document to match with the version supports ? Last week only I started a big project that has around 15+ collection and I will need good documentation to get help.

You mean provide a way to view docs for an older version? I'm not sure if that's possible with docusaurus. I'll try to implement it. The docs are lacking anyway. I'd be grateful for some community help :)

**Comment by dgandhi17** [comment]
Well only the core developers will know what is being implemented and working. I mean to say the version 0.2.0

**Comment by leisim** [comment]
Fixed with the newest version
