### ISSUE TITLE
Watch object by unique index

### ISSUE THREAD

**Issue by DevNico** [isar/isar#566]
I'd like to watch objects by a unique index value. Currently, you'd need to watch the entire collection for changes and then query the respective object.

I am unsure whether this could be implemented in a way that would be that much more performant to justify additional methods for each unique index?

**Comment by leisim** [comment]
I would watch a query with a where clause or filter matching your index value. That is the most performant way to do it. Even a dedicated way to watch by index would not be faster that's why I didn't implement it.

**Comment by DevNico** [comment]
Alright closing as per your comment.
