### ISSUE TITLE
The method 'repeat' isn't defined for the type 'QueryBuilder'

### ISSUE THREAD

**Issue by philos3** [isar/isar#573]
**Steps to Reproduce**
The method 'repeat' isn't defined for the type 'QueryBuilder'. 
Try correcting the name to the name of an existing method, or defining a method named 'repeat'.

**Code sample**
```
Query<Quote> buildQuery({bool offsetLimit = false}) {
    final searchTermWords = searchTerm.split(RegExp(r'\s+'));
    return widget.isar.quotes.where()
        .repeat(
          searchTermWords,
          (q, String word) => q.optional(
            word.isNotEmpty,
            (q) => q.textWordsAnyStartsWith(word),
          ),
        )
        .filter()
        .optional(
          author.isNotEmpty,
          (q) => q.authorEqualTo(author),
        )
        .optional(offsetLimit, (q) => q.offset(quotes.length).limit(20))
        .build();
  }
```

**Version**
 - Platform: iOS, Android
 - Flutter version: 3.0.5
 - isar: 3.0.0-dev.8
 - isar_flutter_libs: 3.0.0-dev.8
 - isar_generator: 3.0.0-dev.8

![image](https://user-images.githubusercontent.com/8424317/185788218-c5678d55-1193-4eba-b540-a7208b0a4230.png)

**Comment by Jtplouffe** [comment]
The `repeat` method is being replace with `anyOf` and `allOf` methods in 3.0.
I don't think the documentation for 3.0 is up yet, but you can take a look at this unit test, which uses those methods
https://github.com/isar/isar/blob/main/packages/isar_test/test/query/any_of_all_of_test.dart

**Comment by philos3** [comment]
https://isar.dev/queries.html#filters still use repeat，just add the  tutorilas doc  a version
