### ISSUE TITLE
Flutter exits with error when starting using flutter run

### ISSUE THREAD

**Issue by Coinmaster123456** [isar/isar#585]
Flutter gives back these error when trying to launch isar 3.0.0-dev.8 in a web app
Desktop and Mobile compile just fine and also run like normal
![image](https://user-images.githubusercontent.com/70707774/186508586-31fe0ef3-9131-4f7a-b14f-93fc8b1a7ebc.png)

**Comment by leisim** [comment]
Flutter web is not supported in 3.0.x yet.

Duplicate of #535
