### ISSUE TITLE
Can't test the 3.0.0-dev.12 since isar_flutter_libs is still in 3.0.0-dev.10 on pub.dev

### ISSUE THREAD

**Issue by FredJul** [isar/isar#587]
I guess it's simply a forgetting or a problem with the deployment pipeline but I would have expected to see isar_flutter_libs 3.0.0-dev.12 on pub as well since the app does not seems to start without:
`IsarError: Incorrect Isar Core version: Required 3.0.0-dev.12 found 3.0.0-dev.10. Make sure to use the latest isar_flutter_libs. If you have a Dart only project, make sure that old Isar Core binaries are deleted.`

**Comment by leisim** [comment]
Yeah I currently have problems with the release CI. Thanks for opening this, I'll update as soon as I have news 🙂

**Comment by leisim** [comment]
Fixed :)

**Comment by FredJul** [comment]
That was quick! Thanks a lot.
