### ISSUE TITLE
Unhandled Exception: IsarError: LmdbError (12): "Cannot allocate memory"

### ISSUE THREAD

**Issue by dgandhi17** [isar/isar#59]
I simply ran the app which tries to open the isar it is random. 
Note : My iPAD has enough storage in GBs.

Having 15+ tables and 7k+ records overall.

**Comment by leisim** [comment]
@dgandhi17 That's weird. Does the same error happen on an iPhone? Does it happen randomly or is it reproducible?

**Comment by dgandhi17** [comment]
Its random only. Ipad mini 4.
I don't have iPhone, testing on iPhone simulator didn't happen.

**Comment by leisim** [comment]
@dgandhi17
Would be amazing if you could help me to reproduce this. Did you have maybe observe a pattern? Maybe you could even create a small sample app. If that's not possible any detail may help :)

**Comment by dgandhi17** [comment]
I am still working with my codebase, let me test my scenarios in couple days then may be I can share any pattern if it occurs

**Comment by dgandhi17** [comment]
Do you have in mind any ETA on stable release?

**Comment by leisim** [comment]
@dgandhi17 We need to fix this error asap. After that about 1-2 months.

**Comment by dunm165913** [comment]
@leisim Do you fix this error? 
I tested on simulator, it was not happen, but on iOS device(iphone X, ipad air 4) both debug and release mode, i got error.

**Comment by Enlarge-RyotaTsunoi** [comment]
We faced this problem too.
It did not occur in the simulator, but only in the behavior on the device.
Device: iPhone X 

We were able to work around it by setting the maxSize argument of the openIsar function to 1/10 of the default value, which is a temporary workaround.
More detailed information will be provided if needed.

I hope this issue will be resolved soon.

**Comment by leisim** [comment]
Fixed with stable release
