### ISSUE TITLE
Set support dropped with TypeConverter in 3.0.0-dev.12

### ISSUE THREAD

**Issue by starkdmi** [isar/isar#594]
**Steps to Reproduce**
```Set<String>``` property isnt's supported in newer than **3.0.0-dev.8** because TypeConverter was removed from package.
It's really simple type though, Dart support two way convertion internally via ```toSet()``` and ```toList()```.

**Code sample**
```dart
class SetConverter extends TypeConverter<Set<String>, List<String>> {
  const SetConverter(); 
  @override Set<String> fromIsar(List<String> object) => object.toSet();
  @override List<String> toIsar(Set<String> object) => object.toList();
}
```

Isar generator fails with suggestion to use `@enumerated`.

**Version**
 - Platform: Mac
 - Flutter version: 3.0.5
 - Isar version: 3.0.0-dev.12
 - Isar Generator version: 3.0.0-dev.12

**Comment by leisim** [comment]
Please use Lists instead of Sets. If you still want to keep using Sets in your model do the following:

```dart
@collection
class YourModel {
  Id? id;

  @ignore
  Set<int>? yourSet;

  List<int>? get yourIsarSet => yourSet?.toList();
}
```

`@enumerated` is only for enums. Since there is an easy workaround and I don't want to complicate the Isar code and API unnecessarily I'll close this issue for now 🙂

**Comment by starkdmi** [comment]
Thanks, looks like setter is requred too.
```dart
@collection
class SomeModel {
  Id? id;

  @ignore
  Set<int>? someSet;

  List<int>? get isarSet => someSet?.toList();
  set isarSet(List<int> list) => someSet = list.toSet();
}
```
