### ISSUE TITLE
Cannot connect to isar inspector when the database is initialised inside of a background service

### ISSUE THREAD

**Issue by IttaiBarkai** [isar/isar#597]
Firstly thanks for this amazing package :) Recently moved away from sqflite to isar. 

**Steps to Reproduce**
When I add the following lines of code below in the app's main function I am able to connect to the isar inspector without any issues:

`final directory = await getApplicationSupportDirectory();`
`final isar = await Isar.open(schemas: [ServiceTripTrackSchema], directory: directory.path, inspector: true);`

However, if instead I add these lines of code to the onStart function of my background service (using flutter_background_services package), I am unable to connect. I don't have any error messages in my debug console and I still get the usual ISAR CONNECT STARTED message with the url provided. I copy the url to the inspector, press connect and nothing happens.  

<img width="458" alt="Screenshot 2022-08-28 at 14 48 32" src="https://user-images.githubusercontent.com/53575993/187072673-4d11b83a-dd7f-46d1-8705-0910bc32e959.png">

Any help solving this issue would be greatly appreciated! 

**Version**
 - Platform: iOS
 - Flutter version: [3.0.5]
 - Isar version: [2.5.0]
 - Isar Generator version: [2.5.0]

**Comment by leisim** [comment]
The old inspector is not super reliable. The community and I have put a ton of work into the new web-based inspector. You can already test it in `3.0.0-dev.8` and you don't need to install anything anymore.
Because the old one will be obsolete very soon I don't really want to invest time fixing it. Hope you understand that 🙂

**Comment by IttaiBarkai** [comment]
Thanks for the quick response and totally understandable :) I followed your suggestion, unfortunately I still seem to be getting an issue with opening the inspector when the database is initialised in the background service. I get the following message on my chrome browser and no errors in the debug console. 

<img width="1044" alt="Screenshot 2022-08-28 at 16 30 52" src="https://user-images.githubusercontent.com/53575993/187076452-bf43e64a-e662-47cf-bfde-f84376c476a1.png">

![Screenshot 2022-08-28 at 16 29 02](https://user-images.githubusercontent.com/53575993/187076363-910218b1-5f36-43f5-893c-3c6df66bd7fa.png)

**Comment by leisim** [comment]
Make sure that you don't use the newest release but `3.0.0-dev.8`.

Set it to `isar: 3.0.0-dev.8` instead of `isar: ^3.0.0-dev.8`

**Comment by IttaiBarkai** [comment]
This is a picture of my yaml

<img width="992" alt="Screenshot 2022-08-28 at 16 38 48" src="https://user-images.githubusercontent.com/53575993/187076729-fd0a3443-0289-436f-b94f-b5eb0db80fa5.png">

**Comment by IttaiBarkai** [comment]
> Sorry, read your comment too quickly: Isar Inspector relies on the dart observatory protocol. I'm not sure it works in a background isolate.

ah okay I see

**Comment by leisim** [comment]
I'm going to close this for now because the Inspector can be used from the main Isolate.
