### ISSUE TITLE
Achieve feature parity (or near-parity) on web

### ISSUE THREAD

**Issue by AKushWarrior** [isar/isar#6]
Right now, the web repository is empty. We'll need to work on that ;)

We'll need to investigate the practicality of various things with IndexedDB. The main semantic effort will be creating a dexie-esque library which uses automerge CRDTs under the hood.

**Comment by frank06** [comment]
Re: relationships in IndexedDB

> The alternative, then is to run a query on the foreign database every time we need to find the foreign information by key, which is no longer a relationship at all. [from #4]

Right, I think that is attempted here: https://github.com/ignasbernotas/dexie-relationships/blob/master/src/index.js

As you say, those are not "real" relationships strictly speaking and performance might be subpar (makes sense it doesn't make it into Isar) but as a third party module they do bring convenience. These same third-party tools, in their scope, can also offer referential integrity.

**Comment by AKushWarrior** [comment]
> As you say, those are not "real" relationships strictly speaking and performance might be subpar (makes sense it doesn't make it into Isar) but as a third party module they do bring convenience. These same third-party tools, in their scope, can also offer referential integrity.

I can see the idea here. I think that having external libraries, which function primarily as a wrapper over Isar, could be helpful (especially considering how fast Isar will be on native). On the other hand, that might not be the foremost concern (for now).

**Comment by viveknimkarde** [comment]
We have been using hive since last year and planning to move to isar db.
It Looks pretty amazing but we need web support to be able to migrate from hive.

I would like to know how far the web support is on the roadmap. as I don't see much web related activity in this repo ?

**Comment by leisim** [comment]
@viveknimkarde Unfortunately web support is not a priority currently. Unless someone wants to contribute, I think it will take about 3-4 months until web support is ready.

**Comment by viveknimkarde** [comment]
Glad to know web support is not very far away. Web support will play huge role in building crossplatform apps using isar  as flutter web has seen huge developments in recent months.

**Comment by AKushWarrior** [comment]
@viveknimkarde I had started it, but I've been really busy. I didn't make too much progress; I remember opening a discussion with my progress on one of the isar repositories, but I'm not sure where it is.

**Comment by AKushWarrior** [comment]
Found it: https://github.com/isar/isar/discussions/23

If anyone is looking at this and wants to contribute to web, that would probably be your starting point.

**Comment by leisim** [comment]
Done :)
