### ISSUE TITLE
Multiple Instance with same or different Schemas on Web and Android

### ISSUE THREAD

**Issue by pradeep-here** [isar/isar#605]
**Steps to Reproduce**

**Create 2 Schemas** 
Schema1 and Schema2

**Create 3 Instances** 
instance_1 = await Isar.open(
        name: 'ins_one',
        schemas: [Schema1],
      );
instance_2 = await Isar.open(
        name: 'ins_two',
        schemas: [Schema1],
      );
instance_3 = await Isar.open(
        name: 'ins_three',
        schemas: [Schema2],
      );

Above Code works differently on Web and Android
**On Web,** 
its creating instance_1 and instance_2, I can read/write to these and verified these are different instances.
but not creating instance_3 - cannot open multiple isar instances with different schema

**On Android,** 
All (instance_1, instance_2 and instance_3) are pointing to same instance seems.
whatever I write to any of these, I can read from other.

**Please advise if this is planned in Isar to allow opening 2 instances with different schemas on all platforms, or is it not planned in Isar**

**Version**
 - Platform: Android, Web
 - Flutter version: 3.0.5
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Comment by leisim** [comment]
Hey, this is not planned because it does not bring advantages. Just add all schemas to all instances and only use the ones you actually need. There is zero performance cost for unused schemas.

**Comment by pradeep-here** [comment]
Ok, thanks for quick clarification. 
On Android I observed all instances were pointing to same instance somehow. Is it some issue or was I doing something wrong.

**Comment by pradeep-here** [comment]
hi @leisim 

Here is my test code with 2 instances having same schema
**On Android its not working as expected.** 
On Web its working fine.

**Schema - Employee**
```
import 'package:isar/isar.dart';

part 'employee.g.dart';

@Collection()
class Employee {
  @Id()
  int? id;

  String? name;

  @Index(unique: true)
  String? empId;

  @override
  String toString() {
    return "($id / $empId / $name)";
  }
}

```

**Test widget**
```
import 'package:flutter/foundation.dart';
import 'package:isar/isar.dart';
import 'package:isar_test_proj/employee.dart';
import 'package:path_provider/path_provider.dart';
import 'package:flutter/material.dart';

class IsarInstanceTest extends StatefulWidget {
  const IsarInstanceTest({Key? key}) : super(key: key);

  @override
  State<IsarInstanceTest> createState() => _IsarInstanceTestState();
}

class _IsarInstanceTestState extends State<IsarInstanceTest> {
  Isar? instance_1;
  Isar? instance_2;

  Future<bool> isarOpen1() async {
    if (kIsWeb) {
      instance_1 = await Isar.open(
        name: 'db_one',
        schemas: [EmployeeSchema],
      );
    } else {
      final dir = await getApplicationSupportDirectory();

      instance_1 = await Isar.open(
        schemas: [EmployeeSchema],
        directory: dir.path,
      );
    }
    print('isarOpen1.. opened name: ${instance_1?.name}');
    return true;
  }

  Future<bool> isarOpen2() async {
    if (kIsWeb) {
      instance_2 = await Isar.open(
        name: 'db_two',
        schemas: [EmployeeSchema],
      );
    } else {
      final dir = await getApplicationSupportDirectory();

      instance_2 = await Isar.open(
        schemas: [EmployeeSchema],
        directory: dir.path,
      );
    }
    print('isarOpen2.. opened name: ${instance_2?.name}');
    return true;
  }

  test() async {
    print('Starting test');

    try {
      print('isarOpen1..');
      await isarOpen1();
      print('isarOpen2..');
      await isarOpen2();
    } catch (e) {
      print('Error: $e');
    }

    print('instance_1 name: ${instance_1?.name}');
    print('instance_2 name: ${instance_2?.name}');

    Employee a1 = Employee()
      ..empId = 'a1'
      ..name = 'a one';
    Employee a2 = Employee()
      ..empId = 'a2'
      ..name = 'a two';
    Employee b1 = Employee()
      ..empId = 'b1'
      ..name = 'b_one';

    print('data created..');

    await instance_1?.writeTxn((isar) async {
      await isar.employees.put(a1, replaceOnConflict: true);
    });
    print('instance_1.. write_1 done..');

    await instance_1?.writeTxn((isar) async {
      await isar.employees.put(a2, replaceOnConflict: true);
    });
    print('instance_1.. write_2 done..');

    await instance_2?.writeTxn((isar) async {
      await isar.employees.put(b1, replaceOnConflict: true);
    });
    print('instance_2.. write_1 done..');

    final allDataInstance1 = await instance_1?.employees.where().findAll();
    print('allDataInstance1: $allDataInstance1');

    final allDataInstance2 = await instance_2?.employees.where().findAll();
    print('allDataInstance2: $allDataInstance2');
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: Column(
            children: [
              const SizedBox(height: 50),
              const Text('Test Isar'),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () {
                  test();
                },
                child: const Text('Start Test'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```


**Console output on Android**

> Restarted application in 4,774ms.
> I/flutter (11264): Starting test
> I/flutter (11264): isarOpen1..
> I/flutter (11264): isarOpen1.. opened name: isar
> I/flutter (11264): isarOpen2..
> I/flutter (11264): Error: IsarError: Instance has already been opened.
> I/flutter (11264): instance_1 name: isar
> I/flutter (11264): instance_2 name: null
> I/flutter (11264): data created..
> I/flutter (11264): instance_1.. write_1 done..
> I/flutter (11264): instance_1.. write_2 done..
> I/flutter (11264): instance_2.. write_1 done..
> I/flutter (11264): allDataInstance1: [(1 / a1 / a one), (2 / a2 / a two)]
> I/flutter (11264): allDataInstance2: null
> Reloaded 1 of 857 libraries in 1,632ms.

**Console output on Web**

> Flutter Web Bootstrap: Programmatic
> Starting test
> isarOpen1..
> isarOpen1.. opened name: db_one
> isarOpen2..
> isarOpen2.. opened name: db_two
> instance_1 name: db_one
> instance_2 name: db_two
> data created..
> instance_1.. write_1 done..
> instance_1.. write_2 done..
> instance_2.. write_1 done..
> allDataInstance1: [(1 / a1 / a one), (2 / a2 / a two)]
> allDataInstance2: [(1 / b1 / b_one)]

**Comment by leisim** [comment]
@pradeep-here it is working? Can we close this issue then or is there something else I can help you with? 🙂

**Comment by pradeep-here** [comment]
@leisim  yes please close this ticket, thank you.
