### ISSUE TITLE
inspector  don't open 

### ISSUE THREAD

**Issue by samithe7** [isar/isar#606]
**Steps to Reproduce**
Please describe exactly how to reproduce the problem you are running into.

**Code sample**
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final isar = await Isar.open(
      [  MxLikeSchema ],
       inspector: true,
  );

  runApp(QuotesApp(
    isar: isar,
  ));
}
```

**Version**
 - Platform: i Android, 
 - Flutter version: 3.3.0
 - Isar version: ^3.0.0-dev.13
 - Isar Generator version: ^3.0.0-dev.13

error mass : 

W/isarworker(14826): type=1400 audit(0.0:123): avc: denied { getattr } for path="/metadata" dev="vdd1" ino=2 scontext=u:r:untrusted_app:s0:c157,c256,c512,c768 tcontext=u:object_r:metadata_file:s0 tclass=dir permissive=0 app=com.example.local_dbtry

**Comment by leisim** [comment]
What device model does this happen on? Does the app crash or does the database still work?

**Comment by samithe7** [comment]
![ssssisra](https://user-images.githubusercontent.com/53804061/187547397-03bfa43a-3290-4876-94ee-50b9ebbedf45.png)

**Comment by samithe7** [comment]
> What device model does this happen on? Does the app crash or does the database still work?

app work  fine   ,Isar Inspector    give  url   'https://inspect.isar.dev/3.0.0-dev.13/#/9881/3C9sZlbPwLQ  . but  inspector web url don't work

**Comment by leisim** [comment]
The inspector is not supported on the newest dev version yet. Please use `3.0.0-dev.8` if you need it

**Comment by samithe7** [comment]
thanks 👍👍👍
