### ISSUE TITLE
Unsupported type Uint8List

### ISSUE THREAD

**Issue by zawadZwd** [isar/isar#607]
Hello, I'm trying to create a new collection, but during the schema generation, I'm getting an error:

```dart

Unsupported type. Please annotate the property with @ignore.
11 │   Uint8List? avatar;

```

**Code sample**

```dart
import 'dart:typed_data';
import 'package:isar/isar.dart';

part 'contact_schema.g.dart';

@Collection()
class ContactData {

  Id id = Isar.autoIncrement;
  Uint8List? avatar;
  late String contactId;
  late String number;
  late String name;
}
```

At first I thought this is about new Flutter version (3.3.0), but when I switched down the version to 3.0.5, and the error still occurs.
In the online [documentation](https://isar.dev/schema.html#annotating-classes) is information that Isar supports Uint8List, but maybe this is about version 2.5.0 of Isar 🤔
Or probably I am doing something not right, this is also possible 😅
Helph ^^

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 3.3.0
 - Isar version: ^3.0.0-dev.13
 - Isar Generator version: ^3.0.0-dev.13

**Comment by leisim** [comment]
The 3.0.0-dev versions are not documented yet. The new type is called `List<byte`.

You can do the following:
```dart
List<byte>? avatar; // you can assign a Uint8List to this.
```

**Comment by zawadZwd** [comment]
That was the fastest reply in the history of replies 👀
and also helpful, thank you for your time!

**Comment by leisim** [comment]
Shall we close this issue? 🙂

**Comment by zawadZwd** [comment]
Yes sir! Thank you once again 😊

**Comment by triggerfx** [comment]
In Isar 3 Uint8List is not supported anymore. Converting many images from List<byte> to Uint8List, they will blink on StateRefresh because of the conversion at every rebuild. I would like to see Uint8List available again.
