### ISSUE TITLE
Isar does not terminate when launched from the command line

### ISSUE THREAD

**Issue by ivoleitao** [isar/isar#611]
**Steps to Reproduce**
When I create a very simple Isar command line application every time I run it does not close (pure command line, vs code terminal or vscode debugger). This only happens with the async version of open:

* `await Isar.open([ContactSchema], directory: '.dart_tool', inspector: false);` does not work
*  `Isar.openSync([ContactSchema], directory: '.dart_tool', inspector: false);` works

From my past experiences this normally happens when a resource (like a socket) is not closed but no idea what is happening in this case

**Code sample**
```
import 'dart:ffi';
import 'dart:io';

import 'package:isar/isar.dart';
import 'package:isar_bug/src/bug/contact.dart';

void main() async {
  // Initialize Isar
  await Isar.initializeIsarCore(libraries: {
    Abi.current(): '${Directory.current.path}/.dart_tool/libisar.dylib'
  }, download: true);

  // Temporary directory
  final path = Directory.systemTemp.path;

 // Tried with inspector false and inspector true no difference
final isar = await Isar.open([ContactSchema],
      directory: '.dart_tool', inspector: false);

// The sync version works
// final isar = Isar.openSync([ContactSchema], directory: '.dart_tool', inspector: false);

  // returns true
  print(await isar.close());
}
```

**Version**
 - Platform: Mac
 - Flutter version: 3.3.0
 - Isar version: 3.0.0-dev.13
 - Isar Generator version: 3.0.0-dev.13

**Comment by leisim** [comment]
Thanks for reporting. This has been fixed in the main branch and will be release soon.
