### ISSUE TITLE
Allow query based on persisted fields

### ISSUE THREAD

**Issue by SEGVeenstra** [isar/isar#618]
**Is your feature request related to a problem? Please describe.**
For the puzzle game I'm working on I need to:

> find all puzzles that have been solved with the minimum amount of possible moves.

I'm storing the puzzle with:
1. minMoves (minimum amount of moves in which this puzzle can be solved)
2. currentBest (the least amount of moves the player has used to solve the puzzle)

So what I need is all the puzzles where: `minMoves == currentBest`.

**Describe the solution you'd like**
I think it would be nice that the code maybe could generate comparison functions for that.

So maybe something like:
```dart
await _isar.getCollection<Puzzle>()
        .filter()
        .minMovesEqualsCurrentBest() // also: minMovesLessThenCurrentBest, minMovesGreaterThenCurrentBest, etc
        .findAll();
```

**Describe alternatives you've considered**
My current work-around is adding a boolean when storing the `Puzzle` which simply holds the result of `minMoves == currentBest`.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 3.0.5
 - Isar version: 2.5.0

**Comment by leisim** [comment]
I like this idea. A few concerns:
- this would generate 3*n! more query methods (n = number of properties)
- this api does not work well with embedded objects
- it is unclear what happens with properties of different types

I'm sure we can find solutions to these but I'd like to see whether others need this feature too. It's quite a lot of work to implement and test.

**Comment by SEGVeenstra** [comment]
> this would generate 3*n! more query methods (n = number of properties)

Maybe it can be optional, so the user can `Annotate` a property (like with the indexes)?
This way you only generate the function for what you configured.

> this api does not work well with embedded objects

I don't know what that means :(

> it is unclear what happens with properties of different types

No clue for this yet either.

**Comment by leisim** [comment]
I thought a little more about it and I think adding a getter that returns `minMoves == currentBest` is the best option.
It is easy to implement, fast and space efficient 🤷🏼‍♂️

And it also supports more complex things: it would be very difficult to have a `tags.contains(username)` condition.

**Comment by cgestes** [comment]
Just my 2 cents, would some kind of API like this be possible: 
```dart
await _isar.getCollection<Puzzle>()
        .filter()
        .eq(PuzzleSchema.minMoves, PuzzleSchema.currentBest).findAll();
```

**Comment by leisim** [comment]
Yeah but what happens if `minMoves` is a float and `currentBest` an integer? Or how can you compare properties of embedded objects?
I think exposing a getter is the better solution.

**Comment by cgestes** [comment]
I though about it more, and from what I understand filtering is just the same as filtering a list or a map (it doesn't use indexes), so yeah using the same system as dart uses would make sense. it's actually already possible and what I would do.

```dart
await _isar.getCollection<Puzzle>()
        .findAll()
        .where((a) => a.minMove == a.CurrentBest);
```

it's just a bit confusing what the where means. It changes meaning before and after the findAll(). (Usually I split my request in two separated lines for that reason).

From what I understand, what would make this request faster would be to store an index with the result of the equality, but I guess this is another story :)

**Comment by leisim** [comment]
The recommended way of doing this is adding a getter to your class. It does not make sense for Isar to support this feature natively.
