### ISSUE TITLE
Why didn't you save two records?

### ISSUE THREAD

**Issue by catalunha** [isar/isar#620]
![image](https://user-images.githubusercontent.com/19995819/188180854-58df9c9b-e8b7-4064-8a39-806b078aab1b.png)

**Comment by leisim** [comment]
You gave both objects the same id.

**Comment by catalunha** [comment]
OK. I was using the same ObjectBox approach which creates an id for me with each insert.
So in Isar I manage the Id myself?
Testing here.

**Comment by catalunha** [comment]
Sorry. Sorry. It is true
```Dart
@Collection()
class ContactModel {
  Id? id; //or Id id = Isar.autoIncrement;
  late String name;

  @override
  String toString() => 'ContactModel(id: $id, name: $name)';
}
```
