### ISSUE TITLE
Isar.dev website not working.

### ISSUE THREAD

**Issue by muddassar-lab** [isar/isar#627]

**Comment by leisim** [comment]
Thanks for letting me know. It's fixed. Sorry for the downtime...

**Comment by muddassar-lab** [comment]
Thanks, Simon for fixing it so fast.

**Comment by keybow007** [comment]
unfortunately downtime happening again...

![スクリーンショット 2022-09-06 15 44 31](https://user-images.githubusercontent.com/12907755/188565523-27cb1070-88f1-4c5e-9271-595eeeced6ec.png)

**Comment by leisim** [comment]
Should be fixed :)

**Comment by keybow007** [comment]
Thanks!

![スクリーンショット 2022-09-06 19 40 00](https://user-images.githubusercontent.com/12907755/188618046-d561d07b-368d-4db1-bcbe-e751792ba8c0.png)
