### ISSUE TITLE
IsarError when calling .clear() or .clearSync() - Write operations require an explicit transaction.

### ISSUE THREAD

**Issue by JamesHertzog** [isar/isar#637]
**Steps to Reproduce**
Originally ran into this problem in our application, so I created a new Flutter project to recreate this issue.

I used the example on pub dev, using the `Post` class as the object being stored.

1) Create an `Isar` instance
2) Write some objects into the instance.
3) Call `isar.clear()` or `isar.clearSync()`

Both functions throw the same error:
`Unhandled Exception: IsarError: Write operations require an explicit transaction.`

**Code sample**

Isar object & initState:
```
  Isar? isar;

  @override
  void initState() {
    super.initState();
    _initIsar();
  }
```
Isar Setup: 
```
  Future<void> _initIsar() async {
    final dir = await getApplicationSupportDirectory();

    isar = await Isar.open(
      [PostSchema],
      directory: dir.path,
    );

    for (int i = 0; i < 50; i++) {
      await isar?.writeTxn(() async {
        final post = Post();
        post..title = "Post $i";
        post..date = DateTime.now();
        await isar?.posts.put(post);
      });
    }
  }
```
Function Call:
```
onPressed: () {
    isar?.clearSync();
},
```

I also just have a widget to display the amount of objects in the collection:
```
Text('Post Count: ${isar?.posts.countSync()}'),
```

**Version**
 - Platform: Tested on iOS - both a simulator and a physical iPhone 12 Pro Max, as well as a iPhone 13 Pro Max
 - Flutter version: `3.3.0`
 - Isar version: Tested both `2.4.0` that we use in our application, as well as `3.0.0-dev.13`
 - Isar Generator version: Tested both `2.4.0` that we use in our application, as well as `3.0.0-dev.13`
 
 **Screenshot**
 Here is the stack trace:
 
![image](https://user-images.githubusercontent.com/104830843/188838482-ae27bd20-18b9-4c33-8ade-efb7e938b682.png)

**Comment by leisim** [comment]
Since `clear` and `clearSync` write to the database they need to be wrapped in a write transaction 🙂

**Comment by JamesHertzog** [comment]
Thank you for the quick response.

I just tested this in the sample app and everything is working as expected.

I will mark this issue as closed.
