### ISSUE TITLE
No id property defined. Use the "Id" type for your id property.

### ISSUE THREAD

**Issue by saddig** [isar/isar#639]
**Steps to Reproduce**
Using Isar 3.0.0-dev.14 the Isar generator fails to generate the Id property properly when using Isar in combination with freezed.

**Code sample**
```
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:isar/isar.dart';

part 'foo.freezed.dart';
part 'foo.g.dart';

// ignore_for_file: invalid_annotation_target
@freezed
@Collection(ignore: {'copyWith'})
class Foo with _$Foo {
  Foo._();
  factory Foo({
    @Default(Isar.autoIncrement) Id localId,
    @Index(unique: true, replace: true) required String id,
    @Default('') String description,
  }) = _Foo;

  factory Foo.fromJson(Map<String, dynamic> json) =>
      _$FooFromJson(json);
}

```

**Version**
 - Platform: Linux
 - Flutter version: 3.3.0
 - Isar version: 3.0.0-dev.14 
 - Isar Generator version: 3.0.0-dev.14

**Comment by saddig** [comment]
So I think the problem comes from switching from Isar 3.0.0-dev.5 => 3.0.0-dev.14.

If I create a new file with the above code it works, but changing my existing code to the above results in an error:

Isar 3.0.0-dev.5 Code:

`
@freezed
@Collection()
class Foo with _$Foo {
  Foo._();
  factory Foo({
      @Id() int? localId,
      ...
`

**Comment by leisim** [comment]
I think that is a freezed issue. It does not use the `Id` typendef for the property.

**Comment by saddig** [comment]
The foo.freezed.dart file seems fine to me, but the foo.g.dart file does not contain any Isar related code.

**Comment by leisim** [comment]
Yes but you are not defining a real class with real properties but a constructor. Freezed turnes that into a class that the Isar Generator then analyzes.

But freezed changes the `Id` type to `int` and the Isar Generator has no way of knowing that it was an `Id`

**Comment by saddig** [comment]
Would it be possible to offer the old `@Id() int idName` annotations as well as the `Id` type?

I raised an issue in freezed aswell

**Comment by leisim** [comment]
This cannot be fixed by Isar.

**Comment by liemfs** [comment]
Any workaround?

**Comment by stevehayles** [comment]
> Any workaround?

I think the easiest workaround is along the following lines.  

In your freezed class factory constructor include an int? variable, and use a small mixin to expose that int as and Isar Id (which is just a typedef for an int anyway).  Override the mixin property and I think both the freezed and Isar generators will be happy.

```
mixin IsarId {
  Id? get isarId;
}

@freezed
@Collection(accessor: 'collectionName', ignore: {'copyWith'})
class MyModel with _$MyModel, IsarId {
    const factory MyModel({
        required double value1,
        required double value2,
        int? id,
    }) = _MyModel;

    const MyModel._();

    @override
    Id? get isarId => id;
}
```

I have been using this approach since the problem appeared as it seems the authors of both this library and freezed have good reason for things to remain as they are on their respective sides...   Two amazing projects though, and great benefits to using them together!

**Comment by junyip195** [comment]
Try declaring Id this way, its written in their  quickstart document
Id id = Isar.autoIncrement;

https://isar.dev/tutorials/quickstart.html#_1-add-dependencies
