### ISSUE TITLE
Unique index errors are thrown as IsarError, not IsarUniqueViolationError

### ISSUE THREAD

**Issue by spatialbits** [isar/isar#649]
**Steps to Reproduce**
[iOS/Android]
1. Create a model with a unique index property.
2. Create insert two instances with the same index value.
3. Error thrown is `IsarError` and the error message is `Unique index violated.`.

I notice that searching the GitHub Isar org for `IsarUniqueViolationError` shows the only instance of it being thrown is in the web implementation:

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/4192023/188998269-8bb7f4a5-355e-4db2-b956-84b3782b0358.png">

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.10.5
 - Isar version: 2.4.0
 - Isar Generator version: 2.4.0

**Comment by kulture-rob-snider** [comment]
dupe of #574

**Comment by leisim** [comment]
This is different actually. One is the incorrect error type the other is incorrect behavior on web
