### ISSUE TITLE
Renamed Model Class file issue 

### ISSUE THREAD

**Issue by darul9061** [isar/isar#653]
I renamed schema file name from "Customer" to "customer after generating part file. Tried regenerating part file again but get this error
<img width="860" alt="Screenshot 2022-09-08 at 07 08 51" src="https://user-images.githubusercontent.com/57532074/189075700-d345e7ec-0cd4-4770-bcea-60ad37bbe176.png">

What do i clear ? Does isar have a command to clear old renamed file it has stored?

**Comment by leisim** [comment]
Isar does not store files and this is not an Isar issue. Please check how to use build runner first. There is a `--delete-conflicting-outputs` option for build runner
