### ISSUE TITLE
Crash: mdbx:5945: pnl_check: assertion "limit >= 3 - 1" failed on 3.0.0-dev.14

### ISSUE THREAD

**Issue by MartiSilvio** [isar/isar#654]
Has anyone had your app crash with the above error while adding a lot of data (30k+ objects ~40MB from a list in memory)? I have tried running it both on the main isolate and on a separate isolate but same result.

**Version**
 - Platform: Android
 - Flutter version: 3:0:5
 - Isar version: 3.0.0-dev.14
 - Isar Generator version: 3.0.0-dev.14

**Comment by MartiSilvio** [comment]
`
Future<List<int>> _saveTask(
  final List<ReadingSheetRecord> records,
) async {
  // Gets already open Isar instance in new isolate
  final isar = await openIsar();
  return isar.writeTxnSync<List<int>>(
    () {
      isar.readingSheetRecords.clearSync();
      return isar.readingSheetRecords.putAllSync(records);
    },
  );
}
`

I did more testing and discovered that it happens on lower end devices, when the data is larger than 10MB roughly.

**Comment by leisim** [comment]
@MartiSilvio 

Id it reproducible or does it happen rarely?

What devices could you reproduce it on exactly?

Thanks for helping me fix this 🙏

**Comment by MartiSilvio** [comment]
The error is always reproducible on a specific device: Tecno SA6 running Android 8.1.0.

The full error output is:

```
F/libc    ( 9443): mdbx:5945: pnl_check: assertion "limit >= 3 - 1" failed
F/libc    ( 9443): Fatal signal 6 (SIGABRT), code -6 in tid 9658 (DartWorker), pid 9443 (om.mobiread.dev)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'TECNO/VP510/TECNO-SA6-PRO:8.1.0/O11019/J-ETEC-190213V2:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 9443, tid: 9658, name: DartWorker  >>> com.mobiread.dev <<<

```

I will test it on 3.0.0-dev.8 and get back to you.

**Comment by MartiSilvio** [comment]
Similar error on 3.0.0-dev.8

```
F/libc    (24043): mdbx:6603: mdbx_pnl_check: assertion "limit >= 3 - 1" failed
F/libc    (24043): Fatal signal 6 (SIGABRT), code -6 in tid 24154 (DartWorker), pid 24043 (om.mobiread.dev)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'TECNO/VP510/TECNO-SA6-PRO:8.1.0/O11019/J-ETEC-190213V2:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 24043, tid: 24154, name: DartWorker  >>> com.mobiread.dev <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'mdbx:6603: mdbx_pnl_check: assertion "limit >= 3 - 1" failed'
    r0 00000000  r1 00005e5a  r2 00000006  r3 00000008
    r4 00005deb  r5 00005e5a  r6 75dfd024  r7 0000010c
    r8 00000000  r9 8ed1f0fc  sl 7fe22004  fp 75dfd060
    ip 8ed1f0fc  sp 75dfd010  lr a86b2a5b  pc a86ac48c  cpsr 200b0030
backtrace:
    #00 pc 0001a48c  /system/lib/libc.so (abort+63)
    #01 pc 0001a6ad  /system/lib/libc.so (__assert2+20)
    #02 pc 00076dac  /data/app/com.mobiread.dev-UXoWpTOC-pNaB57RkDYpoA==/lib/arm/libisar.so
Lost connection to device.
Exited (sigterm)
```

**Comment by leisim** [comment]
This is likely a kernel bug of your device if you can only reproduce it for a single device. Unfortunately I can't really help unless we find a way for me to reproduce it.

**Comment by leisim** [comment]
@MartiSilvio do you still experience this error? do you have a way to reproduce it?

**Comment by leisim** [comment]
Going to close this for now
