### ISSUE TITLE
Planned release of 3.0.0

### ISSUE THREAD

**Issue by McCrafterIV** [isar/isar#659]
First of all, thanks for the amazing project!

After following the 3.0.0 development  for a while, the following questions arise:
1. Is there a timeframe in which we can await a 3.0.0 stable and/or beta release? (e.g. in two weeks, not before the end of the year, ...)
2. Is there some kind of todo list listing all the things still needed to be done? The TODO.md file wasn't updated for 8 months (as of now) and therefore doesn't seem to be up-to-date.

**Comment by leisim** [comment]
Going to close this as this is not an issue.

3.0.0 will hopefully be ready in September. October at the latest.

Todo:
- Fix web version (almost a rewrite)
- Fix inspector (good progress here: https://github.com/isar/isar/pull/555)
- Update all docs (may happen a little after the release)

**Comment by McCrafterIV** [comment]
Thanks @leisim for the quick and detailed response!
