### ISSUE TITLE
It will be awesome to add graphql like feature to fetch property those required ?

### ISSUE THREAD

**Issue by dgandhi17** [isar/isar#66]
@leisim  Do you think it will be an simple yet useful feature to fetch properties which are passed like in graphql we do ?

**Comment by leisim** [comment]
@dgandhi17 Not sure I understand exactly what you mean. We already have property queries: https://isar.dev/queries#property-queries

**Comment by dgandhi17** [comment]
I saw that but it is for single property only, what if I have 10 property in my collection but for a couple of scenarios I would want to fetch 3-4 properties only. Hope this will clear the question.

**Comment by leisim** [comment]
@dgandhi17 That would not be hard to implement but we would need a nice API that fits into the existing API. Do you have a suggestion?

**Comment by dgandhi17** [comment]
A simple map ? which will return list of[ property and value] map this should be generic ?

**Comment by yringler** [comment]
I think that selecting a subset of properties is really only useful when it's traveling over a network (ie, what graphql is for). Here, everything is local, so I don't think there would be much performance gain.
Unless you have really massive records with dozens and dozens (100s?) of large fields, but IMO that's a schema which should be improved.

**Comment by leisim** [comment]
@yringler I fully agree. The performance gain will be really small an not worth the additional complexity.
