### ISSUE TITLE
delete  don't work

### ISSUE THREAD

**Issue by samithe7** [isar/isar#660]
When i delete  a  transactions i got this mass Unhandled Exception: IsarError: Write operations require an explicit transaction.

**Steps to Reproduce**

error mass : 
E/flutter (13397): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: Write operations require an explicit transaction.
E/flutter (13397): #0      IsarImpl.getTxn
package:isar/…/native/isar_impl.dart:127
E/flutter (13397): #1      IsarCollectionImpl.deleteAll
package:isar/…/native/isar_collection_impl.dart:336
E/flutter (13397): #2      IsarCollection.delete
package:isar/src/isar_collection.dart:102
E/flutter (13397): #3      Counter.delatexComment

**Code sample**
```dart
final rxIsarxSave = StateNotifierProvider<Counter, AsyncValue<void>>((ref) {
  return Counter(ref);
});

class Counter extends StateNotifier<AsyncValue<void>> {
  Counter(this.ref) : super(const AsyncData(null));

  final Ref ref;




  Future<void> delatexComment({required int id}) async {
    final isar = await ref.read(rxIsarxDB.future);

    await isar.mCxLikes.delete(id);
  }
}



class WxEditxDelate extends ConsumerWidget {
  const WxEditxDelate({Key? key, required this.data}) : super(key: key);
  final MCxLike data;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    debugPrint('data Id ${data.id} ');
    return Row(
      children: [

        IconButton(
          icon: Icon(Icons.delete_forever),
          onPressed: () =>
              ref.read(rxIsarxSave.notifier).delatexComment(id: data.id ?? 5),
        ),
      ],
    );
  }
}


```

**Version**
 - Platform:  Android, 
 - Flutter version: 3.3.1
 - Isar version: 3.0.0-dev.8
 - Isar Generator version: 3.0.0-dev.8

**Comment by leisim** [comment]
Please read error message and docs before opening an issue. Deleting is obviously a write operation and needs to be wrapped in a write transaction.
