### ISSUE TITLE
Code generator does not ignore accessor in super interface

### ISSUE THREAD

**Issue by blaugold** [isar/isar#667]
```
UnimplementedError
package:isar_generator/src/isar_type.dart 82:11             DartTypeX.isarType
package:isar_generator/src/isar_analyzer.dart 274:20        IsarAnalyzer.analyzeObjectProperty
package:isar_generator/src/isar_analyzer.dart 23:26         IsarAnalyzer.analyzeCollection
package:isar_generator/src/collection_generator.dart 46:35  IsarCollectionGenerator.generateForAnnotatedElement
package:source_gen/src/generator_for_annotation.dart 53:30  GeneratorForAnnotation.generate
package:source_gen/src/builder.dart 352:33                  _generate
```

### Steps to Reproduce

Try to generate code for this file:

```dart
import 'package:isar/isar.dart';

part 'a.g.dart';

abstract class IA {
  List<B> get b;
}

@Collection()
class A implements IA {
  A();

  late Id id = Isar.autoIncrement;

  @ignore
  @override
  List<B> get b => [];
}

class B {}
```

If `A` does not implement `IA` `b` is correctly ignored.

### Details

 - Isar version: 3.0.0-dev.14

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
Could you please try using the new `ignore` parameter of `@Collection()`

**Comment by blaugold** [comment]
Thanks, `Collection.ignore` works. Is `@Ignore` going to be removed?

**Comment by leisim** [comment]
No but I think the current behaviour is good. `@ignore` ignores only the property in the current class and `@Collection(ignore)` ignores all properties with that name. Going to close this issue.
