### ISSUE TITLE
issue on archive

### ISSUE THREAD

**Issue by seifeibrahim** [isar/isar#67]
Issue when i try to archive the iOS build

<img width="718" alt="Screen Shot 2021-04-12 at 1 02 51 PM" src="https://user-images.githubusercontent.com/15933375/114384912-9eb19980-9b8f-11eb-88f3-4c344b338c56.png">

**Version**
 - Platform: iOS
 - Flutter version: 2.0.4
 - Isar version: 0.4.0
 - Isar Generator version: 0.4.0

**Comment by leisim** [comment]
@seifeibrahim Looks like you try to build for an iOS device with armv7 professor (probably iPhone 5?). Unfortunately Isar only supports armv8 processors due to their overwhelming market share.

If you need to support older devices I suggest build Isar Core with support for armv7 architecture.

**Comment by seifeibrahim** [comment]
@leisim  Thanks for your reply,
Can you please tell me how to remove the armv7 support and replace it with armv8?
