### ISSUE TITLE
Avoid leading underscores for local identifiers

### ISSUE THREAD

**Issue by victormhg** [isar/isar#671]
### Steps to Reproduce

Running "flutter pub run build_runner build" with Flutter 3.3.1 produces a lot of warnings "Avoid leading underscores for local identifiers":

![image](https://user-images.githubusercontent.com/21988790/190378628-45c9a4c3-78fd-44a6-bf54-da0020b47bf5.png)

More info in https://dart-lang.github.io/linter/lints/no_leading_underscores_for_local_identifiers.html

### Details

 - Platform: Flutter Web.
 - Flutter version: 3.3.1
 - Isar version: 2.5.0

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version

**Comment by saddig** [comment]
You could tell the analyzer to ignore generated files by creating an `analysis_options.yaml` file in your project root directory:

```
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
```

**Comment by leisim** [comment]
This has been fixed in the newest versions so I'm going to close this issue. @saddig's suggestion is a good workaround.
