### ISSUE TITLE
ArgumentError (Invalid argument(s): Failed to load dynamic library on Windows (isar-3.00-dev-15)

### ISSUE THREAD

**Issue by muddassar-lab** [isar/isar#676]
### Steps to Reproduce
After upgrading to isar-3.00-dev-15 I am getting this error when running the app on windows at startup. But this error is not appearing on android
ArgumentError (Invalid argument(s): Failed to load dynamic library 'G:\Projects\Flutter Projects\clean_code_cricket_app_flutter\isar.dll': error code 126)

### Code sample

```
class DatabaseService {
  Future<Isar> openIsarDatabase() async {
    final isar = await Isar.open(
      [
        PlayerSchema,
        TeamSchema,
        PlayerMatchDetailSchema,
        TeamMatchDetailSchema,
        MatchDetailSchema
      ],
      name: 'cricket',
      inspector: true,
    );

    return isar;
  }
}
```

### Details

 - Platform:  Windows Desktop.
 - Flutter version: 3.3.2
 - Isar version: 3.00-dev-15

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
Thanks it's fixed now :)
