### ISSUE TITLE
Web is not building [isar 2.5.0]

### ISSUE THREAD

**Issue by tomasweigenast** [isar/isar#677]
My project is not building when target web. A lot of errors appears on the console, for example:
```
: Error: Type 'WorkContractFinalizer' not found.
../…/working/work_contract.g.dart:2158

 QueryBuilder<WorkContract, List<WorkContractFinalizer>, QQueryOperations>
```

**Comment by srix55** [comment]
Web works fine for 2.5.0. I suggest doing `flutter clean` & `flutter pub upgrade`. Still facing, then `flutter pub cache repair`.
