### ISSUE TITLE
Native support for arm64 iOS Simulator

### ISSUE THREAD

**Issue by DFelten** [isar/isar#678]
### Steps to Reproduce

There is a scrolling problem with Isar and the M1 iOS simulator. As soon as Isar is activated, scrolling no longer works as usual. Every gesture scrolls way too much. It was possible to switch the simulator to Rosetta, but unfortunately this no longer works on the latest Mac Monterey version (12.6).

More information for the scrolling bug  on [StackOverflow](https://stackoverflow.com/questions/65476069/ios-simulator-scrolls-too-fast-on-apple-m1#comment130204868_65511051).

As far as I can see, the problem is that you are excluding the Arm64 architecture in the `isar_flutter_libs.podspec`.

```swift
'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386 arm64',
```

### Details

 - Platform: iPhone Simulators on MacBook M1 with MacOS 12.6
 - Flutter version:  3.3.0
 - Isar version: 3.0.0

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by DFelten** [comment]
Our current workaround is to to use a real device for debugging or temporary disable isar.

**Comment by thipokch** [comment]
@DFelten Thanks. Nice catch by the way! I was scratching my head.
 
FYI. I'll try modifying the podspec (temporarily) and see how it goes.

**Comment by thipokch** [comment]
@DFelten I was able to compile the library for the arm64 Simulator and use it as a workaround. It works, but you can't pack both arm64 iOS and arm64 simulator together for distribution. 🥲

**Comment by thipokch** [comment]
[libisar.a.zip](https://github.com/isar/isar/files/9612610/libisar.a.zip)
You can try dropping this into your pubcache as a workaround and modify podspec, but don't ship it with the app.

**Comment by leisim** [comment]
3.0.1 ships arm64 simulator binaries
