### ISSUE TITLE
"openIsar" is not a function

### ISSUE THREAD

**Issue by emmanuelagarry** [isar/isar#68]
The function "openIsar" does not exist after importing Isar in my projects.
 ![image](https://user-images.githubusercontent.com/26308935/114663361-73978900-9cfa-11eb-8bfd-79b020ac1752.png)

**Comment by leisim** [comment]
@emmanuelagarry You need to run the `build_runner` and import `isar.g.dart`

**Comment by nik-v-hax** [comment]
what should it generate for? Like what annotation does it search for?

**Comment by LeonFuss** [comment]
ou can find all of this perfectly documented on [isar.dev]()

**Comment by nik-v-hax** [comment]
SOLVED: yeah I just discovered the docs website - missed the @Id annotation inside the collection. Then it generated
