### ISSUE TITLE
How to properly update links in collection

### ISSUE THREAD

**Issue by intik** [isar/isar#69]
**Steps to reproduce**
I have two simple collections, like in the docs: Student, Teachers 
Student have field teachers of links to teachers.
I want to have simple form where i can edit Student and his teachers at one.
How to properly save changed teachers (new ones and some edited) along with student edit?

**Simplified code**
```
@Collection class Student { 
 String name;
 @IsarLinks teachers = IsarLinks<Teacher>();
}

@Collection class Teacher {
 String name;
}

final student = await isar.students.get(1);
await student.teachers.load();

student.name = 'Luke';
student.teachers.elementAt(1).name = 'Joe';
student.teachers.add(Teacher()..name='April');

isar.writeTxn((isar) async {
 await isar.students.put(student);
 await student.teachers.saveChanges();
 // How to save changed student, added teacher and changed teacher?
};

```
**Issue**
I expected that the solution above would work, but no somehow existing teachers always dissapears from the student. They remain in the db (I can query for them explicitly), but newly loaded (refreshed) student only contains the newly added teacher.

I've tried different combinations of what to when save (clearing teachers from student and adding again and more). Closest was when I manually copied every teacher to a new object, clear student teachers and and new copies of teachers, which is not optimal 😀 I see in code, that `saveChanges()` probably only applies to newly added/removed items in list, I would be ok that existing teachers wasn't updated, but why are the removed from studen teachers list?

Am I missing something?

**Version**
 - Platform: Windows
 - Flutter version: 2.0.1
 - Isar version: 0.4.0
 - Isar Generator version: 0.4.0

**Comment by leisim** [comment]
@intik The `.saveChanges()` method only saves changes you made to the link (adding or removing linked objects). The following code should work:

```dart
student.name = 'Luke';
student.teachers.elementAt(1).name = 'Joe';
student.teachers.add(Teacher()..name='April');

isar.writeTxn((isar) async {
 await isar.students.put(student);
 await student.teachers.saveChanges();
 await isar.teachers.put(student.teachers.elementAt(1));
};
```
