### ISSUE TITLE
Isar Insepctor dont support secondary Instance

### ISSUE THREAD

**Issue by TimBudarick** [isar/isar#699]
In the previous Releases of the Isar Inspector I able to view and edit the secondary open Instance.

In the latest Stable Version is this not didn't work anymore.

Version: 3.0.0

I can See the secondary opened Instance, but when I clicking on that. It does nothing.

<img width="325" alt="Bildschirm­foto 2022-09-20 um 07 35 25" src="https://user-images.githubusercontent.com/73606530/191175580-3bd93038-cd2b-415d-b36e-adbef44d16f2.png">

**Comment by leisim** [comment]
This is fixed in the newest version.

**Comment by TimBudarick** [comment]
Now works perfectly. Thanks!

**Comment by BAndonovski** [comment]
The click itself works, but it's stuck on loading. Console does show an `Uncaught Error`
