### ISSUE TITLE
Will these compete with graph like db as well ?

### ISSUE THREAD

**Issue by dgandhi17** [isar/isar#7]
Wanted to know whether this will complete with graph dbs where relations are first class citizens.

**Comment by leisim** [comment]
I have not completed development of relationships yet. While Isar will not be a Graph database, maybe we can still cover your use case.

Could you please describe what you had in mind? Maybe even a query :+1:

**Comment by dgandhi17** [comment]
I have my app where I need queries to be fast enough between nodes. And that is only possible if the underling structure is native graph. In your design is it possible that if we configure db it will behave as graph?

**Comment by leisim** [comment]
It would help a lot if you could provide a small example of the data you want to store. Maybe also how you plan to query the data. Just something very simple to give me an idea what you are trying to achieve.

**Comment by dgandhi17** [comment]
find(person).where(address="").and(ingroup="").and(fieldfilter="").list(),   this is a sample query. it will be get complex if i add property level filter. The query above is simple and at node or edge level only.

**Comment by leisim** [comment]
This query is very to represent using Isar.

**Comment by dgandhi17** [comment]
Anyway if you are providing a query language, how about graphql query ?
