### ISSUE TITLE
.save and .delete methods do not exist

### ISSUE THREAD

**Issue by barbalex** [isar/isar#70]
I have seen a number of things that though documented are not implemented yet.

I have so far successfully used these methods to edit data:
- `isar.projects.put(project)` to create a new project
- `isar.projects.delete(id)` to delete a project

I have not managed to use:
- `project.delete()`
- `project.save()`

The reason is: these two methods do not exist when I query a project, for instance like this: `isar.projects.get(id)`. The returned object _does_ contain all the variables defined in the model though.

So the quick question is: Have these methods been implemented?
The longer one is (and maybe I need to show some more code for that): What needs to happen for those methods to exist?

**Comment by leisim** [comment]
@barbalex The `.delete()` and `.save()` methods were part of an old API design and are no longer required. I'll remove them from the docs.

>  when I query a project, for instance like this: isar.projects.get(id). The returned object does contain all the variables defined in the model though.

That should definitely not happen. Could you maybe share your `Project` class?

**Comment by leisim** [comment]
@barbalex Is there something else that is not implemented yet?

**Comment by barbalex** [comment]
> The .delete() and .save() methods were part of an old API design and are no longer required

How can an object be changed/edited then? I haven't seen or found a different method.

> Is there something else that is not implemented yet?

Yes, there are/were a few  things I found in own/other's issues. Some you have already resolved. They are mentioned in those issues so no need to repeat them here.

Plus: You are building an extremely promising tool here which is why I have decided to try to implement it in a new project. Which may be why I am opening a number of issues. I realize:
- It is early days for isar. I may be using it too soon. That is my own risk, you should not feel guilty for the troubles resulting from that
- You are letting us profit from your knowledge and time. THANKS A LOT FOR THAT. I hope you take issues as a sign of our interest in your ideas and work rather than us criticizing it

**Comment by barbalex** [comment]
By the way: While I am not up to adding value to the code of this project, I _could_ add to the documentation. That would probably not be great documentation and would surely have to be enhanced by you later but it could prevent more people from opening issues and spending time before that.

**Comment by leisim** [comment]
> How can an object be changed/edited then? I haven't seen or found a different method.

Both inserting and updating works with `yourCollection.put(yourObject)`. If the `id` is `null` (or does not exist), the object is inserted, otherwise it is updated.

> Which may be why I am opening a number of issues

Please don't hesitate opening any number of issues. I'm super grateful for insights from early adopters.

> I could add to the documentation

Any help is more than welcome. Don't worry about the level of your knowledge. Docs for beginners or sample apps are just as important as more advanced guides :)
