### ISSUE TITLE
Allow client to specify custom max size for documents

### ISSUE THREAD

**Issue by gustavjohansen98** [isar/isar#704]
**Is your feature request related to a problem? Please describe.**
Not really, as it is quite client-specific. I store large text pieces in my documents, and some exceed the 16MB limit.

**Describe the solution you'd like**
Allow for client-specific document size limit.

**Describe alternatives you've considered**
Custom sharding of the large text pieces and store the sharded elements via IsarLinks. Alternatively, an easy solution would be to store the text in the device file system, and save a reference in the actual DB document.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 3.0.5 stable
 - Isar version: 3.0.0

**PS. loving the ISAR API**

**Comment by gustavjohansen98** [comment]
Compressing the string, encoding and decoding it might also be a viable solution :))

**Comment by leisim** [comment]
It is a bad idea to store big chunks of data in a database. Please use the file system instead and store a path to your file in Isar.

The 16MB limit is not arbitrary. It allows great data size and performance improvements and cannot be configured by users.

**Comment by gustavjohansen98** [comment]
Got it. Thanks for the swift reply.

Great job with the new stable release 👍
