### ISSUE TITLE
Isar package at pub.dev still shows isar 3.0.0-dev-14 version.

### ISSUE THREAD

**Issue by muddassar-lab** [isar/isar#705]
### Steps to Reproduce
Isar package at pub.dev still shows isar 3.0.0-dev-14 version.

### Code sample

```dart
dependencies:
  isar: 3.0.0-dev.14
  isar_flutter_libs: 3.0.0-dev.14 # contains Isar Core

dev_dependencies:
  isar_generator: 3.0.0-dev.14
  build_runner: any
```

### Details
 - Platform: iPhone 13 Pro, Galaxy S7, x86 Android Emulator on Windows etc.
 - Flutter version:  3.3.2
 - Isar version:  3.0.0

**Comment by leisim** [comment]
Fixed in the main branch already. Wasn't worth to do a release just for that.
