### ISSUE TITLE
Isar write transaction throws bad state no element error

### ISSUE THREAD

**Issue by jackdy19** [isar/isar#713]
### Steps to Reproduce

Sometimes write transactions throws an error as the following: 

### Code sample

```dart

await isar.writeTxn(() async {
        await isar.usersModel.putAll(listOfUsers);
});

```
Where listOfUsers is a list of user objects. It throws the following error very randomly and unable to see what the issue is.

```dart

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter (12283): #0      ListQueue.removeFirst (dart:collection/queue.dart:822:25)
E/flutter (12283): #1      new Txn.<anonymous closure> (package:isar/src/native/txn.dart:18:28)
E/flutter (12283): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (12283): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (12283): #4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (12283): #5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (12283): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (12283): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (12283): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

### Details

 - Flutter version: latest
 - Isar version: 3.0.0

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
Thanks for reporting! Do you have code to reproduce it?

**Comment by jackdy19** [comment]
It was an issue on my side, thus closing this :)

**Comment by leisim** [comment]
@jackdy19 what was the issue? I've also experienced this before and would like to fix it

**Comment by jackdy19** [comment]
So I was trying to do something like the following. The logic was that, in case the user is not yet in the database, get it from an api, map it and then insert it. 

`
      
    Future<UserModel> getUserByUuid(String uuid) async {
    
     final isar = await getInstance();

     final UserModel? user =
        await isar.userModels.filter().uuidEqualTo(uuid).findFirst();

     if (user == null) {
       final userFromApi =
           await _getProfileDetailsFromApiService.getProfileDetails(uuid);

       final mappedUser = mapUserModel(userFromApi);

       await isar.writeTxn(() async {
         await isar.userModels.put(mappedUser);
       });
      return mappedUser;
     } else {
      return user;
     } }

`
It was failing on the line 

`
await isar.userModels.put(mappedUser);
`

Map user model function just maps the user returned from the api to an Isar model as the following example: 


`
     
     UserModel mapUserModel(ProfileDetails userFromApi) {

        return UserModel()
          ..id = Isar.autoIncrement
          ..uuid = userFromApi.userNode.uuid
          ..name = userFromApi.userInfo.name;}
`

So my unlikely guess was that instead of doing an insert, it was probably trying to do an update by trying to find an element with that id instead, thus throwing Bad state: No element. Otherwise, not sure what the issue was since it is just a normal put operation. I found a workaround, that is more specific to my project, but i still think that there is an issue that I cannot really pin down as to what it is.
