### ISSUE TITLE
ignore annotation not working

### ISSUE THREAD

**Issue by kamyar75** [isar/isar#716]
I wanted to set up first class for converting . I needed inherit Equatable class, so , I extended from that.
I use @ignor annotation top of props value. after run blow command on terminal.
flutter pub run build_runner build

I have an error about unsupported type, and use @ignore property.

### Code sample

import 'package:equatable/equatable.dart';
import 'package:isar/isar.dart';

part 'city_entity.g.dart';

@collection
class City extends Equatable{

   Id? id=Isar.autoIncrement;

  final String name;

   City({required this.name,this.id});

  @override

  @ignore
  List<Object?> get props => throw UnimplementedError();

}

************************************************
*****************  Error *************************
*************************************************

Unsupported type. Please annotate the property with @ignore.
package:equatable/src/equatable.dart:29:21
   ╷
29 │   List<Object?> get props;
   │                     ^^^^^
   ╵
[INFO] Running build completed, took 2.9s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 45ms

[SEVERE] Failed after 3.0s
pub finished with exit code 1

### Details

 - Platform: Windows
 - Flutter version: 3.3.2
 - Isar version: 3.0.1

**Comment by leisim** [comment]
Try `@Collection(inheritance: false)`

**Comment by kamyar75** [comment]
thanks, my problem solved with your way.

**Comment by Ejasackey** [comment]
I need solution for @embedded too
