### ISSUE TITLE
Feature Request: Insert Data Using Inspector

### ISSUE THREAD

**Issue by KhaledBasiony** [isar/isar#717]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
I would like to easily manipulate (Insert/Update/Delete) the data using the inspector
Would be super nice to have this during development :smile: 

**Describe alternatives you've considered**
creating temporary forms in my app to do the insertions.

**Version**
 - Platform: Android, Linux
 - Flutter version: 3.3.0
 - Isar version: 3.0.1

**Comment by leisim** [comment]
You can already update and delete data so this is a request to insert data.

**Comment by KhaledBasiony** [comment]
> so this is a request to insert data

Ah yes, my bad, I just wanted to explain what I meant by "manipulate".

**Comment by WingCH** [comment]
It would be nice if Inspector supports `importJsonRaw`

**Comment by leisim** [comment]
This is implemented in the newest version.
