### ISSUE TITLE
`stringFieldLessThan` not working.

### ISSUE THREAD

**Issue by jsquirrelz** [isar/isar#726]
### Steps to Reproduce
1. Create a Collection.
2. Add a `String?` field.
3. Run flutter pub run build_runner build
4. Insert an item into the collection.
5. Call `isar.collection.filter.fieldLessThan('string').findFirst()`;

This will return `null`. Confirmed that `fieldGreaterThan` works.

### Code sample

I believe this [test](https://github.com/isar/isar/blob/main/packages/isar_test/test/filter/filter_string_test.dart#L162-L199) sets everything up correctly but the `fieldLessThan` tests are commented out with a `FIXME`

### Details

 - Platform: MacOS v12.5.1
 - Flutter version: 3.3.1
 - Isar version: 3.0.1
---

 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version
 - [X] I am able to provide a reproducible example

---

I tried to find the root cause but got a little lost in the code 😅 Happy to try and investigate but definitely need some pointing in the right direction.

**Comment by simc** [comment]
This is fixed in v4
