### ISSUE TITLE
Query only specific time range of DateTime

### ISSUE THREAD

**Issue by McCrafterIV** [isar/isar#734]
Hello!

I've a schema `Concert` with a DateTime property `startDateTime` that stores the time and date when the concert starts. How would I write a query that returns all concerts that start between 6pm and 9pm no matter the date?

```dart
@collection
class Concert {
  final id = Isar.autoIncrement;

  .....

  late DateTime startDateTime;

  ....
}
```

**Comment by leisim** [comment]
That's not possible. I suggest you add an additional `hour` getter to your model

**Comment by McCrafterIV** [comment]
Thanks for the answer. Maybe advanced filter methods for e.g. DateTime's could be a future feature..

**Comment by cgestes** [comment]
(note that I am not from the isar team. just speaking general knowledge)

You can already filter the whole dataset the way you want. It makes sense
to add features to the core if it gets more optimised (probably by using an
index). Indexing by hours is too specific, so just adding a column fixes
your issue in a proper way.

Hope it helps a little bit understanding.

**Comment by McCrafterIV** [comment]
I don't think it's too specific. Advanced filtering/sorting like this already exists in other database solutions like databases working with SQL. While Isar is already really powerful, it would profit from some more specific filter methods like filtering DateTime's by only a part of the DateTime, simply because DateTimes are used everywhere in many modern applications and if you plan to use Isar for some kind of data-analysis this may be useful too.
For strings, this is already implemented (see `.filter().variableStartsWith()`) and since DateTimes are stored as UTC representation this could also be done on the rust side I figure.
