### ISSUE TITLE
Isar does not terminate when launched from the command line (new scenarios)

### ISSUE THREAD

**Issue by ivoleitao** [isar/isar#739]
**Steps to Reproduce**

As reported on #611:

When I create a very simple Isar command line application every time I run it does not close (pure command line, vs code terminal or vscode debugger). This only happens with the async version of open:

* `await Isar.open([ContactSchema], directory: '.dart_tool', inspector: false);` does not work
*  `Isar.openSync([ContactSchema], directory: '.dart_tool', inspector: false);` works

This seems to be partially solved on 3.0.2 but when I interact with the db it happens again. Attached bellow my test program

[isar_bug.zip](https://github.com/isar/isar/files/9700053/isar_bug.zip)

**Code sample**
```
iimport 'dart:ffi';
import 'dart:io';

import 'package:isar/isar.dart';
import 'package:isar_bug/src/bug/contact.dart';

void main() async {
  // Initialize Isar
  await Isar.initializeIsarCore(libraries: {
    Abi.current(): '${Directory.current.path}/.dart_tool/libisar.dylib'
  }, download: true);

  // No difference with inspector values
  final isar = await Isar.open([ContactSchema],
      directory: '.dart_tool', inspector: false);

  final contact = Contact()
    ..firstName = "First Name"
    ..lastName = "Last Name"
    ..isStarred = true;

  await isar.writeTxn(() async {
    await isar.contacts.put(contact);
  });

  // No difference with close or not it's the same
  print(await isar.close());
}
```

**Version**
 - Platform: Mac
 - Flutter version: 3.3.0
 - Isar version: 3.0.2
 - Isar Generator version: 3.0.2

**Comment by leisim** [comment]
Thanks a lot for reporting. I found the issue and it'll be fixed with the next release.
