### ISSUE TITLE
Generate serializers for @collection classes / allow registering custom serializers

### ISSUE THREAD

**Issue by joelmo** [isar/isar#744]
I think serializers can be generated for collections in order to support code like this:

```dart
@collection
class A {
  Id id = Isar.autoIncrement;
  List<B> otherType = List.empty(growable: true);
}

@collection
class B {
  Id id = Isar.autoIncrement;
// ... more fields
}
```

Lets imagine `B` is written/updated a lot, so in this example it's not appropriate to embed B into A.
I think this is a common use-case and can be supported.
A first step toward this can be to allow users to register serializers for types that are not supported.

**Comment by simc** [comment]
I don't want to support this because it will be very hard for users to maintain and cause a lot of weird bugs. It will also not help with the performance of updating embedded properties.

Instead I suggest using JSON to store your custom classes. It's easy to have custom `toJson()` and `fromJson()`
