### ISSUE TITLE
Isar Protected Methods

### ISSUE THREAD

**Issue by Peng-Qian** [isar/isar#745]
Hi @leisim ,

Thx for the great updates. Really love the embed property feature and the new inspector!

For the new API of Isar, is this possible to make the name-related and index-related methods not be protected? such as `deleteByIndex()` and `getByIndexSync()` in `IsarCollection` and `getCollectionByNameInternal()` in `Isar`.

This will allow us to build a general Isar service to reduce the boilerplate coding. e.g. we can create a general delete method to remove an object by its id(not isar id but id of entity). we can also write a method to automatically load links and delete links (for these methods we need to get the collection by its name). I believe opening these APIs will make Isar more flexible and suite for large project architecture, since reuses logic and reduce duplicate codes. (I have actually done all these features with the previous API and it is quite good. But the new API makes these methods to be protected.)

**Comment by punitganshani** [comment]
This is really essential to reduce the boilerplate code and improve the speed of development with clean code

**Comment by leisim** [comment]
Thanks! I made these methods available and added docs. A new version will be released soon!
