### ISSUE TITLE
Error in quickstart example

### ISSUE THREAD

**Issue by dalewking** [isar/isar#755]
The quick start example (https://github.com/isar/isar#2-annotate-a-collection) contains an error and if you cut and paste the code it doesn't work.

The status property looks like this:
```
  @enumerated
  Status status = Status.pending;

```

However `pending` is not a defined value for `Status`:
```
enum Status {
  draft,
  sending,
  sent,
}
```

I think you should change `pending` to `draft` to make the example valid.

**Comment by leisim** [comment]
Fixed :)
