### ISSUE TITLE
Unsupported Type "LatLng"

### ISSUE THREAD

**Issue by Rebew111** [isar/isar#758]
### Discussed in https://github.com/isar/isar/discussions/757

<div type='discussions-op-text'>

<sup>Originally posted by **Rebew111** October  9, 2022</sup>
Hy everybody,

i got an "Unsupported type" error for variable of type LatLng.

This is my class:

import 'package:isar/isar.dart';
import 'package:latlong2/latlong.dart';

part 'location.g.dart';

@Collection()
class Location {
  LatLng? latlng;
}

This is the error message:

![grafik](https://user-images.githubusercontent.com/72982682/194758960-f24fb7db-7af6-46a1-93b8-98dceee499b4.png)

What is the problem? How to solve it?

Thanks for all answers.

Simon</div>

**Comment by Rebew111** [comment]
Or do i have to change the class to:
import 'package:isar/isar.dart';
import 'package:latlong2/latlong.dart';

part 'location.g.dart';

@Collection()
class Location {
double? lat;
double? lng;
}

**Comment by leisim** [comment]
Please check out the schema docs on isar.dev about supported types.

The location class you suggested will work.
