### ISSUE TITLE
Failure to create writeTxn within a bloc event handler

### ISSUE THREAD

**Issue by jabari-pulliam** [isar/isar#765]
### Steps to Reproduce

Please describe exactly how to reproduce the problem you are running into.
I am trying to create a write transaction within an event handler for a bloc and it fails immediately without giving an error. It fails in the saveAll method provided below. The call only fails within the bloc's event handler. I can call it directly in a test setUp function and it works.

### Code sample

Here is the bloc. It fails when calling the saveAll method.
```dart
TransactionBloc(this._transactionRepository, this._categoryRepository, this._apiService)
      : super(const TransactionState()) {
    on<TransactionEventFetch>(_onFetch);
    on<TransactionEventLoad>(_onLoad);
    on<TransactionEventEdit>(_onEdit);
  }

  Future<void> _onFetch(TransactionEventFetch event, Emitter<TransactionState> emit) async {
    final result = await _apiService.fetchPage(
      startDate: event.filters.startDate,
      endDate: event.filters.endDate,
    );

    await _transactionRepository.saveAll(result);
    ...
}
```

Here is the code for the saveAll method:
```dart
Future<List<Transaction>> saveAll(List<Transaction> transactions) async {
    return await _db.writeTxn(() async {
      final txns = transactions.map((e) => e.copyWith()).toList();
      try {
        await _db.transactions.putAll(txns);
      } catch (e) {
        _logger.e(e);
        rethrow;
      }
      return txns;
    });
}
```

I stepped through in the debugger to find that it fails at line 72 of native/txn.dart where it returns completer.future.
```dart
Future<void> wait() {
    final completer = Completer<void>();
    _completers.add(completer);
    return completer.future;
}
```

The `Transaction` class that is being saved.
```dart
@CopyWith(constructor: 'copy')
@Collection(inheritance: false, ignore: {"props"})
class Transaction with EquatableMixin {
  Id? dbId;
  @Index(unique: true, replace: true)
  String? id;
  @Index(name: 'date')
  late DateTime date;
  @Index(name: 'name', caseSensitive: false)
  late String name;
  final _categoryLink = IsarLink<FinancialCategory>();
  final _originalCategoryLink = IsarLink<FinancialCategory>();
  late String dbAmount;
  late String cursor;

  Transaction();

  Transaction.create({
    required this.id,
    required this.date,
    required this.name,
    required Decimal amount,
    required this.cursor,
  }) : dbAmount = amount.toString();

  Transaction.copy(
      {this.dbId, this.id, required this.date, required this.name, required this.dbAmount, required this.cursor});

  @Index(type: IndexType.value, caseSensitive: false)
  List<String> get nameWords => Isar.splitWords(name);

  @Index(type: IndexType.value, caseSensitive: false)
  List<String> get categoryWords => Isar.splitWords(_categoryLink.value?.name ?? '');

  @ignore
  FinancialCategory? get category => _categoryLink.value;
  set category(FinancialCategory? c) => _categoryLink.value = c;
  Future<void> saveCategory() async => _categoryLink.save();

  @ignore
  FinancialCategory? get originalCategory => _originalCategoryLink.value;
  set originalCategory(FinancialCategory? c) => _originalCategoryLink.value = c;
  Future<void> saveOriginalCategory() async => _originalCategoryLink.save();

  @override
  List<Object?> get props => [id];
}
```

### Details

 - Platform: Chrome (web) on MacOS 12.6,  Apple M1 Pro
 - Flutter version: 3.3.0
 - Isar version: 3.0.2

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
What is the error message?

**Comment by jabari-pulliam** [comment]
> 

There is no error message or exception. The writeTxn method just returns and none of the code within is ever executed. Even the _onFetch() method exits after the call to saveAll() with none of the code below it being executed.

Additionally, I tried just creating a trivial write transaction that just returns a future with an empty string in the _onFetch() method and it failed the same way.

**Comment by leisim** [comment]
I'm not able to reproduce your problem unfortunately. Without more information or an error it is difficult for me to help.

**Comment by jabari-pulliam** [comment]
I found the problem. It works when I remove `Isar.splitWords()`, which I see in the docs is not supported yet on web.
