### ISSUE TITLE
Thread panic on linux devices

### ISSUE THREAD

**Issue by StefanZimmermann98** [isar/isar#766]
### Steps to Reproduce
After updating Isar to version 3.0.2 on startup i get the following error:
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
thread 'isarworker' panicked at 'range end index 41218 out of range for slice of length 161', library/core/src/slice/index.rs:73:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error connecting to the service protocol: failed to connect to http://127.0.0.1:42219/WNJKKt_fDxE=/

### Code sample

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final isar = await Isar.open(
    [
      SimpleTestSchema
    ],
    name: 'myapp',
    directory: (await getApplicationDocumentsDirectory()).path,
    inspector: false,
  );
}
```

### Details

 - Platform: Ubuntu 22.04.1
 - Flutter version: 3.3.4
 - Isar version: 3.0.2

---

 - [ x ] I searched for similar issues already
 - [ x ] I filled the details section with the exact device model and version
 - [ x ] I am able to provide a reproducible example

**Comment by StefanZimmermann98** [comment]
Addition: only happens when trying to open an isar db created with version 2, on a new one the application starts as usual

**Comment by leisim** [comment]
Do you have a small sample that triggers this issue on upgrade? I tried for some time now and fail to reproduce it 😭

**Comment by anandsubbu007** [comment]
On windows, app crashes with 

```
thread 'isarworker' panicked at 'range end index 33282 out of range for slice of length 152', library\core\src\slice\index.rs:73:5
stack backtrace:
   0:     0x7ffc12d09e39 - <unknown>
   1:     0x7ffc12ca735a - <unknown>
   2:     0x7ffc12d00f49 - <unknown>
   3:     0x7ffc12d0b87b - <unknown>
   4:     0x7ffc12d0c4a6 - <unknown>
   5:     0x7ffc12d0c083 - <unknown>
   6:     0x7ffc12d0bfe9 - <unknown>
   7:     0x7ffc12d0bfa4 - <unknown>
   8:     0x7ffc12d84595 - <unknown>
   9:     0x7ffc12ca6b5b - <unknown>
  10:     0x7ffc12ca6ad9 - <unknown>
  11:     0x7ffc12ca6ac9 - <unknown>
  12:     0x7ffc12d84639 - <unknown>
  13:     0x7ffc12cdba55 - <unknown>
  14:     0x7ffc12cd50b4 - <unknown>
  15:     0x7ffc12cd22b0 - <unknown>
  16:     0x7ffc12ccadd8 - <unknown>
  17:     0x7ffc12c9d375 - <unknown>
  18:     0x7ffc12c795a4 - <unknown>
  19:     0x7ffc12d0e2d9 - <unknown>
  20:     0x7ffc12d0d43b - <unknown>
  21:     0x7ffc12d0933c - <unknown>
  22:     0x7ffc418f7034 - BaseThreadInitThunk
  23:     0x7ffc42a226a1 - RtlUserThreadStart
Lost connection to device.
```
