### ISSUE TITLE
I can't create a composite index to double field

### ISSUE THREAD

**Issue by omarfaroke** [isar/isar#768]
### Steps to Reproduce

When I try to create a composite index to double field, I get the following error from the isar_generator:

```
Only the last property of a composite index may be a double value.
/features/vendors/repositories/local/collections/vendor_rate.dart:12:10
   ╷
12 │   double rating;
   │          ^^^^^^
   ╵
```

### Code sample

```dart
part 'vendor_rate.g.dart';

@collection
class VendorRate {
  @Index(unique: true, replace: true)
  Id id;

  @Index(composite: [CompositeIndex('ratingCount')])
  double rating;

  int ratingCount;
 // double ratingCount; // I tried to create a composite index for two double fields, but I get the same error

  DateTime updatedAt;
}
```

### Details

 - Flutter version: 3.3.3
 - Isar version: 3.0.2

**Comment by leisim** [comment]
The error message is very clear here. Only the last property of a composite index can be a double property.

**Comment by kirpit** [comment]
Hi, this is an awesome database, much appreciated! However, defining a composite index is really, I mean REALLY confusing.. See, I've been trying to create a composite index like this:

```
class SomePlace {
  Id? id;

  @Index(type: IndexType.hash)  // <-- This is fine
  late String category;

  // Composite index on these:
  late double latitude;
  late double longitude;
}
```

but no matter what combination I tried, I get the same error. It's true that I do query these coordinates with the `category` field so I also tried to combine them altogether, no luck.

I do need to have both `latitude` as well as `longitude` fields included in the composite index. Also, which one exactly is the "last property" ? Is it the one that the index defined ON? or the one that comes in the `composite:` list? Does the order of field definition matter at all? Should I put the index on the earlier field definition or the last one? Sorry, so many questions here but the error message is not really clear..

=================
None of the below attempts seem to work for me and I would really use some help.

```
  @Index(name: 'geo_only', composite: [CompositeIndex('longitude')])
  late double latitude;
  late double longitude;
```

```
  late double latitude;
  @Index(name: 'geo_only', composite: [CompositeIndex('latitude')])
  late double longitude;
```

```
  @Index(name: 'geo_by_category', type: IndexType.hash, composite: [
    CompositeIndex('latitude'),
    CompositeIndex('longitude'),
  ])
  late String category;

  late double latitude;
  late double longitude;
```

```
  late String category;
  late double latitude;

  @Index(name: 'geo_by_category', composite: [
    CompositeIndex('category', type: IndexType.hash),
    CompositeIndex('latitude'),
  ])
  late double longitude;
```
