### ISSUE TITLE
Insert works on IsarLink, but doesn't update data

### ISSUE THREAD

**Issue by ebelevics** [isar/isar#774]
So a plain simple example of IsarLink/IsarLinks example I stumbled recently. While inserting data in db with relations student with assigned teacher, the update part doesn't work as flawlessly as insert. The subject stays the same "Math", and did not update to "Physics" in DB. 
Did I forgot something or do I need to do putSync for every nested IsarLink in Object, which is weird because insert works fine?
Also I get student from DB with updated teacher ID, so there's is a reference which row should be updated in DB. If there's no workaround then it just seems I have to create Dao object for every table I have in DB, and do putSync manually for every object in relation.

```dart
@collection
class Teacher {
  Id? id;
  late String subject;
}

@collection
class Student {
  Id? id;
  late String name;
  final teacher = IsarLink<Teacher>();
}

void main() async {
  final isar = await Isar.open([StudentSchema, TeacherSchema], inspector: true);

  final mathTeacher = Teacher()..subject = 'Math';

  final linda = Student()
    ..name = 'Linda'
    ..teacher.value = mathTeacher;

  final studentId = isar.writeTxnSync(() => isar.students.putSync(linda));
  final updatedStudent = isar.students.getSync(studentId)!;

  updatedStudent.name = "Anna";
  final teacher = updatedStudent.teacher.value!;
  teacher.subject = "Physics";
  updatedStudent.teacher.value = teacher;

  final studentId2 = isar.writeTxnSync(() => isar.students.putSync(updatedStudent));
  print(studentId2);
}
```

**Comment by darul9061** [comment]
@ebelevics you need to save the isarlink(teacher).

Add this:
updatedStudent.teacher.saveSync();

**Comment by ebelevics** [comment]
Alright I'll try again in example and separate project. Thanks, will give feedback.

**Comment by darul9061** [comment]
Remember to put that line of code inside a synchronous transaction

**Comment by ebelevics** [comment]
```dart
...
  updatedStudent.name = "Anna";
  final teacher = updatedStudent.teacher.value!;
  teacher.subject = "Physics";
  updatedStudent.teacher.value = teacher;

  final studentId2 = isar.writeTxnSync(() {
    updatedStudent.teacher.saveSync();
    isar.students.putSync(updatedStudent);
  });
...
```

Well tried doing this, but the value is still the same ("Math")

<img width="236" alt="image" src="https://user-images.githubusercontent.com/25333580/195603680-f81708c3-0bb6-4306-adc6-6daf19b63105.png">

**Comment by darul9061** [comment]
Remove this from the transaction.

isar.students.putSync(updatedStudent);

**Comment by darul9061** [comment]
Try this --->

final updatedStudent = isar.students.getSync(studentId)!;

updatedStudent.name = "Anna";

await updatedStudent.teacher.load();
final teacher = updatedStudent.teacher.value!;
teacher.subject = "Physics";
updatedStudent.teacher.value = teacher;

final studentId2 = isar.writeTxnSync(() {
    updatedStudent.teacher.saveSync();
    isar.students.putSync(updatedStudent);
});

**Comment by ebelevics** [comment]
Tried it, nope same result ("Math"). Doesn't it work properly for you?

```dart
  updatedStudent.name = "Anna";

  await updatedStudent.teacher.load();
  final teacher = updatedStudent.teacher.value!;
  teacher.subject = "Physics";
  updatedStudent.teacher.value = teacher;

  final studentId2 = isar.writeTxnSync(() {
    updatedStudent.teacher.saveSync();
    isar.students.putSync(updatedStudent);
  });

  final updatedStudent2 = isar.students.getSync(studentId)!;
  await updatedStudent2.teacher.load();
```
The only thing that does work is:
```dart
  final studentId2 = isar.writeTxnSync(() {
    isar.teachers.putSync(teacher);
    isar.students.putSync(updatedStudent);
  });
```
But then I'll have to create separate DAO for every collection. And even then I came to issue not enabling merge isar.write if there's nested isar.write:

```dart
  final studentId2 = isar.writeTxnSync(() {
    isar.students.putSync(updatedStudent);
    teacherDaoPut(isar, teacher);
  });

  final updatedStudent2 = isar.students.getSync(studentId)!;
  await updatedStudent2.teacher.load();
}

void teacherDaoPut(Isar isar, Teacher teacher) {
  isar.writeTxnSync(() {
    isar.teachers.putSync(teacher);
  });
}
```

**Comment by ebelevics** [comment]
Switched DB to Realm as there these things just work. Closed as this issue now is irrelevant.
