### ISSUE TITLE
Multi-entry indexes unsupportedOnWeb

### ISSUE THREAD

**Issue by JanRegent** [isar/isar#777]
used:
 @Index(type: IndexType.value, caseSensitive: false)
  List<String> get descriptionWords => Isar.splitWords(description);  //failed on this line 

got:
packages/isar/src/web/isar_web.dart 18:3
unsupportedOnWeb

**Version**
 - Platform:  Web 
 - Flutter version: (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19044.2006], locale
    cs-CZ)
 - Isar version: ^3.0.0-dev.5

**Comment by samithe7** [comment]
At 3.0.0 version web is not supported, you will need to wait a bit longer before the web is supported.
yoy can use 2.5.0 which is support web

**Comment by simc** [comment]
This issue is obsolete now
