### ISSUE TITLE
flutter: Invalid argument(s): Failed to load dynamic library (dlopen(libisar.dylib, 1): image not found)

### ISSUE THREAD

**Issue by derolf** [isar/isar#79]
Version: 0.4.0

Works fine on iOS, but on MacOS (64bit), the library isn't loaded...

**Comment by derolf** [comment]
I successfully added the framework and I am now getting:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: IsarError: LmdbError (1): "Operation not permitted"
```

**Comment by derolf** [comment]
Using instruments, I found this:

```
failed on open with path private/tmp/isar/lock.mdb. Error = Operation not permitted
```

**Comment by viveknimkarde** [comment]
@derolf were you able to fix the issue ?

**Comment by defuncart** [comment]
Experiencing the same issue with isar 0.4.0 and latest isar-core for macOS ([0.4.3](https://github.com/isar/isar-core/releases/tag/0.4.3)). From [this discussion](https://github.com/isar/isar/discussions/101#discussioncomment-718381), it seems that the binaries are working on Windows.

Has anyone tried to build the macOS dylib locally? (some info [here](https://github.com/isar/isar-core/blob/main/dart-ffi/tools/build_desktop.sh)).

**Comment by barbalex** [comment]
I got it to work on windows but am experiencing this error on macos

**Comment by leisim** [comment]
Fixed now
