### ISSUE TITLE
Cannot @ignore overridden getters

### ISSUE THREAD

**Issue by westy92** [isar/isar#794]
### Steps to Reproduce

1. Extend a class with a getter.
2. Override the getter and also add `@ignore`

Expected result: overridden getter is "ignored".
Actual result: error during `flutter packages pub run build_runner build`.

Assume that `Name1` is an external class we have no control over (we can't add `@ignore` to it.)

### Code sample

```dart
abstract class Name1 {
  const Name1();

  List<Object?> get props;
}

@embedded
class Name2 extends Name1 {
  const Name2({
    this.name = 'unknown'
  });

  final String name;

  @ignore
  @override
  List<Object> get props => <Object>[name];
}
```

```bash
[SEVERE] isar_generator on lib/models/Name.dart:

Unsupported type. Please annotate the property with @ignore.
package:checkiday/models/Name.dart:13:21
   ╷
13 │   List<Object?> get props;
   │                     ^^^^^
   ╵
```

Workaround:
List the properties in the annotation and drop the `@ignore` annotation on the getter.
```dart
@Embedded(ignore: <String>{'props'})
class Name2 extends Name1 {
  const Name2({
    this.name = 'unknown'
  });

  final String name;

  @override
  List<Object> get props => <Object>[name];
}
```

### Details

 - Platform: N/A
 - Flutter version: 3.3.4 stable
 - Isar version: 3.0.2

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version - N/A
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
Please use the search before opening an issue. The workaround was introduced specifically for overriding.
The docs also mention how to use it 🙂

**Comment by pravindodia** [comment]
> Please use the search before opening an issue. The workaround was introduced specifically for overriding. The docs also mention how to use it 🙂

@simc  it would great if you could point me to the documentation or workaround as I could not find it. and still facing with latest version of isar.
