### ISSUE TITLE
IsarError: Unique index violated when Export & Import From 2.5 to 3 

### ISSUE THREAD

**Issue by anandsubbu007** [isar/isar#800]
### Steps to Reproduce

when i tru to import the data with `isar.{schema}.importJson()` it is always throwing `IsarError: Unique index violated`
The data is generated from isar 2.5.0
I tried deleting all data in each schema before importing. it also throw Error. 
is there any way to implement `replaceOnConflicts` like in 2.5 for isar 3.0

### Code sample

```dart
//export 
          await isar.data.where().exportJson();
//Import
 await isar.writeTxn(() async {
        await isar.data.importJson(jsonData['data'] ?? []);
      }, silent: true);
```

### Details

 - Platform: Windows.
 - Flutter version: [e.g. 3.3.4]
 - Isar version: [e.g. 3.0.2]

---

 - [ ] I searched for similar issues already
 - [ ] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by bringbackthedog** [comment]
Is `replaceOnConflicts` completely removed or was it replaced by another method? It was pretty critical for us to have the possibility to overwrite data with newer data.

**Comment by leisim** [comment]
Yes, the index annotation has a replace parameter.

**Comment by roiskhoiron** [comment]
@anandsubbu007  how you solve this issue before?

this is mycode :
`@Index(unique: true, replace: true)`
