### ISSUE TITLE
The database is full.

### ISSUE THREAD

**Issue by xioxin** [isar/isar#813]
### Steps to Reproduce

When the database file size reaches ~2G (2097152000 bytes), the database is full
```
Unhandled exception:
IsarError: The database is full.
```

### Code sample

```dart
import 'dart:io';
import 'package:isar/isar.dart';
part 'test_isar.g.dart';

@collection
class User {
  Id id = Isar.autoIncrement; // you can also use id = null to auto increment
  String? name1;
  String? name2;
  String? name3;
  String? name4;
}

const bigText = """
Features💙 Made for Flutter. Easy to use, no config, no boilerplate🚀 Highly scalable The sky is the limit (pun intended)🍭 Feature rich. Composite & multi-entry indexes, query modifiers, JSON support etc.⏱ Asynchronous. Parallel query operations & multi-isolate support by default🦄 Open source. Everything is open source and free forever!Isar database can do much more (and we are just getting started🕵️ Full-text search. Make searching fast and fun📱 Multiplatform. iOS, Android, Desktop and FULL WEB SUPPORT!🧪 ACID semantics. Rely on database consistency💃 Static typing. Compile-time checked and autocompleted queries✨ Beautiful documentation. Readable, easy to understand and ever-improvingJoin the Telegram group for discussion and sneak peaks of new versions of the db.If you want to say thank you, star us on GitHub and like us on pub.dev 🙌💙
""";

void main() async {
  await Isar.initializeIsarCore(download: true);
  final isar = await Isar.open([UserSchema],
      inspector: true, directory: Directory.current.path, name: "full-test");

  while (true) {
    await isar.writeTxn(() async {
      isar.users.putAll(List.generate(
          100,
          (index) => User()
            ..name1 = bigText
            ..name2 = bigText
            ..name3 = bigText
            ..name4 = bigText));
    });
  }
}

```
Waiting for fill to 2.1G
![image](https://user-images.githubusercontent.com/5716100/197398896-c41adc58-5c82-404e-ad89-56ab3fc10693.png)
![image](https://user-images.githubusercontent.com/5716100/197399050-ae0e63f1-b14e-4600-b0a7-03251897cf05.png)

### Details

 - Platform: Windows 11
 - Dart SDK version: 2.19.0-255.0.dev
 - Isar version: 3.0.2

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by xioxin** [comment]
> How much memory have you allocated? I believe the database size is limited by the available virtual memory.

Thank you for your advice.
I don't know how to allocate memory.
I checked `dart --help --verbose`
`old_gen_heap_size: 30720 MB`
Dart VM appears to have plenty of memory.

**Comment by leisim** [comment]
2GB is the maximum supported size currently. I'll add an option to increase the allowed size

**Comment by leisim** [comment]
There is a new property to customise the max database size (`maxSizeMib`) a new version will be released soon

**Comment by lrorpilla** [comment]
I seem to be getting instances where I get this message even though I am nowhere near past the limit, I've even increased my size to 10GB (the size of user data/cache is only around 1GB) and I set the above parameter to 10240.

I'm trying to import 700K objects in one single transaction and get "The database is full", while the message does not show if I import 1K objects 700K times instead.

I also have feedback from users on slower devices where importing too many objects crashes their device but if I do the alternative 1K per transaction limit, no crash occurs. I'll probably make a new issue for this with the proper information, I'm on the latest Isar version.
