### ISSUE TITLE
Windows 11 undetermined crash

### ISSUE THREAD

**Issue by StevenGolhen** [isar/isar#827]
### Steps to Reproduce

I think the bug I am experiencing is related to the two issues #762 #687. But I am not totally sure, that's why I open a new issue.
Here is an example of a reproducible code, I hope it will be useful.
[isar_windows_issue.zip](https://github.com/isar/isar/files/9858414/isar_windows_issue.zip)
You have to run the main function 3 times to see the bug appear.

The first two times, everything is fine...
![image](https://user-images.githubusercontent.com/28529032/197719971-ea073c04-7101-4baf-9617-76bdb3ad3f10.png)

... But after the third time, the problem appears like below, always in the same place. And nothing can be done (clear() etc.) except to delete the DB by hand.
![image](https://user-images.githubusercontent.com/28529032/197720149-c9150f1a-289c-426b-9958-9043d4848544.png)

### Code sample

```dart
import 'package:isar/isar.dart';

part 'isar_windows_issue.g.dart';

@Collection()
class Entry {
  Id? id;
  @Index(unique: true, replace: true)
  String data;

  Entry(this.data);
}
```

```dart
import 'dart:io';

import 'package:isar/isar.dart';
import 'package:isar_windows_issue/isar_windows_issue.dart';

Future<void> main(List<String> arguments) async {
  await Isar.initializeIsarCore(download: true);

  var s = Stopwatch();
  s.start();

  final isar =
      await Isar.open([EntrySchema], name: 'entries', directory: './bin');

  List<Entry> entries = [];

  for (int i = 1; i <= 10000; i++) {
    entries.add(Entry('A' * i));
  }

  var collection = isar.entrys;

  try {
    await isar.writeTxn(() async {
      for (final entry in entries) {
        var id = await collection.putByData(entry);
        print(id);
      }
      // var id = await collection.putAllByData(entries);
      // print(id);
    });

    var collectionCount = await collection.count();
    print('DB count : $collectionCount');
    var size = await isar.getSize();
    print('${size / 1000} ko');
  } catch (err) {
    print(err);
  } finally {
    print(await isar.close());
  }

  s.stop();
  print('${s.elapsed.inMilliseconds} millisecond(s) to build DB');

  exit(0);
}
```

### Details

 - Platform: Windows 11
 - Flutter version: 3.3.5
 - Isar version: 3.0.2

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
Thanks for the example I'll take a look 💜

**Comment by StevenGolhen** [comment]
hi!
Any news on this issue? @leisim 
Currently, I can't use Isar on windows because of this problem for fields larger than 4kb (which strangely appears after a 3rd write/re-write, which freezes the DB and makes it unusable).
Or maybe I'm not using the package correctly, any tips or ideas on how I can get unstuck?
Thx!

**Comment by leisim** [comment]
#687
