### ISSUE TITLE
Isar is not working in background service

### ISSUE THREAD

**Issue by Djihanegh** [isar/isar#829]
### Steps to Reproduce

When the app is running in the foreground everything is working fine, when i close the app, the database is cleaned(maybe its creating a new instance each time), why ?

### Code sample
Here is how im using Isar

```dart
class IsarService {
  static Future<Isar>? db;

  IsarService() {
    db = openDB();
  }

  static Future<List<Apps>> getAllApps() async {
    final isar = await db;
    List<Apps> apps = [];

    try {
      await isar!.txn(() async {
        apps = await isar.apps.where().findAll();
      });
    } catch (e) {
      log(e.toString());
    }

    return apps;
  }

  static selectApp(String name) async {
    final isar = await db;
    Apps? app = await isar!.apps.filter().nameEqualTo(name).findFirst();

    if (app != null) {
      await isar.writeTxn(() async {
        app.isSelected = !app.isSelected;
        isar.apps.put(app); // perform update operations
      });
    }
  }

  static Future<void> setIgnoreLastApp(bool value) async {
    final isar = await db;
    IgnoredApps? app = await isar!.ignoredApps.get(1);

    if (app != null) {
      await isar.writeTxn(() async {
        app.shouldIgnore = value;
        await isar.ignoredApps.put(app); // perform update operations
      });
    } else {
      IgnoredApps newApp = IgnoredApps(false);
      await isar.writeTxn(() async {
        isar.ignoredApps.put(newApp);
      });
    }
  }

  static Future<bool?> getIgnoreLastApp() async {
    final isar = await db;

    return isar!.ignoredApps
        .filter()
        .idEqualTo(1)
        .findFirstSync()!
        .shouldIgnore;
  }

  static Future<void> setNavigation(bool value) async {
    final isar = await db;
    AppNavigation? app = await isar!.appNavigations.get(1);

    if (app != null) {
      await isar.writeTxn(() async {
        app.navigated = value;
        isar.appNavigations.put(app); // perform update operations
      });
    } else {
      AppNavigation newApp = AppNavigation(false);
      await isar.writeTxn(() async {
        isar.appNavigations.put(newApp);
      });
    }
  }

  static Future<bool?> getNavigation() async {
    final isar = await db;

    return isar!.appNavigations
        .filter()
        .idEqualTo(1)
        .findFirstSync()!
        .navigated;
  }

  static Future<void> updateAllApps(List<Apps> apps) async {
    final isar = await db;
    return await isar!.writeTxn(() async {
      isar.apps.putAll(apps);
    });
  }

  static Future<Apps?> getOpenedApp() async {
    final isar = await db;
    return isar!.apps.filter().isOpenedEqualTo(true).findFirst();
  }

  static Future<void> closeAllOpenedApps() async {
    final isar = await db;
    await isar!.writeTxn(() async {
      List<Apps>? app =
          await isar.apps.filter().isOpenedEqualTo(true).findAll();
      if (app != null) {
        if (app != []) {
          for (var e in app) {
            if (e.isOpened) {
              e.isOpened = false;
            }
          }
        }

        isar.apps.putAll(app);
      }
    });
  }

  static openApp(String packageName) async {
    final isar = await db;
    await isar!.writeTxn(() async {
      try {
        final app = await isar.apps
            .filter()
            .packageNameEqualTo(packageName)
            .findFirst();

        app?.isOpened = true;
        isar.apps.put(app!);
      } catch (e) {
        log(e.toString());
      }
    });
  }

  static closeApp(String packageName) async {
    final isar = await db;
    await isar!.writeTxn(() async {
      final app =
          await isar.apps.filter().packageNameEqualTo(packageName).findFirst();

      app?.isOpened = false;
      isar.apps.put(app!);
    });
  }

  static Future<Apps?> isAppSelected(String packageName) async {
    final isar = await db;
    return isar!.apps
        .filter()
        .packageNameEqualTo(packageName)
        .isSelectedEqualTo(true)
        .findFirstSync();
  }

  static Future<bool?> isBreak(String packageName) async {
    final isar = await db;
    Apps? app =
        isar!.apps.filter().packageNameEqualTo(packageName).findFirstSync();
    return app!.isBreak;
  }

  static Future<void> setIsBreak(String packageName, bool value) async {
    final isar = await db;
    if (packageName.isEmpty) {
      try {
        List<Apps>? app =
            await isar!.apps.filter().isBreakEqualTo(true).findAll();

        if (app != []) {
          for (var e in app) {
            if (e.isBreak) {
              log("PACKAGE NAME  ${e.packageName}");
              await isar.writeTxn(() async {
                e.isBreak = value;
                isar.apps.put(e); // perform update operations
              });
            }
          }
        }
      } catch (e) {
        log(e.toString());
      }
    } else {
      Apps? app =
          isar!.apps.filter().packageNameEqualTo(packageName).findFirstSync();
      if (app != null) {
        await isar.writeTxn(() async {
          app.isBreak = value;
          isar.apps.put(app); // perform update operations
        });
      }
    }
  }

  static Stream<List<Apps>> listenToApps() async* {
    final isar = await db;
    yield* isar!.apps.where().watch();
  }

  static Future<void> cleanDb() async {
    final isar = await db;
    await isar!.writeTxn(() => isar.clear());
  }

  static Future<Isar> openDB() async {
    if (Isar.instanceNames.isEmpty) {
      db = Isar.open(
        [
          AppsSchema,
          AppNavigationSchema,
          IgnoredAppsSchema,
          SelectedTimesSchema
        ],
        inspector: true,
      );
    } else {
      db = Future.value(Isar.getInstance());
    }

    return db!;
  }
}
```

### Details

 - Platform: Android device ( Android 10 )
 - Flutter version: 3.0.5
 - Isar version: 3.0.2

**Comment by liemfs** [comment]
Did you call `cleanDb` somewhere in your code ?

**Comment by Djihanegh** [comment]
> No, i'am just initializing isar in **main** and in the beginning of the **background service**
> 
> ```dart
> void initializeIsarDB() async {
>   getIt<IsarService>();
>   await IsarService.setIgnoreLastApp(false);
>   await IsarService.setNavigation(false);
>   await IsarService.closeAllOpenedApps();
>   await IsarService.setIsBreak("", false);
> }
> 
> // Background service
> @pragma('vm:entry-point')
> void onStart(ServiceInstance service) async {
> 
>   DartPluginRegistrant.ensureInitialized();
>   configureInjection(Environment.dev);
> 
>   await Prefs.load();
>   initializeIsarDB();
> ........
> } 
> 
> // main 
> 
> @pragma("vm:entry-point")
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   configureInjection(Environment.dev);
>   await Prefs.load();
>   initializeIsarDB();
> ........ }
> ```

@liemfs

**Comment by khjde1207** [comment]
[isar-3.0.2/lib/src/native/open.dart](https://github.com/isar/isar/blob/4ae51d7a25a3ec50991e0c59b9cd0dd044ad69a8/packages/isar/lib/src/native/open.dart#L114)
stopping here.
I used the awesome notification flutter to retrieve data from isar when the button is pressed even after the application is closed.
It didn't work.

**Comment by Djihanegh** [comment]
> [isar-3.0.2/lib/src/native/open.dart](https://github.com/isar/isar/blob/4ae51d7a25a3ec50991e0c59b9cd0dd044ad69a8/packages/isar/lib/src/native/open.dart#L114) stopping here. I used the awesome notification flutter to retrieve data from isar when the button is pressed even after the application is closed. It didn't work.

Whats your problem i didn't get it ?

**Comment by khjde1207** [comment]
Isar.open in the background will wait indefinitely.

**Comment by liemfs** [comment]
> > No, i'am just initializing isar in **main** and in the beginning of the **background service**
> > ```dart
> > void initializeIsarDB() async {
> >   getIt<IsarService>();
> >   await IsarService.setIgnoreLastApp(false);
> >   await IsarService.setNavigation(false);
> >   await IsarService.closeAllOpenedApps();
> >   await IsarService.setIsBreak("", false);
> > }
> > 
> > // Background service
> > @pragma('vm:entry-point')
> > void onStart(ServiceInstance service) async {
> > 
> >   DartPluginRegistrant.ensureInitialized();
> >   configureInjection(Environment.dev);
> > 
> >   await Prefs.load();
> >   initializeIsarDB();
> > ........
> > } 
> > 
> > // main 
> > 
> > @pragma("vm:entry-point")
> > void main() async {
> >   WidgetsFlutterBinding.ensureInitialized();
> >   configureInjection(Environment.dev);
> >   await Prefs.load();
> >   initializeIsarDB();
> > ........ }
> > ```
> 
> @liemfs

Can I see your full code? I can't replicate your issue based on your code below

**Comment by khjde1207** [comment]
https://github.com/khjde1207/isartest

https://youtu.be/JLB2ZSvEd0U

I implemented it as simple as possible in the flutter basic sample.

A video is also attached.

**Comment by Djihanegh** [comment]
> Isar.open in the background will wait indefinitely.

so what's the solution to that ?

**Comment by Djihanegh** [comment]
> https://github.com/khjde1207/isartest
> 
> https://youtu.be/JLB2ZSvEd0U
> 
> I implemented it as simple as possible in the flutter basic sample.
> 
> A video is also attached.



> https://github.com/khjde1207/isartest
> 
> https://youtu.be/JLB2ZSvEd0U
> 
> I implemented it as simple as possible in the flutter basic sample.
> 
> A video is also attached.

please read again my code above

**Comment by khjde1207** [comment]
I found a problem with my logic.
sorry.

**Comment by leisim** [comment]
@djihanegh could you please test version 3.0.5? It should fix your problem 🙂

**Comment by leisim** [comment]
Please reopen if you still have issues with version 3.0.5
