### ISSUE TITLE
pub.dev installation page does include isar_generator

### ISSUE THREAD

**Issue by guyluz11** [isar/isar#830]
[pub.dev installation page](https://pub.dev/packages/isar/install) does not include [isar_generator](https://pub.dev/packages/isar_generator/install)

![image](https://user-images.githubusercontent.com/9304740/197835281-80410c4c-47d3-4a3c-8f01-d083cb674e8f.png)

The packages isar and isar_generator complementing each other and come together so why not let the developer know on the installation page?

It is stated in the readme page section [Quickstart](https://pub.dev/packages/isar#quickstart) 

![image](https://user-images.githubusercontent.com/9304740/197836257-5bb6d0c0-97b0-4008-8b36-d5cfd9d4a6bc.png)

**Comment by leisim** [comment]
The installation page is auto generated by pub.dev and not customizable
