### ISSUE TITLE
Isar dart native linux Failed to load dynamic library libisar.so

### ISSUE THREAD

**Issue by guyluz11** [isar/isar#832]
Does Isar support dart native on Linux?, if so I will create a reproducible example.

I have just moved all my project to Isar and now that it crashes I am not even sure if it supports dart native.
Saw [here](https://stackoverflow.com/questions/74128552/failed-to-load-isar-dylib-libisar-dylib) that it needs `isar_flutter_libs` in order to run, but this is dart native so I can't user flutter packages. 

### Steps to Reproduce

1. Create a dart native project on a Linux machine (not a Flutter project).
2. Add some Isar objects and code to excess it.
3. Run your code

### Code sample

```dart
Provide a few simple lines of code to show your problem.
```

### Details

 - Platform: Linux
 - Flutter version: (no flutter version it is dart native)
- Dart version: `^2.18.0`
 - Isar version: `^3.0.2`

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

Error:

> Invalid argument(s): Failed to load dynamic library '/project_path/cbj_hub/bin/libisar.so': /project_path//cbj_hub/bin/libisar.so: cannot open shared object file: No such file or directory

**Comment by leisim** [comment]
Please check out the last section of the repo readme about unit tests and Dart only programs

**Comment by guyluz11** [comment]
Ok so I need to use `await Isar.initializeIsarCore(download: true) `.

But is it recommend for dart native or it will be bad experience.

I wouldn't expect that part to be under unit tests, so does it means that it will run poorly in production if it is only intended for tests?

**Comment by leisim** [comment]
Its just a way of downloading the Isar libraries automatically. Even better would be if you took care of distributing them with your program.

You can find the libraries in the latest release on GitHub
