### ISSUE TITLE
when upgrade to 3.0.2, I can't run my project on ios

### ISSUE THREAD

**Issue by codepgq** [isar/isar#841]
## Error info
```
    - `isar_flutter_libs` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

I know that it can be solved by adding `ENV['SWIFT_VERSION'] = '5'` to the Podfile, but my project is a Flutter module, and the files are automatically generated, and I don't want to modify it every time.

**Comment by leisim** [comment]
Yes, this has been implemented. New version will go out in the coming days
