### ISSUE TITLE
error in generated file for collection with embedded classes in seperate file

### ISSUE THREAD

**Issue by DennisSchm** [isar/isar#842]
### Steps to Reproduce

Hello, 

when I tried to implement an embedded class in a seperate file it produced errors in the gerenerated file of the class trying to embedd it. This also prevents you from embedding the same class in two different classes. 

I can't tell if this feature is just not supported or if this is a bug. For the time being I marked it as a bug since it seems to be inconvenient to handle it that way. 

You can reproduce my case with the following code snippets. 

### Code sample

**library.dart**
```dart
import 'package:isar/isar.dart';
import 'book.dart'
part 'library.g.dart';

@Collection(accessor: 'libraries')
class Library {
  Library({this.books = const []});
  Id? id;
  List<Book>? books;
}
```

**book.dart**
```dart
import 'package:isar/isar.dart';

@embedded
class Book {
  Book({this.title, this.publishedAt});
  String? title;
  DateTime? publishedAt;
}
```
five lines in the generated library file "library.g.dart" produce an error
in line 34 
```dart
embeddedSchemas: {r'Book': BookSchema},
``` 
it is
```
A value of type 'Null' can't be assigned to a parameter of type 'Map<String, Schema<dynamic>>' in a const constructor.
Try using a subtype, or removing the keyword 'const'.dart[const_constructor_param_type_mismatch](https://dart.dev/diagnostics/const_constructor_param_type_mismatch)
Undefined name 'BookSchema'.
Try correcting the name to one that is defined, or defining the name.dart[undefined_identifier](https://dart.dev/diagnostics/undefined_identifier)
The values in a const map literal must be constant.
Try removing the keyword 'const' from the map literal.dart[non_constant_map_value](https://dart.dev/diagnostics/non_constant_map_value)
Invalid constant value.dart(invalid_constant)
Const variables must be initialized with a constant value.
Try changing the initializer to be a constant expression.dart[const_initialized_with_non_constant_value](https://dart.dev/diagnostics/const_initialized_with_non_constant_value)
```

in line 55
```
bytesCount += BookSchema.estimateSize(value, offsets, allOffsets);
```
it is 
```
A value of type 'num' can't be assigned to a variable of type 'int'.
Try changing the type of the variable, or casting the right-hand type to 'int'.dart[invalid_assignment](https://dart.dev/diagnostics/invalid_assignment)
```

in line 72,
```
BookSchema.serialize
```
line 86 and 105 
```
BookSchema.deserialize
```
the BookSchema can't be accessed because it is not defined.

if you create a single file like this, no error occurs.

**library.dart**
```dart
import 'package:isar/isar.dart';

part 'library.g.dart';

@Collection(accessor: 'libraries')
class Library {
  Library({this.books = const []});
  Id? id;
  List<Book>? books;
}

@embedded
class Book {
  Book({this.title, this.publishedAt});
  String? title;
  DateTime? publishedAt;
}
``` 
### Details

 - Flutter version: 3.3.6
 - Isar version: 3.0.2

---

 - [x] I searched for similar issues already
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
Please rerun the generator for all your Isar files. Looks like some of them are outdated.

**Comment by dos1in** [comment]
same issue. Isar version: 3.0.5

**Comment by AdilMango** [comment]
Any update on above issue, try to fix this from 2 days. 
`Isar version: 3.0.5`

**Comment by PresKhaled** [comment]
Same issue, but in general, this's a very good database.
`isar: ^3.1.0+1`

**Comment by willsalasare** [comment]
Same issue
version: ^3.0.5

**Comment by lionsilva** [comment]
This looks an ongoing issue. I generated the classes for all embedded involved, and what I noticed is that, for the one that had Collection annotation, the .g file had errors, just like said in this thread, and I was able to fix by going to the beginning of the file where the error about schemas were and right click and import the schemas. 

Is this correct?

Why not doing it automatically?
