### ISSUE TITLE
Sort argument isn't applied in where.

### ISSUE THREAD

**Issue by xVemu** [isar/isar#843]
### Steps to Reproduce
Read items from db with desc sorting.

### Code sample

```dart
    final db = await Isar.open([NewsSchema]);
    final list = [
      News(
        id: 123,
        tytul: "123",
        foto: "foto",
        data: "data",
        intro: "intro",
        opis: "opis",
      ),
      News(
        id: 234,
        tytul: "234",
        foto: "foto",
        data: "data",
        intro: "intro",
        opis: "opis",
      ),
    ];
    await db.writeTxn(() async {
      await db.news.where().deleteAll();
      await db.news.putAll(list);
    });
    final newlist = await db.news.where(sort: Sort.desc).findAll();
    print(newlist);
    db.close();
```
news_model:
```dart
import 'package:isar/isar.dart';
import 'package:json_annotation/json_annotation.dart';

part 'generated/news_model.g.dart';

@JsonSerializable()
@collection
class News {
  News({
    required this.id,
    required this.tytul,
    required this.foto,
    required this.data,
    required this.intro,
    required this.opis,
  });

  Id id;
  String tytul;
  String foto;
  String data;
  String intro;
  String opis;

  factory News.fromJson(Map<String, dynamic> json) => _$NewsFromJson(json);

  @override
  String toString() {
    return 'News{id: $id, tytul: $tytul, foto: $foto, data: $data}';
  }
}
```

### Expected result
[News{id: 234, tytul: 234, foto: foto, data: data}, News{id: 123, tytul: 123, foto: foto, data: data}]

### Actual behavior
[News{id: 123, tytul: 123, foto: foto, data: data}, News{id: 234, tytul: 234, foto: foto, data: data}]

### Details

 - Platform: Android Emulator on Windows, Android SDK 33
 - Flutter version: 3.3.5
 - Isar version: 3.0.2

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
You want sorting by id in ascending order right? You specify `Sort.desc` which stands for descending.

Remove it or change it to `Sort.asc`

**Comment by xVemu** [comment]
No, I want sorting in descending order.

**Comment by leisim** [comment]
Oh sorry misread your description 😅

**Comment by xVemu** [comment]
Any news?

**Comment by nayeemtby** [comment]
Same here, want to sort by id in descending order. In my case though ids are like auto-incrementing so I can generate the list of ids in reverse order and use `getAll()` to get the data.

**Comment by a1573595** [comment]
Same issue

**Comment by LesYampolskyi** [comment]
Try to add .anyId() after .where()

final newlist = await db.news.where(sort: Sort.desc).anyId().findAll();

**Comment by xVemu** [comment]
> Try to add `anyId()` after `where()`
> 
> `final newlist = await db.news.where(sort: Sort.desc).anyId().findAll();`

This workaround works, thank you.

**Comment by simc** [comment]
This is fixed in v4
