### ISSUE TITLE
Error resolving isar_connect 0.4.0 dependencies

### ISSUE THREAD

**Issue by Yeikel200** [isar/isar#85]
I have error adding `isar` dependencies to project in `pubspec.yaml`

**Code sample**
```
[tranfer_history] flutter pub get
Running "flutter pub get" in tranfer_history...                 
Because tranfer_history depends on isar_connect 0.4.0 which doesn't match any versions, version solving failed.
pub get failed (1; Because tranfer_history depends on isar_connect 0.4.0 which doesn't match any versions, version solving failed.)
exit code 1
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 2.0.5
 - Isar version: 0.4.0
 - Isar Generator version: 0.4.0

**Comment by barbalex** [comment]
Duplicate of https://github.com/isar/isar/issues/65

**Comment by leisim** [comment]
Unfortunately this can only be fixed with the next release in a few days :/
