### ISSUE TITLE
Constructors of embedded objects must not have required parameters.

### ISSUE THREAD

**Issue by liamsammut97** [isar/isar#853]
how can this be decoded from a json object and used in isar ? removing it from required will make me check for null safety all over the UI, which is not needed as the id will never be null

@embedded
class EventId {
  EventId({
    required this.id,
  });

  int id;

  factory EventId.fromJson(Map<String, dynamic> json) => EventId(
        id: json["id"],
      );
}

**Comment by Macacoazul01** [comment]
You could force id = 0 as default if you're certain that it will always have a value and the null check isn't necessary.

**Comment by leisim** [comment]
Yes, Isar needs to instantiate embedded objects without parameters so just provide a default value for your parameters.

**Comment by Ayad-Ben-Saliem** [comment]
What is the point of making the constructors must not have required parameters?

**Comment by simc** [comment]
Isar v4 supports this
