### ISSUE TITLE
Big ints are not getting stored correctly

### ISSUE THREAD

**Issue by cm-tec** [isar/isar#856]
Hey,

while trying to implement String ids, following this approach https://isar.dev/recipes/string_ids.html, I made the discovery that big numbers are not stored correctly.

For example:
The UUID: "bb9e1875-5d7f-40ef-8baf-4b6619d3797c"  gets by the recommended hashing function hashed to -9054632377310234349. If you try to insert this number as an id to isar it gets converted to -9054632377310235000.

The issue is in my opinion related to this limitation of JSON: https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigin

**Comment by leisim** [comment]
Do you have a small sample that shows the issue?

**Comment by cm-tec** [comment]
Yeah sure:

```
import 'package:isar/isar.dart';

part 'fruit.g.dart';

@collection
class Fruit {
  Fruit({
    required this.id,
    required this.name,
  });

  Id id;

  String name;
}
```

If you now try to add the following fruit to the database via the isar-inspector or by writing to the database...
```
{
  "id": -9054632377310234349,
  "name": "apple"
}
```
the stored fruit gets the following id:
```
{
"id": -9054632377310235000,
"name": "apple"
}
```

**Comment by leisim** [comment]
Oh I missed the fact that you were using the Inspector. Javascript does not support integers above 2^53.

If you try to insert the number in Dart everything will be fine 🙂

**Comment by cm-tec** [comment]
No, unfortunately it does not work in Dart either. I originally noticed the error in Dart. Here is a code example which creates the same wrong id as with the isar inspector:

````
final fruit = Fruit(id: -9054632377310234349, name: 'apple');

await _isar.writeTxn(() async {
      await _isar.fruits.put(fruit);
});
````
