### ISSUE TITLE
return id when new record is put

### ISSUE THREAD

**Issue by barbalex** [isar/isar#86]
It would be nice if when creating a new record, it's id were returned:

```dart
int id = await contacts.put(newContact);
```

Today this is not possible because put returns void.

I feel that it is standard for api's and databases to offer an ability to have the id returned in some way or other when inserting a new record. Often the entire object is returned.

My use-case: When the user creates a new object, the app should open it's form. So I want to pass the id to the route.

**Version**
 - Platform: Android
 - Flutter version: 2.2.0-10.1.pre
 - Isar version: 0.4.0

**Comment by leisim** [comment]
@barbalex The id property of your `newContact` will contain the new id.

**Comment by barbalex** [comment]
Omg. Thanks!

**Comment by volser** [comment]
@leisim  hm, it mutates input? does not look like a good solution :)

**Comment by leisim** [comment]
@volser It only mutates the input if the id is set to `null` (= auto increment). But you are right we have a problem if we want to support immutable models.

**Comment by yringler** [comment]
The id can be declared `late`; I think that's close enough to immutable?

**Comment by f-person** [comment]
> if we want to support immutable models

Is it possible to use immutable models now? I'm considering `Isar` for a side-project of mine but I'd like to fully avoid mutable models
