### ISSUE TITLE
IsarError: Cannot open Environment: MdbxError (75): Value too large for defined data type

### ISSUE THREAD

**Issue by jlangfor** [isar/isar#860]
### Steps to Reproduce

I'm simply attempting to run on the Android simulator and as soon as I attempt to open the database it throws the error that can be seen below. The code in the sample section is where the error is thrown. I am calling the open from the app.dart and passing it down through to my other pages so it is only ever run once. 

Interesting note is that I do NOT see this on the iOS simulator and everything works as intended. 

### Error Image
![Screenshot 2022-11-04 at 10 41 48 PM](https://user-images.githubusercontent.com/10674733/200099330-717a70a5-407d-4dab-90cd-49c3cbf1e339.png)

### Code sample

```dart
Future<Isar> open() async {
    if (Isar.instanceNames.isEmpty) {
      return await Isar.open(
        [
          DownloadCourseSchema,
          DownloadLectureSchema,
        ],
        inspector: true,
      );
    }

    return Future.value(Isar.getInstance());
  }
```

### Details

 - Platform: x86 Android Emulator on macOS (Pixel 4 API 30)
 - Flutter version: 3.3.7
 - Isar version: 3.0.2

---

 - [ x ] I searched for similar issues already
 - [ x ] I filled the details section with the exact device model and version
 - [ x ] I am able to provide a reproducible example

**Comment by leisim** [comment]
There is an issue that only affects x86 emulators. Please use an x64 emulator instead

**Comment by jlangfor** [comment]
You are a gentleman and a scholar! Thanks for the quick reply, that was the issue.

**Comment by willsalasare** [comment]
Is there an android tv x64 emulator?
