### ISSUE TITLE
Safe to use Isar 2.5.0 with ffi ^2.x.x?

### ISSUE THREAD

**Issue by bringbackthedog** [isar/isar#867]
### Discussed in https://github.com/isar/isar/discussions/866

<div type='discussions-op-text'>

<sup>Originally posted by **bringbackthedog** November  7, 2022</sup>
Based on #686 we must use Isar 2.5.0.  

Isar 2.5.0 depends on `ffi: ^1.1.2`.  Our app's packages depends on `ffi ^2.x.x`, causing an error in version solving (different major versions of ffi).   

Is is safe to override the ffi dependency to ^2.0.1 while using Isar 2.5.0? 
</div>

**Comment by leisim** [comment]
Yes
