### ISSUE TITLE
Did the https://inspect.isar.dev/ inspector just stop working?

### ISSUE THREAD

**Issue by enchance** [isar/isar#870]
### Steps to Reproduce

Please describe exactly how to reproduce the problem you are running into.
Inspector won't go beyond the preloader. Checking the browser console it  seems that there's an issue with the websocket. I'm on  a linux system and yes, this did work before.

![screenshot](https://i.imgur.com/blbi5k0.png "Browser screenshot")

### Code sample

Nothing out of the ordinary here. This could be a server issue.
```dart
final dir = await getApplicationSupportDirectory();
await Isar.open(
  [MySchemas],
  directory: dir.path,
);
```

### Details

Flutter info:
```bash
Flutter 3.3.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e99c9c7cd9 (6 days ago) • 2022-11-01 16:59:00 -0700
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0
```
Isar info
```dart
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
```

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by enchance** [comment]
Sorry, I just realized that it's talking to `127.0.0.1`. The problem must be in my system. Will have to check it out.

**Comment by enchance** [comment]
Yes, this can be closed now. It seems an update of Brave caused this. After running it in chrome it worked just fine. Still doesn't work in Firefox though.

**Comment by jeroenvervaeke** [comment]
@enchance How did you resolve this? I have the same issue.

**Comment by jeroenvervaeke** [comment]
Update, everything seems to work well when I try the same thing on Android, seems to be a linux issue
