### ISSUE TITLE
Offline inspector for Linux

### ISSUE THREAD

**Issue by enchance** [isar/isar#871]
**Is your feature request related to a problem? Please describe.**
I understand that the inspector talks to the Isar server. This might pose a security issue for some projects. Plus the requirement that you need to have on online connection to check the db.

**Describe the solution you'd like**
Offline version for Linux users. This can be in the form of either an AppImage file, DEB, or even better a local JS version of the remote site (maybe).

**Describe alternatives you've considered**
None at the moment. I'm limited to the inspector which isn't working right now.

**Version**
 Platform: LinuxMint 21
 
Flutter
```dart
Flutter 3.3.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e99c9c7cd9 (6 days ago) • 2022-11-01 16:59:00 -0700
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0
```

Isar
```dart
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
```

**Comment by leisim** [comment]
No it does not talk to a server. You can verify that by opening the inspector and then disconnecting your internet.

The inspector Flutter app is just hosted on GitHub pages. I have no intention of distributing a standalone app for every platform. Isar 2.x had that and it was a nightmare. You can just build the Inspector locally if you prefer.
