### ISSUE TITLE
`Stream` of results as soon as they are available

### ISSUE THREAD

**Issue by CaptainDario** [isar/isar#874]
**Is your feature request related to a problem? Please describe.**
I am using a rather large DB (~500.000 entries of type `List<String>`) and querying with a `contains` method takes some time to finish. Now I would be interested in a way to get the query results as soon as an entry matches.
Example:
```
db = [test, house, ... ***imagine 100.000 other entries***, maid, testing, speaker]
Stream<String> results = db.filter().contains("test").watchIndividual()
```

When watching and printing the stream this results in
```
> test
> ...
> testing
```
printing the results as soon as they matched and not waiting for the whole query to finish

**Describe the solution you'd like**
A way to get the results of a query in a stream as soon as they are available.

**Describe alternatives you've considered**
I tried the `watch` / `watchLazy` methods but they only return a result once the whole query was finished.

**Comment by simc** [comment]
Use synchronous queries in a background isolate to achieve this behavior 👍
