### ISSUE TITLE
Failed to load dynamic library libisar.so

### ISSUE THREAD

**Issue by gilcu2** [isar/isar#881]
Hello, I tried to run your Quickstart on updated ArchLinux and get:
 
Unhandled exception:
Invalid argument(s): Failed to load dynamic library '/home/gilcu2/prog/catch_hard/catch_health/lib/examples/db_isar/libisar.so': /home/gilcu2/prog/catch_hard/catch_health/lib/examples/db_isar/libisar.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      _initializePath (package:isar/src/native/isar_core.dart:92:28)
#3      initializeCoreBinary (package:isar/src/native/isar_core.dart:75:9)
#4      openIsar (package:isar/src/native/open.dart:85:3)
#5      Isar.open (package:isar/src/isar.dart:104:12)
#6      main (package:catch_health/examples/db_isar/user.dart:16:27)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)

### Code sample

```dart
import 'package:isar/isar.dart';

part 'user.g.dart';

@collection
class User {
  Id id = Isar.autoIncrement; // you can also use id = null to auto increment

  String? name;

  int? age;
}

void main() async {
  final isar = await Isar.open([UserSchema]);

  final newUser = User()
    ..name = 'Jane Doe'
    ..age = 36;

  await isar.writeTxn(() async {
    await isar.users.put(newUser); // insert & update
  });

  final existingUser = await isar.users.get(newUser.id); // get

  if (existingUser != null) {
    await isar.writeTxn(() async {
      await isar.users.delete(existingUser.id); // delete
    });
  }
}

```

### Details

 - Platform: ArchLinux
 - Flutter version:  3.3.8
 - Isar version: 3.0.2

**Comment by leisim** [comment]
If you're working on a Flutter app you forgot to add the isar_flutter_libs package.

For a dart-only app check out https://github.com/isar/isar#unit-tests
