### ISSUE TITLE
Isar inspector - 404 page not found error - Isar version 3.0.3 

### ISSUE THREAD

**Issue by zarkob** [isar/isar#883]
### Steps to Reproduce

When executing the application in debug mode on the Android emulator (windows), I cannot access any more to the Isar inspector by using the url written in the debug console.

By example:
Output produced in debug console:
I/flutter ( 6778): ╔════════════════════════════════════════════════════╗
I/flutter ( 6778): ║                ISAR CONNECT STARTED                ║
I/flutter ( 6778): ╟────────────────────────────────────────────────────╢
I/flutter ( 6778): ║        Open the link to connect to the Isar        ║
I/flutter ( 6778): ║       Inspector while this build is running.       ║
I/flutter ( 6778): ╟────────────────────────────────────────────────────╢
I/flutter ( 6778): ║ https://inspect.isar.dev/3.0.3/#/57951/Tn1NVRL4540 ║
I/flutter ( 6778): ╚════════════════════════════════════════════════════╝

When trying to access the url: https://inspect.isar.dev/3.0.3/#/57951/Tn1NVRL4540

the error in the browser is:

404
File not found

![image](https://user-images.githubusercontent.com/7801434/201531849-9842af42-1635-4f19-81c1-99c0eba2f2cc.png)

With the version 3.0.2 of Isar, everything worked well.

However if I modify the url and put 3.0.2 instead of 3.0.3 it works:
https://inspect.isar.dev/3.0.2/#/57951/Tn1NVRL4540

### Details

 - Platform: x86_64 Android Emulator on Windows
 - Flutter version: 3.3.7
 - Isar version: 3.0.3

**Comment by leisim** [comment]
Sorry there was a deployment issue. Fixed now :)

**Comment by zarkob** [comment]
Great, thanks a lot. It works perfectly now ;-)
