### ISSUE TITLE
'Exception: Bad state: Arena no longer in use' in findFirst query

### ISSUE THREAD

**Issue by pradeep-here** [isar/isar#896]
Stacktrace from console:

> [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Arena no longer in use, `releaseAll(reuse: false)` was called.
> #0      Arena._ensureInUse
> package:ffi/src/arena.dart:105
> #1      Arena.allocate
> package:ffi/src/arena.dart:51
> #2      QueryImpl.findInternal.<anonymous closure> (package:isar/src/native/query_impl.dart)
> package:isar/…/native/query_impl.dart:1
> #3      IsarCommon.getTxn
> package:isar/…/common/isar_common.dart:94
> #4      QueryImpl.findInternal
> package:isar/…/native/query_impl.dart:46
> #5      QueryImpl.findFirst
> package:isar/…/native/query_impl.dart:33
> #6      QueryExecute.findFirst
> package:isar/src/query_builder_extensions.dart:197
> #7      UsrDetailsDbService.getKbUser
> package:kb_qa1/…/db/logged_in_usr_details_db_service.dart:141
> <asynchronous suspension>

This is happening in certain flow, when reading data from Firestore listener.
Also I have introduced few seconds delay before calling findFirst.. else the app was crashing without even printing this stack trace.

```
          await Future.delayed(Duration(seconds: 3));
          kbUserDetail = await kbUsersColl.where().usrIdEqualTo(kbUserId).findFirst();
```

If I trigger from UI - the same method calling findFirst query, this Exception did not occur and code ran fine. 
Will try to get more detail around the Exception scenario and update in comments.

**Isar Version used**
  isar: ^3.0.4
  isar_flutter_libs: ^3.0.4
  isar_generator: ^3.0.4
  
(However the app crash happened with **isar 2.5** also.. for same scenario. I did not try few seconds delay with v 2.5... so this exception was not seen)

**Device:** 
    ios simulator iPhone 11 (iOS 13.7)

**Comment by leisim** [comment]
Thanks a lot for this detailed report 💜

Do you have a small code sample triggering this issue? Do you use the `Future.delayed` within a transaction?

**Comment by pradeep-here** [comment]
> 

hi @leisim, 
I did not use `Future.delayed` within transaction.
Called it just before .findFirst(), as wanted to see if anything else happening their.. as app was crashing without printing any exception.
Will try to come up with small code to reproduce and share.
Thanks.

**Comment by leisim** [comment]
Fixed in 3.0.5 🙂

**Comment by pradeep-here** [comment]
> 

I tried now with 3.0.5, but still getting same exception in that scenario.

Tried below :
> pubspec.yaml -> updated all 3 isar libs to 3.0.5 
> flutter clean
> flutter pub get
> flutter pub run build_runner build --delete-conflicting-outputs
> ios simulator -> Erase all contents and settings
> ran the app in ios simulator


**In my code I am having multiple isar db instances**, and at time of exception I believe there are atleast 2 isar-db-instances having simultaneous read/write. Not sure if that would cause such issue.
So far I could not reproduce this issue in smaller code.

**Comment by leisim** [comment]
Oh no :( Let's reopen then.

If you find a way to reproduce that would be awesome 💜

**Comment by pradeep-here** [comment]
> 

Hi, the issue occurred with below scenario:
another function is called within writeTxn on isar-db-instance-1
this other function uses other instance of isar (isar-db-instance-2)

**Code sample with issue**
```
  funcA(Msg msg) {
    isarInstance?.writeTxn(() async {
      insertedId = await isarInstance_1.msgs.put(msg);
      if (insertedId != null) {
        funcB(msg);
      }
    });
  }


  funcB(Msg msg) {
    User? user = await isarInstance_2.users.where().usrIdEqualTo(msg.usrId).findFirst();
  }

```

**Fix:**
move the funcB call out of writeTxn

```
  funcA(Msg msg, Function callback) {

    isarInstance?.writeTxn(() async {
      insertedId = await isarInstance_1.msgs.put(msg);
    });

    if (insertedId != null) {
      funcB(msg);
    }

  }

```


Earlier you asked if some call was within transaction, and I missed noticing the callback happening - involving different isar instances.

This workaround works for me. Thank you.

**Comment by leisim** [comment]
Ohhh you nest transactions of different instances. That's not allowed. I'll add a check to throw a better error.
