### ISSUE TITLE
Generate "copyWith" and "operator == method" when running build_runner

### ISSUE THREAD

**Issue by TreyThomas93** [isar/isar#897]
Good afternoon,

I was wondering if there are plans to include _**copyWith**_ and _**operator == method**_ in the generated files, like in the _**freezed**_ package.

Thanks

**Comment by leisim** [comment]
There's a package to generate copy with and equality. It's compatible with Isar.

**Comment by TreyThomas93** [comment]
Do you know the name by chance?

**Comment by leisim** [comment]
This is one: https://pub.dev/packages/copy_with_extension

And all other packages that don't do weird things like freezed should work too

**Comment by leisim** [comment]
Sure you can make them immutable if you prefer

**Comment by TreyThomas93** [comment]
Like this?
```dart
@collection
@immutable
class User {
...
}
```

**Comment by leisim** [comment]
Yes

**Comment by TreyThomas93** [comment]
Thanks.

I am currently using Riverpod with freezed and Hive. I am hoping I can get at least the same functionality that I currently am by using Isar. I really like the looks of this package.

And I will head on over to the telegram channel.
