### ISSUE TITLE
Isar Inspector 3.0.4 gives 404 Error

### ISSUE THREAD

**Issue by jbrisko** [isar/isar#898]
### Steps to Reproduce

When you try to connect to the provided URL for a v3.0.4 inspector, Github returns a 404.

### Code sample
Not Applicable
Visit https://inspect.isar.dev/3.0.4/#/ and see the error

### Details

 - Platform: All
 - Flutter version: 3.3.8
 - Isar version: 3.0.4

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by cliftonlabrum** [comment]
I installed Isar today to give it a try and I ran into this issue as well. I was puzzled why the inspector wasn't a local URL.

Is there a workaround until this gets fixed?

**Comment by jbrisko** [comment]
@cliftonlabrum Yes, switch the version to 3.0.3 in the inspector URL, and it works fine. Keep everything else the same other than the version.

**Comment by cliftonlabrum** [comment]
@jbrisko Fantastic, thank you!

**Comment by leisim** [comment]
Fixed :)
