### ISSUE TITLE
Isar Inspector - Cross platform

### ISSUE THREAD

**Issue by CodeDoctorDE** [isar/isar#90]
**Is your feature request related to a problem? Please describe.**
I have no mac :(

**Describe the solution you'd like**
It would be cool if there is an option to run the isar inspector on linux and windows.

**Describe alternatives you've considered**
-

**Version**
 - Platform: Windows 10, Linux(, Web)

**Comment by leisim** [comment]
@CodeDoctorDE it should be little effort to make the inspector platform independent. I just didn't have time to test it yet. Maybe you want to give it a try 😉

**Comment by snehmehta** [comment]
I have build isar inspector for windows. Executable file is shared on google drive link below.

[Isar Inspector windows - Drive link ](https://drive.google.com/drive/folders/1sXvfywjLQ5-y8W8PgPIYw3RhWhBDWUKX?usp=sharing)

Make sure to download all into one folder.

**Comment by g0coders** [comment]
How open isar inspector in linux? like a ubuntu

**Comment by Mayb3Nots** [comment]
> I have build isar inspector for windows. Executable file is shared on google drive link below.
> 
> [Isar Inspector windows - Drive link ](https://drive.google.com/drive/folders/1sXvfywjLQ5-y8W8PgPIYw3RhWhBDWUKX?usp=sharing)
> 
> Make sure to download all into one folder.

Hi, I tried but to connect but it seems like it is not working. It cant seem to connect to my instance.

**Comment by leisim** [comment]
Fixed in `3.0.0-dev.2`

**Comment by yuanhoujun** [comment]
> 

How to set up `insepector: true`?

**Comment by Mayb3Nots** [comment]
> > 
> 
> How to set up `insepector: true`?

When you use `Isar.open()` pass in the argument there.

**Comment by kingRayhan** [comment]
I need Isar Inspector or linux/ubuntu. Any hope?

**Comment by AndroidDesigner** [comment]
> I have build isar inspector for windows. Executable file is shared on google drive link below.
> 
> [Isar Inspector windows - Drive link ](https://drive.google.com/drive/folders/1sXvfywjLQ5-y8W8PgPIYw3RhWhBDWUKX?usp=sharing)
> 
> Make sure to download all into one folder.


It needs ``flutter_windows.dll``:
```
The code execution cannot proceed because flutter_windows.dll was not found. Reinstalling the program may fix this problem.
```

**Comment by laurencetroyv** [comment]
same issue with @AndroidDesigner `The code execution cannot proceed because flutter_windows.dll was not found. Reinstalling the program may fix this problem.`

**Comment by PickiUp** [comment]
> same issue with @AndroidDesigner `The code execution cannot proceed because flutter_windows.dll was not found. Reinstalling the program may fix this problem.`

same issue here in 2024/11

**Comment by thisishyunn** [comment]
same issue here in 2026/01
