### ISSUE TITLE
Isar will stuck the test and do not stop.

### ISSUE THREAD

**Issue by YoungEii** [isar/isar#900]
### Steps to Reproduce

I want to run the test with Isar.
But the test stuck on initializeIsarCore().

### Code sample

<img width="834" alt="image" src="https://user-images.githubusercontent.com/117349196/202088347-59e5cdb6-6bb5-4fbe-839b-d3cac4e7a08a.png">

### Details
 - Platform: macOS
 - Flutter version: v3.3.7
 - Isar version: v3.0.4

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
Should be fixed in 3.0.5 🙂

Could you please retry and reopen if the issue still happens?

**Comment by YoungEii** [comment]
Thanks~ I'll try and share it with you.
