### ISSUE TITLE
Provide a Way to Compact Isar Database File

### ISSUE THREAD

**Issue by cliftonlabrum** [isar/isar#904]
I just started using Isar and noticed that a `.isar` file, with a couple small records in it, weighs in at **1 MB**. I suspect the size is related to creating efficiencies and speed when using the database.

It would be nice to be able to compact/compress a copy of the file prior to sending it somewhere.

By way of comparison:
- The same data in an SQLite file is around 100 KB. 
- Realm has a [compaction feature](https://www.mongodb.com/docs/realm/sdk/swift/realm-files/compacting/) that lets you save out a copy that removes various things and reduces the file size by ~90%.

Would it be possible to add some kind of compaction feature to Isar for those of us that will send the database over HTTP in our app?

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 3.3.8
 - Isar version: 3.0.4

**Comment by leisim** [comment]
Isar files are much smaller than Realm but for performance reasons it initializes the file with 1MB size. I recommend adding more data to get a complete picture.

There is a compaction feature built in. Check the Isar.open() method.

**Comment by cliftonlabrum** [comment]
Ah, interesting. So if I use `compactOnLaunch` does the file remain compacted to its smallest possible size? I'm trying to make a copy of the file with compaction similar to Realm's `writeCopy` method: https://www.mongodb.com/docs/realm/sdk/swift/realm-files/compacting/#make-a-compacted-copy

**Comment by Jtplouffe** [comment]
> I'm trying to make a copy of the file with compaction similar to Realm's `writeCopy` method: [mongodb.com/docs/realm/sdk/swift/realm-files/compacting/#make-a-compacted-copy](https://www.mongodb.com/docs/realm/sdk/swift/realm-files/compacting/#make-a-compacted-copy)

Isar has the `copyToFile` function, which I think is very similar.
I don't think it's in the doc yet, but can see the comments in the code [here](https://github.com/isar/isar/blob/a037fdd6780845bbb9f4ecda6293d28002011315/packages/isar/lib/src/isar.dart#L232).
These is also a [unit test](https://github.com/isar/isar/blob/a037fdd6780845bbb9f4ecda6293d28002011315/packages/isar_test/test/copy_to_file_test.dart#L76), if you want a more concrete example.

**Comment by cliftonlabrum** [comment]
Ah, nice. Thanks for the tip. Yeah, I didn't see anything like this in the docs.

It looks like the documentation for `copyToFile` states:

> Copy a compacted version of the database to the specified file.
> If you want to backup your database, you should always use a compacted version. Compacted does not mean compressed.

After trying it, it takes a **1 MB** Isar DB and creates a **5 MB** compacted version, so it certainly doesn't compress it (as it states).

Thanks for your help!
