### ISSUE TITLE
Can not update fields and stays always null in Isar inspector

### ISSUE THREAD

**Issue by heshaShawky** [isar/isar#909]
### Steps to Reproduce

Simply I can not edit fields on objects that have been created via the inspector as it always returns to null again.

<img src="https://i.stack.imgur.com/L5uVT.gif">

And I am not the only one facing this as I found a question on StackOverflow has the same problem 
https://stackoverflow.com/questions/74460113/flutter-objects-fields-becoming-null-on-creation-in-isar-inspector

### Details
 - Flutter version: [e.g. 3.3.7]
 - Isar version: [e.g. 3.0.4]

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
Strings have to be in double quotes: `"hello world"`

**Comment by heshaShawky** [comment]
> Strings have to be in double quotes: `"hello world"`. And try hitting enter to submit a value

Yes it's working now thanks but I think this needs to be edited on the inspector to be by default adding the ( "" ) if it's a string

Thanks again and closing this

**Comment by leisim** [comment]
Yes that sounds like a nice improvement 👍
