### ISSUE TITLE
Collection name

### ISSUE THREAD

**Issue by CodeDoctorDE** [isar/isar#91]
Hi,

I have an example:
```dart
@Collection()
class Series {
  @Id()
  late int id = 0;
  late String name;
  late int? color;
  late String description = '';

  Series();

  Series.fromValue({this.description = '', this.color, required this.name});

  Series.fromJson(Map<String, dynamic> json)
      : id = json['id'],
        name = json['name'],
        color = json['color'],
        description = json['description'] ?? '';
  Map<String, dynamic> toJson() =>
      {'id': id, 'name': name, 'color': color, 'description': description};
}
```

The generator creates the property `seriess` because of the plural. It would be cool if there is an option to add a custom name.

**Comment by leisim** [comment]
@CodeDoctorDE Yes that should definitely be added. I also want to port [pluralize](https://github.com/plurals/pluralize) to Dart to improve the generated plurals.

**Comment by leisim** [comment]
This is already possible :+1:

**Comment by alguintu** [comment]
Just encountered this now using ` isar: ^3.1.0+1` where the collection name is a hit and miss. I spent a good 5 minutes wonder why `isar.addresses` does not exist after code generation.

```
@collection
class Address {}

/// generates
extension GetAddressCollection on Isar {
  IsarCollection<Address> get address => this.collection();
}

/// expected
extension GetAddressCollection on Isar {
  IsarCollection<Address> get addresses => this.collection();
}
```
Haven't dug through to check what pluralization package is being used, but could definitely make the coding easier if the expected collection name works well right off the bat.
