### ISSUE TITLE
index unique not work when using "String ids"

### ISSUE THREAD

**Issue by WingCH** [isar/isar#913]
It is found that the index unique will not work after using ""String ids""

### Steps to Reproduce

1. read [String ids doc](https://isar.dev/recipes/string_ids.html)
2. run Code sample

### Code sample

> model.dart

```dart
import 'package:isar/isar.dart';

part 'model.g.dart';

@collection
class User {
  final String? id;

  Id get isarId => fastHash(id!);

  @Index(unique: true)
  final String? name;

  final int? age;

  User({
    this.id,
    this.name,
    this.age,
  });
}

/// FNV-1a 64bit hash algorithm optimized for Dart Strings
int fastHash(String string) {
  var hash = 0xcbf29ce484222325;

  var i = 0;
  while (i < string.length) {
    final codeUnit = string.codeUnitAt(i++);
    hash ^= codeUnit >> 8;
    hash *= 0x100000001b3;
    hash ^= codeUnit & 0xFF;
    hash *= 0x100000001b3;
  }

  return hash;
}
```

> test file

```dart
void main() {
  late Isar isar;

  setUpAll(() async {
    await Isar.initializeIsarCore(download: true);
    isar = await Isar.open([UserSchema]);
  });

  setUp(() async {
    await isar.writeTxn(() async {
      await isar.clear();
    });
  });

  tearDown(() async {
    await isar.close();
  });

  test('add user', () async {
    final user = User(
      id: 'id1',
      name: 'test',
    );
    final user2 = User(
      id: 'id2',
      name: 'test',
    );
    await isar.writeTxn(() async {
      await isar.users.putAll([user, user2]);
    });

    final result = await isar.users.where().findAll();
    print(result.map((e) => e.name).toList()); // [test, test]
  });
}
```

#### Expected results

will throw an error because there are two with the same name "test"

#### Actual results

no error thrown and add two same user successfully
 
### Details

 - Platform: mac (test case)
 - Flutter version:  3.3.8
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by leisim** [comment]
I get a `UniqueIndexViolated` error. I recommend rerunning the code generator. You probably added the index after generating code. Please reopen if you still face issues 🙂
