### ISSUE TITLE
Inspector filters are difficult to update while data is flowing into collections

### ISSUE THREAD

**Issue by gfay63** [isar/isar#914]
### Steps to Reproduce

Please describe exactly how to reproduce the problem you are running into.

1. Stream data fairly rapidly into an Isar collection.
2. Open the Inspector.
3. Add a filter and try to type in a string in double quotes.
4. The Inspector refreshes too fast and keeps replacing "string" with "" before it's possible to submit.

Thought: Perhaps don't refresh the form fields when the data is refreshing? Or pause the data when editing group/filter.

### Code sample

```dart
n/a
```

### Details

 - Platform: iPhone 13 Pro, Galaxy S7, x86 Android Emulator on Windows etc.
 - Flutter version: [3.2.8]
 - Isar version: [2.0.5]

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
This is fixed in the v4 inspector
