### ISSUE TITLE
Intermittend app crashes Android and IOS

### ISSUE THREAD

**Issue by Canislupax** [isar/isar#926]
### Steps to Reproduce

Could not be reproduced. Some users report the crash after getting push notifications from other apps.

![Screenshot 2022-11-22 at 23 28 04](https://user-images.githubusercontent.com/18089562/203436453-378b3c73-c118-4e2b-9212-f94ccbed328e.png)

![Screenshot 2022-11-22 at 23 41 36](https://user-images.githubusercontent.com/18089562/203436431-12d8fec9-7a60-44a4-b683-1f25e8be4d67.png)

### Details

 - Platform: iPhone 13 Pro, Galaxy S7, x86 Android Emulator on Windows etc.
 - Flutter version: [e.g. 3.3.8]
 - Isar version: [e.g. 3.0.5]

---

**Comment by leisim** [comment]
Duplocate of #915
