### ISSUE TITLE
isar_generator fails if a class have a getter method with String return type

### ISSUE THREAD

**Issue by ebadta81** [isar/isar#93]
**Steps to Reproduce**
Isar generator gives the error for this class,  when I run ```flutter pub run build_runner build```.

The error message:
```
[INFO] Running build...
[SEVERE] isar_generator:analyzer on lib/db/PlaceVersion.dart:

Bad state: No element
[INFO] Running build completed, took 364ms
```

If I remove the getQuery method, it is ok.

**Code sample**
```
@JsonSerializable()
@Collection()
class PlaceVersion extends Data<PlaceVersion> implements DataInterface<PlaceVersion> {
  @Id()
  int id = 1;
  int region = 0;
  int town = 0;
  int source = 0;
  @JsonKey(name: 'region_town')
  int region_town = 0;
  @JsonKey(name: 'region_module')
  int region_module = 0;
  @JsonKey(name: 'town_module')
  int town_module = 0;
  int version = 0;

  @Ignore()
  @override
  String get getQuery => '/json/place-version';

  @override
  PlaceVersion fromJson(Map<String, dynamic> json) => _$PlaceVersionFromJson(json);
  @override
  Map<String, dynamic> toJson() => _$PlaceVersionToJson(this);
}
```

**Version**
 - Platform: Mac
 - Flutter version: 2.0.5
 - Isar version: 0.4.0
 - Isar Generator version: 0.4.0
 - build_runner: ^2.0.1

**Comment by ebadta81** [comment]
Also, with a static member: ```static final String query = '/json/place-version';```

**Comment by na2axl** [comment]
Hello there,

@leisim this seems to occur when the model has a getter, no matter the return type. I need to comment all getters to have a successful build...

**Comment by leisim** [comment]
Fixed with stable release
