### ISSUE TITLE
store links value stored with null

### ISSUE THREAD

**Issue by abdelrahman-abied** [isar/isar#933]
### Steps to Reproduce

Please describe exactly how to reproduce the problem you are running into.

### Code sample

```dart

// collections
import 'package:isar/isar.dart';

import 'category.dart';
part 'routine.g.dart';

@Collection()
class Routine {
  Id id = Isar.autoIncrement;

  late String title;

  @Index()
  late String startTime;

  @Index(caseSensitive: false)
  late String day;

  @Index(composite: [CompositeIndex('title')])
  final category = IsarLink<Category>();
}
import 'package:isar/isar.dart';
part 'category.g.dart';

@Collection()
class Category {
  Id id = Isar.autoIncrement;

  @Index(unique: true)
  late String name;
}
// insert method
  void _addRoutine() async {
    final newRoutine = Routine()
      ..title = _titleController.text
      ..startTime = _timeController.text
      ..day = dayValue ?? ""
      ..category.value = categoryValue;

    final isar = ref.read(isarProvider);

    ///  Insert data to routine database via [ Isar.writeTxn() ] method write transactions method
    await isar.writeTxn(() async {
      await isar.routines.put(newRoutine);
    });
    _titleController.clear();
    final selectedTime = TimeOfDay.now();
    _timeController.text =
        "${selectedTime.hour}:${selectedTime.minute} ${selectedTime.period.name}";
    setState(() {
      dayValue = days[0];
      categoryValue = null;
    });
  }```



### Details

 - Platform: iPhone 14 Pro
 - Flutter version: [ 3.3.9]
 - yaml file :  
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1
  path_provider: ^2.0.11


---

**Comment by abdalmonem** [comment]
same issue , did you find any way to pass through it ?

**Comment by abdelrahman-abied** [comment]
> same issue , did you find any way to pass through it ?

no solution for it until now

**Comment by KotBarboz** [comment]
I have the same problem. 

**Work:** 

```
    goodsList = OrderGoodsList()
      ..goods.value = goods
      ..rowNumber = 1;
    isar.writeTxnSync<int>(() => isar.orderGoodsLists.putSync(goodsList));
```

**Doesn't work:**

```
   goodsList = OrderGoodsList()
      ..goods.value = goods
      ..rowNumber = 3;
    isar.writeTxn<int>(() => isar.orderGoodsLists.put(goodsList));
```

```

@collection
class Goods {
  Id? id;
  late String shortName;
}

@collection
class OrderGoodsList {
  Id? id;
  int? rowNumber;

  final goods = IsarLink<Goods>();
}
```


**Result:** 
![2022-12-31 10_38_04-Isar Inspector](https://user-images.githubusercontent.com/53930273/210130703-3eabe4be-d5bb-4aa1-9a15-bad04f0af6d0.png)

dependencies:
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  path_provider: ^2.0.11

**Comment by abdelrahman-abied** [comment]
> I have the same problem.
> 
> **Work:**
> 
> ```
>     goodsList = OrderGoodsList()
>       ..goods.value = goods
>       ..rowNumber = 1;
>     isar.writeTxnSync<int>(() => isar.orderGoodsLists.putSync(goodsList));
> ```
> 
> **Doesn't work:**
> 
> ```
>    goodsList = OrderGoodsList()
>       ..goods.value = goods
>       ..rowNumber = 3;
>     isar.writeTxn<int>(() => isar.orderGoodsLists.put(goodsList));
> ```
> 
> ```
> 
> @collection
> class Goods {
>   Id? id;
>   late String shortName;
> }
> 
> @collection
> class OrderGoodsList {
>   Id? id;
>   double? quantity;
>   int? quantityPackages;
>   int? rowNumber;
> 
>   final goods = IsarLink<Goods>();
> }
> ```
> 
> **Result:** ![2022-12-31 10_38_04-Isar Inspector](https://user-images.githubusercontent.com/53930273/210130703-3eabe4be-d5bb-4aa1-9a15-bad04f0af6d0.png)
> 
> dependencies: isar: ^3.0.5 isar_flutter_libs: ^3.0.5 path_provider: ^2.0.11

    isar.writeTxnSync<T>(() => isar.collectionName.putSync(Value));
    that helped me a lot thanks
