### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: Cannot open Environment: MdbxError (75): Value too large for defined data type

### ISSUE THREAD

**Issue by colabra1000** [isar/isar#943]
Whenever I try running izar i get the following error.
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: Cannot open Environment: MdbxError (75): Value too large for defined data type`

### Code sample

This is my collection.

```import 'package:isar/isar.dart';
    
    part 'prefs.g.dart';
    
    @collection
    class Prefs1 {
      Id? id;
      String? ra;
     }
```

and I initiate it izar here
NOTE: I am using injectible

```

@module
abstract class RegisterModule {
  @preResolve
  Future<Isar> get isar => Isar.open([Prefs1Schema]);
}
```

### Details

 - Platform: Pixel 2 API 30, x86 Android Emulator on Windows.
 - Flutter version: [3.3.0]
 - Isar version: [3.0.5]

---

**Comment by leisim** [comment]
x86 emulators are unsupported. Please use an x64 emulator 🙂

**Comment by colabra1000** [comment]
> x86 emulators are unsupported. Please use an x64 emulator 🙂

thanks for clarifying.
