### ISSUE TITLE
Feature: allow multiple null values on unique index

### ISSUE THREAD

**Issue by fyfrey** [isar/isar#944]
**Is your feature request related to a problem? Please describe.**
Isar's unique index does not support multiple null values and throws an error instead (or overwrites if `replace: true`). Most SQL databases allow multiple null values by default when setting a unique constraint.
We are currently using Hive in [Immich](https://github.com/immich-app/immich) and would like to switch to Isar to add full offline support in the app. Our work-in-progress code looks like this:

```dart
@Collection()
class Asset {
  Id id = Isar.autoIncrement;
  @Index(unique: true, replace: true, type: IndexType.hash)
  String? remoteId;
}
```

Before assets are uploaded, their server-generated `remoteId` is null. Sadly, we currently cannot add more than 1 asset to the database with a null `remoteId`. 

**Describe the solution you'd like**
Isar should allow multiple null values on a unique index or provide a setting (like `@Index(unique: true, ignoreNull: true) to achieve this explicitly.

**Describe alternatives you've considered**
Only use an index without unique. This is bad because we now have to manually check that we do not store duplicates in the DB. This manual check is error prone or might be forgotten resulting in duplicate DB entries. Further, this removes the nice `getByRemoteId` functions.

**Version**
 - Platform: iOS, Android
 - Flutter version: 3.3.x
 - Isar version: 3.0.5

**Comment by zoodyy** [comment]
I've updated my issue description.
@simc is this enhancement something you would consider?

**Comment by simc** [comment]
@zoodyy Thanks! I like the idea but I'm unsure about whether both modes should be supported.

I'm considering ignoring all null values in indexes in Isar v4. What do you think?

**Comment by zoodyy** [comment]
@simc thanks for the quick response!

I'm mainly using Postgres as a DB and it conforms to the SQL standard: allow multiple nulls in a unique column.
When needed (e.g. to emulate the non-standard behavior of MS SQL Server), it is possible to additionally enforce a single null value per unique column.

If you only want to support one mode in Isar, I'd follow the SQL standard and ignore null values in unique indices.

**Comment by simc** [comment]
This is implemented in Isar v4
