### ISSUE TITLE
Isar inspector is not working, 

### ISSUE THREAD

**Issue by ch-muhammad-adil** [isar/isar#948]
Hello @leisim I am facing below error with Isar Inspector, I have tried to reload it many times but it still doesn't work

<img width="1652" alt="Screenshot 2022-12-02 at 12 25 56 PM" src="https://user-images.githubusercontent.com/8264639/205238514-7d3db959-330d-44fa-b8d4-5874feaa46ec.png">

### Details
Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-a
rm, locale en-PK)      
Platform: MacOS Ventura
Isar version: 3.0.5
Isar Generator version: 3.0.5
Browser: BRAVE [Version 1.45.131 Chromium: 107.0.5304.110 (Official Build) (arm64)]

**Comment by ch-muhammad-adil** [comment]
Sorry I have just realised it works fine at Google Chrome.. So I am using that.

**Comment by xVemu** [comment]
You have to disable Brave Shield.
