### ISSUE TITLE
Id generated causing problems on web 

### ISSUE THREAD

**Issue by FdevTech** [isar/isar#950]
### Steps to Reproduce
I am building an app to run on the web, desktops and phones and since ISAR supports web as mentioned in the doc I decided to go with it , the app is working well on other platforms but when I try the web I get an error:  "The integer literal 5167257216639711243 can't be represented exactly in JavaScript",  this integer is generated automatically for Id within the generated file .

### MyCollection:
import 'package:isar/isar.dart';

part 'point.g.dart';
@Collection()
class MyPoint{
  Id id = Isar.autoIncrement;
  final double x,y;
  final int color;
  final double strokeWidth;

  @Enumerated(EnumType.name)
  final MyPaintingStyle paintingStyle;

  MyPoint({required this.x, required this.y,this.color=0xFFE3F2FD,
    this.strokeWidth=3.0,
    this.paintingStyle=MyPaintingStyle.stroke});

}
enum MyPaintingStyle{
  fill,
  stroke
}

### Collection Generated by Isar:

extension GetMyPointCollection on Isar {
  IsarCollection<MyPoint> get myPoints => this.collection();
}

const MyPointSchema = CollectionSchema(
  name: r'MyPoint',
  id: -5167257216639711243,
  properties: {
    r'color': PropertySchema(
      id: 0,
      name: r'color',
      type: IsarType.long,
    ),
    r'paintingStyle': PropertySchema(
      id: 1,
      name: r'paintingStyle',
      type: IsarType.string,
      enumMap: _MyPointpaintingStyleEnumValueMap,
    ),
    r'strokeWidth': PropertySchema(
      id: 2,
      name: r'strokeWidth',
      type: IsarType.double,
    ),
    r'x': PropertySchema(
      id: 3,
      name: r'x',
      type: IsarType.double,
    ),
    r'y': PropertySchema(
      id: 4,
      name: r'y',
      type: IsarType.double,
    )
  },
  estimateSize: _myPointEstimateSize,
  serialize: _myPointSerialize,
  deserialize: _myPointDeserialize,
  deserializeProp: _myPointDeserializeProp,
  idName: r'id',
  indexes: {},
  links: {},
  embeddedSchemas: {},
  getId: _myPointGetId,
  getLinks: _myPointGetLinks,
  attach: _myPointAttach,
  version: '3.0.5',
);

int _myPointEstimateSize(
  MyPoint object,
  List<int> offsets,
  Map<Type, List<int>> allOffsets,
) {
  var bytesCount = offsets.last;
  bytesCount += 3 + object.paintingStyle.name.length * 3;
  return bytesCount;
}

void _myPointSerialize(
  MyPoint object,
  IsarWriter writer,
  List<int> offsets,
  Map<Type, List<int>> allOffsets,
) {
  writer.writeLong(offsets[0], object.color);
  writer.writeString(offsets[1], object.paintingStyle.name);
  writer.writeDouble(offsets[2], object.strokeWidth);
  writer.writeDouble(offsets[3], object.x);
  writer.writeDouble(offsets[4], object.y);
}

MyPoint _myPointDeserialize(
  Id id,
  IsarReader reader,
  List<int> offsets,
  Map<Type, List<int>> allOffsets,
) {
  final object = MyPoint(
    color: reader.readLongOrNull(offsets[0]) ?? 0xFFE3F2FD,
    paintingStyle: _MyPointpaintingStyleValueEnumMap[
            reader.readStringOrNull(offsets[1])] ??
        MyPaintingStyle.stroke,
    strokeWidth: reader.readDoubleOrNull(offsets[2]) ?? 3.0,
    x: reader.readDouble(offsets[3]),
    y: reader.readDouble(offsets[4]),
  );
  object.id = id;
  return object;
}

P _myPointDeserializeProp<P>(
  IsarReader reader,
  int propertyId,
  int offset,
  Map<Type, List<int>> allOffsets,
) {
  switch (propertyId) {
    case 0:
      return (reader.readLongOrNull(offset) ?? 0xFFE3F2FD) as P;
    case 1:
      return (_MyPointpaintingStyleValueEnumMap[
              reader.readStringOrNull(offset)] ??
          MyPaintingStyle.stroke) as P;
    case 2:
      return (reader.readDoubleOrNull(offset) ?? 3.0) as P;
    case 3:
      return (reader.readDouble(offset)) as P;
    case 4:
      return (reader.readDouble(offset)) as P;
    default:
      throw IsarError('Unknown property with id $propertyId');
  }
}

const _MyPointpaintingStyleEnumValueMap = {
  r'fill': r'fill',
  r'stroke': r'stroke',
};
const _MyPointpaintingStyleValueEnumMap = {
  r'fill': MyPaintingStyle.fill,
  r'stroke': MyPaintingStyle.stroke,
};

Id _myPointGetId(MyPoint object) {
  return object.id;
}

List<IsarLinkBase<dynamic>> _myPointGetLinks(MyPoint object) {
  return [];
}

void _myPointAttach(IsarCollection<dynamic> col, Id id, MyPoint object) {
  object.id = id;
}

extension MyPointQueryWhereSort on QueryBuilder<MyPoint, MyPoint, QWhere> {
  QueryBuilder<MyPoint, MyPoint, QAfterWhere> anyId() {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(const IdWhereClause.any());
    });
  }
}

extension MyPointQueryWhere on QueryBuilder<MyPoint, MyPoint, QWhereClause> {
  QueryBuilder<MyPoint, MyPoint, QAfterWhereClause> idEqualTo(Id id) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(IdWhereClause.between(
        lower: id,
        upper: id,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterWhereClause> idNotEqualTo(Id id) {
    return QueryBuilder.apply(this, (query) {
      if (query.whereSort == Sort.asc) {
        return query
            .addWhereClause(
              IdWhereClause.lessThan(upper: id, includeUpper: false),
            )
            .addWhereClause(
              IdWhereClause.greaterThan(lower: id, includeLower: false),
            );
      } else {
        return query
            .addWhereClause(
              IdWhereClause.greaterThan(lower: id, includeLower: false),
            )
            .addWhereClause(
              IdWhereClause.lessThan(upper: id, includeUpper: false),
            );
      }
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterWhereClause> idGreaterThan(Id id,
      {bool include = false}) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(
        IdWhereClause.greaterThan(lower: id, includeLower: include),
      );
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterWhereClause> idLessThan(Id id,
      {bool include = false}) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(
        IdWhereClause.lessThan(upper: id, includeUpper: include),
      );
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterWhereClause> idBetween(
    Id lowerId,
    Id upperId, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(IdWhereClause.between(
        lower: lowerId,
        includeLower: includeLower,
        upper: upperId,
        includeUpper: includeUpper,
      ));
    });
  }
}

extension MyPointQueryFilter
    on QueryBuilder<MyPoint, MyPoint, QFilterCondition> {
  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> colorEqualTo(
      int value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'color',
        value: value,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> colorGreaterThan(
    int value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'color',
        value: value,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> colorLessThan(
    int value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'color',
        value: value,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> colorBetween(
    int lower,
    int upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'color',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> idEqualTo(Id value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'id',
        value: value,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> idGreaterThan(
    Id value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'id',
        value: value,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> idLessThan(
    Id value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'id',
        value: value,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> idBetween(
    Id lower,
    Id upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'id',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> paintingStyleEqualTo(
    MyPaintingStyle value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'paintingStyle',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition>
      paintingStyleGreaterThan(
    MyPaintingStyle value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'paintingStyle',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> paintingStyleLessThan(
    MyPaintingStyle value, {
    bool include = false,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'paintingStyle',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> paintingStyleBetween(
    MyPaintingStyle lower,
    MyPaintingStyle upper, {
    bool includeLower = true,
    bool includeUpper = true,
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'paintingStyle',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> paintingStyleStartsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.startsWith(
        property: r'paintingStyle',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> paintingStyleEndsWith(
    String value, {
    bool caseSensitive = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.endsWith(
        property: r'paintingStyle',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> paintingStyleContains(
      String value,
      {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.contains(
        property: r'paintingStyle',
        value: value,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> paintingStyleMatches(
      String pattern,
      {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.matches(
        property: r'paintingStyle',
        wildcard: pattern,
        caseSensitive: caseSensitive,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> paintingStyleIsEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'paintingStyle',
        value: '',
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition>
      paintingStyleIsNotEmpty() {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        property: r'paintingStyle',
        value: '',
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> strokeWidthEqualTo(
    double value, {
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'strokeWidth',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> strokeWidthGreaterThan(
    double value, {
    bool include = false,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'strokeWidth',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> strokeWidthLessThan(
    double value, {
    bool include = false,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'strokeWidth',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> strokeWidthBetween(
    double lower,
    double upper, {
    bool includeLower = true,
    bool includeUpper = true,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'strokeWidth',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> xEqualTo(
    double value, {
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'x',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> xGreaterThan(
    double value, {
    bool include = false,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'x',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> xLessThan(
    double value, {
    bool include = false,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'x',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> xBetween(
    double lower,
    double upper, {
    bool includeLower = true,
    bool includeUpper = true,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'x',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> yEqualTo(
    double value, {
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.equalTo(
        property: r'y',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> yGreaterThan(
    double value, {
    bool include = false,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.greaterThan(
        include: include,
        property: r'y',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> yLessThan(
    double value, {
    bool include = false,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.lessThan(
        include: include,
        property: r'y',
        value: value,
        epsilon: epsilon,
      ));
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterFilterCondition> yBetween(
    double lower,
    double upper, {
    bool includeLower = true,
    bool includeUpper = true,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(FilterCondition.between(
        property: r'y',
        lower: lower,
        includeLower: includeLower,
        upper: upper,
        includeUpper: includeUpper,
        epsilon: epsilon,
      ));
    });
  }
}

extension MyPointQueryObject
    on QueryBuilder<MyPoint, MyPoint, QFilterCondition> {}

extension MyPointQueryLinks
    on QueryBuilder<MyPoint, MyPoint, QFilterCondition> {}

extension MyPointQuerySortBy on QueryBuilder<MyPoint, MyPoint, QSortBy> {
  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> sortByColor() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'color', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> sortByColorDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'color', Sort.desc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> sortByPaintingStyle() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'paintingStyle', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> sortByPaintingStyleDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'paintingStyle', Sort.desc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> sortByStrokeWidth() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'strokeWidth', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> sortByStrokeWidthDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'strokeWidth', Sort.desc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> sortByX() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'x', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> sortByXDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'x', Sort.desc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> sortByY() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'y', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> sortByYDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'y', Sort.desc);
    });
  }
}

extension MyPointQuerySortThenBy
    on QueryBuilder<MyPoint, MyPoint, QSortThenBy> {
  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByColor() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'color', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByColorDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'color', Sort.desc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenById() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'id', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByIdDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'id', Sort.desc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByPaintingStyle() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'paintingStyle', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByPaintingStyleDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'paintingStyle', Sort.desc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByStrokeWidth() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'strokeWidth', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByStrokeWidthDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'strokeWidth', Sort.desc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByX() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'x', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByXDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'x', Sort.desc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByY() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'y', Sort.asc);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QAfterSortBy> thenByYDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'y', Sort.desc);
    });
  }
}

extension MyPointQueryWhereDistinct
    on QueryBuilder<MyPoint, MyPoint, QDistinct> {
  QueryBuilder<MyPoint, MyPoint, QDistinct> distinctByColor() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'color');
    });
  }

  QueryBuilder<MyPoint, MyPoint, QDistinct> distinctByPaintingStyle(
      {bool caseSensitive = true}) {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'paintingStyle',
          caseSensitive: caseSensitive);
    });
  }

  QueryBuilder<MyPoint, MyPoint, QDistinct> distinctByStrokeWidth() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'strokeWidth');
    });
  }

  QueryBuilder<MyPoint, MyPoint, QDistinct> distinctByX() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'x');
    });
  }

  QueryBuilder<MyPoint, MyPoint, QDistinct> distinctByY() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'y');
    });
  }
}

extension MyPointQueryProperty
    on QueryBuilder<MyPoint, MyPoint, QQueryProperty> {
  QueryBuilder<MyPoint, int, QQueryOperations> idProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'id');
    });
  }

  QueryBuilder<MyPoint, int, QQueryOperations> colorProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'color');
    });
  }

  QueryBuilder<MyPoint, MyPaintingStyle, QQueryOperations>
      paintingStyleProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'paintingStyle');
    });
  }

  QueryBuilder<MyPoint, double, QQueryOperations> strokeWidthProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'strokeWidth');
    });
  }

  QueryBuilder<MyPoint, double, QQueryOperations> xProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'x');
    });
  }

  QueryBuilder<MyPoint, double, QQueryOperations> yProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'y');
    });
  }
}

### Error:
 lib/model/point.g.dart:18:8: Error: The integer literal 5167257216639711243 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 5167257216639711232 is the nearest value that can be represented exactly.
  id: -5167257216639711243,
       ^^^^^^^^^^^^^^^^^^^

**Comment by BrianCraig** [comment]
@FdevTech isar 3.0.x currently doesn't work on web, use 2.5.
Check #686.

**Comment by leisim** [comment]
Duplicate
