### ISSUE TITLE
Document library exceptions

### ISSUE THREAD

**Issue by 0ttik** [isar/isar#954]
**Is your feature request related to a problem? Please describe.**
When using methods of the library it's unclear if methods are throwing any exceptions and if they are expected for me to be handled. Like I assume I can get certain exceptions connected with IO or file access when opening Isar instance or some other exceptions during writing/reading data to it. It's impossible to know if certain exception will be thrown unless I've inspected source code or did testing for the edge cases to deduct resulting exceptions. 

**Describe the solution you'd like**
Document exceptions that library are throwing.

**Describe alternatives you've considered**
Maybe documentation could be done in a general way and not for each method I can call, but describe overall logic behind library's exceptions system. 

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web

**Comment by simc** [comment]
There are now specific classes for all the different errors that can happen: https://github.com/isar/isar/blob/main/packages/isar/lib/src/isar_error.dart
