### ISSUE TITLE
Unique Columns?

### ISSUE THREAD

**Issue by antholeole** [isar/isar#96]
Many database solutions (read: all) have a way to make a column a "unique" column. I'd like to do this in Isar too.

**Describe the solution you'd like**
Perhaps an `@Unique` tag on a field that perhaps just performs a query by that field and if it already exists throws an error?

**Describe alternatives you've considered**
I've been literally doing the previous in my repository - Something like this:

```dart
class GroupRepository {
  Future<void> addOne(Group group) async {
    if (await _isar.groups.where().filter().idEqualTo(group.id).findFirst() !=
        null) {
      throw NonUniqueException();
    }

    await _isar.writeTxn((isar) async {
      await isar.groups.put(group);
    });
  }
}
```

I should clarify that I know that the PK column is unique - but, I'm using uuid's in my database and so my model has two Id's: `isar_id` and `id`, the latter being a Uuid.

It'd be helpful to remove this boilerplate by having an `@Unique` flag on a field that doesn't allow inserts if this already exists.

Thanks, and thanks for the awesome package :)

**Comment by leisim** [comment]
It's already possible using indexes: https://isar.dev/indexes#unique-indexes

You can even define a "replace index" that replaces existing entries instead of throwing an error.

**Comment by antholeole** [comment]
Ah! Thank you - just what I'm looking for.

you're awesome :)
