### ISSUE TITLE
[BUG] Inspector incorrectly displays numbers larger than 52 bits

### ISSUE THREAD

**Issue by JaffaKetchup** [isar/isar#972]
Hi there, 
Back from https://github.com/isar/isar/discussions/965 :D.

### Information

I need quite a complex layout for a pure JSON system, so I've implemented a registry-style system. As you can see in the screenshot, the 'registry' contains stores, and the ID should be the same between the store and the database it refers to.

![image](https://user-images.githubusercontent.com/58115698/207045699-e27d2eca-365e-44ca-89e5-ba624b153ddc.png)
![image](https://user-images.githubusercontent.com/58115698/207045965-78c4e0e3-7faa-4fc2-a789-5d1351f6ac4b.png)

As you can see from the image above, the ID's don't match however (in the last few digits). The correct ID's are generated (by this algorithm: https://isar.dev/recipes/string_ids.html), as can be seen in the database selector and in my console, however, these don't seem to be correct in the store entries themselves.

Within my code, I use exactly the same algorithm for both, and can see from my console output during debugging that the correct IDs are being generated and passed everywhere, so there must be an issue within Isar?

EDIT: It's important perhaps to note that it is a consistent difference for the same string, although sometimes bigger (in the hundreds). The same string gives the same correct and incorrect hashes. It also seems that this applies to every store, not just the two shown.

### Code samples

Unfortunatley, I can't provide a minimal reproducible example, there's just too much to write for that. So I've left some snippets instead.

The important thing is that I can gurantee that the same hashes are being passed everywhere necessary, because of the `print` statements in the hash function and the fact that the hash function output is always passed direct to somewhere, there is never any processing done to it.

#### Hash function (with debugging stuff left in):
```dart
/// Efficiently converts a string into an ID for a [Collection]
static int hash(String string) {
    final str = string.trim();

    // ignore: avoid_js_rounded_ints
    int hash = 0xcbf29ce484222325;
    int i = 0;

    while (i < str.length) {
        final codeUnit = str.codeUnitAt(i++);
        print('$str: $codeUnit - ${String.fromCharCode(codeUnit)}');
        hash ^= codeUnit >> 8;
        hash *= 0x100000001b3;
        hash ^= codeUnit & 0xFF;
        hash *= 0x100000001b3;
    }

    print('$str: $hash');
    print('-----------');
    return hash;
}
```

#### Store object:
```dart
@internal
@Collection(accessor: 'stores')
class DbStore {
  Id get id => DatabaseTools.hash(name);

  final String name;

  int hits = 0;
  int misses = 0;

  DbStore({required this.name});
}
```

<details>
<summary><b>Registry code, should you need it</b></summary>

```dart
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:isar/isar.dart';
import 'package:meta/meta.dart';

import '../fmtc.dart';
import 'defs/store.dart';
import 'defs/tile.dart';

/// Manages the tile stores available
///
/// The registry database contains a list of [DbStore]s, which as well as
/// containing some metadata, have an ID generated by the store name, which
/// refers to the independent database file of the same name, which contains
/// tiles.
///
/// It is very important for the registry to remain in sync with the actual state
/// of the root directory ([_directory]), otherwise data loss can easily occur.
/// See [synchronise]'s documentation for more information.
@internal
class FMTCRegistry {
  final String _directory;

  final Isar registryDatabase;
  final Map<int, Isar> tileDatabases = {};

  FMTCRegistry._(this._directory, this.registryDatabase);
  static late FMTCRegistry instance;

  static Future<FMTCRegistry> initialise({
    Directory? dirReal,
    String? dirString,
  }) async {
    if (dirReal == null && dirString == null) {
      throw ArgumentError('Either `dirReal` or `dirString` should be provided');
    }

    final String directory = dirString ?? dirReal!.absolute.path;

    instance = FMTCRegistry._(
      directory,
      await Isar.open(
        [DbStoreSchema, if (kDebugMode) DbTileSchema],
        name: 'registry',
        directory: directory,
      ),
    );
    await instance.synchronise();

    return instance;
  }

  Future<void> uninitialise({bool delete = false}) async {
    await synchronise();
    await Future.wait<void>([
      ...tileDatabases.entries.map((e) async {
        await e.value.close(deleteFromDisk: delete);
        tileDatabases.remove(e.key);
      }),
      registryDatabase.close(deleteFromDisk: delete),
    ]);
  }

  /// Synchronise the contents of the registry with the contents of the root
  /// directory
  ///
  /// To manage a store, see [StoreManagement]. Those methods change the state of
  /// the registry, then call this method to synchronise.
  ///
  /// Note that calling this method can lead to data loss - a tile store without
  /// a corresponding registry entry will be deleted without warning.
  Future<void> synchronise() async => Future.wait<void>([
        ...tileDatabases.entries.map((e) async {
          if (await registryDatabase.stores.get(e.key) == null) {
            tileDatabases.remove(e.key);
            if (e.value.isOpen) await e.value.close(deleteFromDisk: true);
          }
        }),
        ...(await registryDatabase.stores.where().findAll()).map((s) async {
          if (!tileDatabases.containsKey(s.id)) {
            tileDatabases[s.id] = await Isar.open(
              [DbTileSchema],
              name: s.id.toString(),
              directory: _directory,
            );
          }
        }),
      ]);
}
```

</details>

<details>
<summary><b>Store management code, should you need it</b></summary>

```dart
// Copyright © Luka S (JaffaKetchup) under GPL-v3
// A full license can be found at .\LICENSE

part of '../fmtc.dart';

/// Manages a [StoreDirectory]'s representation on the filesystem, such as creation and deletion
@internal
class StoreManagement {
  /// The store directory to manage
  final StoreDirectory _storeDirectory;

  FMTCRegistry get _registry => FMTCRegistry.instance;

  /// Manages a [StoreDirectory]'s representation on the filesystem, such as creation and deletion
  StoreManagement._(this._storeDirectory);

  /// Create all of the directories asynchronously
  Future<void> create() async {
    await _registry.registryDatabase.writeTxn(
      () => _registry.registryDatabase.stores
          .put(DbStore(name: _storeDirectory.storeName)),
    );
    await _registry.synchronise();
  }

  /// Delete all of the directories asynchronously
  ///
  /// This will remove all traces of this store from the user's device. Use with caution!
  Future<void> delete() async {
    await _registry.registryDatabase.writeTxn(
      () => _registry.registryDatabase.stores
          .delete(DatabaseTools.hash(_storeDirectory.storeName)),
    );
    await _registry.synchronise();
  }

  /// Resets this store asynchronously
  ///
  ///  This will remove all traces of this store from the user's device. Use with caution!
  Future<void> reset() async {
    await create();
    await delete();
  }

  /// Rename the store directory asynchronously
  ///
  /// The old [StoreDirectory] will still retain it's link to the old store, so always use the new returned value instead: returns a new [StoreDirectory] after a successful renaming operation.
  Future<StoreDirectory> rename(String storeName) async {
    File constructor(String name) =>
        FMTC.instance.rootDirectory.directory >>>
        '${DatabaseTools.hash(name)}.isar';

    // Close the currently opened store
    await _registry
        .tileDatabases[DatabaseTools.hash(_storeDirectory.storeName)]!
        .close();
    await _registry.registryDatabase.writeTxn(() async {
      // Register a new store in the registry and unregister the old one
      await _registry.registryDatabase.stores
          .delete(DatabaseTools.hash(_storeDirectory.storeName));
      await _registry.registryDatabase.stores.put(DbStore(name: storeName));
      // Manually rename the old file (with the old ID) to the new ID
      await constructor(_storeDirectory.storeName)
          .rename(constructor(storeName).absolute.path);
      // Apply changes
      await _registry.synchronise();
    });

    return _storeDirectory.copyWith(storeName: storeName);
  }
}
```

</details>

### Details

 - Platform: Windows
 - Flutter version: 3.3.9 (latest stable)
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by simc** [comment]
This very likely only affects the Inspector. Since browsers only support 52bit numbers with full accuracy.

Please try running your native app without opening the inspector.

**Comment by JaffaKetchup** [comment]
@simc Thanks for the fast response again. I'm not far enough in to check this is working, but if what you said was the case, then wouldn't both of the displayed IDs be wrong (the database name, and store ID)? Or are filenames treated as strings to get around this issue?

**Comment by JaffaKetchup** [comment]
If so, that would make a lot of sense. Maybe it should be documented somewhere?

**Comment by simc** [comment]
Yes, database names are strings. Rather than documenting it I'd rather transfer the ids as Strings to the inspector. If you confirm that this is an inspector only issue then I can easily fix it.

**Comment by JaffaKetchup** [comment]
Ok, will try to confirm sooner rather than later. I'll leave this open for now.

**Comment by JaffaKetchup** [comment]
Hey @simc, glad to say that it all works OK, so this issue is just limited to the Inspector.

I've given this fantastic library front page credit on my docs :) 
![image](https://user-images.githubusercontent.com/58115698/208268452-026280fd-65f8-4c4b-b49d-f4ce85910e76.png)

Thanks for your insights!

**Comment by simc** [comment]
Awesome, thanks @JaffaKetchu. Let's keep this issue open to fix the inspector bug

**Comment by simc** [comment]
Unfortunately it's harder to fix than I thought. I'd have to transform the json to a binary format or all numbers to Strings before sending it to the inspector. This would also make the json export in the inspector incorrect.

I think at this time I won't fix the issue
