### ISSUE TITLE
Isar fails to load dll on windows desktop 64 bit

### ISSUE THREAD

**Issue by bsutton** [isar/isar#985]
### Steps to Reproduce

I'm trying to start an flutter app which initialises an Isar database.

During the initialisation process an exception is throw say it failed trying to load the isar.dll.

```dart

FutureOr<void> initializeCoreBinary({
  Map<Abi, String> libraries = const {},
  bool download = false,
}) {
  if (_isarInitialized) {
    return null;
  }

  String? libraryPath;
  if (!Platform.isIOS) {
    libraryPath = libraries[Abi.current()] ?? Abi.current().localName;
  }

  try {
    _initializePath(libraryPath);
  } catch (e) {
    if (!Platform.isAndroid && !Platform.isIOS) {
      final downloadPath = _getLibraryDownloadPath(libraries);
      if (download) {
        return _downloadIsarCore(downloadPath).then((value) {
          _initializePath(downloadPath);
        });
      } else {
        // try to use the binary at the download path anyway
        _initializePath(downloadPath);
      }
```
The code fails in the above call to `_initializePath` ( the second last line)

I note that the call to `initializeCoreBinary` is called with no arguments.

```
Invalid argument(s): Failed to load dynamic library '.....\op-vault\isar.dll': error code 126
dart:ffi                                      new DynamicLibrary.open
_initializePath
package:isar/…/native/isar_core.dart:92
initializeCoreBinary
package:isar/…/native/isar_core.dart:75
openIsar
package:isar/…/native/open.dart:81
Isar.open
package:isar/src/isar.dart:107
IsarService.openDatabase
package:opvault/src/isar_service.dart:18
new IsarService
package:opvault/src/isar_service.dart:11
File.create
package:opvault/…/model/file.dart:68
main.<fn>
```

I'm trying to run the app from within vscode in debug mode.

I note that I can see the isar.dll in the isar windows directory under pub-cache.

### Details

Windows 11 Home
64-bit operating system, x64-based processor

Isar - 3.0.5
Flutter

```
flutter --version
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (4 weeks ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

````

 - [x ] I searched for similar issues already
 - [x ] I filled the details section with the exact device model and version
 - [x ] I am able to provide a reproducible example

**Comment by bsutton** [comment]
Just a brief update.

1) if I manually copy the isar.dll to the root of my project then it gets loaded correctly.
2) I'm running the code as part of a unit test. I'm not yet in a position to launch the code as an app to see if that makes a difference.

**Comment by nayeemtby** [comment]
Did you check this https://pub.dev/packages/isar#unit-tests

**Comment by simc** [comment]
This should be fixed
