### ISSUE TITLE
[BUG] Bad state: Arena no longer in use, `releaseAll(reuse: false)` was called.

### ISSUE THREAD

**Issue by JaffaKetchup** [isar/isar#987]
Hi again @simc, sorry for bothering you!

### Description

I'm trying to maximise performance as much as possible during a bulk writing. Whilst using an individual transaction for each write operation (each write operation depends on a network call to get some bytes, and these network calls are called in a queue with 10 parallel threads) is best in terms of reliability/durability, it has signigicantly worse performance than just writing to the filesystem (of course, this is still better in the long run, as statistics can be retrieved almost instantly).

Whilst trying to increase this performance by only using one transaction, I'm running into the error in the title. In the code below, you can see that I listen to a long-lived (singleton controlled) stream inside the transaction, and the stream contains the objects to write to the database. For every `stream.add` operation, I get the error above, which traces back to the transaction block.

What is the correct way to create a long lived transaction which can have multiple write events added dynamically by a stream?

### Code sample

```dart
class BulkTileWriter {
  BulkTileWriter._(FMTCTileProvider provider)
      : _tileWriteStream = StreamController.broadcast(),
        _db = FMTCRegistry.instance.tileDatabases[DatabaseTools.hash(
          provider.storeDirectory.storeName,
        )]!;
  final StreamController<DbTile> _tileWriteStream;
  final Isar _db;

  static late BulkTileWriter instance;

  static void start(FMTCTileProvider provider) {
    instance = BulkTileWriter._(provider);
    instance._db.writeTxn(
      () async {
        instance._tileWriteStream.stream
            .listen((e) => instance._db.tiles.put(e));
      },
    );
  }

  static void write(DbTile tile) => instance._tileWriteStream.add(tile);

  static void stop() => instance._tileWriteStream.close();
}

// Elsewhere
BulkTileWriter.start(provider);

// Elsewhere
BulkTileWriter.write(DbTile(url: url, bytes: bytes));
```

### Details

 - Platform: Windows
 - Flutter version: 3.3.9
 - Isar version: 3.0.5

The only other similar issue I could find was https://github.com/isar/isar/issues/896, but that appears to be a little different.

---

 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version
 - [X] I am able to provide a reproducible example

**Comment by simc** [comment]
@JaffaKetchup when the stream subscription in the transaction receives an event, it is already closed. There is nothing keeping this transaction running. The async callback you provide to `writeTxn()` returns immediately.

I don't understand however why you see such an unergonomic error message. That's certainly something that needs to be fixed.

I'd be extremely grateful if you could provide a small `main()` function that reproduces the issue.

Generally what you are trying to do is a **very** bad idea for multiple reasons:

Short transactions are not very expensive. They have a cost but not bad. Very long running transactions that wait for a network call or stream are very expensive and let the database file grow fast.

Additionally only a single write transaction can run at a time so you can't write anywhere else why this transaction is running.

**Comment by JaffaKetchup** [comment]
Hi @simc,

Ah, that certainly makes sense: I should've seen it myself!
I'll try and make an MRE for you this week, it should be relatively easy to reproduce.

Interesting that only one write thread can be in use at one time, I've noticed that in every database I've come across. I guess this is a limitation of IO?

I realised that what I'm doing is a poor idea, I was more interested to see if Isar could be faster than pure IO if I pushed it to the max.

If you're interested in the difference in tiles per second, when making requests to the same server around the same time in 10 threads, pure IO writes about 250 whereas Isar writes ~170. As I said, everything else is much faster, so it's a tradeoff I'm willing to make (and I'm sure my users won't mind either). I guess it will be a game of optimising my code then!

Thanks for your fast response :)

**Comment by simc** [comment]
Yes multi-threaded writing is generally very difficult and would slow down reading.

I guess 70% of IO is not too bad. Then again 170 writes / second sounds extremely slow. Isar should be easily able to write thousands of objects per second.

Maybe try batching some writes or compare the performance between sync and async writing so see how much you loose waiting for the Dart Isolate to sync with the Isar thread.

**Comment by JaffaKetchup** [comment]
After implementing an Isolate system with bi-directional communication, I've managed to get this to write at ~280 tiles per second: I'm pretty sure it's a network limitation at this point, as it fluctuates over and under this number a fair bit (whereas it was a limit previously).
Batching might further increase performance, but it's not ideal for memory consumption (due to the nature of what I'm storing).

I should be able to get a minimal reproducible example posted on here tomorrow (day after at the latest).

**Comment by JaffaKetchup** [comment]
@simc Here's the reproducible example:

```dart
Future<void> main(List<String> arguments) async {
  final db = await Isar.open([UserSchema]); // Any schema
  final stream = StreamController<User>.broadcast();
  await db.writeTxn(() async => stream.stream.listen((e) => db.users.put(e)));
  stream.add(User());
```

Interestingly, if I remove the `await` from in front of `writeTxn`, it exits without error. I can't find the actual database file to confirm if it wrote anything or not, and the Inspector link isn't shown.

**Comment by simc** [comment]
Thanks so much for your help @JaffaKetchup 🙏

**Comment by JaffaKetchup** [comment]
No problem at all, thanks for yours as well :)

**Comment by JaffaKetchup** [comment]
Hey @simc,

Realised that my ~280 tps was actually misleading: the database thread had become unsynced with the download thread. So not all of the tiles had actually been written.

In reality, I can still only manage ~160 writes/second. Interestingly, the write operation takes exactly 5ms - 6ms per tile, no matter it's size:

![image](https://user-images.githubusercontent.com/58115698/209218610-a5b6a5bb-5ecd-469e-98f2-1e8da8f836b6.png)

I've tried everything I can to increase performance, but I seem to be stuck at this limit, and it seems to be the database thread that is limiting (I can reach upwards of ~330 downloads/second if I detatch the thread completley).
![image](https://user-images.githubusercontent.com/58115698/209218709-bce44bc3-54b9-4c73-aee5-de219257e6bd.png)
![image](https://user-images.githubusercontent.com/58115698/209218758-460ae2e2-2e47-4d35-b724-9fae5f6b319c.png)

Do you have any idea of why this might be?
Thanks for all your help so far, it really is appriciated :)

**Comment by simc** [comment]
@JaffaKetchup I don't entirely understand the code you posted. A few general tips:

Try batch writing e.g. wait a few ms for a few tiles to arrive and write them in a single transaction.

Try benchmarking individual components. Create a small benchmark inserting a list of tiles into Isar without all the network stuff. Then we can see whether it's an Isar limitation. If that's the case we can find a fix.

**Comment by JaffaKetchup** [comment]
Buffering does seem to work well, although I have to worry about memory usage and app stability now. I'll leave the decision up to the developer on the other end.
Maybe a sentence or two in the docs would be good, referring to how buffering can remove the cost of multiple transactions when writing a lot of asynchronous data?
