### ISSUE TITLE
No automatic imports of Converted types inside Isar.g.dart

### ISSUE THREAD

**Issue by Teio07** [isar/isar#99]
**Steps to Reproduce**
I have a simple Collection with an id and an enum.
I created a TypeConverter and annotated the enum with the converter.
The file `isar.g.dart` is generated with the converter applied but I have to manually import the enum inside the `isar.g.dart` (which is not ideal because I have to do it every time the build runner runs)

**Code sample**

The Collection :
```
@Collection()
@Name("AppTheme")
class AppThemeEntity {
  int? id;
  @AppThemeConverter()
  late AppThemeId appThemeId;

  AppTheme toDomain() => AppTheme.withId(appThemeId);

  static AppThemeEntity fromDomain(AppTheme appTheme) =>
      AppThemeEntity()..appThemeId = appTheme.id;
}
```

The TypeConverter :
```
class AppThemeConverter extends TypeConverter<AppThemeId, int> {
  const AppThemeConverter(); // Converters need to have an empty const constructor

  @override
  AppThemeId fromIsar(int appThemeIdIndex) {
    return AppThemeId.values[appThemeIdIndex];
  }

  @override
  int toIsar(AppThemeId appThemeId) {
    return appThemeId.index;
  }
}
```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux
 - Flutter version: 2.0.6
 - Isar version: 0.4.0
 - Isar Generator version: 0.4.0

**Comment by TheOnlyNurse** [comment]
I ran into this problem as well, something I've been doing to side step this is to export the files needed in the converter library.
So basically, I have a separate file with just TypeConverters and I export the files needed in that file.

```dart
export 'package:fpdart/fpdart.dart';

class OptionFileConverter extends TypeConverter<Option<File>, String> {
  const OptionFileConverter();

  @override
  Option<File> fromIsar(String path) {
    return path.isNotEmpty ? some(File(path)) : none();
  }

  @override
  String toIsar(Option<File> file) => file.match((a) => a.path, () => '');
}
```

Not sure how this would be addressed, but I don't think this is a bad compromise while we wait for a better idea.

**Comment by leisim** [comment]
Fixed with stable release
