### ISSUE TITLE
open detabase error

### ISSUE THREAD

**Issue by rezadevelopers2** [isar/isar#991]
@collection
class Message{

  Id id = Isar.autoIncrement;

  @Index(type:IndexType.value)
  String? content;

  List<Files>? files;

}

@embedded
class Files {
  String? name;

}

`final isar = await Isar.open([MessageSchema],);`

error : Unhandled Exception: IsarError: Cannot open Environment: MdbxError (75): Value too large for defined data type

version : isar: ^3.0.5

[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.19044.2364], locale en-US)
    • Flutter version 3.3.9 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (4 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

**Comment by Dosenbiiir** [comment]
I wasn't able to reproduce your error. The build runner crashed on your provided code snippet. I corrected it to the following:

`@collection
class Message{

Id id = Isar.autoIncrement;

https://github.com/Index(type:IndexType.value)
String? content;

List? files;

}

@Embedded
class Files {
String? name;

}`

With that i got no errors. I was able to open the database and insert data. Can you please give us more information what exactly you did and on which plattform you tested your app?

**Comment by simc** [comment]
This can be fixed by not using a x86 Android emulator
