### ISSUE TITLE
Isar is not deleting data after unistalling flutter app

### ISSUE THREAD

**Issue by Djihanegh** [isar/isar#992]
### Steps to Reproduce

Isar is working fine in background & foreground service, but when i tried to unistall/ reinstall the same, i still have the same Id 

### Code sample

```dart
// get user id  

 static Future<String?> getUserId() async {
    final isar = await db;
    String id = "";
    try {
      id = isar!.users.filter().idEqualTo(1).findFirstSync()?.userId ?? "";
    } catch (e) {
      log(e.toString());
    }

    return id;
  }

//  save user id

  static Future<void> saveUserId(String userID) async {
    final isar = await db;
    User newUser = User(userId: userID, id: 1);

    await isar!.writeTxnSync(() async {
      isar.users.putSync(newUser);
    });
  }
```

### Details

 - isar : 3.0.5

---

 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version
 - [X] I am able to provide a reproducible example

**Comment by simc** [comment]
That is not an Isar issue. Depending on which device you use and where you store the instance, the data might be backed up. For example in iCloud.

**Comment by Djihanegh** [comment]
Im using Oppo F7, android version 10, even with OPPO A16 ( android version 12 ) , im only storing data locally
