### ISSUE TITLE
[inspector] Handle instances with different schemata

### ISSUE THREAD

**Issue by iazel** [isar/isar#994]
The inspector is currently unable to support instances with different schemata. This is because the call to `getSchema` doesn't care about which instance it is working with, and supposes all instances have the same schema.

I wonder, is this by design or rather a bug?  

### Steps to Reproduce

- Open two Isar instances with different schemata
- Open the inspector
- The first instance will show the right schemata, however once we switch to the second one, it still uses the old schemata.

### Code sample

```dart
final db1 = await Isar.open("first-db", [FirstSchema]);
final db2 = await Isar.open("second-db", [SecondSchema]);
```

### Details

 - Platform: Android, Linux
 - Flutter version: 3.3.9
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by MrNB0dy** [comment]
same issue, any updates?

**Comment by simonpham** [comment]
@simc 
I can confirm that version 3.0.5 has the issue. Here are the screenshots:

```dart
final db1 = await Isar.open("new", [ChatListSchema, ChatHistorySchema]);
final db2 = await Isar.open("second-db", [ChatMessageSchema]);
```

1. `new` instance contains ChatList, ChatHistory: correct
<img width="338" alt="image" src="https://user-images.githubusercontent.com/8846657/229429427-4c1e2f1b-b85b-49bf-9197-31bf55d426f1.png">

2. `4bfd645a-12e7-4359-b496-367be6e5c5f3` instance contains ChatList, ChatMessage: in correct
<img width="810" alt="image" src="https://user-images.githubusercontent.com/8846657/229429395-2ae65f55-ce89-4fe6-88ba-142e131e126d.png">

It should contains ChatMessage instead.

**Comment by mchouchane-enedis** [comment]
I am having the same issue. @simc Any news, this bug is very annoying for us ? Thanks

**Comment by simc** [comment]
Isar v4 will support that. Can't give an exact timeline however. Sorry 😬

**Comment by simc** [comment]
This is fixed in the v4 inspector

**Comment by Pulkit077** [comment]
@simc is there any workaround for time being ? or any specific change that we can fork and pick locally for debugging purposes ?
CC: @mchouchane-enedis
