### ISSUE TITLE
[Inspector] Allow usage of Firefox or other non-chrome based browsers

### ISSUE THREAD

**Issue by Kara-Zor-El** [isar/isar#995]
**Is your feature request related to a problem? Please describe.**
I use Firefox as my primary browser and would love to be able to use it for Isar Inspector as well

**Describe the solution you'd like**
I'd like you to allow for non Chromium based browser. If you don't want to provide support to other browsers, you could add a banner saying "warning, this browser is unsupported and may not function as intended" or allow for it to only be enabled if you specify it when opening up the Isar instance

**Describe alternatives you've considered**
I have tried using a different User Agent for the page but that is annoying to do and not ideal. Firefox actually works better in my experience, even with the UserAgent being chrome

**Version**
 - Platform: Mac, Windows, Linux
 - Flutter version: v3.3.10
 - Isar version: v3.0.5

**Comment by simc** [comment]
I don't think Firefox supports websocket connections to localhost. That's required for the inspector since we don't want to send user information over the internet.

**Comment by Kara-Zor-El** [comment]
Hi, 
Firefox does support websocket connections to localhost.

**Comment by simc** [comment]
Oh that's awesome! I'll enable it then 👍

**Comment by Kara-Zor-El** [comment]
hi, any updates on adding this ability to isar's inspector?

**Comment by simc** [comment]
This is fixed in the v4 inspector
